<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mathematical_framework – Shreesh Bhattarai</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-74ba59708be70b1949d5896c354d4bb9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shreesh Bhattarai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../catw/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Along the Way</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../papers/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper Comprehensions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notes</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#mathematical-framework-for-project-3---e3---equivariant-network-for-3d-point-cloud-classification" id="toc-mathematical-framework-for-project-3---e3---equivariant-network-for-3d-point-cloud-classification" class="nav-link active" data-scroll-target="#mathematical-framework-for-project-3---e3---equivariant-network-for-3d-point-cloud-classification">Mathematical Framework for Project 3 - E(3) - Equivariant Network for 3D Point Cloud Classification</a>
  <ul class="collapse">
  <li><a href="#context" id="toc-context" class="nav-link" data-scroll-target="#context">Context</a></li>
  <li><a href="#concepts" id="toc-concepts" class="nav-link" data-scroll-target="#concepts">Concepts</a></li>
  <li><a href="#underlying-mathematics" id="toc-underlying-mathematics" class="nav-link" data-scroll-target="#underlying-mathematics">Underlying Mathematics</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="mathematical-framework-for-project-3---e3---equivariant-network-for-3d-point-cloud-classification" class="level1">
<h1>Mathematical Framework for Project 3 - E(3) - Equivariant Network for 3D Point Cloud Classification</h1>
<hr>
<section id="context" class="level2">
<h2 class="anchored" data-anchor-id="context">Context</h2>
<p>The project is an extension of Project: Graph Neural Network for Molecular Property Prediction (QM9). It implements EGNN (Equivariant Graph Neural Network) from scratch on the ModelNet40 dataset (3D object classification: chairs, tables, planes, etc.) without using PyG’s built-in equivariant layers.</p>
<p><strong>THE MAIN GOAL:</strong> The goal is to train model that achieves competitive accuracy on ModelNet40 showing the accuracy delta between equivariant and non-equivariant architectures under random rotations at test time.</p>
<hr>
</section>
<section id="concepts" class="level2">
<h2 class="anchored" data-anchor-id="concepts">Concepts</h2>
<ul>
<li><p><strong>Point Cloud:</strong> Formally, a set of 3D coordinates <span class="math inline">\(\mathcal{P} = \{x_1, \ldots, x_N\} \subset \mathbb{R}^3\)</span>. In practice, it includes features per point, represented as a matrix <span class="math inline">\(P \in \mathbb{R}^{N \times (3 + D)}\)</span> containing 3D positions and <span class="math inline">\(D\)</span>-dimensional attributes (e.g., ModelNet40 stores <span class="math inline">\((x, y, z)\)</span> coordinates alongside surface normals <span class="math inline">\((n_x, n_y, n_z)\)</span>).</p></li>
<li><p><strong>Message Passing:</strong> A process where graph nodes update their states by aggregating features from their neighbors. <em>Example: Node A updates its value by averaging the values of connected nodes B and C.</em></p></li>
<li><p><strong>Equivariance:</strong> A property where transforming the input transforms the output in a predictable, matching way (<span class="math inline">\(f(g(x)) = g(f(x))\)</span>). <em>Example: Rotating a 3D chair model rotates its predicted 3D bounding box by the exact same amount.</em></p></li>
<li><p><strong>Rotation Matrix:</strong> A square matrix used to perform a rotation in Euclidean space. <em>Example: Multiplying a 2D vector by a 2D rotation matrix spins the vector around the origin by a specific angle.</em></p></li>
<li><p><strong><span class="math inline">\(SO(3)\)</span> (Special Orthogonal Group):</strong> The mathematical group representing all possible continuous rotations in 3D space.</p></li>
<li><p><strong><span class="math inline">\(O(3)\)</span> (Orthogonal Group):</strong> The group of all linear transformations in 3D space that preserve distances, including both rotations and reflections.</p></li>
<li><p><strong><span class="math inline">\(E(3)\)</span> (Euclidean Group):</strong> The group of all transformations in 3D space that preserve distances, combining rotations, reflections, and translations.</p></li>
<li><p><strong>Group Action:</strong> A formal way of using a group element to transform elements of a specific space. <em>Example: Applying a rotation matrix (group element) to a 3D coordinate vector (space element).</em></p></li>
<li><p><strong><span class="math inline">\(G\)</span>-Equivariant:</strong> A function where transforming the input by a group element results in a predictably transformed output.</p></li>
<li><p><strong><span class="math inline">\(G\)</span>-Invariant:</strong> A function where transforming the input by a group element leaves the output completely unchanged. <em>Example: Rotating a house does not change its total square footage.</em></p></li>
<li><p><strong>Edge Vector (<span class="math inline">\(r_{ij}\)</span>):</strong> The directional vector pointing from node <span class="math inline">\(i\)</span> to node <span class="math inline">\(j\)</span> in 3D space. <em>Example: If atom <span class="math inline">\(i\)</span> is at <span class="math inline">\((0,0,0)\)</span> and atom <span class="math inline">\(j\)</span> is at <span class="math inline">\((0,0,2)\)</span>, the edge vector is <span class="math inline">\((0,0,2)\)</span>.</em></p></li>
<li><p><strong>Edge Length (<span class="math inline">\(d_{ij}\)</span>):</strong> The straight-line Euclidean distance between node <span class="math inline">\(i\)</span> and node <span class="math inline">\(j\)</span>. <em>Example: For the edge vector <span class="math inline">\((0,0,2)\)</span>, the edge length is <span class="math inline">\(2\)</span>.</em></p></li>
<li><p><strong>EGNN (Equivariant Graph Neural Network):</strong> A type of graph neural network designed to process 3D spatial data while guaranteeing that the outputs rotate and translate predictably with the inputs.</p></li>
<li><p><strong>Coordinate Update:</strong> The layer or mechanism within a spatial GNN that shifts the physical 3D positions (<span class="math inline">\(x_i\)</span>) of nodes based on message passing.</p></li>
<li><p><strong>Linearity of Matrix Multiplication:</strong> The algebraic property where a matrix distributes over addition (<span class="math inline">\(R(a + b) = Ra + Rb\)</span>) and factors out of scalar multiplication (<span class="math inline">\(R(ca) = c(Ra)\)</span>).</p></li>
<li><p><strong>Global Mean Pooling:</strong> An operation that takes the average value of features across all nodes in a graph. <em>Example: For a point cloud with four points, mean pooling coordinates calculates the exact middle point of those four positions.</em></p></li>
<li><p><strong>Permutation Invariance:</strong> A property where changing the ordering or indexing of the inputs does not change the final output. <em>Example: Shuffling the rows of a point cloud matrix yields the exact same average coordinate.</em></p></li>
<li><p><strong>Center of Mass (Geometric Centroid):</strong> The average position of all points in a shape or point cloud, representing its geometric center.</p></li>
<li><p><strong>Smooth Manifold (<span class="math inline">\(M\)</span>):</strong> A mathematical space that looks globally curved but behaves locally exactly like flat Euclidean space. <em>Example: The Earth is a 2D spherical manifold; it looks curved from space, but looks like a flat 2D plane to an observer on the ground.</em></p></li>
<li><p><strong>Tangent Space (<span class="math inline">\(T_pM\)</span>):</strong> The vector space containing all possible velocity vectors of curves passing through a specific point <span class="math inline">\(p\)</span> on a manifold.</p></li>
<li><p><strong>Local PCA (Principal Component Analysis):</strong> A data analysis technique applied to a small localized cluster of data points to find the directions of maximum variation. <em>Example: Fitting a flat cardboard disc to a cluster of points on a basketball surface to capture its local slope.</em></p></li>
<li><p><strong>Surface Normal:</strong> A vector perpendicular to a surface at a specific point, pointing directly away from it.</p></li>
<li><p><strong>PointNet:</strong> A pioneer deep learning architecture that processes point clouds directly by mapping each point individually using a shared Multi-Layer Perceptron (MLP) and aggregating features globally.</p></li>
<li><p><strong>Shared MLP:</strong> A network structure where the exact same weights and biases are applied independently to the coordinates of every single point in the cloud.</p></li>
<li><p><strong>Global Max-Pooling:</strong> A pooling operation that takes a set of point features and extracts the maximum value across each feature channel, collapsing the point cloud into a single global vector.</p></li>
</ul>
<hr>
</section>
<section id="underlying-mathematics" class="level2">
<h2 class="anchored" data-anchor-id="underlying-mathematics">Underlying Mathematics</h2>
<hr>
<section id="stage-1---environment-dataset-inspection" class="level3">
<h3 class="anchored" data-anchor-id="stage-1---environment-dataset-inspection">Stage 1 - Environment &amp; Dataset Inspection</h3>
<p>We’re building the foundation: loading ModelNet40 and understanding what we’re actually working with before writing a single line of model code. This matters because the entire architectural motivation for EGNN flows from one fact — our data lives in 3D Euclidean space and carries geometric symmetry that naive GNNs throw away.</p>
<p><br></p>
</section>
<section id="questions-1" class="level3">
<h3 class="anchored" data-anchor-id="questions-1">Questions [1]</h3>
<p>A point cloud is often described as “a set of 3D points.” But sets have no structure beyond membership — and GNNs operate on graphs.</p>
<ol type="1">
<li><p><strong>Mathematically</strong>, what is a point cloud as a formal object? Is it just <span class="math inline">\(\mathcal{P} = \{x_1, \ldots, x_N\} \subset \mathbb{R}^3\)</span>, or does it carry more structure than that in practice (think: what ModelNet40 actually stores per point)?</p></li>
<li><p><strong>Structurally</strong>, what is the minimal additional structure you must impose on <span class="math inline">\(\mathcal{P}\)</span> to run message passing on it — and what choice of that structure will turn out to matter enormously for equivariance?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-1" class="level3">
<h3 class="anchored" data-anchor-id="answers-1">Answers [1]</h3>
<p><strong>1. Mathematical Object vs.&nbsp;Practical Structure</strong></p>
<p>Mathematically, a raw point cloud is just an unordered set of coordinates. In practice (like ModelNet40), it carries geometric attributes: <span class="math display">\[\mathcal{P} = \{(x_i, f_i) \mid x_i \in \mathbb{R}^3, f_i \in \mathbb{R}^D\}\]</span> where <span class="math inline">\(x_i\)</span> is the position and <span class="math inline">\(f_i\)</span> is a feature vector (e.g., normals, RGB intensity).</p>
<p><br></p>
<p><strong>2. Minimal Structure for Message Passing &amp; Equivariance</strong></p>
<ul>
<li><p><strong>Minimal Structure:</strong> An adjacency relation (a graph topology) defining neighbors, typically constructed via a <span class="math inline">\(k\)</span>-nearest neighbors (<span class="math inline">\(k\)</span>-NN) graph or an <span class="math inline">\(\epsilon\)</span>-radius ball graph.</p></li>
<li><p><strong>The Equivariance Choice:</strong> The method used to compute relative positions (<span class="math inline">\(x_i - x_j\)</span>) or distances (<span class="math inline">\(\|x_i - x_j\|\)</span>) within that neighborhood determines equivariance. Using absolute coordinates breaks translation invariance, whereas using relative coordinates and invariant features (like Euclidean distances) allows the network to respect <span class="math inline">\(E(3)\)</span> or <span class="math inline">\(SE(3)\)</span> symmetries.</p></li>
</ul>
<p><br></p>
<p>The deeper point is why the choice of graph construction is itself a design decision with equivariance consequences. Specifically: the k-NN graph built from Euclidean distances is itself rotation-equivariant — rotating the point cloud permutes the graph edges but doesn’t change which points are neighbors. That’s a non-trivial property we get for free.</p>
<hr>
<p>In Stage 1, the initial setup and data inspection phase, we have verified and established the following core components for our 3D deep learning pipeline:</p>
<ul>
<li><strong>Environment &amp; Hardware Integration:</strong> The deep learning environment is correctly configured with PyTorch and PyTorch Geometric. It has full access to an enterprise-grade NVIDIA Tesla P100 GPU (16GB), ensuring that our model training will be hardware-accelerated.</li>
<li><strong>Dataset Structure:</strong> The ModelNet40 dataset was successfully downloaded and processed from scratch. It contains a total of <strong>12,311 3D CAD models</strong>, cleanly split into:</li>
<li><strong>9,843 training samples</strong> to train our neural network.</li>
<li><strong>2,468 test samples</strong> to evaluate final model performance.</li>
<li><strong>40 distinct object classes</strong> (such as airplanes, bathtubs, and beds).</li>
</ul>
<p><br></p>
<ul>
<li><strong>Data Representation:</strong> Raw 3D meshes are converted into uniform, normalized point clouds. Each individual object in the dataset is structured as a PyTorch Geometric <code>Data</code> object containing two critical arrays:</li>
<li><code>pos</code>: A matrix of shape <code>[1024, 3]</code> tracking the precise <span class="math inline">\((X, Y, Z)\)</span> coordinates of 1,024 points sampled from the object’s surface, automatically centered and scaled.</li>
<li><code>normal</code>: A matrix of shape <code>[1024, 3]</code> tracking the surface normal vectors, providing the network with crucial local geometric context about surface orientation.</li>
</ul>
<p>With the environment verified, data pipeline structured, and spatial dimensions audited via 3D visualization, the data is officially ready to be fed into a geometric deep learning model.</p>
<hr>
</section>
<section id="stage-2---the-e3-group-group-rotations-reflections-translations" class="level3">
<h3 class="anchored" data-anchor-id="stage-2---the-e3-group-group-rotations-reflections-translations">Stage 2 - The E(3) Group: Group: Rotations, Reflections, Translations</h3>
<p>Here, we define the three generators of E(3) explicitly as transformation matrices and functions. Implement <code>rotate(points, R)</code>, <code>reflect(points, axis)</code>, and <code>translate(points, t)</code> as explicit, testable Python functions. Then, we apply each to a single point cloud and visualize the result before and after.</p>
<p><br></p>
</section>
<section id="questions-2" class="level3">
<h3 class="anchored" data-anchor-id="questions-2">Questions [2]</h3>
<ol type="1">
<li><p>Write the 3×3 rotation matrix <span class="math inline">\(R_z(\theta)\)</span> for a rotation by angle <span class="math inline">\(\theta\)</span> around the z-axis.</p></li>
<li><p>State the two conditions a matrix <span class="math inline">\(R \in \mathbb{R}^{3\times3}\)</span> must satisfy to be a valid element of <span class="math inline">\(SO(3)\)</span>.</p></li>
<li><p>In one sentence each: how does <span class="math inline">\(O(3)\)</span> extend <span class="math inline">\(SO(3)\)</span>, and how does <span class="math inline">\(E(3)\)</span> extend <span class="math inline">\(O(3)\)</span>?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-2" class="level3">
<h3 class="anchored" data-anchor-id="answers-2">Answers [2]</h3>
<p><strong>1. Rotation Matrix around the Z-axis</strong></p>
<p>The <span class="math inline">\(3\times3\)</span> rotation matrix <span class="math inline">\(R_z(\theta)\)</span> is:</p>
<p><span class="math display">\[R_z(\theta) = \begin{bmatrix} \cos\theta &amp; -\sin\theta &amp; 0 \\\\ \sin\theta &amp; \cos\theta &amp; 0 \\\\ 0 &amp; 0 &amp; 1 \end{bmatrix}\]</span></p>
<p><br></p>
<p><strong>2. <span class="math inline">\(SO(3)\)</span> Conditions</strong></p>
<p>A matrix <span class="math inline">\(R \in \mathbb{R}^{3\times3}\)</span> must satisfy:</p>
<ol type="1">
<li><strong>Orthogonality:</strong> <span class="math inline">\(R^T R = I\)</span> (the columns are orthonormal and preserve lengths).</li>
<li><strong>Orientation-Preserving:</strong> <span class="math inline">\(\det(R) = +1\)</span> (prevents reflections).</li>
</ol>
<p><br></p>
<p><strong>3. Group Extensions</strong></p>
<ul>
<li><strong><span class="math inline">\(O(3)\)</span> extension of <span class="math inline">\(SO(3)\)</span>:</strong> <span class="math inline">\(O(3)\)</span> adds reflection transformations to <span class="math inline">\(SO(3)\)</span>, allowing the matrix determinant to be <span class="math inline">\(-1\)</span> instead of strictly <span class="math inline">\(+1\)</span>.</li>
<li><strong><span class="math inline">\(E(3)\)</span> extension of <span class="math inline">\(O(3)\)</span>:</strong> <span class="math inline">\(E(3)\)</span> adds translation transformations to <span class="math inline">\(O(3)\)</span>, shifting objects in space rather than just rotating or reflecting them around the origin.</li>
</ul>
<p>One precision note: <span class="math inline">\(O(3)\)</span> doesn’t just “add” reflections — it’s the full group of distance-preserving linear maps, with <span class="math inline">\(SO(3)\)</span> as the index-2 subgroup of orientation-preserving elements. And <span class="math inline">\(E(3)\)</span> is a semidirect product <span class="math inline">\(\mathbb{R}^3 \rtimes O(3)\)</span>, not a direct product, because translations and rotations don’t commute.</p>
<hr>
<p>In Stage 2, from the geometric manipulation and verification phase, we have established and proven the fundamental properties of 3D spatial transformations required to analyze model invariance and equivariance:</p>
<ul>
<li><p><strong>Euclidean Transformation Engine:</strong> We implemented the three foundational operations of the Euclidean group (<span class="math inline">\(E(3)\)</span>) using vectorized PyTorch operations:</p>
<ul>
<li><strong>Rotation:</strong> Modeled via matrix multiplication (<span class="math inline">\(X \cdot R^T\)</span>) using an orthogonal matrix <span class="math inline">\(R \in \text{SO}(3)\)</span>.</li>
<li><strong>Reflection:</strong> Handled by inverting the sign of a specified coordinate hyperplane axis.</li>
<li><strong>Translation:</strong> Executed via PyTorch tensor broadcasting (<span class="math inline">\(X + t\)</span>) to shift global positioning.</li>
</ul></li>
<li><p><strong>Rigid Rotation Generation:</strong> We built a robust random rotation generator utilizing <strong>QR matrix decomposition</strong> on a random normal matrix. By explicitly checking and correcting the sign of the determinant (<span class="math inline">\(\det(Q) = 1\)</span>), we ensured that the matrix yields a true rigid rotation rather than an accidental mirror reflection.</p></li>
<li><p><strong>Geometric Invariance Proof:</strong> Through visual plotting and mathematical assertion, we verified that these transformations preserve local structure. Specifically, calculating the pairwise distance matrices (<span class="math inline">\(\text{CDist}\)</span>) before and after translation returned an exact match (<code>True</code>). This mathematically guarantees that the operations are isometric—shifting, rotating, or flipping the point clouds without introducing geometric warping, stretching, or structural distortion.</p></li>
</ul>
<hr>
</section>
<section id="stage-3---equivariance-vs.-invariance-checkers" class="level3">
<h3 class="anchored" data-anchor-id="stage-3---equivariance-vs.-invariance-checkers">Stage 3 - Equivariance vs.&nbsp;Invariance Checkers</h3>
<p>Here, we implement a formal numerical equivariance checker: a function <code>check_equivariance(f, transform, x)</code> that verifies whether f(transform(x)) ≈ transform(f(x)) up to tolerance. Implement a formal invariance checker: <code>check_invariance(f, transform, x)</code> that verifies f(transform(x)) ≈ f(x). These two functions will be reused throughout the project as the ground-truth test for every architectural component.</p>
<p><br></p>
</section>
<section id="questions-3" class="level3">
<h3 class="anchored" data-anchor-id="questions-3">Questions [3]</h3>
<ol type="1">
<li><p>State the formal definition of equivariance using group action notation. If <span class="math inline">\(G\)</span> acts on input space <span class="math inline">\(X\)</span> via <span class="math inline">\(\rho_X\)</span> and on output space <span class="math inline">\(Y\)</span> via <span class="math inline">\(\rho_Y\)</span>, what equation must hold for <span class="math inline">\(f: X \to Y\)</span> to be <span class="math inline">\(G\)</span>-equivariant?</p></li>
<li><p>For molecular property prediction (e.g., predicting the energy of a molecule), should the output head be equivariant or invariant under <span class="math inline">\(E(3)\)</span> — and why? What breaks if you get this wrong?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-3" class="level3">
<h3 class="anchored" data-anchor-id="answers-3">Answers [3]</h3>
<p><strong>1. Formal Definition of Equivariance</strong></p>
<p>For a function <span class="math inline">\(f: X \to Y\)</span> to be <span class="math inline">\(G\)</span>-equivariant, the following equation must hold for all <span class="math inline">\(g \in G\)</span> and all <span class="math inline">\(x \in X\)</span>:</p>
<p><span class="math display">\[f(\rho_X(g) \cdot x) = \rho_Y(g) \cdot f(x)\]</span></p>
<p><br></p>
<p><strong>2. Molecular Property Prediction Symmetries</strong></p>
<ul>
<li><strong>The Correct Choice:</strong> The output head must be <strong>invariant</strong> under <span class="math inline">\(E(3)\)</span>.</li>
<li><strong>Why:</strong> Molecular energy is a scalar quantity that depends only on the relative spatial configuration of the atoms, not on where the molecule is located or how it is rotated in space.</li>
<li><strong>What Breaks:</strong> If you use an equivariant head (or a non-symmetric model), translating or rotating the molecule changes its predicted energy, violating the physical laws of conservation of energy.</li>
</ul>
<hr>
<p>In Stage 3, from the design and verification of the symmetry-testing framework, we have established rigorous methods to evaluate how models handle geometric transformations:</p>
<ul>
<li><p><strong>Symmetry Testing Suite:</strong> We designed and implemented two algorithmic checkers to mathematically evaluate any function <span class="math inline">\(f\)</span> under spatial transformations <span class="math inline">\(T\)</span>:</p>
<ul>
<li><strong>Equivariance (<span class="math inline">\(f(T(x)) \approx T(f(x))\)</span>):</strong> Verifies that the output transforms in exact alignment with the input.</li>
<li><strong>Invariance (<span class="math inline">\(f(T(x)) \approx f(x)\)</span>):</strong> Verifies that the output remains entirely unaffected by spatial modifications.</li>
</ul></li>
<li><p><strong>Baseline Mathematical Verification:</strong> We confirmed the precision of our testing suite against known geometric operations using a floating-point tolerance threshold (<span class="math inline">\(atol\)</span>):</p></li>
<li><p>The <strong>pairwise distance matrix</strong> calculation (<span class="math inline">\(\text{CDist}\)</span>) was proven to be strictly <strong>invariant</strong> under random rotation (<code>True</code>), as rigid transformations preserve local lengths.</p></li>
<li><p>The <strong>identity function</strong> was proven to be strictly <strong>equivariant</strong> under rotation (<code>True</code>), showing an absolute error of exactly zero.</p></li>
<li><p><strong>Data Edge-Cases and Validation Rigor:</strong> Testing intentionally challenging counter-examples revealed a critical nuance in geometric deep learning:</p>
<ul>
<li>The global centroid function (<code>mean_fn</code>) unexpectedly passed <em>both</em> equivariance and invariance tests. It was invariant because our dataset was already perfectly pre-centered at <span class="math inline">\((0,0,0)\)</span> in Stage 1, highlighting that data normalization choices can introduce false positives in symmetry testing.</li>
<li>The distance-from-origin function (<code>broken_fn</code>) successfully failed the equivariance test (<code>False</code> with a massive error of <span class="math inline">\(2.72\)</span>), mathematically confirming that discarding directional information while retaining spatial coordinate shapes destroys geometric equivariance.</li>
</ul></li>
</ul>
<p>Cell 12 Code:</p>
<pre><code># cell 12 — deliberately break equivariance to confirm the checker catches failures
# global mean is invariant, not equivariant — checker must return False
mean_fn = lambda p: p.mean(dim=0, keepdim=True).expand_as(p)

passed, err = check_equivariance(mean_fn, rotate_fn, pts)
print(f"constant-mean equivariant (should be False): {passed} (max err {err:.2e})")

passed, err = check_invariance(mean_fn, rotate_fn, pts)
print(f"constant-mean invariant (should be False): {passed} (max err {err:.2e})")</code></pre>
<p>Cell 12 Output:</p>
<pre><code>constant-mean equivariant (should be False): True  (max err 9.52e-10)
constant-mean invariant (should be False):   True  (max err 6.05e-08)</code></pre>
<p>Cell 12.5 Fix:</p>
<p>Think about what <code>mean_fn</code> actually computes:</p>
<pre><code>mean_fn = lambda p: p.mean(dim=0, keepdim=True).expand_as(p)</code></pre>
<p>This returns a tensor where <em>every row is the global mean</em> <span class="math inline">\(\bar{x} = \frac{1}{N}\sum_i x_i\)</span>.</p>
<p>Is <span class="math inline">\(R\bar{x} = \overline{Rx}\)</span>? Work it out — that’s exactly why both tests pass and why this is actually a <em>correct</em> equivariant/invariant function, not a broken one.</p>
<p>We need a function that genuinely breaks equivariance. A classic example: take the norm of each point independently.</p>
<pre><code># ‖x_i‖ is invariant per point, so the output doesn't transform with R
broken_fn = lambda p: p.norm(dim=1, keepdim=True).expand_as(p)

passed, err = check_equivariance(broken_fn, rotate_fn, pts)
print(f"norm-expand equivariant (should be False): {passed}  (max err {err:.2e})")</code></pre>
<p><strong>Why this <code>broken_fn</code> is <em>not</em> equivariant and what does equivariance require the output to do under rotation, and what does this function’s output actually do?</strong></p>
<p>Equivariance requires: if you rotate the input, the output rotates by the same <span class="math inline">\(R\)</span>. Concretely, <span class="math inline">\(f(Rp)\)</span> must equal <span class="math inline">\(Rf(p)\)</span>.</p>
<p><code>broken_fn</code> outputs <span class="math inline">\(\|x_i\|\)</span> broadcast across all 3 coordinates. Since <span class="math inline">\(\|Rx_i\| = \|x_i\|\)</span> (rotations are isometries), rotating the input changes nothing — <span class="math inline">\(f(Rp) = f(p)\)</span>. But <span class="math inline">\(Rf(p)\)</span> rotates those norm values as if they were 3D vectors, producing something different. The function is actually <em>invariant per point</em>, which is strictly weaker than equivariant. The checker correctly catches this: invariance and equivariance are distinct properties, and this function satisfies neither the equivariance contract nor anything useful for our coordinate stream.</p>
<p><strong>THE KEY POINT:</strong> the original <code>mean_fn</code> passed both tests because linear maps commute with rotation — <span class="math inline">\(R\bar{x} = \overline{Rx}\)</span> exactly. It was never broken; it was a bad choice of counterexample. A genuine failure requires a function that discards directional information, which <code>norm-expand</code> does.</p>
<hr>
</section>
<section id="stage-4---graph-construction-from-point-cloud-k-nn-graph" class="level3">
<h3 class="anchored" data-anchor-id="stage-4---graph-construction-from-point-cloud-k-nn-graph">Stage 4 - Graph Construction from Point Cloud (k-NN Graph)</h3>
<p>We build a k-nearest-neighbor graph over each point cloud: for each point, connect it to its k=20 nearest neighbors by Euclidean distance. Compute edge vectors (relative positions) <span class="math inline">\(r_{ij} = x_j - x_i \quad \text{and edge lengths} \quad d_{ij} = \lVert r_{ij} \rVert\)</span></p>
<p>We inspect the resulting graph structure: node count, edge count, degree distribution. We’re imposing the minimal structure needed for message passing: a k-NN graph over each point cloud, plus edge vectors and edge lengths.</p>
<p><br></p>
</section>
<section id="questions-4" class="level3">
<h3 class="anchored" data-anchor-id="questions-4">Questions [4]</h3>
<ol type="1">
<li><p>Of these two edge features — the edge vector <span class="math inline">\(r_{ij} = x_j - x_i \in \mathbb{R}^3\)</span> and the edge length <span class="math inline">\(d_{ij} = \|r_{ij}\| \in \mathbb{R}\)</span> — which is invariant under rotation and which is equivariant?</p></li>
<li><p>If we discard <span class="math inline">\(r_{ij}\)</span> and use only <span class="math inline">\(d_{ij}\)</span> as the edge feature, what geometric information is lost — and does that loss break the equivariance of the network?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-4" class="level3">
<h3 class="anchored" data-anchor-id="answers-4">Answers [4]</h3>
<p><strong>1. Invariance vs.&nbsp;Equivariance of Edge Features</strong></p>
<ul>
<li><p><strong><span class="math inline">\(d_{ij}\)</span> (Edge Length) is invariant:</strong> Rotating the points does not change the distance between them (<span class="math inline">\(\|R x_j - R x_i\| = \|R(x_j - x_i)\| = \|x_j - x_i\|\)</span>).</p></li>
<li><p><strong><span class="math inline">\(r_{ij}\)</span> (Edge Vector) is equivariant:</strong> Rotating the points rotates the resulting vector in an identical manner (<span class="math inline">\(R x_j - R x_i = R(x_j - x_i) = R r_{ij}\)</span>).</p></li>
</ul>
<p><br></p>
<p><strong>2. Information Loss from Discarding <span class="math inline">\(r_{ij}\)</span></strong></p>
<ul>
<li><p><strong>What is lost:</strong> You lose all <strong>angular/directional orientation</strong> information between edges. The network can no longer resolve the relative angles between different neighbor points (e.g., it cannot distinguish between a flat, planar molecule and a puckered, non-planar molecule if all pairwise distances happen to match).</p></li>
<li><p><strong>Impact on Equivariance:</strong> No, it does not break equivariance. Because <span class="math inline">\(d_{ij}\)</span> is strictly invariant, any network processing it remains trivially equivariant (specifically, invariant) because transforming the input yields a predictably unchanged output. However, it severely limits the network’s expressive power to capture 3D geometric shapes.</p></li>
</ul>
<hr>
<p>In Stage 4, from the graph topological construction and validation phase, we have established how to transform raw unstructured 3D points into structured, localized networks suitable for Geometric Deep Learning:</p>
<ul>
<li><p><strong>Graph Topological Construction:</strong> We successfully generated a local spatial neighborhood structure using a <strong><span class="math inline">\(k\)</span>-Nearest Neighbors (<span class="math inline">\(k\)</span>-NN)</strong> algorithm (<span class="math inline">\(k=20\)</span>). This converted an isolated 1,024-point cloud into a connected graph mapped by an <code>edge_index</code> matrix tracking exactly <strong>20,480 directed connections</strong>.</p></li>
<li><p><strong>Decoupled Geometric Features:</strong> We extracted two fundamental local edge properties required for graph message passing, isolating directional and scaling attributes:</p>
<ul>
<li><strong>Relative Edge Vectors (<span class="math inline">\(r_{ij} = x_j - x_i\)</span>):</strong> A matrix of shape <code>[20480, 3]</code> capturing local spatial orientation. It is strictly <strong>rotation-equivariant</strong>.</li>
<li><strong>Absolute Edge Lengths (<span class="math inline">\(d_{ij} = \|r_{ij}\|\)</span>):</strong> A matrix of shape <code>[20480, 1]</code> capturing local scale. It is strictly <strong>rotation-invariant</strong>.</li>
</ul></li>
<li><p><strong>Graph Degree Heterogeneity:</strong> Analyzing the network’s degree distribution showed an exact mathematical average of 20.0 connections per node. However, we discovered structural variation ranging from an absolute minimum degree of 5 (isolated points on sparse edges like wingtips) to a maximum degree of 41 (dense structural hubs like the fuselage junction), proving that spatial graphs natively adapt to varying local densities.</p></li>
<li><p><strong>Topological and Vectorial Equivariance Proof:</strong> Using our Stage 3 verification suite, we mathematically validated the structural stability of the graph under random 3D rotations:</p>
<ul>
<li><strong>Topology Preservation:</strong> The <span class="math inline">\(k\)</span>-NN connectivity structure is strictly <strong>invariant</strong> under rigid rotation (<code>True</code>), meaning the network map remains identical regardless of how the object is spun.</li>
<li><strong>Vector Equivariance:</strong> The underlying relative edge vectors are strictly <strong>equivariant</strong> (<code>True</code>, with a negligible floating-point error of <span class="math inline">\(1.38 \times 10^{-7}\)</span>), confirming that local geometric directions transform in perfect mathematical synchronization with global coordinates.</li>
</ul></li>
</ul>
<hr>
</section>
<section id="stage-5---egnn-message-passing-from-scratch" class="level3">
<h3 class="anchored" data-anchor-id="stage-5---egnn-message-passing-from-scratch">Stage 5 - EGNN Message Passing from Scratch</h3>
<p>We now implement the EGNN message passing layer from scratch (no PyG MessagePassing base class, no equivariant layer libraries). The update rule has two coupled streams: a scalar feature stream h and a coordinate stream x. Each layer updates both:</p>
<p><span class="math display">\[
m_{ij} = \phi_e(h_i, h_j, d_{ij}^2)
\]</span></p>
<p><span class="math display">\[
x_i \leftarrow x_i + \sum_j (x_i - x_j) \cdot \phi_x(m_{ij})
\]</span></p>
<p><span class="math display">\[
h_i \leftarrow \phi_h\left(h_i, \sum_j m_{ij}\right)
\]</span></p>
<p>where <span class="math inline">\(\phi_e\)</span>, <span class="math inline">\(\phi_x\)</span>, and <span class="math inline">\(\phi_h\)</span> are learned MLPs.</p>
<p><br></p>
</section>
<section id="questions-5" class="level3">
<h3 class="anchored" data-anchor-id="questions-5">Questions [5]</h3>
<p>Derive the equivariance of the coordinate update algebraically.</p>
<p>The EGNN coordinate update is:</p>
<p><span class="math display">\[x_i \leftarrow x_i + \sum_j (x_i - x_j) \cdot \phi_x(m_{ij})\]</span></p>
<p>where <span class="math inline">\(m_{ij} = \phi_e(h_i, h_j, d_{ij}^2)\)</span> depends only on scalar features and the invariant distance <span class="math inline">\(d_{ij}^2\)</span>.</p>
<p>Now suppose we rotate all input coordinates by <span class="math inline">\(R\)</span>, replacing every <span class="math inline">\(x_k\)</span> with <span class="math inline">\(Rx_k\)</span>. Carry out the substitution on the right-hand side and show that the result equals <span class="math inline">\(R\)</span> applied to the original update. Write out the algebra step by step — don’t skip the distribution over the sum.</p>
<p><br></p>
</section>
<section id="answers-5" class="level3">
<h3 class="anchored" data-anchor-id="answers-5">Answers [5]</h3>
<p>Let the original update function be <span class="math inline">\(f(x_i) = x_i + \sum_j (x_i - x_j) \cdot \phi_x(m_{ij})\)</span>.</p>
<p>We apply a 3D rotation matrix <span class="math inline">\(R \in SO(3)\)</span> to all coordinates, substituting <span class="math inline">\(x_k \to R x_k\)</span>. Because the message scalar <span class="math inline">\(m_{ij}\)</span> relies only on invariant node features and the distance <span class="math inline">\(d_{ij}^2 = \|R x_i - R x_j\|^2 = \|x_i - x_j\|^2\)</span>, the scalar output <span class="math inline">\(\phi_x(m_{ij})\)</span> remains completely unchanged.</p>
<p>Substituting the rotated coordinates into the right-hand side of the update equation:</p>
<p><span class="math display">\[\text{RHS} = (R x_i) + \sum_j \left( (R x_i) - (R x_j) \right) \cdot \phi_x(m_{ij})\]</span></p>
</section>
<section id="step-by-step-algebra" class="level3">
<h3 class="anchored" data-anchor-id="step-by-step-algebra">Step-by-Step Algebra</h3>
<ol type="1">
<li><strong>Factor out <span class="math inline">\(R\)</span> inside the summation:</strong></li>
</ol>
<p><span class="math display">\[\text{RHS} = R x_i + \sum_j \left( R(x_i - x_j) \right) \cdot \phi_x(m_{ij})\]</span></p>
<ol start="2" type="1">
<li><strong>Commute the scalar <span class="math inline">\(\phi_x(m_{ij})\)</span> with the matrix <span class="math inline">\(R\)</span>:</strong></li>
</ol>
<p><span class="math display">\[\text{RHS} = R x_i + \sum_j R \left( (x_i - x_j) \cdot \phi_x(m_{ij}) \right)\]</span></p>
<ol start="3" type="1">
<li><strong>Distribute the matrix <span class="math inline">\(R\)</span> out of the summation (by linearity):</strong></li>
</ol>
<p><span class="math display">\[\text{RHS} = R x_i + R \left( \sum_j (x_i - x_j) \cdot \phi_x(m_{ij}) \right)\]</span></p>
<ol start="4" type="1">
<li><strong>Factor out <span class="math inline">\(R\)</span> from the entire expression:</strong></li>
</ol>
<p><span class="math display">\[\text{RHS} = R \left( x_i + \sum_j (x_i - x_j) \cdot \phi_x(m_{ij}) \right)\]</span></p>
<p>The term inside the parentheses is the original unrotated coordinate update. Therefore:</p>
<p><span class="math display">\[\text{RHS} = R \cdot f(x_i)\]</span></p>
<p>This proves that transforming the input coordinates by <span class="math inline">\(R\)</span> applies the exact same transformation <span class="math inline">\(R\)</span> to the updated coordinates, satisfying the definition of equivariance.</p>
<hr>
<p>In Stage 5, from the architectural design, implementation, and numerical verification of the Equivariant Graph Neural Network (EGNN), we have established how to construct a deep learning system that preserves spatial symmetries:</p>
<ul>
<li><p><strong>Dual-Stream Layer Architecture:</strong> We implemented a custom <code>EGNNLayer</code> based on Satorras et al.&nbsp;(2021) that successfully decouples point cloud updates into two distinct computational pathways:</p>
<ul>
<li><strong>An Invariant Scalar Stream (<span class="math inline">\(h\)</span>):</strong> Updated using a Multi-Layer Perceptron (<span class="math inline">\(\phi_e\)</span>) parameterized by squared local distances (<span class="math inline">\(d_{ij}^2\)</span>), which are strictly unaffected by rotation or translation.</li>
<li><strong>An Equivariant Coordinate Stream (<span class="math inline">\(x\)</span>):</strong> Shifted dynamically along relative displacement vectors (<span class="math inline">\(r_{ij} = x_j - x_i\)</span>) scaled by a learned scalar gate (<span class="math inline">\(\phi_x\)</span>), forcing coordinates to transform predictably in 3D space.</li>
</ul></li>
<li><p><strong>Purely Geometric Feature Learning:</strong> We constructed an end-to-end <code>EGNN</code> backbone model that stacked these layers sequentially. By initializing the scalar stream with uninformative constant features (<span class="math inline">\(\mathbf{1}\)</span>), we forced the network to learn rich structural shape descriptors exclusively from raw 3D geometry (<span class="math inline">\(x\)</span>) during graph message passing.</p></li>
<li><p><strong>Deterministic Symmetry Validation:</strong> Using our Stage 3 verification framework, we subjected the complete network to random 3D rotations, mathematically proving its spatial correctness:</p>
<ul>
<li><strong>Coordinate Equivariance:</strong> The structural coordinate stream returned <code>True</code> (<span class="math inline">\(max\ err = 1.19 \times 10^{-7}\)</span>), confirming that local geometric updates track global rotations perfectly.</li>
<li><strong>Classification Invariance:</strong> The final classification head returned <code>True</code> (<span class="math inline">\(max\ err = 8.94 \times 10^{-8}\)</span>), mathematically proving that the model outputs identical classification logits regardless of how the 3D shape is oriented in space.</li>
</ul></li>
</ul>
<hr>
</section>
<section id="stage-6---invariant-and-equivariant-output-heads" class="level3">
<h3 class="anchored" data-anchor-id="stage-6---invariant-and-equivariant-output-heads">Stage 6 - Invariant and Equivariant Output Heads</h3>
<p>We now implement two separate output heads on top of the EGNN backbone:</p>
<ul>
<li>An invariant head: global mean-pool the scalar features <span class="math inline">\(h_i\)</span> <span class="math inline">\(\to\)</span> predict class label (for classification).</li>
<li>An equivariant head: aggregate the coordinate stream <span class="math inline">\(x_i\)</span> <span class="math inline">\(\to\)</span> predict a 3D vector output (e.g., center of mass displacement).</li>
</ul>
<p>We run both through our <code>check_invariance</code> and <code>check_equivariance</code> functions respectively and confirm they pass.</p>
<p><br></p>
</section>
<section id="questions-6" class="level3">
<h3 class="anchored" data-anchor-id="questions-6">Questions [6]</h3>
<p>Global mean pooling of scalar features <span class="math inline">\(h_i\)</span> is used for classification. Global mean pooling of coordinate features <span class="math inline">\(x_i\)</span> would give a 3D vector output. Explain why:</p>
<ol type="1">
<li>Mean pooling <span class="math inline">\(h_i\)</span> is invariant to both permutation and rotation</li>
<li>Mean pooling <span class="math inline">\(x_i\)</span> is equivariant to rotation but not invariant</li>
</ol>
<p>Be precise — what does the pooled coordinate vector actually represent geometrically, and why does rotating the point cloud rotate that vector?</p>
<p><br></p>
</section>
<section id="answers-6" class="level3">
<h3 class="anchored" data-anchor-id="answers-6">Answers [6]</h3>
<p><strong>1. Invariance of Mean Pooled Scalar Features (<span class="math inline">\(h_i\)</span>)</strong></p>
<ul>
<li><p><strong>Permutation Invariance:</strong> The average operation (<span class="math inline">\(\frac{1}{N}\sum_{i=1}^N h_i\)</span>) is commutative and associative. Changing the order or indexing of the nodes does not change the sum or the final average.</p></li>
<li><p><strong>Rotation Invariance:</strong> The scalar features <span class="math inline">\(h_i\)</span> are internal node properties (like chemical element type or local density) that do not depend on spatial coordinates. Rotating the point cloud leaves every <span class="math inline">\(h_i\)</span> completely unchanged, making their mean inherently invariant.</p></li>
</ul>
<p><br></p>
<p><strong>2. Equivariance of Mean Pooled Coordinates (<span class="math inline">\(x_i\)</span>)</strong></p>
<p><strong>Geometric Representation:</strong> The pooled coordinate vector <span class="math inline">\(\bar{x} = \frac{1}{N}\sum_{i=1}^N x_i\)</span> represents the <strong>geometric centroid</strong> (center of mass) of the point cloud.</p>
<p><strong>Why Rotation Rotates the Vector?</strong></p>
<p>If you rotate every point in the cloud by a rotation matrix <span class="math inline">\(R\)</span>, the new pooled vector becomes:</p>
<p><span class="math display">\[\bar{x}_{\text{rotated}} = \frac{1}{N}\sum_{i=1}^N (R x_i) = R \left( \frac{1}{N}\sum_{i=1}^N x_i \right) = R \bar{x}\]</span></p>
<p>Because the rotation matrix factors out of the summation due to linearity, rotating the individual points shifts the center of mass by that exact same rotation. It is not invariant because the output vector physically changes position, but it is strictly equivariant because the output changes in lockstep with the input.</p>
<hr>
<p>Stage 6 concluded the architectural blueprint of our Equivariant Graph Neural Network (EGNN) by designing, wiring, and verifying specialized pooling and projection layers. These layers map internal graph features to downstream tasks without disrupting the geometric symmetries maintained by the upstream backbone.</p>
<p><br></p>
<p><strong>1. Invariant Downstream Reasoning (Classification)</strong></p>
<p>We implemented an <code>InvariantHead</code> to compress local, point-level structural embeddings into global shape descriptors:</p>
<ul>
<li><strong>Mathematical Invariance via Permutation Symmetry:</strong> The head utilizes a global mean pooling operator over the scalar feature stream:</li>
</ul>
<p><span class="math display">\[\text{global\_mean\_pool}(h) = \frac{1}{N} \sum_{i=1}^{N} h_i\]</span></p>
<p>Because addition is commutative, this averaging step is inherently invariant to node ordering and permutations.</p>
<ul>
<li><p><strong>Preservation of Rotation Invariance:</strong> Since the incoming hidden scalar attributes <span class="math inline">\(h\)</span> are explicitly decoupled from coordinate orientations within the <code>EGNNLayer</code> message-passing loop, their global average is completely static under spatial transformations.</p></li>
<li><p><strong>Logit Mapping:</strong> Passing this invariant descriptor through a Multi-Layer Perceptron (MLP) with SiLU activations computes classification confidence scores (logits) that depend strictly on structural topology, not physical orientation.</p></li>
</ul>
<p><br></p>
<p><strong>2. Equivariant Spatial Tracking (Regression)</strong></p>
<p>We designed an <code>EquivariantHead</code> to handle physical tasks such as coordinate tracking, trajectory estimation, or center-of-mass localization:</p>
<ul>
<li><strong>Vector Equivariance via Linear Pooling:</strong> The head applies global mean pooling directly over the transformed 3D coordinate stream <span class="math inline">\(x\)</span>:</li>
</ul>
<p><span class="math display">\[\vec{x}_{\text{centroid}} = \frac{1}{N} \sum_{i=1}^{N} x_i\]</span></p>
<ul>
<li><strong>Rigid Transformation Scaling:</strong> Because a rigid 3D rotation matrix <span class="math inline">\(R\)</span> distributes linearly over addition, calculating the centroid of a rotated point cloud yields the exact same vector as rotating the original centroid:</li>
</ul>
<p><span class="math display">\[\frac{1}{N} \sum_{i=1}^{N} R x_i = R \left( \frac{1}{N} \sum_{i=1}^{N} x_i \right)\]</span></p>
<p>This enables the network to output spatial coordinate predictions that rotate and translate in perfect harmony with the input space without requiring any learnable parameters.</p>
<p><br></p>
<p><strong>3. Verification Suite Proofs</strong></p>
<p>Using the symmetry-testing suite established in Stage 3, we subjected the fully integrated multi-task model to random 3D rotations, yielding deterministic mathematical verification of both paths:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Model Component</th>
<th>Target Symmetry Property</th>
<th>Pass Status</th>
<th>Maximum Numerical Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><code>InvariantHead</code></strong></td>
<td>Invariance (<span class="math inline">\(f(R \cdot p) \approx f(p)\)</span>)</td>
<td><strong><code>True</code></strong></td>
<td><span class="math inline">\(1.19 \times 10^{-7}\)</span></td>
</tr>
<tr class="even">
<td><strong><code>EquivariantHead</code></strong></td>
<td>Equivariance (<span class="math inline">\(f(R \cdot p) \approx R \cdot f(p)\)</span>)</td>
<td><strong><code>True</code></strong></td>
<td><span class="math inline">\(3.43 \times 10^{-9}\)</span></td>
</tr>
</tbody>
</table>
<p>The minuscule absolute errors confirm that our model can simultaneously extract invariant categorical labels and equivariant spatial vectors from a unified geometric graph representation, bounded only by standard 32-bit floating-point rounding limits (<span class="math inline">\(10^{-7}\)</span>).</p>
<hr>
</section>
<section id="stage-7---tangent-bundle-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="stage-7---tangent-bundle-interpretation">Stage 7 - Tangent Bundle Interpretation</h3>
<p>For one point cloud, we treat each point’s k-NN neighborhood as a local coordinate chart. We compute the local PCA frame (3 principal axes) for that neighborhood. Then, we visualize the local frame as arrows overlaid on the point cloud. This is the tangent bundle made concrete: each point has a local “coordinate system” defined by its neighborhood geometry. We’re grounding the architecture in differential geometry: making the connection between the abstract notion of a tangent bundle and what we’re actually computing on point clouds.</p>
<p><br></p>
</section>
<section id="questions-7" class="level3">
<h3 class="anchored" data-anchor-id="questions-7">Questions [7]</h3>
<p>For a smooth manifold <span class="math inline">\(M\)</span>, the tangent bundle <span class="math inline">\(TM = \bigsqcup_{p \in M} T_pM\)</span> assigns a tangent space to every point.</p>
<ol type="1">
<li><p>What lives at each point <span class="math inline">\(p \in M\)</span> in the tangent bundle — what is <span class="math inline">\(T_pM\)</span> geometrically, and what does a basis for <span class="math inline">\(T_pM\)</span> represent?</p></li>
<li><p>A point cloud has no smooth structure. Explain how the local PCA frame of a k-NN neighborhood around point <span class="math inline">\(x_i\)</span> serves as a discrete approximation of <span class="math inline">\(T_{x_i}M\)</span> — specifically, what do the three principal axes correspond to geometrically, and why is the smallest-variance axis particularly meaningful for surface data?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-7" class="level3">
<h3 class="anchored" data-anchor-id="answers-7">Answers [7]</h3>
<p><strong>1. Geometrical Nature of the Tangent Space</strong></p>
<ul>
<li><p><strong>What <span class="math inline">\(T_pM\)</span> is geometrically:</strong> For a 2D surface manifold embedded in 3D space, <span class="math inline">\(T_pM\)</span> is a flat 2D plane that kisses the surface perfectly at point <span class="math inline">\(p\)</span>. It contains the velocity vectors of all smooth paths moving through <span class="math inline">\(p\)</span>.</p></li>
<li><p><strong>What a basis represents:</strong> A basis for <span class="math inline">\(T_pM\)</span> represents a coordinate frame for local directions along the surface. For example, on a globe, a standard basis at your position could be a unit vector pointing directly North and a unit vector pointing directly East.</p></li>
</ul>
<p><br></p>
<p><strong>2. Discrete Approximation via Local PCA</strong></p>
<p>When you run PCA on the <span class="math inline">\(k\)</span>-nearest neighbors of a point <span class="math inline">\(x_i\)</span>, you calculate three orthogonal principal axes (eigenvectors of the local covariance matrix):</p>
<ul>
<li><p><strong>First two principal axes (Highest Variance):</strong> These two axes span the directions where the neighboring points scatter the most. They approximate the flat 2D tangent plane (<span class="math inline">\(T_{x_i}M\)</span>) across the underlying surface.</p></li>
<li><p><strong>Third principal axis (Smallest Variance):</strong> This axis captures the direction of minimum data scatter. For a clean, non-noisy 2D surface, the points do not deviate significantly out of their plane, meaning the variation along this axis is near zero.</p></li>
<li><p><strong>Meaning of the smallest-variance axis:</strong> This axis corresponds directly to the <strong>surface normal vector</strong> at <span class="math inline">\(x_i\)</span>. It is highly meaningful because estimating this normal allows algorithms to reconstruct surface orientation, calculate lighting, and compute geometric curvatures without an explicit mesh structure.</p></li>
</ul>
<hr>
<p>Stage 7 introduced an alternative paradigm for achieving geometric robustness in 3D deep learning: <strong>Local Reference Frames (LRFs)</strong>. Rather than relying on architectural constraints to maintain symmetry (as done with the EGNN dual-stream architecture), this approach uses localized unsupervised geometry to construct invariant surface representations.</p>
<p><br></p>
<p><strong>1. Mathematical Formulation of Local PCA Frames</strong></p>
<p>We developed a deterministic method (<code>local_pca_frame</code>) to map raw spatial coordinates to an anchored, localized 3D coordinate system for any target node <span class="math inline">\(i\)</span>:</p>
<ul>
<li><p><strong>Neighborhood Isolation:</strong> For a target point <span class="math inline">\(x_i\)</span>, a local spatial context is isolated using a <span class="math inline">\(k\)</span>-NN graph (<span class="math inline">\(k=20\)</span>), yielding a neighborhood matrix <span class="math inline">\(X_i \in \mathbb{R}^{k \times 3}\)</span>.</p></li>
<li><p><strong>Centroid Alignment (Translation Invariance):</strong> The neighborhood is centered around its local mean vector to eliminate absolute positional dependencies:</p></li>
</ul>
<p><span class="math display">\[X_{i,\text{centered}} = X_i - \frac{1}{k}\sum_{j \in \mathcal{N}(i)} x_j\]</span></p>
<ul>
<li><strong>Covariance Computation:</strong> A structural <span class="math inline">\(3 \times 3\)</span> covariance matrix <span class="math inline">\(\Sigma_i\)</span> is constructed to measure spatial dispersion:</li>
</ul>
<p><span class="math display">\[\Sigma_i = \frac{1}{k-1} X_{i,\text{centered}}^T X_{i,\text{centered}}\]</span></p>
<ul>
<li><strong>Eigendecomposition:</strong> Performing an eigenvalue decomposition yields the local frame:</li>
</ul>
<p><span class="math display">\[\Sigma_i V_i = V_i \Lambda_i\]</span></p>
<p>Where <span class="math inline">\(V_i = [v_1, v_2, v_3] \in \mathbb{R}^{3 \times 3}\)</span> represents the orthogonal eigenvectors (principal axes), and <span class="math inline">\(\Lambda_i = \text{diag}(\lambda_1, \lambda_2, \lambda_3)\)</span> contains the eigenvalues sorted in ascending order (<span class="math inline">\(\lambda_1 \le \lambda_2 \le \lambda_3\)</span>).</p>
<p><br></p>
<p><strong>2. Geometric Interpretation and Properties</strong></p>
<p>Inspecting and visualizing the extracted frame at node index 0 revealed distinct geometric attributes:</p>
<ul>
<li><p><strong>Surface Normal Approximation:</strong> The first principal component (<span class="math inline">\(v_1\)</span>), corresponding to the minimum eigenvalue (<span class="math inline">\(\lambda_1 = 0.00114\)</span>), defines the axis of least variance. On dense 3D manifolds, this vector acts as an unoriented estimate of the <strong>surface normal</strong>.</p></li>
<li><p><strong>Flatness Quantified:</strong> The variance ratio along this normal axis was calculated as:</p></li>
</ul>
<p><span class="math display">\[\frac{\lambda_1}{\sum \lambda_m} = 0.2455\]</span></p>
<p>Since this value is strictly below <span class="math inline">\(\frac{1}{3}\)</span> (<span class="math inline">\(0.3333\)</span>), it proves the local neighborhood forms a valid, relatively flat localized tangent plane rather than a spherical volume. * <strong>Orthonormality Verification:</strong> The orthogonality and unit scaling of the coordinate axes were confirmed via:</p>
<p><span class="math display">\[V_i^T V_i = I_3\]</span></p>
<p>This returns <code>True</code>, proving that the frame is a valid metric space that will not distort spatial features when used for coordinate projections.</p>
<p><br></p>
<p><strong>3. Subspace Equivariance Under Rotation</strong></p>
<p>Eigenvector computation introduces an inherent sign-flip ambiguity: both <span class="math inline">\(v\)</span> and <span class="math inline">\(-v\)</span> satisfy the directional requirements of the covariance matrix. Consequently, standard rigid rotation verification using direct element-wise equality will fail if a sign inversion occurs during numerical optimization.</p>
<p>To robustly validate the rotation-equivariance of the LRF, we implemented a <strong>subspace agreement test</strong> utilizing the determinant of the overlap matrix between the explicitly rotated frame (<span class="math inline">\(V_{\text{rot}}\)</span>) and the globally transformed original frame (<span class="math inline">\(R \cdot V_{\text{orig}}\)</span>):</p>
<p><span class="math display">\[\left| \det\left( V_{\text{rot}}^T \cdot (R \cdot V_{\text{orig}}) \right) \right| = 1.0\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric / Check</th>
<th style="text-align: left;">Value / Status</th>
<th style="text-align: left;">Geometric Implication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Subspace Agreement <span class="math inline">\(\lvert\det\rvert\)</span></td>
<td style="text-align: left;"><strong><code>1.000000</code></strong></td>
<td style="text-align: left;">The frames span the exact same oriented physical subspace.</td>
</tr>
<tr class="even">
<td style="text-align: left;">PCA Frame Equivariance</td>
<td style="text-align: left;"><strong><code>True</code></strong></td>
<td style="text-align: left;">Constructing an LRF after rotation is equivalent to rotating the original LRF.</td>
</tr>
</tbody>
</table>
<p>This mathematically proves that the local PCA frame functions as a perfectly <strong>rotation-equivariant</strong> base platform. By projecting surrounding relative coordinates onto these localized axes (<span class="math inline">\(V_i^T \cdot r_{ij}\)</span>), a neural network can extract deep 3D structural representations that are entirely <strong>invariant</strong> to global rigid transformations.</p>
<hr>
</section>
<section id="stage-8---pointnet-baseline-non-equivariant" class="level3">
<h3 class="anchored" data-anchor-id="stage-8---pointnet-baseline-non-equivariant">Stage 8 - PointNet Baseline (Non-Equivariant)</h3>
<p>We implement a PointNet baseline from scratch: shared MLP applied independently to each point, followed by global max-pooling, followed by a classification MLP. This architecture is permutation-invariant but NOT rotation-equivariant. We’re building the foil to EGNN. PointNet’s architecture is elegant and historically important — but it has a specific, diagnosable failure mode under rotation that the Stage 9 experiment will quantify.</p>
<p><br></p>
</section>
<section id="questions-8" class="level3">
<h3 class="anchored" data-anchor-id="questions-8">Questions [8]</h3>
<p>PointNet applies a shared MLP independently to each point, then aggregates with global max-pooling.</p>
<p>Predict what happens to PointNet’s classification accuracy when test-time point clouds are randomly rotated by arbitrary <span class="math inline">\(SO(3)\)</span> rotations — and give a geometric argument for <em>why</em>. Specifically:</p>
<ul>
<li>Global max-pooling gives permutation invariance. Does it give any protection against rotation? Why or why not?</li>
<li>During training on aligned data, what does the shared MLP effectively learn about each point’s coordinates — and why does that learned representation fail when the object arrives rotated at test time?</li>
</ul>
<p><br></p>
</section>
<section id="answers-8" class="level3">
<h3 class="anchored" data-anchor-id="answers-8">Answers [8]</h3>
<p><strong>What happens when PointNet encounter arbitrary rotations?</strong></p>
<p>If PointNet is trained on aligned data (e.g., all chairs facing forward) and tested on randomly rotated data, its classification accuracy <strong>drops drastically</strong>.</p>
<p><br></p>
<p><strong>1. Does Global Max-Pooling protect against rotation?</strong></p>
<ul>
<li><p><strong>The Answer:</strong> No, it offers absolutely zero protection against rotations.</p></li>
<li><p><strong>Geometric Argument:</strong> Global max-pooling only ensures <strong>permutation invariance</strong> (the order you list the points does not matter). It calculates the maximum feature value across all points <em>independently for each feature channel</em>. It does not look at spatial relationships between points. If you rotate the object, the underlying spatial coordinates (<span class="math inline">\(x, y, z\)</span>) feed completely different values into the shared MLP. The max-pooling operation simply takes the maximum values of these corrupted features, resulting in an entirely different, unpredictable global feature vector.</p></li>
</ul>
<p><strong>2. What the shared MLP learns and why it fails?</strong></p>
<ul>
<li><p><strong>What it learns during training:</strong> When trained on perfectly aligned objects, the shared MLP effectively learns to partition the absolute 3D bounding box of the dataset. It creates axis-aligned bounding boundaries in coordinate space. For example, it might learn a rule like: <em>“If a point has a very high <span class="math inline">\(z\)</span> coordinate and centered <span class="math inline">\(x,y\)</span> coordinates, it represents the top headrest of a chair.”</em></p></li>
<li><p><strong>Why it fails at test time:</strong> Absolute coordinates are not invariant. If the chair is rotated upside down, the points forming the headrest now have a very low <span class="math inline">\(z\)</span> coordinate. The shared MLP interprets these points based on their new absolute locations in space, mistaking the headrest for the legs of the chair. Because PointNet lacks structural equivariance or relative coordinate tracking, it completely misinterprets the geometry when the absolute coordinate frames no longer align with training.</p></li>
</ul>
<hr>
<p>Stage 8 established an empirical baseline comparison between a standard 3D deep learning model (<strong>PointNet</strong>) and our geometric architecture (<strong>EGNN</strong>). By subjecting both networks to deterministic permutation and rigid rotation transformations, we demonstrated the practical differences between structural graph processing and raw coordinate modeling.</p>
<p><br></p>
<p><strong>1. PointNet Structural Properties and Permutation Invariance</strong></p>
<p>We implemented a standard <code>PointNet</code> baseline architecture designed to process unordered point sets directly without constructing a spatial adjacency graph:</p>
<ul>
<li><strong>Per-Point Feature Lifting:</strong> Absolute spatial coordinates <span class="math inline">\(x \in \mathbb{R}^{N \times 3}\)</span> are projected independently into a high-dimensional latent space via a shared Multi-Layer Perceptron (MLP):</li>
</ul>
<p><span class="math display">\[h_i = \text{SharedMLP}(x_i)\]</span></p>
<ul>
<li><strong>The Symmetric Pooling Shield:</strong> To collapse the point dimensions into a unified global shape descriptor, the model applies a global maximum pooling operator:</li>
</ul>
<p><span class="math display">\[h_{\text{graph}} = \max_{i \in \{1, \dots, N\}} (h_i)\]</span></p>
<ul>
<li><strong>Permutation Verification:</strong> Shuffling the row indices of the input matrix (<span class="math inline">\(x_{\text{perm}} = P \cdot x\)</span>, where <span class="math inline">\(P\)</span> is a permutation matrix) yielded an absolute error of exactly <strong><code>0.00e+00</code></strong>, returning <strong><code>True</code></strong> for permutation invariance. Because the max operator is associative and commutative, the global feature vector remains mathematically identical regardless of the order in which nodes are fed to the GPU.</li>
</ul>
<p><br></p>
<p><strong>2. The Failure Mode of Absolute Coordinate Modeling</strong></p>
<p>While PointNet successfully handles unordered data, it processes raw, absolute spatial coordinates directly. This design choice creates a significant vulnerability to rigid spatial transformations:</p>
<ul>
<li><strong>Rotation Sensitivity:</strong> When an object is rotated (<span class="math inline">\(x_{\text{rot}} = x \cdot R^T\)</span>), the absolute values in the coordinate matrix shift completely. Because the linear projection weights within the shared MLP are static, they cannot adapt to global coordinate rotations:</li>
</ul>
<p><span class="math display">\[\text{SharedMLP}(x_i \cdot R^T) \neq \text{SharedMLP}(x_i)\]</span></p>
<ul>
<li><strong>Empirical Verification:</strong> Subjecting PointNet to our rotation verification suite returned <strong><code>False</code></strong>, yielding a significant output logit deviation (<span class="math inline">\(max\ err = 1.20 \times 10^{-2}\)</span>). This proves that standard PointNet cannot generalize across orientations; spinning an object changes the model’s internal representations and shifts its final prediction confidence scores.</li>
</ul>
<p><br></p>
<p><strong>3. Empirical Comparison Suite</strong></p>
<p>To confirm the advantages of geometric deep learning, we evaluated our <code>EGNN</code> architecture under identical conditions. Crucially, the EGNN test dynamically re-computed the underlying <span class="math inline">\(k\)</span>-NN graph structure on the transformed coordinates to ensure that graph reconstruction did not introduce geometric instability.</p>
<p>The final comparative results are summarized in the table below:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Model Architecture</th>
<th>Evaluated Transformation</th>
<th>Target Symmetry Property</th>
<th>Pass Status</th>
<th>Maximum Numerical Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><code>PointNet</code> (Baseline)</strong></td>
<td>Row Index Shuffling (<span class="math inline">\(P \cdot x\)</span>)</td>
<td>Permutation Invariance</td>
<td><strong><code>True</code></strong></td>
<td><span class="math inline">\(0.00 \times 10^{00}\)</span> (Exact)</td>
</tr>
<tr class="even">
<td><strong><code>PointNet</code> (Baseline)</strong></td>
<td>3D Rotation Matrix (<span class="math inline">\(x \cdot R^T\)</span>)</td>
<td>Rotation Invariance</td>
<td><strong><code>False</code></strong></td>
<td><span class="math inline">\(1.20 \times 10^{-2}\)</span> (Failed)</td>
</tr>
<tr class="odd">
<td><strong><code>EGNN</code> (Geometric)</strong></td>
<td>3D Rotation Matrix (<span class="math inline">\(x \cdot R^T\)</span>)</td>
<td>Rotation Invariance</td>
<td><strong><code>True</code></strong></td>
<td><span class="math inline">\(5.96 \times 10^{-8}\)</span> (Passed)</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>4. Core Takeaway</strong></p>
<p>Stage 8 demonstrated that <strong>permutation invariance does not imply geometric invariance</strong>. While symmetric pooling layers (like <code>global_max_pool</code> or <code>global_mean_pool</code>) protect a network from variations in data ordering, they offer no protection against spatial rotations.</p>
<p>By grounding its message-passing equations in relative distances (<span class="math inline">\(d_{ij}^2\)</span>) rather than absolute spatial points (<span class="math inline">\(x_i\)</span>), the <strong>EGNN</strong> maintains an invariant scalar stream across all internal layers. This allows the network to maintain consistent classification outputs under rigid transformations down to floating-point precision limits (<span class="math inline">\(10^{-8}\)</span>), eliminating the need for computationally heavy data augmentation.</p>
<hr>
</section>
<section id="stage-9---pointnet-baseline-non-equivariant-empirical-training-and-rigorous-symmetry-benchmarking" class="level3">
<h3 class="anchored" data-anchor-id="stage-9---pointnet-baseline-non-equivariant-empirical-training-and-rigorous-symmetry-benchmarking">Stage 9 - PointNet Baseline (Non-Equivariant): Empirical Training and Rigorous Symmetry Benchmarking</h3>
<p>We now train both models on ModelNet40 for 3D object classification. We use a standard 80/10/10 split. Evaluate under two test conditions:</p>
<ul>
<li>Condition A: no rotation augmentation (aligned test set).</li>
<li>Condition B: random SO(3) rotation applied to every test sample.</li>
</ul>
<hr>
<p>Stage 9 transitioned our theoretical models into full-scale empirical training and validation. By training both the Equivariant Graph Neural Network (<strong>EGNN</strong>) and <strong>PointNet</strong> under identical, controlled conditions on the ModelNet40 dataset, we exposed the stark operational trade-offs between absolute coordinate modeling and geometry-grounded message passing.</p>
<p><br></p>
<p><strong>1. High-Efficiency Data Ingestion Pipeline</strong></p>
<p>To feed our models efficiently during training, we optimized data ingestion by moving geometric operations out of the active GPU execution loop:</p>
<ul>
<li><p><strong>Precomputed Spatial Topology:</strong> Calculating a <span class="math inline">\(k\)</span>-Nearest Neighbors graph scales quadratically with point density (<span class="math inline">\(O(N^2)\)</span>). Computing this dynamically on the GPU at every epoch creates severe CPU-GPU synchronization bottlenecks.</p></li>
<li><p><strong>Transform Serialization:</strong> By constructing an asset pipeline using <code>torch_geometric.transforms</code> (<code>SamplePoints</code> <span class="math inline">\(\rightarrow\)</span> <code>NormalizeScale</code> <span class="math inline">\(\rightarrow\)</span> <code>KNNGraph</code>), we precomputed local topology once upfront, serializing the structural edges directly into the dataset tensors.</p></li>
<li><p><strong>Collated Multi-Object Graph Batching:</strong> PyTorch Geometric aggregates a mini-batch of size 32 by flattening separate entities into a unified, giant disjoint graph structure:</p></li>
</ul>
<p><span class="math display">\[\mathbf{X}_{\text{batch}} \in \mathbb{R}^{32768 \times 3}, \quad \mathbf{E}_{\text{batch}} \in \mathbb{R}^{2 \times 655360}, \quad \mathbf{Y}_{\text{batch}} \in \mathbb{R}^{32}\]</span></p>
<p>This avoids padding matrices with useless zeros, keeping GPU tensor operations highly parallelized and efficient.</p>
<p><br></p>
<p><strong>2. Controlled Optimization Strategy</strong></p>
<p>To isolate architectural differences as the sole independent variable, we synchronized both training runs across a shared hyperparameter space:</p>
<ul>
<li><strong>Model Dimensions:</strong> Capacity was pinned at <span class="math inline">\(\text{Hidden Dimension} = 64\)</span>, <span class="math inline">\(\text{Message Dimension} = 64\)</span>, and <span class="math inline">\(\text{Layer Depth} = 4\)</span>.</li>
<li><strong>Learning Rate Schedule:</strong> Both models utilized an initial learning rate of <span class="math inline">\(\eta = 10^{-3}\)</span> managed by a <code>CosineAnnealingLR</code> scheduler over a 64-epoch horizon:</li>
</ul>
<p><span class="math display">\[\eta_t = \eta_{\text{min}} + \frac{1}{2}(\eta_{\text{max}} - \eta_{\text{min}})\left(1 + \cos\left(\frac{T_{\text{cur}}}{T_{\text{max}}}\pi\right)\right)\]</span></p>
<p>This smoothly decayed the optimization step sizes down to narrow local minima by epoch 64.</p>
<p><br></p>
<p><strong>3. Empirical Training Profiles</strong></p>
<p>The two models exhibited drastically different behaviors during their 64-epoch training runs:</p>
<section id="pointnet-profiles" class="level4">
<h4 class="anchored" data-anchor-id="pointnet-profiles">PointNet Profiles</h4>
<ul>
<li><p><strong>Computational Footprint:</strong> Concluded training in <strong>41 minutes and 23 seconds</strong> (<span class="math inline">\(\approx 38.80\text{s/epoch}\)</span>).</p></li>
<li><p><strong>Convergence Behavior:</strong> Fitted the training data rapidly, reaching a low training loss of <span class="math inline">\(0.3040\)</span> and achieving a standard validation accuracy of <strong><span class="math inline">\(83.23\%\)</span></strong>. Because it ignores spatial topology and updates each point independently through a shared MLP, PointNet has a massive advantage in floating-point operation (FLOP) efficiency, allowing it to easily map global spatial patterns.</p></li>
</ul>
<p><br></p>
</section>
<section id="egnn-profiles" class="level4">
<h4 class="anchored" data-anchor-id="egnn-profiles">EGNN Profiles</h4>
<ul>
<li><p><strong>Computational Footprint:</strong> Concluded training in <strong>1 hour, 16 minutes, and 20 seconds</strong> (<span class="math inline">\(\approx 71.57\text{s/epoch}\)</span>).</p></li>
<li><p><strong>Convergence Behavior:</strong> Exhibited slower, more constrained learning, plateauing at a training loss of <span class="math inline">\(1.5589\)</span> and a baseline test accuracy of <strong><span class="math inline">\(49.47\%\)</span></strong>. This behavior occurs because the network is strictly restricted to learning from relative distance scalars (<span class="math inline">\(d_{ij}^2\)</span>), making it more difficult to memorize the raw spatial coordinates of the training objects.</p></li>
</ul>
<p><br></p>
<p><strong>4. Rigorous Stress-Testing: The <span class="math inline">\(2 \times 2\)</span> Symmetry Matrix</strong></p>
<p>The true value of built-in symmetry guarantees became obvious when we evaluated both models against unexpected rigid SO(3) coordinate rotations (<span class="math inline">\(\mathbf{X}_{\text{rot}} = \mathbf{X} \cdot \mathbf{R}^T\)</span>).</p>
<p>The final evaluation results across our 4-way testing suite are detailed below:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Model Architecture</th>
<th>Aligned Test Accuracy</th>
<th>Rotated Test Accuracy</th>
<th>Performance Degradation (<span class="math inline">\(\Delta\)</span>)</th>
<th>Empirical Vulnerability Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>EGNN</strong> (Geometric)</td>
<td><span class="math inline">\(0.4935\)</span></td>
<td><span class="math inline">\(0.4931\)</span></td>
<td><strong><code>0.0004</code></strong></td>
<td><strong>Perfect Rotation Invariance</strong></td>
</tr>
<tr class="even">
<td><strong>PointNet</strong> (Baseline)</td>
<td><span class="math inline">\(0.8310\)</span></td>
<td><span class="math inline">\(0.0778\)</span></td>
<td><strong><code>0.7532</code></strong></td>
<td><strong>Catastrophic Structural Collapse</strong></td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>5. Final Synthesis of Learned Concepts</strong></p>
<ul>
<li><p><strong>The Illusion of Aligned Metrics:</strong> PointNet’s high accuracy on standard data (<span class="math inline">\(83.10\%\)</span>) is a product of dataset alignment bias. In datasets like ModelNet40, objects share a uniform orientation (e.g., chairs always stand upright along the Z-axis). PointNet capitalizes on this bias by memorizing absolute spatial positions.</p></li>
<li><p><strong>The Catastrophic Breakdown:</strong> The moment raw point coordinates are rotated, PointNet’s spatial representations shatter. Its accuracy collapses to <strong><span class="math inline">\(7.78\%\)</span></strong>—close to random guessing on a 40-class dataset.</p></li>
<li><p><strong>The Invariance Guarantee:</strong> In contrast, our <strong>EGNN</strong> tracks a flat performance degradation line (<span class="math inline">\(\Delta = 0.0004\)</span>), maintaining identical predictions down to floating-point precision limits. Because its internal message equations rely entirely on relative distance vectors, the network’s latent features do not shift when an object spins.</p></li>
</ul>
<p>Ultimately, <strong>PointNet proved to be <span class="math inline">\(1,859.0\times\)</span> more vulnerable to rotation than the EGNN</strong>. This outcome demonstrates that while geometric deep learning architectures are harder to optimize initially, they provide absolute generalization guarantees that standard, coordinate-bound networks cannot achieve without massive data augmentation.</p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shreeshb51\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Shreesh Bhattarai · GDL &amp; COT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/shreeshb51">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/shreesh-bhattarai-1ba1681bb/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>