project:
  type: website

website:
  title: "Shreesh Bhattarai"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Concepts Along the Way"
        href: catw/index.qmd
      - text: "Paper Comprehensions"
        href: papers/index.qmd
  page-footer:
    left: "Shreesh Bhattarai · GDL & COT"
    right:
      - icon: github
        href: https://github.com/shreeshb51
      - icon: linkedin
        href: https://www.linkedin.com/in/shreesh-bhattarai-1ba1681bb/

format:
  html:
    theme: darkly
    toc: true
    toc-depth: 2
    toc-title: "On this page"

css: styles.css
