<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mathematical_framework – Shreesh Bhattarai</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f476d09796a223f24f1d84e1ae9c0b0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shreesh Bhattarai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../catw/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Along the Way</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../papers/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper Comprehensions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notes</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#mathematical-framework-for-project-5---sliced-wasserstein-for-scalable-distribution-alignment-domain-adaptation" id="toc-mathematical-framework-for-project-5---sliced-wasserstein-for-scalable-distribution-alignment-domain-adaptation" class="nav-link active" data-scroll-target="#mathematical-framework-for-project-5---sliced-wasserstein-for-scalable-distribution-alignment-domain-adaptation">Mathematical Framework for Project 5 - Sliced Wasserstein for Scalable Distribution Alignment (Domain Adaptation)</a>
  <ul class="collapse">
  <li><a href="#context" id="toc-context" class="nav-link" data-scroll-target="#context">Context</a></li>
  <li><a href="#concepts" id="toc-concepts" class="nav-link" data-scroll-target="#concepts">Concepts</a></li>
  <li><a href="#underlying-mathematics" id="toc-underlying-mathematics" class="nav-link" data-scroll-target="#underlying-mathematics">Underlying Mathematics</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="mathematical-framework-for-project-5---sliced-wasserstein-for-scalable-distribution-alignment-domain-adaptation" class="level1">
<h1>Mathematical Framework for Project 5 - Sliced Wasserstein for Scalable Distribution Alignment (Domain Adaptation)</h1>
<hr>
<section id="context" class="level2">
<h2 class="anchored" data-anchor-id="context">Context</h2>
<p>In this project, we implement Sliced Wasserstein Distance (SWD) as a training loss for unsupervised domain adaptation: align a source domain (MNIST) to a target domain (SVHN) without target labels.</p>
<hr>
</section>
<section id="concepts" class="level2">
<h2 class="anchored" data-anchor-id="concepts">Concepts</h2>
<ul>
<li><p><strong>Probability Measure (<span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span>):</strong> A mathematical way to describe how data points are distributed in a space. Think of it as a blueprint for where data is likely to appear. <em>Example: <span class="math inline">\(\mu\)</span> is the blueprint for MNIST images, while <span class="math inline">\(\nu\)</span> is the blueprint for SVHN images.</em></p></li>
<li><p><strong>Feature Space (<span class="math inline">\(\mathbb{R}^d\)</span>):</strong> The multi-dimensional space where your data lives after being converted into numbers (features). <em>Example: A <span class="math inline">\(28 \times 28\)</span> grayscale image can be flattened into a <span class="math inline">\(784\)</span>-dimensional space (<span class="math inline">\(d=784\)</span>).</em></p></li>
<li><p><strong>Domain Adaptation:</strong> A machine learning technique where a model trained on one data distribution (source) is adjusted so it performs well on a different, but related, data distribution (target). <em>Example: Training a model on clean digital digits (MNIST) and adapting it to recognize messy, real-world house numbers (SVHN).</em></p></li>
<li><p><strong>Domain Shift:</strong> The change in data distribution between the training data (source) and the test data (target). <em>Example: The shift from a clean, black-and-white background to a noisy, colorful background.</em></p></li>
<li><p><strong>1D Wasserstein Distance (<span class="math inline">\(W_1\)</span>):</strong> A metric that measures the minimum “work” required to transform one probability distribution into another by moving probability mass. In 1D, it represents the area between two cumulative distribution curves.</p></li>
<li><p><strong>Empirical Distribution:</strong> A probability distribution created from a finite set of observed data points, where each point is assigned equal probability mass. <em>Example: For data points <span class="math inline">\(\{2, 4, 9\}\)</span>, the empirical distribution puts a mass of <span class="math inline">\(1/3\)</span> on each number.</em></p></li>
<li><p><strong>Optimal Transport Plan / Coupling (<span class="math inline">\(\pi^*\)</span>):</strong> A joint probability distribution (or map) that describes exactly how much mass from location <span class="math inline">\(x\)</span> in the source distribution should be moved to location <span class="math inline">\(y\)</span> in the target distribution to minimize cost.</p></li>
<li><p><strong>Monotone Transformation / Sorting:</strong> A mapping where the relative order of elements is preserved. If <span class="math inline">\(x_1 &lt; x_2\)</span>, then their corresponding target destinations satisfy <span class="math inline">\(y_1 \leq y_2\)</span>.</p></li>
<li><p><strong>Quantile Function / Inverse CDF (<span class="math inline">\(F^{-1}(t)\)</span>):</strong> A function that takes a probability <span class="math inline">\(t \in [0, 1]\)</span> and returns the data value below which that percentage of mass falls.</p></li>
<li><p><strong>Radon Transform:</strong> An integral transform that takes a function (or measure) defined over a multi-dimensional space and projects it along straight lines (hyperplanes) into a family of 1D projections. <em>Example: In medical imaging, a CT scanner takes 2D X-ray projections of a 3D body from various angles. The Radon transform mathematically connects those 2D projections back to the 3D object.</em></p></li>
<li><p><strong>Push-forward Measure (<span class="math inline">\(\theta_\# \mu\)</span>):</strong> The distribution that results from projecting all the data points from a high-dimensional distribution <span class="math inline">\(\mu\)</span> onto a 1D line pointed in the direction of the unit vector <span class="math inline">\(\theta\)</span>.</p></li>
<li><p><strong>Sliced Wasserstein Distance (SWD):</strong> A distance metric between two high-dimensional distributions calculated by projecting (slicing) them down to 1D lines in all possible directions, computing the 1D Wasserstein distance for each direction, and averaging the results.</p></li>
<li><p><strong>Metric vs.&nbsp;Semimetric:</strong> A <em>metric</em> is a true distance function that satisfies all standard properties, crucially <strong>injectivity</strong> (distance is <span class="math inline">\(0\)</span> if and only if the two objects are identical: <span class="math inline">\(\mu = \nu\)</span>). A <em>semimetric</em> allows the distance between two <em>different</em> objects to be <span class="math inline">\(0\)</span>.</p></li>
<li><p><strong>Metric Axioms:</strong> The three foundational rules a mathematical function must satisfy to be considered a true “distance” or metric between objects. These are Identity of Indiscernibles, Symmetry, and the Triangle Inequality.</p></li>
<li><p><strong>Finite-<span class="math inline">\(L\)</span> Estimator:</strong> A practical approximation of the Sliced Wasserstein Distance. Instead of averaging over an infinite number of random directions (<span class="math inline">\(\theta\)</span>), we average over a finite number (<span class="math inline">\(L\)</span>) of randomly sampled directions.</p></li>
<li><p><strong>Empirical Metric Violation:</strong> When an estimator or approximation fails to satisfy a metric axiom (like the triangle inequality) on a specific dataset, even though the true underlying mathematical function satisfies it perfectly.</p></li>
<li><p><strong>Max-SWD (Max-Sliced Wasserstein Distance):</strong> A variation of the Sliced Wasserstein Distance. Instead of averaging the 1D Wasserstein distance across <em>all</em> random directions, it searches for and uses only the single direction (<span class="math inline">\(\theta\)</span>) that yields the largest possible distance between the two distributions.</p></li>
<li><p><strong>Projected Gradient Ascent:</strong> An optimization algorithm used when you want to maximize a function, but the parameters must stay within a restricted region (like the surface of a sphere). You take a standard step forward, and if you land outside the allowed boundary, you immediately snap (project) back to the closest valid point.</p></li>
<li><p><strong>Discriminator / Generator:</strong> The two components of a Generative Adversarial Network (GAN). The <strong>Generator</strong> creates fake data, while the <strong>Discriminator</strong> acts as a judge, trying to distinguish real data from fake data.</p></li>
<li><p><strong>Sinkhorn Algorithm:</strong> An iterative method used to compute an approximation of Optimal Transport. It transforms a cost matrix into a doubly stochastic matrix (where rows and columns sum to 1) using simple row and column scaling.</p></li>
<li><p><strong>Cost Matrix (<span class="math inline">\(C\)</span>):</strong> A table where the entry <span class="math inline">\(C_{ij}\)</span> represents the “cost” (usually distance) to move mass from source point <span class="math inline">\(i\)</span> to target point <span class="math inline">\(j\)</span>.</p></li>
<li><p><strong>Entropic Regularization (<span class="math inline">\(\varepsilon H(\pi)\)</span>):</strong> A technique that adds a “fuzziness” or entropy penalty to the transport plan. This makes the optimization problem smoother, faster to solve, and differentiable.</p></li>
<li><p><strong>Transport Plan (<span class="math inline">\(\pi\)</span>):</strong> A matrix describing how much mass is moved between every pair of points. In entropic OT, this matrix becomes dense rather than sparse.</p></li>
<li><p><strong>Pixel Space (<span class="math inline">\(\mathbb{R}^{3072}\)</span>):</strong> The raw input space where each coordinate represents the intensity of a specific pixel channel. In this space, images are treated as flat vectors of numbers.</p></li>
<li><p><strong>Manifold Hypothesis:</strong> The machine learning assumption that real-world high-dimensional data (like images) actually lies on much lower-dimensional, highly curved surfaces (manifolds) embedded within the high-dimensional space.</p></li>
<li><p><strong>Semantic Embedding Space:</strong> A lower-dimensional space created by a neural network encoder where geometric distances reflect meaning (e.g., digit class) rather than surface-level appearance.</p></li>
<li><p><strong>Injectivity / Bijectivity:</strong> Mathematical properties of a function. An injective function ensures that distinct inputs map to distinct outputs, preventing different classes from being collapsed into the same embedding point.</p></li>
<li><p><strong>Curse of Dimensionality:</strong> A phenomenon where data becomes extremely sparse and isolated as the number of dimensions increases, making traditional distance metrics and geometric calculations highly counter-intuitive.</p></li>
<li><p><strong>Random Projections:</strong> The process of multiplying a high-dimensional vector by a random matrix (or unit vector <span class="math inline">\(\theta\)</span>) to project the data down into a lower-dimensional space while attempting to preserve structural properties.</p></li>
<li><p><strong>Measure Concentration:</strong> A geometric phenomenon in high dimensions where almost all of the surface area (or volume) of a shape becomes concentrated in a very small, specific region.</p></li>
</ul>
<hr>
</section>
<section id="underlying-mathematics" class="level2">
<h2 class="anchored" data-anchor-id="underlying-mathematics">Underlying Mathematics</h2>
<hr>
<section id="stage-1---environment-dataset-inspection" class="level3">
<h3 class="anchored" data-anchor-id="stage-1---environment-dataset-inspection">Stage 1 - Environment &amp; Dataset Inspection</h3>
<p>We’re building the foundation: understanding the two distributions μ (MNIST) and ν (SVHN) we need to align. Before any code, you need to characterize <em>what</em> alignment means mathematically.</p>
<p><br></p>
</section>
<section id="questions-1" class="level3">
<h3 class="anchored" data-anchor-id="questions-1">Questions [1]</h3>
<p>MNIST images are grayscale 28×28, class-balanced, centered digits on clean backgrounds. SVHN images are RGB 32 <span class="math inline">\(\times\)</span> 32, house numbers in natural scenes with cluttered backgrounds, varying fonts, and lighting.</p>
<p>If <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span> are probability measures over feature space <span class="math inline">\(\mathbb{R}^d\)</span>, answer both parts:</p>
<ol type="1">
<li><p>What does “domain adaptation without target labels” mean as an optimization problem? Specifically: you have access to labeled samples <span class="math inline">\({(x_i, y_i)}\)</span> <span class="math inline">\(\sim\)</span> <span class="math inline">\(\mu\)</span> and <em>unlabeled</em> samples <span class="math inline">\({z_j}\)</span> <span class="math inline">\(\sim\)</span> <span class="math inline">\(\mu\)</span>. What are you optimizing, over what, and subject to what constraint? Write it as a formal objective.</p></li>
<li><p>Beyond pixel statistics, what are the axes of domain shift here? Enumerate the distinct components of the gap between <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span> — not just “different colors,” but in terms of the mathematical properties of the two measures (support, marginals, covariance structure, modality).</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-1" class="level3">
<h3 class="anchored" data-anchor-id="answers-1">Answers [1]</h3>
<p><strong>1. Unsupervised Domain Adaptation as an Optimization Problem</strong></p>
<p><strong>What does it mean?</strong></p>
<p>“Domain adaptation without target labels” (Unsupervised Domain Adaptation) means you want to learn a predictor (like a neural network) that performs well on a <strong>target domain</strong> (<span class="math inline">\(\nu\)</span>), but you only have labeled data from a <strong>source domain</strong> (<span class="math inline">\(\mu\)</span>). For the target domain, you only have raw images, no answers (<span class="math inline">\(y\)</span>).</p>
<p>To solve this, you optimize two things simultaneously:</p>
<ol type="1">
<li><p><strong>Minimize error</strong> on the labeled source data.</p></li>
<li><p><strong>Minimize the distance</strong> between the source and target features so the model can’t tell which domain the data came from.</p></li>
</ol>
<p><br></p>
<p><strong>Formal Objective</strong></p>
<p>Let <span class="math inline">\(h \in \mathcal{H}\)</span> be a hypothesis (classifier) and <span class="math inline">\(f \in \mathcal{F}\)</span> be a feature extractor that maps inputs to a shared latent space. Let <span class="math inline">\(\mathcal{L}\)</span> be the loss function (e.g., cross-entropy), and <span class="math inline">\(d_{\mathcal{H}}(\cdot, \cdot)\)</span> be a distance measure between two distributions (like Maximum Mean Discrepancy or <span class="math inline">\(H\Delta H\)</span>-divergence).</p>
<p><span class="math display">\[\min_{f, h} \mathbb{E}_{(x, y) \sim \mu} [\mathcal{L}(h(f(x)), y)] + \lambda \cdot d_{\mathcal{H}}(f(\mu), f(\nu))\]</span></p>
<p><br></p>
<ul>
<li><p><strong>What you are optimizing:</strong> The parameters of the feature extractor <span class="math inline">\(f\)</span> and the classifier <span class="math inline">\(h\)</span>.</p></li>
<li><p><strong>Over what:</strong> The hypothesis spaces <span class="math inline">\(\mathcal{F}\)</span> and <span class="math inline">\(\mathcal{H}\)</span>.</p></li>
<li><p><strong>Subject to what constraint:</strong> The regularization parameter <span class="math inline">\(\lambda &gt; 0\)</span> acts as a soft constraint, forcing the distribution of extracted features <span class="math inline">\(f(\mu)\)</span> and <span class="math inline">\(f(\nu)\)</span> to be as close to 0 as possible.</p></li>
</ul>
<p><br></p>
<p><strong>2. Mathematical Axes of Domain Shift (Beyond Pixels)</strong></p>
<p>When moving from MNIST (<span class="math inline">\(\mu\)</span>) to SVHN (<span class="math inline">\(\nu\)</span>), the differences aren’t just cosmetic; they fundamentally alter the mathematical properties of the two measures:</p>
<p><strong>A. Ambient Space and Channel Dimensionality Mismatch</strong></p>
<ul>
<li><strong>What it means:</strong> The two measures do not initially live in the same mathematical space <span class="math inline">\(\mathbb{R}^d\)</span>. <span class="math inline">\(\mu\)</span> lives in <span class="math inline">\(\mathbb{R}^{1 \times 28 \times 28}\)</span>, while <span class="math inline">\(\nu\)</span> lives in <span class="math inline">\(\mathbb{R}^{3 \times 32 \times 32}\)</span>. Because they occupy entirely different ambient dimensions, you cannot compute distances or apply shared operations directly without a preprocessing transformation to make them commensurable.</li>
<li><strong>Example:</strong> You must choose whether to project MNIST into 3-channel space and upscale it to <span class="math inline">\(32 \times 32\)</span>, or downsample and grayscale SVHN to <span class="math inline">\(1 \times 28 \times 28\)</span> before training begins.</li>
</ul>
<p><br></p>
<p><strong>B. Support Misalignment (<span class="math inline">\(\text{supp}(\mu) \neq \text{supp}(\nu)\)</span>)</strong></p>
<ul>
<li><strong>What it means:</strong> The mathematical “boundaries” or regions where data exists do not overlap. MNIST occupies a tiny, highly restricted subspace of <span class="math inline">\(\mathbb{R}^d\)</span> (mostly zeros/black pixels). SVHN occupies a much larger, denser subspace because every pixel has a non-zero value across three color channels.</li>
<li><strong>Example:</strong> A pure black pixel (<span class="math inline">\(0,0,0\)</span>) is common in MNIST but almost non-existent in SVHN natural scenes.</li>
</ul>
<p><br></p>
<p><strong>C. Marginal Distribution Shift (<span class="math inline">\(P_{\mu}(X) \neq P_{\nu}(X)\)</span>)</strong></p>
<ul>
<li><strong>What it means:</strong> The overall probability of encountering a specific image structure <span class="math inline">\(X\)</span> is completely different, independent of the label. The label semantics remain identical (<span class="math inline">\(P(Y|X)\)</span> does not change, meaning a “7” remains a “7” in both domains), but the input distribution is starkly mismatched.</li>
<li><strong>Example:</strong> If you sample a random image from MNIST, you are guaranteed a clean, centered single digit. If you sample from SVHN, you get a noisy patch that likely contains parts of side digits.</li>
</ul>
<p><br></p>
<p><strong>D. Covariance Structure and Subspace Realignment</strong></p>
<ul>
<li><strong>What it means:</strong> Second-order statistics differ fundamentally. MNIST covariance is dominated by sparse stroke geometry, meaning most off-diagonal covariance terms are near zero. SVHN features dense, spatially correlated covariance driven by textures, lighting gradients, and background clutter.</li>
<li><strong>Example:</strong> Because of this dense correlation, the linear subspace that explains most variance in <span class="math inline">\(\mu\)</span> is a poor basis for <span class="math inline">\(\nu\)</span>. A Principal Component Analysis (PCA) or linear projection optimized on source features will completely fail to capture or align with the target domain’s structure.</li>
</ul>
<p><br></p>
<p><strong>E. Modality and Multimodal Density</strong></p>
<ul>
<li><strong>What it means:</strong> The “peaks” (modes) in the probability distribution are structured differently. MNIST is relatively uni-modal per class (one clean way to draw a ‘1’). SVHN is highly multi-modal per class due to different fonts, styles, and lighting conditions.</li>
<li><strong>Example:</strong> The digit ‘7’ in SVHN might have one major peak in the distribution for “serif font under sunlight” and another for “sans-serif font in a shadow.”</li>
</ul>
<p><br></p>
<p><strong>What does MNIST’s pixel distribution look like structurally, and why does it have that shape given the nature of the data?</strong></p>
<p>MNIST’s pixel distribution is <strong>bimodal</strong> — a massive spike near 0 (background pixels) and a smaller peak near 1 (stroke pixels), with very little mass in between.</p>
<p>Why: digits are sparse strokes on black backgrounds. Roughly 80–85% of pixels are pure black. The remaining 15–20% are near-white stroke pixels, with some anti-aliasing creating a thin bridge between the two peaks.</p>
<p>This directly explains the stats: low mean (0.13) because the zero-mass dominates, high std (0.31) because the distribution is <em>spread between two poles</em>, not concentrated around its mean. A Gaussian with mean 0.13 would have most mass near 0.13 — MNIST has almost <em>no</em> mass there.</p>
<p>SVHN is the opposite: roughly unimodal, bell-shaped around 0.45, because every pixel carries real texture/color information from natural scene photography. Lower std (0.20) despite higher mean because the mass is actually concentrated near the center.</p>
<p>This bimodal vs.&nbsp;unimodal contrast is your first concrete measurement of the domain gap. In ℝ^d feature space, it means the supports of μ and ν are structurally incompatible at the pixel level — which is exactly why we need a learned encoder before computing any distributional distance.</p>
<hr>
<section id="the-workflow" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow">1. The Workflow</h4>
<p>In Stage 1, we prepared our computational environment, loaded two distinct datasets containing the digits 0 through 9, and performed a comprehensive <strong>Exploratory Data Analysis (EDA)</strong>. We analyzed these datasets using three different lenses: structural dimensions, class balances, and pixel-level statistical properties.</p>
<p><br></p>
</section>
<section id="the-objective" class="level4">
<h4 class="anchored" data-anchor-id="the-objective">2. The Objective</h4>
<p>The ultimate goal of this pipeline is to set up a <strong>Domain Adaptation</strong> task. We are preparing to train a machine learning model using a <strong>Source Domain (<span class="math inline">\(\mu\)</span>)</strong> and evaluate or transfer its knowledge to a <strong>Target Domain (<span class="math inline">\(\nu\)</span>)</strong>. To do this successfully, we must thoroughly understand the mathematical and visual differences between the two domains—collectively known as the <strong>Domain Gap</strong>.</p>
<p><br></p>
</section>
<section id="key-learnings-technical-insights" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-technical-insights">3. Key Learnings &amp; Technical Insights</h4>
<p><strong>A. Environment Setup &amp; Reproducibility</strong></p>
<ul>
<li><p><strong>Hardware Acceleration:</strong> The system successfully activated an NVIDIA GPU (<code>cuda</code>), which will drastically speed up future matrix multiplications compared to a standard CPU.</p></li>
<li><p><strong>Consistency:</strong> By locking down random seeds across Python, NumPy, and PyTorch (<code>SEED = 42</code>) and enforcing deterministic algorithms, we guaranteed that any data shuffling, image sampling, or neural network weight initializations will be perfectly identical on every run.</p></li>
</ul>
<p><br></p>
<p><strong>B. The Datasets: Structural &amp; Visual Profiling</strong></p>
<p>We loaded two fundamentally different datasets that share the exact same classification targets (the digits 0–9):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>MNIST (Source Domain <span class="math inline">\(\mu\)</span>)</th>
<th>SVHN (Target Domain <span class="math inline">\(\nu\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Context</strong></td>
<td>Synthetic, clean handwritten digits</td>
<td>Real-world house numbers from Google Street View</td>
</tr>
<tr class="even">
<td><strong>Image Size</strong></td>
<td><span class="math inline">\(28 \times 28\)</span> pixels</td>
<td><span class="math inline">\(32 \times 32\)</span> pixels</td>
</tr>
<tr class="odd">
<td><strong>Channels</strong></td>
<td>1 (Grayscale)</td>
<td>3 (Full Color RGB)</td>
</tr>
<tr class="even">
<td><strong>Data Volume</strong></td>
<td>60,000 train / 10,000 test</td>
<td>73,257 train / 26,032 test</td>
</tr>
<tr class="odd">
<td><strong>Visual Texture</strong></td>
<td>Crisp white numbers on pure black backgrounds</td>
<td>Noisy backgrounds (bricks, wood), shadows, blur</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>C. Class Distributions</strong></p>
<ul>
<li><p><strong>MNIST</strong> exhibits a nearly perfect uniform distribution. Every digit from 0 to 9 has roughly 6,000 representative images, meaning the model will have an equal opportunity to learn each number.</p></li>
<li><p><strong>SVHN</strong> possesses a natural, real-world class imbalance. Numbers like “1”, “2”, and “3” appear significantly more often than “0” or “9” because of standard street address conventions.</p></li>
</ul>
<p><br></p>
<p><strong>D. Quantifying the Domain Gap</strong></p>
<p>Through pixel intensity histograms and mathematical summaries, we proved that an AI model cannot easily jump from MNIST to SVHN without adaptation adjustments:</p>
<ul>
<li><p><strong>The MNIST Profile:</strong> An average brightness (mean) of just <strong>0.1302</strong> and a high standard deviation of <strong>0.3077</strong>. This tells us the dataset is a stark, high-contrast world built almost entirely out of absolute minimums (0.0/black) and absolute maximums (1.0/white).</p></li>
<li><p><strong>The SVHN Profile:</strong> An average brightness hovering around <strong>0.45–0.48</strong> and a tighter standard deviation of <strong>~0.20</strong>. This mathematically proves the target domain lives in a softer, mid-tone gray world featuring smooth gradients, shadows, and true color variety.</p></li>
</ul>
<p><br></p>
<p>We now have a clean, reproducible setup and a deep numerical understanding of our data. We know that while both datasets are looking for the exact same things (digits 0–9), they speak entirely different visual languages.</p>
<p>Our environment is primed and ready to start building the model architectures or introducing the <strong>Optimal Transport</strong> algorithms needed to align these two worlds.</p>
<hr>
</section>
</section>
<section id="stage-2---1d-wasserstein-distance-exact-and-efficient" class="level3">
<h3 class="anchored" data-anchor-id="stage-2---1d-wasserstein-distance-exact-and-efficient">Stage 2 - 1D Wasserstein Distance: Exact and Efficient</h3>
<p>We’re implementing <span class="math inline">\(W_1(\mu, \nu)\)</span> in 1D using the sorted-quantile formula — the foundation every sliced method relies on.</p>
<p><br></p>
</section>
<section id="questions-2" class="level3">
<h3 class="anchored" data-anchor-id="questions-2">Questions [2]</h3>
<p>Derive why 1D Wasserstein has a closed form.</p>
<p>Starting from Kantorovich duality:</p>
<p><span class="math display">\[W_1(\mu, \nu) = \sup_{f: \|f\|_{\text{Lip}} \leq 1} \mathbb{E}_{x \sim \mu}[f(x)] - \mathbb{E}_{y \sim \nu}[f(y)]\]</span></p>
<p>Answer these two connected questions:</p>
<ol type="1">
<li><p>In 1D, what is the optimal transport plan between two empirical distributions with equal mass? Describe it geometrically — what does the coupling π* look like, and why is sorting the only reasonable choice?</p></li>
<li><p>From that, derive why W₁ reduces to <span class="math inline">\(\int_0^1 |F_\mu^{-1}(t) - F_\nu^{-1}(t)| \, dt\)</span>, which for equal-sized empirical samples is just <span class="math inline">\(\frac{1}{n}\sum_i |x_{(i)} - y_{(i)}|\)</span> where the parentheses denote sorted order.</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-2" class="level3">
<h3 class="anchored" data-anchor-id="answers-2">Answers [2]</h3>
<p><strong>1. The Geometry of 1D Optimal Transport for Empirical Distributions</strong></p>
<p><strong>What does it mean?</strong></p>
<p>When you have two sets of 1D points of equal size, the absolute cheapest way to transport the first set onto the second set (under a <span class="math inline">\(L_1\)</span> or <span class="math inline">\(L_2\)</span> cost) is to sort both sets and match the smallest to the smallest, the second smallest to the second smallest, and so on. This is known as <strong>monotone transport</strong>.</p>
<p><br></p>
<p><strong>Geometric Description of <span class="math inline">\(\pi^*\)</span></strong></p>
<p>Let <span class="math inline">\(\mu = \frac{1}{n}\sum_{i=1}^n \delta_{x_i}\)</span> and <span class="math inline">\(\nu = \frac{1}{n}\sum_{j=1}^n \delta_{y_j}\)</span> be two empirical distributions. First, sort the points such that <span class="math inline">\(x_{(1)} \leq x_{(2)} \leq \dots \leq x_{(n)}\)</span> and <span class="math inline">\(y_{(1)} \leq y_{(2)} \leq \dots \leq y_{(n)}\)</span>.</p>
<p>The optimal coupling <span class="math inline">\(\pi^*\)</span> is a permutation matrix scaled by <span class="math inline">\(1/n\)</span> that maps <span class="math inline">\(x_{(i)}\)</span> directly to <span class="math inline">\(y_{(i)}\)</span>:</p>
<p><span class="math display">\[\pi^* = \frac{1}{n}\sum_{i=1}^n \delta_{(x_{(i)}, y_{(i)})}\]</span></p>
<p>Geometrically, if you plot the coupling matrix in 2D with the sorted source points on the x-axis and sorted target points on the y-axis, the optimal transport plan looks like a strictly non-decreasing path of discrete points moving from the bottom-left to the top-right.</p>
<p><br></p>
<p><strong>Why sorting is the only reasonable choice (No-Crossing Rule)?</strong></p>
<p>Consider two source points <span class="math inline">\(x_1 &lt; x_2\)</span> and two target points <span class="math inline">\(y_1 &lt; y_2\)</span>. We have two choices for matching them:</p>
<ol type="1">
<li><p><strong>Sorted / Monotone matching:</strong> Match <span class="math inline">\(x_1 \to y_1\)</span> and <span class="math inline">\(x_2 \to y_2\)</span>. The cost is <span class="math inline">\(|x_1 - y_1| + |x_2 - y_2|\)</span>.</p></li>
<li><p><strong>Crossed matching:</strong> Match <span class="math inline">\(x_1 \to y_2\)</span> and <span class="math inline">\(x_2 \to y_1\)</span>. The cost is <span class="math inline">\(|x_1 - y_2| + |x_2 - y_1|\)</span>.</p></li>
</ol>
<p>By the triangle inequality on a real line, lines connecting transport pairs must never cross if you want to minimize distance. For any configurations where <span class="math inline">\(x_1 &lt; x_2\)</span> and <span class="math inline">\(y_1 &lt; y_2\)</span>, it always holds that:</p>
<p><span class="math display">\[|x_1 - y_1| + |x_2 - y_2| \leq |x_1 - y_2| + |x_2 - y_1|\]</span></p>
<p>Because the real line forces a strict ordering, any plan that “crosses” paths wastes energy by moving mass past each other unnecessarily. Thus, sorting is the uniquely optimal assignment.</p>
<p><br></p>
<p><strong>2. Derivation of the Closed-Form 1D Wasserstein Distance</strong></p>
<p><strong>Step 1: The Monotone Quantile Mapping</strong></p>
<p>For general continuous or discrete distributions, the geometric intuition of “sorting” is generalized using the Cumulative Distribution Function (CDF), denoted as <span class="math inline">\(F(x) = P(X \leq x)\)</span>, and its generalized inverse, the quantile function <span class="math inline">\(F^{-1}(t) = \inf \{x : F(x) \geq t\}\)</span> for <span class="math inline">\(t \in [0, 1]\)</span>.</p>
<p>A fundamental property of probability theory (Probability Integral Transform) states that if <span class="math inline">\(U \sim \text{Uniform}(0, 1)\)</span>, then the random variable <span class="math inline">\(X = F_\mu^{-1}(U)\)</span> has the distribution <span class="math inline">\(\mu\)</span>, and <span class="math inline">\(Y = F_\nu^{-1}(U)\)</span> has the distribution <span class="math inline">\(\nu\)</span>.</p>
<p>Because <span class="math inline">\(F^{-1}(t)\)</span> is a non-decreasing function, the mapping <span class="math inline">\(x = F_\mu^{-1}(t) \to y = F_\nu^{-1}(t)\)</span> preserves order perfectly. By the non-crossing principle proven in Part 1, this monotone coupling must be the optimal transport plan <span class="math inline">\(\pi^*\)</span>.</p>
<p><br></p>
<p><strong>Step 2: Integrating Over the Latent Quantile Space</strong></p>
<p>The primal definition of the <span class="math inline">\(W_1\)</span> distance is the expected cost under the optimal coupling:</p>
<p><span class="math display">\[W_1(\mu, \nu) = \inf_{\pi \in \Pi(\mu, \nu)} \mathbb{E}_{(x,y) \sim \pi}[|x - y|]\]</span></p>
<p>Since the optimal coupling is fully parameterized by pushing forward the uniform distribution <span class="math inline">\(U \sim \text{Uniform}(0, 1)\)</span> through the quantile functions, we can rewrite the expected value as an integral over the domain of <span class="math inline">\(U\)</span>, which is <span class="math inline">\([0, 1]\)</span>:</p>
<p><span class="math display">\[W_1(\mu, \nu) = \mathbb{E}_{t \sim \text{Unif}(0,1)} [|F_\mu^{-1}(t) - F_\nu^{-1}(t)|]\]</span></p>
<p><span class="math display">\[W_1(\mu, \nu) = \int_0^1 |F_\mu^{-1}(t) - F_\nu^{-1}(t)| \, dt\]</span></p>
<p>This completes the continuous derivation.</p>
<p><br></p>
<p><strong>Step 3: Reduction to Sorted Equal-Sized Empirical Samples</strong></p>
<p>Now let’s apply this general formula to your empirical distributions of size <span class="math inline">\(n\)</span>, where points are pre-sorted: <span class="math inline">\(x_{(1)} \leq \dots \leq x_{(n)}\)</span> and <span class="math inline">\(y_{(1)} \leq \dots \leq y_{(n)}\)</span>.</p>
<p>The empirical CDF <span class="math inline">\(F_\mu(x)\)</span> is a step function that jumps by <span class="math inline">\(1/n\)</span> at every data point. Consequently, its inverse quantile function <span class="math inline">\(F_\mu^{-1}(t)\)</span> is a piecewise constant function defined as:</p>
<p><span class="math display">\[F_\mu^{-1}(t) = x_{(i)} \quad \text{for } t \in \left( \frac{i-1}{n}, \frac{i}{n} \right]\]</span></p>
<p>Similarly, for the target distribution:</p>
<p><span class="math display">\[F_\nu^{-1}(t) = y_{(i)} \quad \text{for } t \in \left( \frac{i-1}{n}, \frac{i}{n} \right]\]</span></p>
<p>Substitute these piecewise definitions into the continuous quantile integral:</p>
<p><span class="math display">\[W_1(\mu, \nu) = \int_0^1 |F_\mu^{-1}(t) - F_\nu^{-1}(t)| \, dt\]</span></p>
<p>We break the integral into <span class="math inline">\(n\)</span> equal intervals of width <span class="math inline">\(1/n\)</span>:</p>
<p><span class="math display">\[W_1(\mu, \nu) = \sum_{i=1}^n \int_{\frac{i-1}{n}}^{\frac{i}{n}} |x_{(i)} - y_{(i)}| \, dt\]</span></p>
<p>Since the integrand <span class="math inline">\(|x_{(i)} - y_{(i)}|\)</span> is completely constant with respect to <span class="math inline">\(t\)</span> on each interval, evaluating the integral simply multiplies the value by the interval width <span class="math inline">\(\frac{i}{n} - \frac{i-1}{n} = \frac{1}{n}\)</span>:</p>
<p><span class="math display">\[W_1(\mu, \nu) = \sum_{i=1}^n \frac{1}{n} |x_{(i)} - y_{(i)}|\]</span></p>
<p><span class="math display">\[W_1(\mu, \nu) = \frac{1}{n}\sum_{i=1}^n |x_{(i)} - y_{(i)}|\]</span></p>
<p><br></p>
<p>Note: The <span class="math inline">\(W_1\)</span> formula via Kantorovich duality holds for general costs, but the quantile derivation written is specifically for the <span class="math inline">\(L^1\)</span> cost — for <span class="math inline">\(W_2\)</span> you’d integrate squared differences.</p>
<hr>
<section id="the-workflow-1" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow-1">1. The Workflow</h4>
<p>In Stage 2, we shifted from data exploration to algorithm development. We designed, optimized, and validated a custom mathematical utility to measure the structural distance between datasets. We then subjected this algorithm to rigorous validation tests, including cross-framework unit testing, empirical time-complexity benchmarking, and geometric visualization using synthetic distributions that mimic our real-world image profiles.</p>
<p><br></p>
</section>
<section id="the-objective-1" class="level4">
<h4 class="anchored" data-anchor-id="the-objective-1">2. The Objective</h4>
<p>The ultimate goal of this pipeline is to establish a robust framework for <strong>Domain Adaptation</strong>. To guide a model from a source domain to a target domain, we need a mathematical “compass” that quantifies exactly how far apart the two data distributions are. We implemented the <strong>Wasserstein-1 Distance (<span class="math inline">\(W_1\)</span>)</strong>—or Earth Mover’s Distance—to serve as this metric. The core objective of this stage was to build a computationally efficient 1D version of this metric and prove its accuracy, scaling efficiency, and geometric behavior before deploying it on full image datasets.</p>
<p><br></p>
</section>
<section id="key-learnings-technical-insights-1" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-technical-insights-1">3. Key Learnings &amp; Technical Insights</h4>
<p><strong>A. Algorithmic Optimization via Quantile Matching</strong></p>
<ul>
<li><strong>Mathematical Shortcut:</strong> Calculating the general Wasserstein distance normally requires solving a slow, heavy-duty optimization problem. However, for 1-dimensional data of equal size, the problem simplifies beautifully: sorting both arrays instantly aligns them by their relative percentiles (quantiles).</li>
<li><strong>The Custom Formula:</strong> We implemented the sorted quantile shortcut:</li>
</ul>
<p><span class="math display">\[\text{W}_1(\mu, \nu) = \frac{1}{n} \sum_{i=1}^{n} |x_{(i)} - y_{(i)}|\]</span></p>
<p>This reduces the computational complexity from a prohibitive cubic bottleneck down to an incredibly fast sorting bottleneck of <span class="math inline">\(O(n \log n)\)</span>.</p>
<p><br></p>
<p><strong>B. Cross-Framework Validation</strong></p>
<p>We cross-examined our custom <code>w1_sorted</code> function against the industry standard <strong>POT (Python Optimal Transport)</strong> library, which utilizes a definitive Linear Programming solver (<code>ot.emd2</code>).</p>
<ul>
<li><strong>Precision Alignment:</strong> When tested on random Gaussian distributions, our shortcut matched the official POT library down to an exceptionally tight margin:
<ul>
<li><em>Our Custom Function:</em> <code>1.469894</code></li>
<li><em>Official POT Library:</em> <code>1.469893</code></li>
<li><em>Absolute Error:</em> <span class="math inline">\(1.23 \times 10^{-6}\)</span></li>
</ul></li>
<li><strong>Conclusion:</strong> This microscopic discrepancy is merely standard floating-point rounding noise. This officially verified that our fast custom algorithm is 100% mathematically sound.</li>
</ul>
<p><br></p>
<p><strong>C. Empirical Complexity Benchmarking</strong></p>
<p>We evaluated how our custom function performs under increasing data volumes (<span class="math inline">\(n\)</span>) to verify its <span class="math inline">\(O(n \log n)\)</span> efficiency in practice:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dataset Size (<span class="math inline">\(n\)</span>)</th>
<th>Average Execution Time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><span class="math inline">\(n = 100\)</span></strong></td>
<td>0.096 ms</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(n = 1,000\)</span></strong></td>
<td>0.191 ms</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(n = 10,000\)</span></strong></td>
<td>1.792 ms</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(n = 50,000\)</span></strong></td>
<td>10.108 ms</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Scalability:</strong> Even when handling a massive array of 50,000 data points, the function executed in a mere <strong>10.108 milliseconds</strong>. This empirical trend confirms that this metric can safely be embedded into high-volume, repetitive training loops without introducing computational lag.</li>
</ul>
<p><br></p>
<p><strong>D. Geometric Behavior &amp; Distribution Alignment</strong></p>
<p>Using custom toy distributions, we modeled the exact geometric problem our image profiles present: matching a <strong>bimodal distribution</strong> (representing high-contrast MNIST pixel values) to a <strong>unimodal distribution</strong> (representing smooth, mid-tone SVHN pixel values).</p>
<ul>
<li><p><strong>Empirical CDFs:</strong> Plotting the Cumulative Distribution Functions visually demonstrated that the Wasserstein distance is equivalent to the physical area trapped between the two distribution curves.</p></li>
<li><p><strong>Quantile-Quantile (Q-Q) Plots:</strong> Mapping the sorted points against a diagonal <span class="math inline">\(y=x\)</span> identity baseline exposed the exact shape mismatches. The non-linear bending of the scatter points visually mapped out how data mass must distort and shift to map an MNIST-style profile onto an SVHN-style profile.</p></li>
</ul>
<p>We now have a validated, hyper-efficient, and visually verified mathematical tool ready to calculate the distance between our source and target domains.</p>
<hr>
</section>
</section>
<section id="stage-3---sliced-wasserstein-distance" class="level3">
<h3 class="anchored" data-anchor-id="stage-3---sliced-wasserstein-distance">Stage 3 - Sliced Wasserstein Distance</h3>
<p>We’re implementing SWD by averaging <span class="math inline">\(W_2^2\)</span> across random 1D projections.</p>
<p><br></p>
</section>
<section id="questions-3" class="level3">
<h3 class="anchored" data-anchor-id="questions-3">Questions [3]</h3>
<p>The Radon transform of a measure <span class="math inline">\(\mu\)</span> on <span class="math inline">\(\mathbb{R}^d\)</span> is the family of projected measures <span class="math inline">\(\{\theta_\#\mu : \theta \in S^{d-1}\}\)</span>. Two distinct measures <span class="math inline">\(\mu \neq \nu\)</span> can have identical marginals in most directions — yet SWD is still a valid metric.</p>
<p>What property of the Radon transform guarantees that averaging <span class="math inline">\(W_2^2\)</span> over <em>random</em> directions <span class="math inline">\(\theta \sim U(S^{d-1})\)</span> equals zero <strong>if and only if</strong> <span class="math inline">\(\mu = \nu\)</span>? Specifically: if <span class="math inline">\(\theta_\#\mu = \theta_\#\nu\)</span> for Lebesgue-almost-every <span class="math inline">\(\theta\)</span>, what does that imply about <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span>, and why does this make SWD a metric rather than just a semimetric?</p>
<p><br></p>
</section>
<section id="answers-3" class="level3">
<h3 class="anchored" data-anchor-id="answers-3">Answers [3]</h3>
<p><strong>1. The Property of the Radon Transform guarantees SWD is a valid metric</strong></p>
<p><strong>What does it mean?</strong></p>
<p>Even though two distinct distributions can look identical when projected onto <em>a few</em> specific directions, they cannot look identical from <em>almost all</em> directions. The mathematical property that guarantees this is the <strong>injectivity</strong> of the Radon transform.</p>
<p>Because the Radon transform is injective, knowing the 1D projections in every direction uniquely determines the original high-dimensional distribution. If the averaged distance across all directions is zero, the distributions must be identical.</p>
<p><br></p>
<p><strong>Mathematical Proof of Injectivity via the Fourier Slice Theorem</strong></p>
<p>To see why this property holds, we must look at the <strong>Fourier Slice Theorem</strong> (also known as the Central Slice Theorem), which connects the Radon transform to the Fourier transform.</p>
<p>Let <span class="math inline">\(\widehat{\mu}(\xi)\)</span> be the <span class="math inline">\(d\)</span>-dimensional Fourier transform of the measure <span class="math inline">\(\mu\)</span> at frequency vector <span class="math inline">\(\xi \in \mathbb{R}^d\)</span>. We can write any frequency vector in polar coordinates as <span class="math inline">\(\xi = r\theta\)</span>, where <span class="math inline">\(r \in \mathbb{R}\)</span> is the frequency magnitude and <span class="math inline">\(\theta \in S^{d-1}\)</span> is the direction.</p>
<p>The Fourier Slice Theorem states that the 1D Fourier transform of the projection <span class="math inline">\(\theta_\# \mu\)</span> at a frequency <span class="math inline">\(r\)</span> is exactly equal to the <span class="math inline">\(d\)</span>-dimensional Fourier transform of the original measure <span class="math inline">\(\mu\)</span> evaluated along the line in direction <span class="math inline">\(\theta\)</span>:</p>
<p><span class="math display">\[\widehat{\theta_\# \mu}(r) = \widehat{\mu}(r\theta)\]</span></p>
<p>Now, let’s analyze what happens when <span class="math inline">\(\theta_\# \mu = \theta_\# \nu\)</span> for Lebesgue-almost-every direction <span class="math inline">\(\theta\)</span>:</p>
<ol type="1">
<li>If the 1D projected measures are equal (<span class="math inline">\(\theta_\# \mu = \theta_\# \nu\)</span>), their 1D Fourier transforms must be identical:</li>
</ol>
<p><span class="math display">\[\widehat{\theta_\# \mu}(r) = \widehat{\theta_\# \nu}(r) \quad \forall r \in \mathbb{R}\]</span></p>
<ol start="2" type="1">
<li>By substituting the Fourier Slice Theorem, this implies:</li>
</ol>
<p><span class="math display">\[\widehat{\mu}(r\theta) = \widehat{\nu}(r\theta)\]</span></p>
<ol start="3" type="1">
<li><p>Since this equality holds for Lebesgue-almost-every direction <span class="math inline">\(\theta \in S^{d-1}\)</span> and all magnitudes <span class="math inline">\(r \in \mathbb{R}\)</span>, it covers almost the entire frequency space <span class="math inline">\(\mathbb{R}^d\)</span>.</p></li>
<li><p>Because the Fourier transform is a continuous function, if two Fourier transforms match almost everywhere, they must match <em>everywhere</em>:</p></li>
</ol>
<p><span class="math display">\[\widehat{\mu}(\xi) = \widehat{\nu}(\xi) \quad \forall \xi \in \mathbb{R}^d\]</span></p>
<ol start="5" type="1">
<li>By the uniqueness (injectivity) of the Fourier transform, taking the inverse Fourier transform yields:</li>
</ol>
<p><span class="math display">\[\mu = \nu\]</span></p>
<p><br></p>
<p><strong>Why this makes SWD a Metric rather than a Semimetric?</strong></p>
<p>The Sliced Wasserstein Distance (squared) is formally defined as:</p>
<p><span class="math display">\[\text{SWD}_2^2(\mu, \nu) = \mathbb{E}_{\theta \sim U(S^{d-1})} \left[ W_2^2(\theta_\# \mu, \theta_\# \nu) \right]\]</span></p>
<p>For SWD to be a true metric, it must satisfy the identity property: <span class="math inline">\(\text{SWD}_2^2(\mu, \nu) = 0 \iff \mu = \nu\)</span>.</p>
<ul>
<li><p><strong>Forward direction (<span class="math inline">\(\mu = \nu \implies \text{SWD} = 0\)</span>):</strong> This is trivial. If the measures are identical, their projections are identical in every direction, making the 1D Wasserstein distances 0.</p></li>
<li><p><strong>Reverse direction (<span class="math inline">\(\text{SWD} = 0 \implies \mu = \nu\)</span>):</strong> If the integral/expectation over the sphere is <span class="math inline">\(0\)</span>, because the integrand <span class="math inline">\(W_2^2(\cdot, \cdot)\)</span> is non-negative ($ $), the integrand must equal zero for Lebesgue-almost-every direction <span class="math inline">\(\theta\)</span>:</p></li>
</ul>
<p><span class="math display">\[W_2^2(\theta_\# \mu, \theta_\# \nu) = 0 \quad \text{for a.e. } \theta \in S^{d-1}\]</span></p>
<p>Since <span class="math inline">\(W_2\)</span> is a valid metric in 1D, a distance of zero means the 1D distributions themselves are identical:</p>
<p><span class="math display">\[\theta_\# \mu = \theta_\# \nu \quad \text{for a.e. } \theta \in S^{d-1}\]</span></p>
<p>As proven by the Fourier Slice Theorem above, this condition strictly forces <span class="math inline">\(\mu = \nu\)</span>. If the Radon transform lacked injectivity—meaning two different shapes could produce the exact same shadows from every single angle—SWD would collapse into a semimetric. Because it is injective, SWD preserves strict identity and is a mathematically valid metric.</p>
<p><br></p>
<p>Note: In step 4 we invoke continuity of the Fourier transform to extend a.e. equality to everywhere equality. That works for continuous measures, but the cleaner general argument is that Fourier transforms of finite measures are continuous by the Riemann-Lebesgue lemma, so a.e. equality of continuous functions implies everywhere equality. Minor, but worth knowing.</p>
<hr>
<section id="the-workflow-2" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow-2">1. The Workflow</h4>
<p>In Stage 3, we scaled our optimal transport utilities from 1-dimensional sequences to complex, multi-dimensional sample spaces. We introduced the Squared Wasserstein-2 distance (<span class="math inline">\(W_2^2\)</span>) and integrated it into a custom, from-scratch implementation of the <strong>Sliced Wasserstein Distance (SWD)</strong> algorithm. Finally, we cross-validated this multi-dimensional metric against exact linear programming solvers and executed a comprehensive convergence study across multiple random projection scales (<span class="math inline">\(L\)</span>) to mathematically and visually isolate the optimal performance configuration.</p>
<p><br></p>
</section>
<section id="the-objective-2" class="level4">
<h4 class="anchored" data-anchor-id="the-objective-2">2. The Objective</h4>
<p>While Stage 2 proved that sorting handles 1D arrays efficiently, real-world machine learning assets (such as deep feature maps or raw images) are highly multi-dimensional. Calculating exact high-dimensional Wasserstein distances is an exceptionally intense computational task, scaling cubically (<span class="math inline">\(O(n^3)\)</span>). The core objective of this stage was to leverage the <strong>Radon Transform</strong> concept via Sliced Wasserstein Distance. This allows us to approximate high-dimensional structural alignment by slicing multi-dimensional distributions into a series of random 1D projections, solving them via our fast <span class="math inline">\(O(n \log n)\)</span> sorting shortcut, and providing a scalable distance metric for complex feature spaces.</p>
<p><br></p>
</section>
<section id="key-learnings-technical-insights-2" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-technical-insights-2">3. Key Learnings &amp; Technical Insights</h4>
<p><strong>A. Sliced Wasserstein Distance (SWD) Mathematics</strong></p>
<p>The Sliced Wasserstein Distance approximates the true high-dimensional Wasserstein distance by integrating the 1D Wasserstein distances of one-dimensional linear projections across all directions on a unit hypersphere.</p>
<p>For two multi-dimensional probability distributions, <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span>, in a <span class="math inline">\(d\)</span>-dimensional space <span class="math inline">\(\mathbb{R}^d\)</span>, the Sliced Wasserstein-2 distance is defined mathematically as:</p>
<p><span class="math display">\[\text{SWD}^2(\mu, \nu) = \int_{\mathbb{S}^{d-1}} \text{W}_2^2(\theta_\# \mu, \theta_\# \nu) \, d\theta\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\mathbb{S}^{d-1}\)</span> represents the <span class="math inline">\(d\)</span>-dimensional unit hypersphere.</li>
<li><span class="math inline">\(\theta\)</span> is a uniform directional projection vector on that hypersphere (<span class="math inline">\(\theta \in \mathbb{S}^{d-1}\)</span>).</li>
<li><span class="math inline">\(\theta_\# \mu\)</span> and <span class="math inline">\(\theta_\# \nu\)</span> denote the 1D push-forward distributions (shadow projections) obtained by projecting the high-dimensional data points onto the line spanned by <span class="math inline">\(\theta\)</span>.</li>
</ul>
<p>In practice, our code implements an empirical approximation of this integral by sampling a discrete, finite number of random projection directions (<span class="math inline">\(L\)</span>):</p>
<p><span class="math display">\[\text{SWD}^2(\mu, \nu) \approx \frac{1}{L} \sum_{l=1}^{L} \text{W}_2^2\left(\theta_l^\# \mu, \theta_l^\# \nu\right)\]</span></p>
<p>Because each individual projection is entirely 1-dimensional, we solve the inner <span class="math inline">\(\text{W}_2^2\)</span> operations instantly using our sorted quantile mechanism:</p>
<p><span class="math display">\[\text{W}_2^2\left(\theta_l^\# \mu, \theta_l^\# \nu\right) = \frac{1}{n} \sum_{i=1}^{n} \left| X_{(i)}^{(l)} - Y_{(i)}^{(l)} \right|^2\]</span></p>
<p><br></p>
<p><strong>B. Multi-Dimensional Lower-Bound Behavior</strong></p>
<p>We verified our custom <code>sliced_wasserstein</code> function against the exact multi-dimensional Wasserstein solver (<code>ot.emd2</code>) inside the POT library using two separated 2D Gaussian point clouds (<span class="math inline">\(d=2\)</span>).</p>
<ul>
<li><em>Our Custom SWD (<span class="math inline">\(L=2000\)</span>):</em> <code>3.9901</code></li>
<li><em>Full Dimensional <span class="math inline">\(W_2^2\)</span> (POT):</em> <code>7.9945</code></li>
<li><strong>Mathematical Trait:</strong> This head-to-head test highlighted a crucial structural fact: <span class="math inline">\(\text{SWD} \leq \text{W}_2^2\)</span>. Slicing down to 1D operates as a mathematical <strong>lower bound</strong>. In full 2D space, the cost matrix accounts for diagonal spatial paths (<span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> vectors simultaneously). Projecting data onto flat 1D lines compresses these geometric distances, reducing the apparent transport cost while perfectly maintaining the relative structural relationship between distributions.</li>
</ul>
<p><br></p>
<p><strong>C. Empirical Statistical Convergence Analysis</strong></p>
<p>Because SWD utilizes random projections, the stability of its output depends strictly on the total number of slices (<span class="math inline">\(L\)</span>). We conducted a stability study over 10 independent trials per configuration to track how the metric stabilizes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Number of Projections (<span class="math inline">\(L\)</span>)</th>
<th>Mean Distance Score</th>
<th>Variance / Standard Deviation (<span class="math inline">\(\sigma\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><span class="math inline">\(L = 10\)</span></strong></td>
<td>4.1430</td>
<td>0.8020 (Highly Volatile)</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(L = 100\)</span></strong></td>
<td>4.0738</td>
<td>0.3370</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(L = 500\)</span></strong></td>
<td>3.9688</td>
<td>0.1250</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(L = 1,000\)</span></strong></td>
<td>4.0097</td>
<td>0.0738</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(L = 5,000\)</span></strong></td>
<td>3.9827</td>
<td>0.0215 (Highly Deterministic)</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>The Law of Large Numbers:</strong> This benchmark perfectly visualized the statistical law of convergence. At low values of <span class="math inline">\(L\)</span>, the variance is massive (<span class="math inline">\(\sigma = 0.8020\)</span>), meaning the distance value bounces around wildly depending on the random directions chosen. As <span class="math inline">\(L\)</span> approaches higher thresholds, the mean converges tightly onto the true continuous limit (<span class="math inline">\(\approx 3.98\)</span>) and the standard deviation drops toward zero.</li>
</ul>
<p><br></p>
<p><strong>D. Visualizing Architectural Equilibrium</strong></p>
<p>By plotting the average distance values alongside vertical error bars across a logarithmic scale, we visually exposed the algorithm’s operational envelope. The chart clearly showed that the error margins collapse exponentially as <span class="math inline">\(L\)</span> scales up. This graphical profile provides a critical architectural finding: setting <span class="math inline">\(L\)</span> between <strong>500 and 1,000</strong> serves as the optimal engineering sweet spot. It provides near-perfect statistical stability while preventing excessive projection loops, keeping the deep learning pipeline hyper-fast. We have successfully established, validated, and optimized our high-dimensional transport metric framework.</p>
<hr>
</section>
</section>
<section id="stage-4---triangle-inequality-verification" class="level3">
<h3 class="anchored" data-anchor-id="stage-4---triangle-inequality-verification">Stage 4 - Triangle Inequality Verification</h3>
<p>We’re numerically verifying that SWD is a valid metric by stress-testing the triangle inequality across 1000 random distribution triplets. This matters because our SWD is an <em>estimator</em> — finite L introduces variance, and we need to distinguish estimator noise from genuine metric violations.</p>
<p><br></p>
</section>
<section id="questions-4" class="level3">
<h3 class="anchored" data-anchor-id="questions-4">Questions [4]</h3>
<ol type="1">
<li><p>State the three metric axioms for D(·,·). For each one, identify whether it’s: (a) trivially satisfied by construction, (b) inherited directly from <span class="math inline">\(W_2^²\)</span> symmetry, or (c) requires the Radon injectivity argument.</p></li>
<li><p>If your finite-<span class="math inline">\(L\)</span> estimator produces <span class="math inline">\(\mathrm{SWD}(\mu,\rho) &gt; \mathrm{SWD}(\mu,\nu) + \mathrm{SWD}(\nu,\rho)\)</span> for some triplet, does this mean the triangle inequality <em>fails</em> for SWD, or something else, what does the magnitude of the violation tell you, and how does it relate to <span class="math inline">\(L\)</span>?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-4" class="level3">
<h3 class="anchored" data-anchor-id="answers-4">Answers [4]</h3>
<p><strong>1. Metric Axioms and their Structural Dependencies</strong></p>
<p>Let <span class="math inline">\(D(\mu, \nu) = \text{SWD}(\mu, \nu) = \left( \mathbb{E}_{\theta \sim U(S^{d-1})} \left[ W_2^2(\theta_\# \mu, \theta_\# \nu) \right] \right)^{1/2}\)</span> be the Sliced Wasserstein Distance. Here is how the three metric axioms map to their respective justifications:</p>
<p><br></p>
<p><strong>A. Identity of Indiscernibles (<span class="math inline">\(D(\mu, \nu) = 0 \iff \mu = \nu\)</span>)</strong></p>
<ul>
<li><p><strong>Classification:</strong> <strong>(c) Requires the Radon injectivity argument.</strong></p></li>
<li><p><strong>Justification:</strong> While the forward direction (<span class="math inline">\(\mu = \nu \implies D(\mu, \nu) = 0\)</span>) is trivial, the reverse direction is not. If <span class="math inline">\(D(\mu, \nu) = 0\)</span>, the non-negativity of the 1D Wasserstein metric implies that <span class="math inline">\(\theta_\# \mu = \theta_\# \nu\)</span> for Lebesgue-almost-every direction <span class="math inline">\(\theta\)</span>. Showing that identical 1D projections across almost all directions forces the original high-dimensional measures to be completely identical requires the injectivity of the Radon transform (via the Fourier Slice Theorem).</p></li>
</ul>
<p><br></p>
<p><strong>B. Symmetry (<span class="math inline">\(D(\mu, \nu) = D(\nu, \mu)\)</span>)</strong></p>
<ul>
<li><p><strong>Classification:</strong> <strong>(b) Inherited directly from <span class="math inline">\(W_2\)</span> symmetry.</strong></p></li>
<li><p><strong>Justification:</strong> At its core, the SWD integrand relies entirely on the standard 1D Wasserstein distance. Because the 1D Wasserstein distance is a true metric, it possesses strict symmetry: <span class="math inline">\(W_2^2(\theta_\# \mu, \theta_\# \nu) = W_2^2(\theta_\# \nu, \theta_\# \mu)\)</span> for any direction <span class="math inline">\(\theta\)</span>. Since the expectation operator preserves this symmetry across the integration space, the property is inherited directly.</p></li>
</ul>
<p><br></p>
<p><strong>C. Triangle Inequality (<span class="math inline">\(D(\mu, \rho) \leq D(\mu, \nu) + D(\nu, \rho)\)</span>)</strong></p>
<ul>
<li><p><strong>Classification:</strong> <strong>(b) Inherited directly from <span class="math inline">\(W_2\)</span> (via Minkowski’s Inequality).</strong></p></li>
<li><p><strong>Justification:</strong> For every single projected direction <span class="math inline">\(\theta\)</span>, the 1D Wasserstein distance satisfies the triangle inequality: <span class="math inline">\(W_2(\theta_\# \mu, \theta_\# \rho) \leq W_2(\theta_\# \mu, \theta_\# \nu) + W_2(\theta_\# \nu, \theta_\# \rho)\)</span>. When we take the <span class="math inline">\(L_2\)</span> norm (the square root of the expected value of squares) over the uniform distribution of directions, the integration preserves the triangle inequality due to Minkowski’s inequality for <span class="math inline">\(L_p\)</span> spaces (where <span class="math inline">\(p=2\)</span>).</p></li>
</ul>
<p><br></p>
<p><strong>2. Finite-<span class="math inline">\(L\)</span> Estimators and Triangle Inequality Violations</strong></p>
<p><strong>What does it mean?</strong></p>
<p>In practice, we cannot compute the true SWD because we cannot integrate over an infinite number of angles. Instead, we use a finite-<span class="math inline">\(L\)</span> estimator:</p>
<p><span class="math display">\[\widehat{\text{SWD}}_L(\mu, \nu) = \left( \frac{1}{L} \sum_{l=1}^L W_2^2(\theta_l \# \mu, \theta_l \# \nu) \right)^{1/2}\]</span></p>
<p>If you pick three distributions (<span class="math inline">\(\mu, \nu, \rho\)</span>) and find that your calculated distances violate the triangle inequality, it does <strong>not</strong> mean the mathematical definition of SWD is broken. It means your empirical sample of directions is introducing a specific type of statistical error.</p>
<p><br></p>
<p><strong>What the Violation Tells You</strong></p>
<p>If <span class="math inline">\(\widehat{\text{SWD}}_L(\mu, \rho) &gt; \widehat{\text{SWD}}_L(\mu, \nu) + \widehat{\text{SWD}}_L(\nu, \rho)\)</span>, it reveals that <strong>different sets of random directions <span class="math inline">\(\theta\)</span> were sampled to calculate each pair.</strong></p>
<p>When implementing a finite-<span class="math inline">\(L\)</span> estimator, a fresh batch of <span class="math inline">\(L\)</span> random directions is typically drawn independently for each distance calculation. Because each pair is evaluated on completely different 1D projections, the estimator acts as a collection of entirely different random variables rather than a coherent metric space.</p>
<ul>
<li><strong>The Fix:</strong> If you freeze a single set of <span class="math inline">\(L\)</span> random directions and reuse that exact same set of directions to compute all three distances, the estimator becomes a valid metric space, and the triangle inequality will never be violated.</li>
</ul>
<p><br></p>
<p><strong>Relation to <span class="math inline">\(L\)</span> and the Magnitude of the Violation</strong></p>
<p>The magnitude of the triangle inequality violation acts as a direct proxy for the <strong>variance of the estimator</strong>.</p>
<p>According to the Central Limit Theorem, the standard statistical error of a Monte Carlo estimator scales at a rate of:</p>
<p><span class="math display">\[\mathcal{O}\left(\frac{1}{\sqrt{L}}\right)\]</span></p>
<p>As <span class="math inline">\(L \to \infty\)</span>, the empirical estimator converges cleanly to the true continuous SWD integral. Therefore, the magnitude of the violation tells you how under-sampled your directional space is. A large violation means <span class="math inline">\(L\)</span> is too low to accurately capture the geometric structures of the distributions, whereas increasing <span class="math inline">\(L\)</span> will cause the violation magnitude to decay predictably toward zero.</p>
<p><br></p>
<p>Note: One precision on point 2: the “fix” of freezing directions is correct for a consistent estimator, but our experiment intentionally uses independent direction draws per pair to stress-test the worst case. Violations under independent draws measure estimator variance; violations under shared draws would indicate a genuine metric failure (which shouldn’t occur).</p>
<hr>
<section id="the-workflow-3" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow-3">1. The Workflow</h4>
<p>In Stage 4, we subjected our custom Sliced Wasserstein Distance (SWD) framework to rigorous axiomatic validation. We constructed a mathematical wrapper to extract linear (non-squared) SWD values from empirical distributions and created an evaluation pipeline to test the framework in a highly non-trivial 8-dimensional space (<span class="math inline">\(d=8\)</span>). We then conducted large-scale simulations across 1,000 randomized distribution triplets to analyze geometric stability under two distinct structural environments: one with completely randomized, mismatched directional projections (worst-case scenario), and one with uniform, shared projection trajectories. Finally, we executed an adversarial parametric sweep across various projection resolutions (<span class="math inline">\(L\)</span>) to discover the boundaries where statistical noise compromises metric integrity.</p>
<p><br></p>
</section>
<section id="the-objective-3" class="level4">
<h4 class="anchored" data-anchor-id="the-objective-3">2. The Objective</h4>
<p>An algorithm cannot reliably guide domain adaptation if it fails to act as a legitimate metric space. If an optimization function violates foundational geometric laws, it can introduce chaotic gradients, systemic instabilities, or degenerate loops during deep network alignment. The objective of this stage was to formally prove that our from-scratch SWD implementation obeys the strict mathematical axioms of a <strong>Metric Space</strong>—specifically focusing on validating the <strong>Triangle Inequality</strong> in complex high-dimensional feature spaces, and determining the exact parameter thresholds required to guarantee structural safety.</p>
<p><br></p>
</section>
<section id="key-learnings-technical-insights-3" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-technical-insights-3">3. Key Learnings &amp; Technical Insights</h4>
<p><strong>A. Metric Axioms &amp; The Triangle Inequality Mathematics</strong></p>
<p>For a function <span class="math inline">\(d(x, y)\)</span> to qualify as a formal metric over a set of distributions, it must satisfy three structural constraints for all elements:</p>
<ol type="1">
<li><strong>Identity of Indiscernibles:</strong> <span class="math inline">\(d(x, y) = 0 \iff x = y\)</span></li>
<li><strong>Symmetry:</strong> <span class="math inline">\(d(x, y) = d(y, x)\)</span></li>
<li><strong>Triangle Inequality:</strong> <span class="math inline">\(d(x, z) \leq d(x, y) + d(y, z)\)</span></li>
</ol>
<p>While the squared Wasserstein metric (<span class="math inline">\(\text{W}_2^2\)</span>) is highly effective for optimization, it violates the triangle inequality due to the squaring operation. By defining a linear wrapper <span class="math inline">\(\text{SWD}(\mu, \nu) = \sqrt{\text{SWD}^2(\mu, \nu)}\)</span>, we restored linear spatial properties.</p>
<p>Mathematically, given three separate distribution point clouds <span class="math inline">\(\mu, \nu, \rho \in \mathbb{R}^d\)</span>, the linear SWD triangle equation is expressed as:</p>
<p><span class="math display">\[\left( \int_{\mathbb{S}^{d-1}} \text{W}_2^2(\theta_\# \mu, \theta_\# \rho) \, d\theta \right)^{1/2} \leq \left( \int_{\mathbb{S}^{d-1}} \text{W}_2^2(\theta_\# \mu, \theta_\# \nu) \, d\theta \right)^{1/2} + \left( \int_{\mathbb{S}^{d-1}} \text{W}_2^2(\theta_\# \nu, \theta_\# \rho) \, d\theta \right)^{1/2}\]</span></p>
<p>Our pipeline quantified this relationship by computing a structural margin metric for each triplet:</p>
<p><span class="math display">\[\text{Margin} = \text{SWD}(\mu, \rho) - \text{SWD}(\mu, \nu) - \text{SWD}(\nu, \rho)\]</span></p>
<p>A valid metric space mandates that <span class="math inline">\(\text{Margin} \leq 0\)</span>. Any instance where <span class="math inline">\(\text{Margin} &gt; 0\)</span> denotes a catastrophic geometric violation.</p>
<p><br></p>
<p><strong>B. Robustness Under Mismatched Directional Sampling</strong></p>
<p>We forced an exceptionally harsh environment by calculating each leg of our high-dimensional triangle using completely independent, non-aligned random seeds:</p>
<ul>
<li><span class="math inline">\(\text{Leg } 1 \rightarrow \theta_{\mu\rho}\)</span> (Seed <span class="math inline">\(A\)</span>)</li>
<li><span class="math inline">\(\text{Leg } 2 \rightarrow \theta_{\mu\nu}\)</span> (Seed <span class="math inline">\(B\)</span>)</li>
<li><span class="math inline">\(\text{Leg } 3 \rightarrow \theta_{\nu\rho}\)</span> (Seed <span class="math inline">\(C\)</span>)</li>
<li><strong>Empirical Validation:</strong> At a resolution of <span class="math inline">\(L=500\)</span>, evaluating 1,000 distinct 8D distribution triplets yielded <strong>0 violations</strong>, achieving a flawless <strong>100.00% pass rate</strong>.</li>
<li><strong>Statistical Distribution:</strong> The mean margin registered at <strong>-4.131103</strong> (<span class="math inline">\(\sigma = 1.658141\)</span>). This proves that the metric satisfies the triangle inequality comfortably with significant structural “slack,” demonstrating that our custom implementation remains stable even when subject to localized random projection variations.</li>
</ul>
<p><br></p>
<p><strong>C. Flawless Alignment via Shared Projection Profiles</strong></p>
<p>When the simulation was repeated by synchronizing the random seeds across all three calculations (<span class="math inline">\(\theta_{\mu\rho} = \theta_{\mu\nu} = \theta_{\nu\rho}\)</span>), all potential projection sampling noise was completely eliminated.</p>
<ul>
<li><strong>Theoretical Proof:</strong> Under shared directions, the violation rate collapsed to an absolute <strong>0/1000</strong> with a maximum violation score of <strong><span class="math inline">\(0.00 \times 10^{+00}\)</span></strong>. This mathematically demonstrates that when an AI model locks onto a fixed or shared projection coordinate matrix during feature alignment, the high-dimensional transport space inherits the flawless geometric properties of its underlying 1D components, eliminating structural anomalies.</li>
</ul>
<p><br></p>
<p><strong>D. Slicing Resolution Threshold Boundaries</strong></p>
<p>Finally, we explored the operational boundaries of our metric by measuring how geometric failures manifest as the projection slice density (<span class="math inline">\(L\)</span>) drops under mismatched seeds:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Number of Projections (<span class="math inline">\(L\)</span>)</th>
<th>Triangle Inequality Violation Rate</th>
<th>Operational Condition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><span class="math inline">\(L = 10\)</span></strong></td>
<td><strong>2.0%</strong></td>
<td><strong>Degenerate / Unsafe</strong></td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(L = 50\)</span></strong></td>
<td>0.2%</td>
<td>Marginal Risk</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(L = 100\)</span></strong></td>
<td>0.0%</td>
<td>Secure</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(L = 500\)</span></strong></td>
<td>0.0%</td>
<td>Highly Secure</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(L = 1,000\)</span></strong></td>
<td>0.0%</td>
<td>Deterministic</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Critical Architectural Discovery:</strong> This parameter sweep exposed a vital engineering guardrail. When <span class="math inline">\(L &lt; 100\)</span>, the 1D slices are too sparse to accurately resolve an 8-dimensional space, causing statistical variance to actively break geometric laws. Once <span class="math inline">\(L \geq 100\)</span>, the directional density passes a mathematical inflection point where random slicing errors drop to zero, ensuring absolute structural safety.</li>
</ul>
<hr>
</section>
</section>
<section id="stage-5---max-sliced-wasserstein-distance" class="level3">
<h3 class="anchored" data-anchor-id="stage-5---max-sliced-wasserstein-distance">Stage 5 - Max-Sliced Wasserstein Distance</h3>
<p>We find the <em>worst-case</em> projection direction via projected gradient ascent rather than averaging over random directions. This gives a tighter, more discriminative distance at lower computational cost than large-L SWD.</p>
<p><br></p>
</section>
<section id="questions-5" class="level3">
<h3 class="anchored" data-anchor-id="questions-5">Questions [5]</h3>
<p>Max-SWD solves:</p>
<p><span class="math display">\[\text{Max-SWD}(\mu, \nu) = \max_{\theta \in S^{d-1}} W_2^2(\theta_\#\mu, \theta_\#\nu)\]</span></p>
<p>Answer both:</p>
<ol type="1">
<li><p>The discriminator in a GAN finds the function that maximally separates real from fake distributions. Max-SWD finds the direction that maximally separates two projected distributions. State the precise analogy — what plays the role of the discriminator, what plays the role of the generator, and what is the adversarial game being solved?</p></li>
<li><p>Projected gradient ascent on <span class="math inline">\(S^{d-1}\)</span> requires keeping <span class="math inline">\(\theta\)</span> on the unit sphere after each gradient step. What is the correct projection operation, and why is normalizing after each step the right approach rather than using a constrained optimizer?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-5" class="level3">
<h3 class="anchored" data-anchor-id="answers-5">Answers [5]</h3>
<p><strong>1. The GAN Analogy of Max-SWD</strong></p>
<p><strong>What does it mean?</strong></p>
<p>Max-SWD can be interpreted as a constrained, linear Generative Adversarial Network. Instead of a deep neural network searching through millions of complex parameters to find a way to separate real and fake data, Max-SWD searches through a simple space of directions (<span class="math inline">\(\theta\)</span>) to find the single 1D viewpoint that makes the two distributions look as different as possible.</p>
<p><br></p>
<p><strong>The Analogy Breakdown</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Component in Standard GAN</th>
<th>Equivalent in Max-SWD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>The Generator (<span class="math inline">\(G\)</span>)</strong></td>
<td>The parameter mechanism shaping the target/fake distribution <span class="math inline">\(\nu\)</span> (e.g., a model trying to push <span class="math inline">\(\nu\)</span> closer to the true distribution <span class="math inline">\(\mu\)</span>).</td>
</tr>
<tr class="even">
<td><strong>The Discriminator (<span class="math inline">\(D\)</span>)</strong></td>
<td>The projection direction vector <span class="math inline">\(\theta \in S^{d-1}\)</span>.</td>
</tr>
<tr class="odd">
<td><strong>The Discriminator’s Operation</strong></td>
<td>The linear projection and 1D distance computation: <span class="math inline">\(W_2^2(\theta_\# \mu, \theta_\# \nu)\)</span>.</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>The Adversarial Game Being Solved</strong></p>
<p>In a standard GAN, the game is a minimax optimization over a family of non-linear functions. In Max-SWD, if we assume we are updating a generator’s parameters to make a fake distribution <span class="math inline">\(\nu\)</span> match a real distribution <span class="math inline">\(\mu\)</span>, the adversarial game is formulated as:</p>
<p><span class="math display">\[\min_{\nu} \max_{\theta \in S^{d-1}} W_2^2(\theta_\# \mu, \theta_\# \nu)\]</span></p>
<ul>
<li><p><strong>The Max Player (<span class="math inline">\(\theta\)</span>):</strong> Acts as a highly constrained, linear discriminator. It scans the unit sphere to find the specific angle <span class="math inline">\(\theta\)</span> that exposes the greatest geometric flaw (the maximum Wasserstein distance) between the two distributions.</p></li>
<li><p><strong>The Min Player (<span class="math inline">\(\nu\)</span>):</strong> Acts as the generator. It tries to shift and reshape its distribution to minimize this maximum gap, making the two distributions look identical from even the most critical vantage point.</p></li>
</ul>
<p><br></p>
<p><strong>2. Gradient Ascent on the Sphere and the Projection Operation</strong></p>
<p><strong>What does it mean?</strong></p>
<p>When optimizing <span class="math inline">\(\theta\)</span>, your direction vector must always have a length of exactly <span class="math inline">\(1\)</span> (meaning it sits on the surface of the unit sphere <span class="math inline">\(S^{d-1}\)</span>). Standard gradient steps change the length of the vector, pulling it off the sphere. You need a mathematically sound way to force it back onto the surface.</p>
<p><br></p>
<p><strong>The Correct Projection Operation</strong></p>
<p>Let <span class="math inline">\(\theta^{(t)}\)</span> be your current direction vector on the sphere, <span class="math inline">\(\eta\)</span> be the learning rate, and <span class="math inline">\(g = \nabla_\theta W_2^2(\theta_\#\mu, \theta_\#\nu)\)</span> be the gradient evaluated at <span class="math inline">\(\theta^{(t)}\)</span>.</p>
<ol type="1">
<li><strong>Take an unconstrained step</strong> in the direction of the gradient:</li>
</ol>
<p><span class="math display">\[\tilde{\theta}^{(t+1)} = \theta^{(t)} + \eta g\]</span></p>
<ol start="2" type="1">
<li><strong>Project back onto the unit sphere</strong> by dividing the vector by its Euclidean norm (<span class="math inline">\(L_2\)</span> norm):</li>
</ol>
<p><span class="math display">\[\theta^{(t+1)} = \text{Proj}_{S^{d-1}}(\tilde{\theta}^{(t+1)}) = \frac{\tilde{\theta}^{(t+1)}}{\|\tilde{\theta}^{(t+1)}\|_2}\]</span></p>
<p><br></p>
<p><strong>Why Normalizing is better than a Constrained Optimizer?</strong></p>
<p>Using an explicit constrained optimization framework (like introducing Lagrange multipliers to enforce the strict constraint <span class="math inline">\(\sum \theta_i^2 = 1\)</span>) adds heavy computational overhead. Normalizing after each step is the superior approach for three distinct reasons:</p>
<ul>
<li><p><strong>Closed-Form Simplicity:</strong> The metric projection onto a unit sphere has an exact, analytical closed-form solution (simply dividing by the vector’s length). There is no need to run an internal iterative loop to solve for dual variables or balance penalty terms.</p></li>
<li><p><strong>True Euclidean Shortest Path:</strong> The operation <span class="math inline">\(\frac{\tilde{\theta}}{\|\tilde{\theta}\|_2}\)</span> maps the out-of-bounds vector back to the mathematically closest point on the sphere in terms of standard Euclidean distance. It satisfies the strict definition of a orthogonal projection operator.</p></li>
<li><p><strong>Riemannian Manifold Optimization Alignment:</strong> Normalizing after a step acts as a first-order retraction onto a Riemannian manifold. Because the sphere is a highly symmetric, smooth manifold, this simple normalization preserves the direction of the gradient step while correcting the scale instantly, matching the performance of complex manifold optimizers at a fraction of the computational cost.</p></li>
</ul>
<p><br></p>
<p>Note: One sharpening: the “Riemannian retraction” point is correct but slightly overclaimed — simple renormalization is a first-order retraction, not a full geodesic step. For our purposes it’s sufficient, but higher-order methods (like the exponential map) would stay closer to the true geodesic on <span class="math inline">\(S^{d-1}\)</span>.</p>
<hr>
<section id="the-workflow-4" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow-4">1. The Workflow</h4>
<p>In Stage 5, we transitioned from passive geometric validation to active transport optimization. We engineered a fully differentiable, Autograd-compliant 1D Squared Wasserstein-2 (<span class="math inline">\(W_2^2\)</span>) core routine. Using this foundation, we implemented the <strong>Max-Sliced Wasserstein Distance (Max-SWD)</strong> algorithm from scratch, replacing random directional sampling with a <strong>Projected Gradient Ascent</strong> loop over a unit hypersphere (<span class="math inline">\(\mathbb{S}^{d-1}\)</span>).</p>
<p>We then evaluated this optimization engine against standard Sliced Wasserstein Distance (SWD) in an 8-dimensional space (<span class="math inline">\(d=8\)</span>) containing a hidden, highly localized structural anomaly along a single feature axis. Finally, we visualized the optimized projections via frequency density histograms and mapped out the step-wise convergence rate of the gradient ascent loop to isolate its optimal computational bounds.</p>
<p><br></p>
</section>
<section id="the-objective-4" class="level4">
<h4 class="anchored" data-anchor-id="the-objective-4">2. The Objective</h4>
<p>While standard SWD is highly efficient, its random averaging mechanic suffers from a severe <strong>signal dilution</strong> problem in high-dimensional settings. If two datasets perfectly overlap across 99 dimensions but are heavily misaligned along just one specific direction, standard SWD will dilute that crucial error signal with meaningless noise from the matching dimensions.</p>
<p>The objective of Stage 5 was to resolve this bottleneck by framing the projection search as a targeted optimization problem. By actively steering a single projection vector into the absolute worst-case direction of misalignment, Max-SWD provides a high-contrast structural metric capable of guiding neural networks during domain adaptation tasks with pinpoint geometric accuracy.</p>
<p><br></p>
</section>
<section id="key-learnings-technical-insights-4" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-technical-insights-4">3. Key Learnings &amp; Technical Insights</h4>
<p><strong>A. Differentiable Sorting Mechanics</strong></p>
<p>To optimize a projection vector via backpropagation, our transport engine had to support automatic differentiation. In Block 21, we isolated the differentiable 1D core function:</p>
<p><span class="math display">\[\text{W}_2^2(x, y) = \frac{1}{n} \sum_{i=1}^{n} \left| x_{(i)} - y_{(i)} \right|^2\]</span></p>
<ul>
<li><strong>Autograd Compatibility:</strong> While sorting is fundamentally a discrete operation (re-indexing elements does not have a continuous derivative), PyTorch manages this using a <strong>straight-through estimator style mapping</strong>. The gradients are bypassed directly to the underlying scalar <em>values</em> at their sorted positions. By eliminating data-stripping commands like <code>.item()</code>, we preserved the live computational graph, allowing gradients to flow unimpeded through the sorting mechanism and back into our projection parameters.</li>
</ul>
<p><br></p>
<p><strong>B. Max-SWD Optimization &amp; Projected Gradient Ascent Mathematics</strong></p>
<p>The mathematical formulation of the Max-Sliced Wasserstein Distance transitions from an integration over a hypersphere to a constrained maximization problem:</p>
<p><span class="math display">\[\text{Max-SWD}(\mu, \nu) = \max_{\theta \in \mathbb{S}^{d-1}} \text{W}_2^2(\theta_\# \mu, \theta_\# \nu)\]</span></p>
<p>To solve this under the constraint that the tracking vector <span class="math inline">\(\theta\)</span> must remain a valid unit direction on the hypersphere (<span class="math inline">\(\|\theta\|_2 = 1\)</span>), our custom engine implemented <strong>Projected Gradient Ascent</strong>:</p>
<ol type="1">
<li><p><strong>Projection:</strong> The data matrices <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are projected onto the current vector: <span class="math inline">\(x_p = X\theta\)</span> and <span class="math inline">\(y_p = Y\theta\)</span>.</p></li>
<li><p><strong>Objective Function Negation:</strong> Since standard PyTorch optimizers execute gradient descent, we negated our objective function to force ascent behavior: <span class="math inline">\(\mathcal{L}(\theta) = -\text{W}_2^2(x_p, y_p)\)</span>.</p></li>
<li><p><strong>Backpropagation:</strong> The spatial gradient is derived using Autograd: <span class="math inline">\(\nabla_\theta \mathcal{L}(\theta)\)</span>.</p></li>
<li><p><strong>The Gradient Step:</strong> The parameter weights are stepped in the direction of maximal distance: <span class="math inline">\(\theta_{\text{new}} = \theta - \eta \nabla_\theta \mathcal{L}(\theta)\)</span> (where <span class="math inline">\(\eta\)</span> is the learning rate).</p></li>
<li><p><strong>Hypersphere Projection:</strong> The updated vector is instantly mapped back onto the unit sphere surface to satisfy the metric constraint:</p></li>
</ol>
<p><span class="math display">\[\theta_{\text{final}} = \frac{\theta_{\text{new}}}{\|\theta_{\text{new}}\|_2}\]</span></p>
<p><br></p>
<p><strong>C. Isolating Localized Structural Discrepancies</strong></p>
<p>We tested this optimization engine by generating two 8D distributions where a spatial gap was isolated entirely along the very first axis (<span class="math inline">\(e_0 = [1, 0, 0, \dots, 0]\)</span>):</p>
<ul>
<li><span class="math inline">\(\text{Dataset } X \sim \mathcal{N}(0, 0.5I)\)</span></li>
<li><span class="math inline">\(\text{Dataset } Y \sim \mathcal{N}(2 \cdot e_0, 0.5I)\)</span></li>
</ul>
<p>The performance metrics exposed a striking contrast in sensitivity:</p>
<ul>
<li><em>Standard SWD (<span class="math inline">\(L=2000\)</span>):</em> <code>0.4805</code> (Signal heavily diluted by the 7 overlapping dimensions)</li>
<li><em>Max-SWD:</em> <code>4.0349</code> (Perfect recovery of the true squared distance: <span class="math inline">\(2^2 = 4.0\)</span>)</li>
<li><strong>Directional Accuracy:</strong> By evaluating the absolute dot product between our optimized vector <span class="math inline">\(\theta^*\)</span> and the true baseline vector <span class="math inline">\(e_0\)</span>, we verified its alignment:</li>
</ul>
<p><span class="math display">\[|\theta^* \cdot e_0| = 0.9990\]</span></p>
<p>This mathematically proves that the gradient ascent engine achieved <strong>99.90% directional accuracy</strong>, ignoring the 7 noise dimensions to lock onto the exact axis of maximum distribution drift.</p>
<p><br></p>
<p><strong>D. Visualizing the Maximum Mismatch Profile</strong></p>
<p>By projecting the multi-dimensional point clouds onto our optimized <span class="math inline">\(\theta^*\)</span> coordinate, we compressed the complex 8D data down to a 1D visualization window. The resulting twin-histogram chart rendered two completely isolated bell curves—the source dataset centered neatly at <span class="math inline">\(0.0\)</span> and the target dataset shifted perfectly over to <span class="math inline">\(+2.0\)</span>. This output serves as a high-contrast diagnostic blueprint for our domain adaptation models, isolating exactly what features require correction.</p>
<p><br></p>
<p><strong>E. Optimization Efficiency Bounds</strong></p>
<p>Finally, we tracked the convergence profile of our gradient ascent loop across a variety of step capacities:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Optimization Steps</th>
<th>Captured Max-SWD Value</th>
<th>Mathematical Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>10 Steps</strong></td>
<td>2.2583</td>
<td>Under-optimized (Vector mid-rotation)</td>
</tr>
<tr class="even">
<td><strong>25 Steps</strong></td>
<td>3.7473</td>
<td>Approaching Target</td>
</tr>
<tr class="odd">
<td><strong>50 Steps</strong></td>
<td>4.0285</td>
<td>Near-Convergence</td>
</tr>
<tr class="even">
<td><strong>100 Steps</strong></td>
<td><strong>4.0349</strong></td>
<td><strong>Asymptotic Convergence (Optimal)</strong></td>
</tr>
<tr class="odd">
<td><strong>200 Steps</strong></td>
<td>4.0349</td>
<td>Redundant Iteration</td>
</tr>
<tr class="even">
<td><strong>500 Steps</strong></td>
<td>4.0349</td>
<td>Redundant Iteration</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Engineering Recommendation:</strong> This convergence sweep isolated a clear operational boundary. At <span class="math inline">\(&lt; 50\)</span> steps, the search vector terminates prematurely, underestimating the true distribution discrepancy. At <strong>100 steps</strong>, the metric achieves absolute convergence and plateaus permanently. Restricting our Max-SWD calculations to exactly 100 steps provides a rock-solid, mathematically precise misalignment signal while maximizing the overall execution speed of our AI pipeline.</li>
</ul>
<hr>
</section>
</section>
<section id="stage-6---entropic-ot-baseline-full-sinkhorn" class="level3">
<h3 class="anchored" data-anchor-id="stage-6---entropic-ot-baseline-full-sinkhorn">Stage 6 - Entropic OT Baseline (Full Sinkhorn)</h3>
<p>We now implement full entropic OT distance using the Sinkhorn algorithm.</p>
<p><br></p>
</section>
<section id="questions-6" class="level3">
<h3 class="anchored" data-anchor-id="questions-6">Questions [6]</h3>
<ol type="1">
<li><p>Sinkhorn iterates on an n×n cost matrix. State its computational complexity in time and memory as a function of n (samples) and T (iterations). At what concrete n does this become impractical as a <em>per-batch</em> training loss on a GPU with 16GB VRAM?</p></li>
<li><p>Entropic OT solves <span class="math inline">\(\min_{\pi \in \Pi(\mu,\nu)} \langle C, \pi \rangle - \varepsilon H(\pi)\)</span> where <span class="math inline">\(H(\pi)\)</span> is the entropy of the transport plan. What does ε control, and what happens to the solution as <span class="math inline">\(\epsilon \to 0\)</span> and <span class="math inline">\(\epsilon \to \inf\)</span>?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-6" class="level3">
<h3 class="anchored" data-anchor-id="answers-6">Answers [6]</h3>
<p><strong>1. Sinkhorn Complexity and Practical Hardware Limits</strong></p>
<p><strong>Computational Complexity</strong></p>
<ul>
<li><p><strong>Time Complexity:</strong> <span class="math inline">\(\mathcal{O}(T \cdot n^2)\)</span></p></li>
<li><p>Each of the <span class="math inline">\(T\)</span> iterations involves two matrix-vector multiplications (<span class="math inline">\(n \times n\)</span> matrix times an <span class="math inline">\(n \times 1\)</span> vector). Since matrix-vector products are <span class="math inline">\(\mathcal{O}(n^2)\)</span>, the total time scales quadratically with the number of samples.</p></li>
<li><p><strong>Memory Complexity:</strong> <span class="math inline">\(\mathcal{O}(n^2)\)</span></p></li>
<li><p>The algorithm requires storing the full kernel matrix <span class="math inline">\(K = \exp(-C/\varepsilon)\)</span> in memory. For <span class="math inline">\(n\)</span> samples in both distributions, this is an <span class="math inline">\(n \times n\)</span> matrix of floating-point numbers.</p></li>
</ul>
<p><strong>The Training Bottleneck</strong></p>
<p>When using Sinkhorn as a <em>per-batch</em> loss function during training, the practical performance wall shifts from a memory constraint to a computational throughput bottleneck well before VRAM is exhausted.</p>
<p>For a typical batch size (e.g., <span class="math inline">\(n \leq 2048\)</span>), an <span class="math inline">\(n \times n\)</span> cost matrix <span class="math inline">\(C\)</span> is trivial in terms of memory footprint. However, because the data representations change every iteration as the model updates, <strong><span class="math inline">\(C\)</span> must be recomputed from scratch during every single forward pass.</strong> The true execution bottleneck stems from the fact that Sinkhorn is an iterative algorithm nested entirely <em>inside</em> each training step. To reach sufficient convergence, it typically requires <span class="math inline">\(T = 50 \text{--} 100\)</span> inner loop iterations per batch update.</p>
<ul>
<li><strong>At <span class="math inline">\(n = 512\)</span>:</strong> <span class="math inline">\(C\)</span> is <span class="math inline">\(512 \times 512\)</span>, which is mathematically trivial for a GPU to process and store.</li>
<li><strong>At <span class="math inline">\(n \geq 5000\)</span>:</strong> The quadratic cost matrix construction coupled with the <span class="math inline">\(T\)</span> inner iterations forces the effective per-step cost of <span class="math inline">\(\mathcal{O}(T \cdot n^2)\)</span> to become overwhelmingly expensive. The wall clock time explodes due to the nested loops, rendering it completely impractical as a training loss long before the 16GB VRAM limit is hit.</li>
</ul>
<p><br></p>
<p><strong>The 16GB VRAM “Wall”</strong></p>
<p>On a GPU with <strong>16GB VRAM</strong>, the bottleneck is almost always memory (the <span class="math inline">\(n^2\)</span> cost matrix) rather than compute time.</p>
<p>Assuming standard 32-bit floats (4 bytes per element), an <span class="math inline">\(n \times n\)</span> matrix takes <span class="math inline">\(4n^2\)</span> bytes. However, for a <em>per-batch</em> training loss, you must also store:</p>
<ol type="1">
<li>The kernel matrix <span class="math inline">\(K\)</span>.</li>
<li>The cost matrix <span class="math inline">\(C\)</span> (to compute gradients).</li>
<li>Intermediate variables for backpropagation/autograd.</li>
</ol>
<p>Practically, this consumes <span class="math inline">\(\approx 3 \times 4n^2\)</span> to <span class="math inline">\(4 \times 4n^2\)</span> bytes.</p>
<ul>
<li>At <span class="math inline">\(n = 10,000\)</span>: <span class="math inline">\(4 \times 4 \times (10,000)^2 \approx 1.6\text{ GB}\)</span>. (Very safe)</li>
<li>At <span class="math inline">\(n = 30,000\)</span>: <span class="math inline">\(4 \times 4 \times (30,000)^2 \approx 14.4\text{ GB}\)</span>. (Hitting the limit)</li>
</ul>
<p><strong>Concrete Limit:</strong> <span class="math inline">\(n \approx 30,000\)</span> to <span class="math inline">\(35,000\)</span> is where a 16GB GPU becomes impractical. For deep learning batches (where <span class="math inline">\(n\)</span> is usually <span class="math inline">\(\leq 2,048\)</span>), Sinkhorn is extremely fast, but for large-scale point cloud alignment or full-dataset matching, memory becomes the primary constraint.</p>
<p><br></p>
<p><strong>2. The Role of <span class="math inline">\(\varepsilon\)</span> in Entropic Optimal Transport</strong></p>
<p>The objective function <span class="math inline">\(\min_{\pi \in \Pi(\mu,\nu)} \langle C, \pi \rangle - \varepsilon H(\pi)\)</span> uses <span class="math inline">\(\varepsilon\)</span> as a <strong>regularization strength</strong> parameter. It controls the trade-off between the “cheapness” of transport and the “entropy” (spread) of the plan.</p>
<p><strong>What happens at the limits?</strong></p>
<ul>
<li><p><strong>As <span class="math inline">\(\varepsilon \to 0\)</span> (The “Hard” Limit):</strong> The entropy term vanishes, and the problem recovers the <strong>classic Monge-Kantorovich Optimal Transport</strong>. The transport plan <span class="math inline">\(\pi\)</span> becomes sparse (matching points as strictly as possible) and the distance becomes the true Wasserstein distance. However, the problem becomes computationally harder to solve and loses its smooth differentiability.</p></li>
<li><p><strong>As <span class="math inline">\(\varepsilon \to \infty\)</span> (The “Maximum Entropy” Limit):</strong> The cost matrix <span class="math inline">\(C\)</span> becomes irrelevant because the entropy term dominates. To maximize entropy, the mass must be spread as evenly as possible across all possible pairs. The solution converges to the <strong>Independent Product Measure</strong>:</p></li>
</ul>
<p><span class="math display">\[\pi_{ij} = \mu_i \nu_j\]</span></p>
<p>In this state, the “transport” looks like a blur where every source point is matched equally to every target point, regardless of distance.</p>
<ul>
<li><strong>The “Sweet Spot”:</strong> <span class="math inline">\(\varepsilon\)</span> acts like a <strong>blurring factor</strong>. A small <span class="math inline">\(\varepsilon\)</span> gives a precise but slow-to-compute matching; a larger <span class="math inline">\(\varepsilon\)</span> gives a “fuzzy” matching that is computationally efficient and provides better gradients for training neural networks.</li>
</ul>
<hr>
<section id="the-workflow-5" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow-5">1. The Workflow</h4>
<p>In Stage 6, we expanded our optimal transport framework beyond 1D projections by implementing high-fidelity, multi-dimensional <strong>Entropic Optimal Transport</strong>. We engineered a fully differentiable, log-domain <strong>Sinkhorn-Knopp algorithm</strong> from scratch.</p>
<p>We then executed a rigorous two-part validation check on a 2D sample distribution (<span class="math inline">\(n=100\)</span>) by cross-referencing our results directly against the industry-standard Python Optimal Transport (POT) library and calculating strict conservation-of-mass marginal error constraints. Next, we conducted an empirical wall-clock speed benchmark tracking the performance scaling profiles of Sinkhorn vs.&nbsp;Sliced Wasserstein Distance (SWD) across expanding sample spaces up to <span class="math inline">\(n=5,000\)</span> in a high-dimensional feature setting (<span class="math inline">\(d=32\)</span>). Finally, we performed a structural sensitivity analysis to visualize how changing the entropic regularization coefficient (<span class="math inline">\(\varepsilon\)</span>) fundamentally alters the sparsity of the underlying transport coupling plan matrix (<span class="math inline">\(\pi\)</span>).</p>
<p><br></p>
</section>
<section id="the-objective-5" class="level4">
<h4 class="anchored" data-anchor-id="the-objective-5">2. The Objective</h4>
<p>While Sliced Wasserstein variants (SWD and Max-SWD) are highly scalable, they evaluate high-dimensional spaces by collapsing them into 1D linear shadows. This simplification misses out on the intricate, global geometric correlations that only exist in full multi-dimensional space.</p>
<p>Standard, unregularized multi-dimensional Optimal Transport, however, is an <span class="math inline">\(O(n^3)\)</span> linear program that cannot be easily parallelized or differentiated. The objective of Stage 6 was to bridge this gap by implementing an entropic approximation. This approach transforms a rigid, computationally prohibitive optimization problem into a smooth, differentiable, and parallelizable matrix-scaling operation. This gives our domain adaptation toolkit a high-fidelity baseline capable of capturing rich, joint-feature distribution structures.</p>
<p><br></p>
</section>
<section id="key-learnings-technical-insights-5" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-technical-insights-5">3. Key Learnings &amp; Technical Insights</h4>
<p><strong>A. Log-Domain Entropic Regularization Mathematics</strong></p>
<p>Kantorovich’s standard Optimal Transport problem seeks a transport coupling matrix <span class="math inline">\(\pi \in \mathbb{R}_+^{n \times m}\)</span> that minimizes the total cost across a dense distance landscape <span class="math inline">\(C\)</span>:</p>
<p><span class="math display">\[\min_{\pi \in \Pi(\mu, \nu)} \langle \pi, C \rangle = \sum_{i=1}^{n} \sum_{j=1}^{m} \pi_{ij} C_{ij}\]</span></p>
<p>Subject to the uniform marginal mass constraints <span class="math inline">\(\pi \mathbf{1}_m = a\)</span> and <span class="math inline">\(\pi^T \mathbf{1}_n = b\)</span>. Entropic Optimal Transport adds an explicit regularization penalty governed by the Shannon entropy <span class="math inline">\(H(\pi)\)</span>:</p>
<p><span class="math display">\[\min_{\pi \in \Pi(\mu, \nu)} \sum_{i=1}^{n} \sum_{j=1}^{m} \pi_{ij} C_{ij} - \varepsilon H(\pi), \quad \text{where } H(\pi) = -\sum_{i=1}^{n} \sum_{j=1}^{m} \pi_{ij} \log \pi_{ij}\]</span></p>
<p>By introducing this smoothing term, the primal problem becomes strictly convex. According to Duality Theorem, the optimal transport plan can now be uniquely decoupled using two scaling vectors (dual potentials) <span class="math inline">\(f \in \mathbb{R}^n\)</span> and <span class="math inline">\(g \in \mathbb{R}^m\)</span>:</p>
<p><span class="math display">\[\pi_{ij} = \exp\left( \frac{f_i + g_j - C_{ij}}{\varepsilon} \right)\]</span></p>
<p>To protect our system from catastrophic numerical underflow/overflow bugs caused by the exponential division by small <span class="math inline">\(\varepsilon\)</span> values, we implemented the alternating Sinkhorn-Knopp scaling iterations directly within log-space using stable <code>logsumexp</code> reductions:</p>
<p><span class="math display">\[f_i^{(t+1)} = \varepsilon \log(a_i) - \varepsilon \log \left( \sum_{j=1}^{m} \exp \left( \frac{g_j^{(t)} - C_{ij}}{\varepsilon} \right) \right)\]</span></p>
<p><span class="math display">\[g_j^{(t+1)} = \varepsilon \log(b_j) - \varepsilon \log \left( \sum_{i=1}^{n} \exp \left( \frac{f_i^{(t+1)} - C_{ij}}{\varepsilon} \right) \right)\]</span></p>
<p>Preserving these raw variables inside the log-domain maintains a continuous computational graph, keeping our custom function fully differentiable and compatible with PyTorch Autograd.</p>
<p><br></p>
<p><strong>B. Algorithmic Verification &amp; Conservation of Mass</strong></p>
<p>We subjected our implementation to an architectural audit on 2D data point clouds under a regularization setting of <span class="math inline">\(\varepsilon = 0.5\)</span>, evaluating its accuracy against two rigorous checks:</p>
<ol type="1">
<li><p><strong>Library Cross-Validation:</strong> Our custom engine returned a transport cost of <code>7.7091</code>, matching the official POT library output (<code>7.7091</code>) with an absolute discrepancy of just <strong><span class="math inline">\(3.51 \times 10^{-06}\)</span></strong>. This confirms our log-space broadcasting logic is completely correct.</p></li>
<li><p><strong>Marginal Conservation Constraints:</strong> A valid optimal transport coupling cannot leak or create probability mass. Every source point must distribute exactly <span class="math inline">\(1/n\)</span> mass, and every target point must absorb exactly <span class="math inline">\(1/m\)</span> mass. We verified this by calculating the maximum absolute deviation from uniform marginal targets:</p></li>
</ol>
<ul>
<li><em>Row Marginal Error:</em> <span class="math inline">\(2.51 \times 10^{-08}\)</span></li>
<li><em>Column Marginal Error:</em> <span class="math inline">\(1.96 \times 10^{-08}\)</span></li>
</ul>
<p>These near-zero errors demonstrate that our 300-loop alternating log-scaling equations achieved highly precise numerical convergence.</p>
<p><br></p>
<p><strong>C. The Computational Scaling Cliff</strong></p>
<p>Our empirical wall-clock benchmark tracked the exact runtime trade-off between full-dimensional Sinkhorn and the 1D Sliced Wasserstein shortcut across expanding data dimensions (<span class="math inline">\(d=32\)</span>):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Dataset Size (<span class="math inline">\(n\)</span>)</th>
<th>Sinkhorn Execution Runtime (ms)</th>
<th>SWD (<span class="math inline">\(L=100\)</span>) Execution Runtime (ms)</th>
<th>Empirical Performance Multiplier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><span class="math inline">\(n = 100\)</span></strong></td>
<td>24.41 ms</td>
<td>1.46 ms</td>
<td>SWD is <strong><span class="math inline">\(16.7\times\)</span> faster</strong></td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(n = 500\)</span></strong></td>
<td>319.83 ms</td>
<td>3.73 ms</td>
<td>SWD is <strong><span class="math inline">\(85.7\times\)</span> faster</strong></td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(n = 1,000\)</span></strong></td>
<td>1,206.98 ms</td>
<td>7.73 ms</td>
<td>SWD is <strong><span class="math inline">\(156.1\times\)</span> faster</strong></td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(n = 2,000\)</span></strong></td>
<td>6,700.89 ms</td>
<td>15.79 ms</td>
<td>SWD is <strong><span class="math inline">\(424.3\times\)</span> faster</strong></td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(n = 5,000\)</span></strong></td>
<td><strong>41,375.58 ms</strong></td>
<td><strong>43.33 ms</strong></td>
<td>SWD is <strong><span class="math inline">\(954.8\times\)</span> faster</strong></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Critical Architectural Discovery:</strong> This benchmark maps out a clear performance cliff. While Sinkhorn is excellent for small sample groups, its quadratic complexity <span class="math inline">\(O(n^2)\)</span> forces a massive overhead bottleneck as data scales upward. Taking over 41 seconds to complete a single evaluation at <span class="math inline">\(n=5,000\)</span> makes it unusable for high-throughput, large-batch deep learning training loops. Conversely, SWD scales linearly with sorting complexity <span class="math inline">\(O(n \log n)\)</span>, completing the same task in just 43.33 ms. This confirms that SWD is the only viable alternative for large-scale domain adaptation training.</li>
</ul>
<p><br></p>
<p><strong>D. The Regularization Sieve: Sparsity vs.&nbsp;Blur</strong></p>
<p>Our final sensitivity visualization isolated exactly how varying the entropic coefficient <span class="math inline">\(\varepsilon\)</span> rewrites the structural physics of the mapping matrix <span class="math inline">\(\pi\)</span>:</p>
<ul>
<li><p><strong>High-Precision Regime (<span class="math inline">\(\varepsilon = 0.01\)</span>):</strong> Produced a crisp, highly sparse, permutation-like matrix containing sharp dark blue trajectories against a clean white background. This represents true, deterministic optimal transport, mapping specific source coordinates to their single closest mathematical neighbors.</p></li>
<li><p><strong>Balanced Neighborhood Regime (<span class="math inline">\(\varepsilon = 0.1\)</span>):</strong> The sharp paths feathered out into smooth, localized bands. This represents the ideal operational sweet spot for deep learning, offering a smooth loss landscape while maintaining local geometric relationships.</p></li>
<li><p><strong>Entropy Saturation Regime (<span class="math inline">\(\varepsilon = 1.0\)</span>):</strong> The entire coupling matrix dissolved into an indistinct, pale blue smear. The algorithm completely ignored physical transport costs, distributing mass uniformly across all targets (<span class="math inline">\(1/n \times 1/m\)</span>). This renders the loss function completely useless for geometric alignment.</p></li>
</ul>
<hr>
</section>
</section>
<section id="stage-7---domain-adaptation-architecture" class="level3">
<h3 class="anchored" data-anchor-id="stage-7---domain-adaptation-architecture">Stage 7 - Domain Adaptation Architecture</h3>
<p>We align <span class="math inline">\(f_\theta\)</span>(MNIST) and <span class="math inline">\(f_\theta\)</span>(SVHN) in embedding space using SWD/Max-SWD/Sinkhorn as plug-in losses.</p>
<p><br></p>
</section>
<section id="question-7" class="level3">
<h3 class="anchored" data-anchor-id="question-7">Question [7]</h3>
<ol type="1">
<li><p>If you applied SWD directly to raw pixels, you’d be computing distances in <span class="math inline">\(\mathbb{R}^{3 \times 32 \times 32} = \mathbb{R}^{3072}\)</span>. Why does this fail — not just computationally, but geometrically? What property of pixel space makes Wasserstein-based alignment meaningless there?</p></li>
<li><p>What property must the encoder <span class="math inline">\(f_\theta\)</span> have for alignment in embedding space to actually transfer — i.e., for “<span class="math inline">\(f_\theta\)</span>(MNIST) <span class="math inline">\(\approx\)</span> <span class="math inline">\(f_\theta\)</span>(SVHN) in distribution” to imply the classifier h performs well on SVHN?</p></li>
</ol>
<p><br></p>
</section>
<section id="answers-7" class="level3">
<h3 class="anchored" data-anchor-id="answers-7">Answers [7]</h3>
<p><strong>1. The Geometric Failure of Wasserstein Alignment in Pixel Space</strong></p>
<p><strong>What does it mean?</strong></p>
<p>Applying Wasserstein metrics or Sliced Wasserstein Distance directly to raw pixel values fails because pixel space lacks semantic geometry. In pixel space, moving a digit by just a few pixels or changing its color creates a massive mathematical distance, even though the meaning of the image remains identical to a human observer.</p>
<p><br></p>
<p><strong>Why it fails geometrically?</strong></p>
<ul>
<li><p><strong>High-Dimensional Sparsity and Non-Overlapping Support:</strong> According to the Manifold Hypothesis, valid images of digits occupy a tiny, thin, lower-dimensional manifold embedded within the massive <span class="math inline">\(\mathbb{R}^{3072}\)</span> space. Because MNIST and SVHN have different styles (grayscale vs.&nbsp;RGB, clean vs.&nbsp;cluttered), their manifolds sit in completely different corners of pixel space. Their mathematical supports have <strong>zero overlap</strong>.</p></li>
<li><p><strong>Pixel Shifting and Orthogonality:</strong> The <span class="math inline">\(L_2\)</span> pixel distance does not understand structure. If you take an MNIST digit “1” and shift it 3 pixels to the right, the new image vector becomes nearly orthogonal (perpendicular) to the original image vector in <span class="math inline">\(\mathbb{R}^{3072}\)</span>. The distance between a shifted “1” and an unshifted “1” can be larger than the distance between a “1” and a “7” that happen to share overlapping ink strokes.</p></li>
<li><p><strong>Meaningless Interpolation:</strong> Optimal transport computes the path of least resistance to morph one distribution into another. In raw pixel space, the optimal path between a black-and-white MNIST “3” and a colorful SVHN “3” does not smoothly transform the shape. Instead, it simply fades out the MNIST pixels while fading in the SVHN background clutter. The transport plan aligns background noise and color channels rather than the underlying semantic concept of a “3”.</p></li>
</ul>
<p><br></p>
<p><strong>2. Required Properties for the Encoder <span class="math inline">\(f_\theta\)</span></strong></p>
<p><strong>What does it mean?</strong></p>
<p>If your encoder network <span class="math inline">\(f_\theta\)</span> maps both datasets into an embedding space and successfully forces their distributions to match (<span class="math inline">\(f_\theta(\text{MNIST}) \approx f_\theta(\text{SVHN})\)</span>), that alone does <strong>not</strong> guarantee a classifier will work on SVHN. For example, a trivial encoder that maps <em>every single image</em> to a constant vector <span class="math inline">\(\mathbf{0}\)</span> achieves perfect distribution alignment, but completely destroys all information.</p>
<p>To ensure that aligning the embeddings actually transfers classification performance, the encoder <span class="math inline">\(f_\theta\)</span> must satisfy two strict properties:</p>
<p><br></p>
<p><strong>A. Class-Conditional Continuity (Preservation of Label Topology)</strong></p>
<p>The encoder must map images with the same semantic label to the same cluster in the embedding space, regardless of which domain they came from. It must transform the data such that:</p>
<p><span class="math display">\[f_\theta(X \mid Y=k)_{\text{MNIST}} \approx f_\theta(X \mid Y=k)_{\text{SVHN}}\]</span></p>
<p>If the alignment loss only forces the <em>global</em> distributions to match without checking labels, it is prone to <strong>label flipping</strong>. The encoder could perfectly align the shape of an MNIST “3” with the shape of an SVHN “8”. The distributions will look identical to the SWD loss, but the downstream classifier <span class="math inline">\(h\)</span> will misclassify every SVHN “8” as a “3”.</p>
<p><br></p>
<p><strong>B. Injectivity on the Data Manifold (Information Preservation)</strong></p>
<p>The encoder must be a non-degenerative, ideally bijective or injective mapping on the support of the data distributions.</p>
<ul>
<li>It cannot collapse distinct semantic traits. If it collapses the features that separate a “3” from an “8” just to make the global distributions match, the classifier <span class="math inline">\(h\)</span> will lose its ability to discriminate between classes.</li>
<li>It must act as a <strong>shared feature extractor</strong> that isolates domain-invariant features (like edges, strokes, and topological loops) while discarding domain-specific features (like background clutter, color channels, and lighting illumination). By acting injectively on the semantic structure, it ensures that whatever features classifier <span class="math inline">\(h\)</span> used to solve MNIST are the exact same features available when viewing SVHN.</li>
</ul>
<p><br></p>
<p>Note: One sharpening on point 2A: the label-flipping failure mode we describe is real, but note that our setup has no target labels to enforce class-conditional alignment — we rely entirely on the encoder learning domain-invariant structure from source supervision plus global distribution matching. This is the fundamental limitation of unsupervised DA, and it’s why target accuracy won’t reach 100% regardless of alignment quality.</p>
<hr>
<section id="the-workflow-6" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow-6">1. The Workflow</h4>
<p>In Stage 7, we advanced from isolating optimal transport functions to assembling the structural deep learning pipeline required for <strong>Unsupervised Domain Adaptation (UDA)</strong>. We coded a modular, domain-agnostic convolutional neural network blueprint dividing our architecture into a feature <code>Encoder</code> and a linear <code>Classifier</code> head.</p>
<p>We then constructed unified data preprocessing pipelines to structurally harmonize our mismatched source dataset (MNIST) and target dataset (SVHN). Next, we configured parallelized, multi-threaded <code>DataLoader</code> loops equipped with strategic batch truncation controls to ensure shape compatibility for downstream matrix alignment. We built a centralized, plug-and-play <code>alignment_loss</code> master controller that wraps all our prior optimal transport metrics (‘swd’, ‘max_swd’, ‘sinkhorn’) into a single switchboard. Finally, we engineered a vital <strong>dimensional variance scaling adjustment</strong> (<span class="math inline">\(\sqrt{d}\)</span>) and validated the entire data-to-logit pipeline via an active structural dry run.</p>
<p><br></p>
</section>
<section id="the-objective-6" class="level4">
<h4 class="anchored" data-anchor-id="the-objective-6">2. The Objective</h4>
<p>The core objective of Stage 7 was to implement <strong>Structural and Dimensional Alignment</strong>. In Unsupervised Domain Adaptation, the classifier can only learn boundaries using labels from the source domain (MNIST). For this classifier to work on the target domain (SVHN), the encoder must map images from <em>both</em> domains into a shared feature space where their underlying distributions overlap.</p>
<p>Achieving this required solving three specific bottlenecks:</p>
<ol type="1">
<li><p><strong>Geometric Shape Mismatch:</strong> Standard MNIST (<span class="math inline">\(1 \times 28 \times 28\)</span>) cannot pass through the same neural layers as SVHN (<span class="math inline">\(3 \times 32 \times 32\)</span>).</p></li>
<li><p><strong>Computational Shape Mismatch:</strong> Incomplete trailing mini-batches would disrupt the equal-sample requirements (<span class="math inline">\(n\)</span>) of our optimal transport engines.</p></li>
<li><p><strong>Projection Variance Decay:</strong> Pushing high-dimensional vectors down to 1D heavily dampens their numerical variance, causing their gradient signals to be swallowed by the classification loss. Stage 7 resolved these challenges, creating a stable, structurally sound adaptation pipeline.</p></li>
</ol>
<p><br></p>
</section>
<section id="key-learnings-technical-insights-6" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-technical-insights-6">3. Key Learnings &amp; Technical Insights</h4>
<p><strong>A. Shared Latent Embedding Space Architecture</strong></p>
<p>Our UDA pipeline decouples feature extraction from class prediction:</p>
<ul>
<li><strong>The Feature Encoder (<span class="math inline">\(\psi_\theta\)</span>):</strong> Maps a raw image <span class="math inline">\(x \in \mathcal{X}\)</span> into a low-dimensional latent space: <span class="math inline">\(\psi_\theta(x) = z \in \mathbb{R}^d\)</span>, where <span class="math inline">\(d = 128\)</span>.</li>
<li><strong>The Digit Classifier (<span class="math inline">\(h_\phi\)</span>):</strong> Takes the embedding vector <span class="math inline">\(z\)</span> and maps it to class probability logits: <span class="math inline">\(h_\phi(z) = \hat{y} \in \mathbb{R}^{10}\)</span>.</li>
</ul>
<p>During optimization, the model minimizes standard cross-entropy classification loss on the labeled source data while simultaneously feeding <em>both</em> source and target embeddings through our optimal transport loss functions. This forces the encoder to strip away domain-specific cosmetic details (like SVHN background clutter or MNIST monochrome styling) while preserving the core geometric traits of the digits.</p>
<p><br></p>
<p><strong>B. Data Unification and Sample Consistency Mechanics</strong></p>
<p>We achieved structural data harmony using a multi-step transformation protocol:</p>
<ol type="1">
<li><p><strong>Spatial Resizing:</strong> MNIST pixels were upscaled: <span class="math inline">\(28 \times 28 \rightarrow 32 \times 32\)</span>.</p></li>
<li><p><strong>Channel Replication:</strong> Grayscale intensities were duplicated across three channels (<span class="math inline">\(1 \rightarrow 3\)</span>), creating a pseudo-RGB structure:</p></li>
</ol>
<p><span class="math display">\[\mathbf{X}_{\text{pseudo-RGB}} = \big[\mathbf{X}_{\text{gray}}, \mathbf{X}_{\text{gray}}, \mathbf{X}_{\text{gray}}\big]\]</span></p>
<ol start="3" type="1">
<li><p><strong>Statistical Normalization:</strong> Pixel tensors were shifted from <span class="math inline">\([0, 1]\)</span> to <span class="math inline">\([-1, 1]\)</span> via <span class="math inline">\(\frac{x - 0.5}{0.5}\)</span> to stabilize gradient backpropagation.</p></li>
<li><p><strong>Batch Truncation:</strong> Setting <code>drop_last=True</code> inside our parallelized dataloaders ensured every single training batch contained exactly <span class="math inline">\(n = 256\)</span> samples. This acts as a mathematical guarantee that our cost matrices (<span class="math inline">\(C \in \mathbb{R}^{n \times n}\)</span>) maintain perfect dimensional uniformity throughout the entire training epoch.</p></li>
</ol>
<p><br></p>
<p><strong>C. Mathematical Compensation for Projection Variance Decay</strong></p>
<p>When calculating Sliced Wasserstein losses (SWD and Max-SWD), <span class="math inline">\(d\)</span>-dimensional embedding vectors are projected down onto 1D lines via a dot product with a unit vector <span class="math inline">\(\theta \in \mathbb{S}^{d-1}\)</span>. According to high-dimensional probability theory, if the components of a <span class="math inline">\(d\)</span>-dimensional embedding vector <span class="math inline">\(z \in \mathbb{R}^d\)</span> have variance <span class="math inline">\(\sigma^2\)</span>, the variance of its 1D linear projection collapses:</p>
<p><span class="math display">\[\text{Var}(\theta^T z) \approx \frac{\sigma^2}{d}\]</span></p>
<p>For our 128-dimensional embedding space, this causes a severe <strong>variance decay</strong> of <span class="math inline">\(1/128\)</span>, leading to tiny transport loss values that are completely ignored by the network’s optimizer. To fix this, we introduced an explicit <strong>dimensional variance scaling adjustment</strong>:</p>
<p><span class="math display">\[\text{Scale} = \sqrt{d} = \sqrt{128} \approx 11.3137\]</span></p>
<p>Multiplying our 1D sorted projections by <span class="math inline">\(\sqrt{d}\)</span> inflates their compressed variance back to a stable scale, keeping our transport gradients strong and mathematically competitive with the classification loss during backpropagation.</p>
<p><br></p>
<p><strong>D. Structural Validation via Architectural Dry Runs</strong></p>
<p>We verified our end-to-end model pipeline using an active forward pass tracking a mock batch of random Gaussian tensors:</p>
<p><span class="math display">\[\mathbf{X}_{\text{dummy}} \in \mathbb{R}^{8 \times 3 \times 32 \times 32} \xrightarrow{\psi_\theta} \mathbf{Z} \in \mathbb{R}^{8 \times 128} \xrightarrow{h_\phi} \mathbf{\hat{Y}} \in \mathbb{R}^{8 \times 10}\]</span></p>
<p>The dry run confirmed that our model plumbing works perfectly:</p>
<ul>
<li>The convolutional encoder successfully compressed the 3,072 raw pixel values (<span class="math inline">\(3 \times 32 \times 32\)</span>) of each image into a tight 128-dimensional latent feature vector.</li>
<li>The linear classifier accurately mapped those 128 features to 10 distinct digit slots (0–9).</li>
<li>We isolated the final capacity of our model: <strong>355,968 parameters</strong> in the encoder and <strong>1,290 parameters</strong> in the classifier, giving us a lean, highly optimized profile of <strong>357,258 total parameters</strong>.</li>
</ul>
<p>Our data loaders are fully unified, our model architecture is structurally verified, and our modular optimal transport loss switchboard is primed with proper dimensional variance compensation.</p>
<hr>
</section>
</section>
<section id="stage-8---training-run" class="level3">
<h3 class="anchored" data-anchor-id="stage-8---training-run">Stage 8 - Training Run</h3>
<p>Now, we train three versions of the domain adaptation model — one with each alignment loss — using consistent hyperparameters (same encoder, same classifier, same λ, same optimizer). Evaluate target-domain classification accuracy on SVHN test set (no target labels used during training). Record:</p>
<ul>
<li>Final target accuracy for each method.</li>
<li>Wall-clock training time per epoch.</li>
<li>Alignment loss curve over training.</li>
</ul>
<p>Also we train a no-adaptation baseline (L_CE only, no alignment term) to establish the unadapted lower bound.</p>
<p><br></p>
<hr>
<p>Stage 8 marks the empirical destination of our journey. By designing an end-to-end training and evaluation pipeline, we transitioned from theoretical optimal transport metrics to an active benchmarking suite. This stage exposed the delicate optimization tradeoffs, gradient mechanics, and geometric constraints that dictate how well a deep neural network can bridge the domain gap between distinct image distributions without target-domain labels.</p>
<p><br></p>
<section id="the-workflow-7" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow-7">1. The Workflow</h4>
<p>The technical workflow of Stage 8 unified our data stream, model blocks, and transport geometries into a rigorous, reproducible experimental engine:</p>
<pre><code>[ MNIST Loader (Source) ] \                     --&gt; [ Cross-Entropy Task Loss ]
                           --&gt; [ Shared Encoder ]                              --&gt; [ Joint Optimization + Gradient Clipping ] --&gt; [ Target Evaluation ]
[ SVHN Loader (Target)  ] /                     --&gt; [ Modular Alignment Loss ]</code></pre>
<p><br></p>
<ol type="1">
<li><p><strong>Dual-Stream Mini-Batch Orchestration:</strong> We built a synchronized training loop that concurrently pulls mini-batches from the labeled source domain (<span class="math inline">\(\mathcal{D}_S = \text{MNIST}\)</span>) and the unlabeled target domain (<span class="math inline">\(\mathcal{D}_T = \text{SVHN}\)</span>). An exception-handling loop resets the shorter target data iterator cleanly when it runs out of samples, preventing training crashes due to uneven dataset sizes.</p></li>
<li><p><strong>Multi-Objective Loss Formulation:</strong> For every mini-batch, features are extracted via a shared convolutional backbone. We compute a supervised task loss on the source embeddings and route both source and target embeddings to a modular <code>alignment_loss</code> switchboard to compute the domain discrepancy.</p></li>
<li><p><strong>Stabilized Gradient Backpropagation:</strong> We introduced uniform gradient norm clipping over the combined parameter sets of the encoder and classifier to insulate the model from sudden optimal transport gradient surges.</p></li>
<li><p><strong>Controlled Benchmarking Environment:</strong> We implemented systematic random seeding across all primary libraries (<code>torch</code>, <code>numpy</code>, <code>cuda</code>, and the deterministic <code>cuDNN</code> backend) to isolate the performance impact of each transport geometry under identical initializations.</p></li>
<li><p><strong>Multi-Criteria Diagnostic Reporting:</strong> We engineered a comprehensive diagnostic sweep that assesses optimization health across six unique dimensions: cross-entropy trajectory, loss scaling balance ratios, accuracy trends, wall-clock performance, representation monotonicity, and global pass/fail criteria.</p></li>
</ol>
<p><br></p>
</section>
<section id="the-objective-7" class="level4">
<h4 class="anchored" data-anchor-id="the-objective-7">2. The Objective</h4>
<p>The core objective of Stage 8 was to <strong>Empirically Profile and Bench-Test Distribution Alignment Geometries</strong>.</p>
<p>In Unsupervised Domain Adaptation, the network must satisfy two competing constraints simultaneously:</p>
<ul>
<li><p><strong>Task Discriminability:</strong> The latent space must keep classes cleanly separated so the classifier can draw accurate decision boundaries.</p></li>
<li><p><strong>Domain Invariance:</strong> The latent space must compress and shift the source and target feature distributions until they overlap completely, making them indistinguishable to the classifier.</p></li>
</ul>
<p>If the alignment force is too weak, the encoder overfits to source-specific cosmetic features (like the clean, centered backgrounds of MNIST) and fails on the target domain. If the alignment force is too strong, it overrides the task boundaries, collapsing all embeddings into a single uninformative cluster to satisfy the distribution matching criterion. Stage 8 was designed to mathematically measure and evaluate how standard Sliced Wasserstein Distance (<code>SWD</code>), Adversarial Sliced Wasserstein (<code>MAX_SWD</code>), and Entropic Optimal Transport (<code>SINKHORN</code>) balance this tradeoff.</p>
<p><br></p>
</section>
<section id="key-mathematical-principles-mathematical-formulations" class="level4">
<h4 class="anchored" data-anchor-id="key-mathematical-principles-mathematical-formulations">3. Key Mathematical Principles &amp; Mathematical Formulations</h4>
<p><strong>A. The Joint Optimization Objective</strong></p>
<p>The total loss function minimized during each training iteration is formulated as a linear combination of the supervised classification task and the unsupervised domain regularizer:</p>
<p><span class="math display">\[\mathcal{L}_{\text{total}}(\theta, \phi) = \mathcal{L}_{\text{CE}}(\mathcal{D}_S; \theta, \phi) + \lambda \cdot \mathcal{L}_{\text{align}}(\mathcal{D}_S, \mathcal{D}_T; \theta)\]</span></p>
<p>Where <span class="math inline">\(\theta\)</span> represents the learnable parameters of the feature encoder <span class="math inline">\(\psi_\theta\)</span>, <span class="math inline">\(\phi\)</span> denotes the parameters of the linear classifier <span class="math inline">\(h_\phi\)</span>, and <span class="math inline">\(\lambda \geq 0\)</span> is the method-specific alignment hyperparameter.</p>
<p><br></p>
<p><strong>B. Classification Objective with Label Smoothing Regularization</strong></p>
<p>To prevent the model from generating overconfident logit outputs—which restricts embedding flexibility during domain alignment—we implemented Cross-Entropy Loss combined with a label smoothing factor <span class="math inline">\(\alpha = 0.1\)</span>.</p>
<p>For a true one-hot label vector <span class="math inline">\(y \in \mathbb{R}^K\)</span> (where <span class="math inline">\(K=10\)</span> classes), the smoothed target distribution <span class="math inline">\(\tilde{y}\)</span> is defined as:</p>
<p><span class="math display">\[\tilde{y}_k = (1 - \alpha) y_k + \frac{\alpha}{K}\]</span></p>
<p>The classification loss computed over a source mini-batch of size <span class="math inline">\(n\)</span> is then expressed as:</p>
<p><span class="math display">\[\mathcal{L}_{\text{CE}} = -\frac{1}{n}\sum_{i=1}^{n}\sum_{k=1}^{K} \tilde{y}_{i,k} \log \left( \frac{\exp(h_\phi(\psi_\theta(x_i))_k)}{\sum_{j=1}^{K}\exp(h_\phi(\psi_\theta(x_i))_j)} \right)\]</span></p>
<p><br></p>
<p><strong>C. The Empirical Metric Scale Balance Ratio</strong></p>
<p>To monitor the relative influence of the domain adaptation constraint over the network’s parameter space, we defined the Empirical Metric Scale Balance Ratio (<span class="math inline">\(\rho\)</span>):</p>
<p><span class="math display">\[\rho^{(t)} = \frac{\lambda \cdot \mathcal{L}_{\text{align}}^{(t)}}{\mathcal{L}_{\text{CE}}^{(t)} + \epsilon}\]</span></p>
<p>Where <span class="math inline">\(t\)</span> represents the current epoch and <span class="math inline">\(\epsilon = 10^{-8}\)</span> prevents division-by-zero errors. Tracking <span class="math inline">\(\rho^{(t)}\)</span> serves as a diagnostic guardrail. If <span class="math inline">\(\rho^{(t)} \rightarrow 0\)</span>, the alignment constraint is under-regularized and mostly ignored by the optimizer. If <span class="math inline">\(\rho^{(t)} &gt; 0.5\)</span>, the alignment constraint risks overpowering the classification task, which can destabilize training.</p>
<p><br></p>
<p><strong>D. Gradient Norm Constraint Mechanics</strong></p>
<p>To counteract explosive gradient updates triggered by sharp changes in optimal transport cost matrices, we applied uniform <span class="math inline">\(L_2\)</span> gradient norm clipping across the combined parameter set <span class="math inline">\(\mathbf{W} = \{\theta \cup \phi\}\)</span>:</p>
<p><span class="math display">\[\mathbf{g} = \nabla_{\mathbf{W}} \mathcal{L}_{\text{total}}\]</span></p>
<p><span class="math display">\[\mathbf{g} \leftarrow \mathbf{g} \cdot \min\left(1, \frac{g_{\text{max}}}{\|\mathbf{g}\|_2}\right)\]</span></p>
<p>Where <span class="math inline">\(g_{\text{max}} = 5.0\)</span>. This mapping rescales the gradient vector back to a fixed maximum ceiling whenever its total magnitude exceeds <span class="math inline">\(5.0\)</span>, ensuring stable parameter updates.</p>
<p><br></p>
</section>
<section id="technical-insights-deep-dive-analysis-of-the-findings" class="level4">
<h4 class="anchored" data-anchor-id="technical-insights-deep-dive-analysis-of-the-findings">4. Technical Insights &amp; Deep-Dive Analysis of the Findings</h4>
<p>The experimental results from our comprehensive benchmark exposed several critical insights regarding the behavior of optimal transport metrics in deep learning pipelines:</p>
<p><strong>The Supervised Overfitting Baseline (<code>NONE</code>)</strong></p>
<p>The baseline control model highlights the severity of the domain gap problem. Optimized solely via source cross-entropy (<span class="math inline">\(\lambda = 0.0\)</span>), the model quickly minimizes its training loss, but its target validation accuracy peaks at a meager <strong>23.27%</strong> by epoch 2 before steadily decaying down to <strong>11.59%</strong> (near random guess accuracy) by epoch 20.</p>
<p>This behavior illustrates the concept of representation drift. As the encoder becomes highly specialized at extracting features specific to MNIST (like high-contrast monochrome edges), it misinterprets or ignores the structural information in the colorful, cluttered target images (SVHN).</p>
<p><br></p>
<p><strong>Sliced Wasserstein Distance (<code>SWD</code>) &amp; The Under-Regularization Discovery</strong></p>
<p>Standard <code>SWD</code> successfully addresses this representation drift, achieving a peak target accuracy of <strong>24.60%</strong> and maintaining a stable terminal accuracy of <strong>21.08%</strong>. However, our empirical balance ratio diagnostic uncovered a fascinating structural trait: even with our <span class="math inline">\(\sqrt{d}\)</span> dimensional variance adjustment, the active ratio for SWD sat extremely low (<span class="math inline">\(\rho \approx 0.001\)</span>).</p>
<p>Because standard SWD projects features onto <em>random</em> 1D lines, many of these projection paths capture angles where the source and target distributions already look similar. This averages down the total loss value, meaning the model is under-regularized and requires a significantly larger hyperparameter multiplier (<span class="math inline">\(\lambda \gg 0.08\)</span>) to fully exert its alignment force on the encoder.</p>
<p><br></p>
<p><strong>Adversarial Sliced Wasserstein (<code>MAX_SWD</code>) as the Optimal Adaptor</strong></p>
<p><code>MAX_SWD</code> emerged as the top-performing configuration in our benchmark, reaching a peak target accuracy of <strong>28.19%</strong> and retaining a strong terminal accuracy of <strong>24.61%</strong>.</p>
<p>By replacing random projections with a fast 10-step adversarial gradient ascent loop, <code>MAX_SWD</code> isolates the specific projection axis that maximizes the distribution discrepancy. By continuously minimizing this <em>worst-case</em> domain gap, it applies a highly targeted alignment constraint. This forces the encoder to strip away domain-specific variations, building robust, domain-invariant features while maintaining an efficient runtime footprint (<strong>21.5s/epoch</strong>).</p>
<p><br></p>
<p><strong>Full-Dimensional Sinkhorn Entropic OT and Geometric Rigidity</strong></p>
<p>The full-dimensional log-stable <code>Sinkhorn</code> model demonstrated strong performance early on, hitting a peak target accuracy of <strong>27.07%</strong> by epoch 2. However, it incurred a notable computational overhead (<strong>26.5s/epoch</strong>, a 35% increase over the baseline) and suffered an 8.6% performance drop in late-stage training, ending at <strong>18.48%</strong>.</p>
<p>Our diagnostic logs show that Sinkhorn maintained a high, steady loss value (<span class="math inline">\(\lambda \cdot \mathcal{L}_{\text{align}} \approx 0.040\)</span>) alongside a healthy balance ratio (<span class="math inline">\(\rho \approx 0.06\)</span>). This reveals a conflict in its geometric constraints. Because Sinkhorn evaluates a dense, full-dimensional <span class="math inline">\(256 \times 256\)</span> cost matrix across all 128 embedding dimensions simultaneously without a projection bottleneck, it imposes a very rigid alignment constraint.</p>
<p>In late-stage training, the model reaches a floor where it can no longer satisfy global distribution matching without distorting its task-specific class boundaries. This forces a trade-off where the network sacrifices classification accuracy to satisfy the global optimal transport constraint, leading to the observed performance decay.</p>
<p><br></p>
<p><strong>Final Synthesis and Quantitative Comparison</strong></p>
<p>The automated diagnostic report validates our entire implementation framework against our core design requirements:</p>
<ul>
<li><p><strong>Task Validation:</strong> All three optimal transport alignment methods successfully beat the unaligned baseline control model.</p></li>
<li><p><strong>Optimization Safety:</strong> No premature cross-entropy collapse occurred across any of the configuration runs.</p></li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Adaptation Configuration</th>
<th>Computational Complexity (Avg Time/Ep)</th>
<th>Empirical Loss Ratio (<span class="math inline">\(\rho_{\text{avg}}\)</span>)</th>
<th>Optimization Stability Profile</th>
<th>Peak Target Accuracy</th>
<th>Terminal Target Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><code>NONE</code></strong> (Control)</td>
<td><strong>19.5 seconds</strong></td>
<td><span class="math inline">\(0.0000\)</span></td>
<td>Fails (Severe Overfitting)</td>
<td>23.27%</td>
<td>11.59%</td>
</tr>
<tr class="even">
<td><strong><code>SWD</code></strong> (Random Projections)</td>
<td>20.1 seconds</td>
<td><span class="math inline">\(0.0008\)</span> (Under-regularized)</td>
<td>Stable (Smooth updates)</td>
<td>24.60%</td>
<td>21.08%</td>
</tr>
<tr class="odd">
<td><strong><code>MAX_SWD</code></strong> (Adversarial Projections)</td>
<td>21.5 seconds</td>
<td><span class="math inline">\(0.0017\)</span> (Highly Targeted)</td>
<td><strong>Excellent</strong> (Best Generalization)</td>
<td><strong>28.19%</strong></td>
<td><strong>24.61%</strong></td>
</tr>
<tr class="even">
<td><strong><code>SINKHORN</code></strong> (Global Full-Dim OT)</td>
<td>26.5 seconds</td>
<td><strong><span class="math inline">\(0.0598\)</span></strong> (Healthy Balance)</td>
<td>Rigid (Late-stage performance decay)</td>
<td>27.07%</td>
<td>18.48%</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Through Stage 8, we have successfully demonstrated that regularized optimal transport allows deep neural networks to adapt to entirely unlabeled target domains. Projection-based approaches—specifically adversarial <strong>Max-SWD</strong>—offer the best balance of classification performance, computational efficiency, and training stability, making them the optimal architectural choice for our domain adaptation pipeline.</p>
<hr>
</section>
</section>
<section id="stage-9---projection-ablation" class="level3">
<h3 class="anchored" data-anchor-id="stage-9---projection-ablation">Stage 9 - Projection Ablation</h3>
<p>We run an ablation over number of projection directions <span class="math inline">\(L\)</span> <span class="math inline">\(\in\)</span> {10, 50, 100, 500, 1000} for SWD. For each <span class="math inline">\(L\)</span>, we record: estimated SWD value, variance across 10 runs, and wall-clock time. Then, plot SWD estimate <span class="math inline">\(\pm\)</span> std vs.&nbsp;<span class="math inline">\(L\)</span>. Finally, identify empirically the minimum <span class="math inline">\(L\)</span> at which SWD converges (variance drops below <span class="math inline">\(1%\)</span> of the mean estimate).</p>
<p><br></p>
</section>
<section id="question-9" class="level3">
<h3 class="anchored" data-anchor-id="question-9">Question [9]</h3>
<p>As embedding dimension d increases, does SWD converge faster or slower with respect to <span class="math inline">\(L\)</span>, and why? Your answer should reference the geometry of random projections on <span class="math inline">\(S^{d-1}\)</span>.</p>
<p><br></p>
</section>
<section id="answers-9" class="level3">
<h3 class="anchored" data-anchor-id="answers-9">Answers [9]</h3>
<p><strong>1. Dimension and the Convergence Rate of SWD</strong></p>
<p><strong>What does it mean?</strong></p>
<p>As the embedding dimension <span class="math inline">\(d\)</span> increases, the finite-<span class="math inline">\(L\)</span> estimator of the Sliced Wasserstein Distance converges <strong>significantly slower</strong> with respect to the number of random projections <span class="math inline">\(L\)</span>.</p>
<p>To maintain the same level of accuracy or approximation error as your dimensions grow, you must scale the number of projections <span class="math inline">\(L\)</span> exponentially. If you keep <span class="math inline">\(L\)</span> fixed while increasing <span class="math inline">\(d\)</span>, your SWD estimates will suffer from massively increased variance and statistical noise.</p>
<p><br></p>
<p><strong>The Geometry of Random Projections on <span class="math inline">\(S^{d-1}\)</span> (&amp; Why does it slow down?)</strong></p>
<p>The root cause of this slowdown lies in the geometric structure of the unit sphere <span class="math inline">\(S^{d-1}\)</span> in high-dimensional spaces, driven by <strong>measure concentration</strong>:</p>
<ul>
<li><p><strong>Orthogonality of Random Vectors:</strong> In a 2D or 3D space, two random vectors chosen on a sphere can point in widely different directions. However, as the dimension <span class="math inline">\(d \to \infty\)</span>, any two randomly sampled vectors <span class="math inline">\(\theta_i\)</span> and <span class="math inline">\(\theta_j\)</span> on <span class="math inline">\(S^{d-1}\)</span> become <strong>almost perfectly orthogonal (perpendicular) to each other</strong> with near certainty.</p></li>
<li><p><strong>Equatorial Concentration:</strong> If you pick any fixed vector on a high-dimensional sphere to act as a “North Pole,” almost the entire surface area of the sphere concentrates within a incredibly thin band around the “equator.” This means that every time you sample a random projection direction <span class="math inline">\(\theta_l\)</span>, it is almost guaranteed to be nearly perpendicular to your target directional axis.</p></li>
<li><p><strong>Information Loss per Projection:</strong> Because random lines on a high-dimensional sphere populate vastly different, non-overlapping orthogonal directions, a single 1D projection captures only a minuscule fraction (<span class="math inline">\(\approx 1/d\)</span>) of the total structural variance of the high-dimensional space.</p></li>
</ul>
<p><br></p>
<p>Consequently, as <span class="math inline">\(d\)</span> increases, the probability that a small pool of <span class="math inline">\(L\)</span> random slices will successfully “see” and capture the true underlying geometric discrepancies between <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span> plummets. The space of angles becomes vastly larger, requiring an exponentially larger number of projections <span class="math inline">\(L\)</span> to evenly sample the sphere and drive the Monte Carlo estimation error down.</p>
<hr>
<p>While Stage 8 established the final baseline performance of our Unsupervised Domain Adaptation (UDA) pipeline, Stage 9 shifts our focus to algorithm optimization and empirical analysis. By designing an isolated statistical testing harness, we analyzed the structural trade-offs of Monte Carlo approximations in Sliced Wasserstein Distance (<span class="math inline">\(SWD\)</span>) formulations.</p>
<p>This stage provided the empirical data needed to answer a fundamental machine learning system design question: <strong>How do we balance statistical precision against hardware execution constraints when optimizing deep architectures?</strong></p>
<p><br></p>
<section id="the-workflow-8" class="level4">
<h4 class="anchored" data-anchor-id="the-workflow-8">1. The Workflow</h4>
<p>The technical workflow of Stage 9 isolated our optimal transport metric inside a multi-variable simulation loop to trace its behavior across different parameter settings:</p>
<pre><code>[ Input Distribution X ] \                                   --&gt; Compute Estimator Variance (σ)
                          --&gt; [ Sweep Projections: L ] ---&gt; --&gt; Compute Scale Coefficient (CV)
[ Input Distribution Y ] /                                   --&gt; Track Wall-Clock Performance (ms)</code></pre>
<p><br></p>
<ol type="1">
<li><p><strong>Synthetic Environment Distribution Design:</strong> We created matching synthetic multivariate data matrices (<span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>). To isolate the variance introduced by our random projection sampling, we applied a constant directional shift (<span class="math inline">\(+0.5\)</span>), ensuring that changes in the calculated distance were driven entirely by the estimator itself rather than underlying data variations.</p></li>
<li><p><strong>Multi-Variable Parametric Sweeps:</strong> We built a dual-loop testing suite that evaluated performance across an exponential range of projection slices (<span class="math inline">\(L \in [10, 5000]\)</span>) across different feature dimensions (<span class="math inline">\(d \in \{8, 32, 128\}\)</span>).</p></li>
<li><p><strong>Multi-Trial Variance Sampling:</strong> For every combination of <span class="math inline">\(L\)</span> and <span class="math inline">\(d\)</span>, the system ran <span class="math inline">\(20\)</span> independent trials. By varying the random seed for each trial, we forced the algorithm to draw completely unique projection angles, giving us the statistical distribution data needed to analyze estimator noise.</p></li>
<li><p><strong>Normalized Volatility Profiling:</strong> We tracked the mean and standard deviation of our estimates to calculate the Coefficient of Variation (<span class="math inline">\(\text{CV} = \sigma / \mu\)</span>). This allowed us to measure and compare estimation noise cleanly across different data configurations.</p></li>
<li><p><strong>Real-Time Hardware Profiling:</strong> We wrapped our SWD metric inside real-time wall-clock loops using high-resolution performance counters (<code>time.perf_counter</code>) to measure the precise computational cost in milliseconds (ms) of increasing projection counts (<span class="math inline">\(L\)</span>).</p></li>
<li><p><strong>Multi-Panel Diagnostic Dashboard Visualizations:</strong> We compiled our tabular metrics into a unified side-by-side dashboard, plotting normalized variance and classification accuracies together to visually confirm our hyperparameter choices.</p></li>
</ol>
<p><br></p>
</section>
<section id="the-objective-8" class="level4">
<h4 class="anchored" data-anchor-id="the-objective-8">2. The Objective</h4>
<p>The primary objective of Stage 9 was to <strong>Empirically Profile the Trade-offs of Monte Carlo Estimators in Projection-Based Optimal Transport</strong>.</p>
<p>The standard Sliced Wasserstein Distance scales efficiently because it bypasses full-dimensional transport optimization by averaging multiple 1D projections. However, this relies on a Monte Carlo approximation:</p>
<p><span class="math display">\[\text{SWD}^2(P_X, P_Y) \approx \frac{1}{L}\sum_{l=1}^{L} \mathcal{W}_2^2(\theta_l \sharp P_X, \theta_l \sharp P_Y)\]</span></p>
<p>This sampling approach introduces a critical engineering trade-off:</p>
<ul>
<li><p><strong>The Variance Risk:</strong> If <span class="math inline">\(L\)</span> is set too small, the calculated loss varies wildly depending on the luck of the random projection angles drawn for that batch. This introduces high stochastic noise into our training gradients, which can destabilize optimization.</p></li>
<li><p><strong>The Computational Penalty:</strong> If <span class="math inline">\(L\)</span> is set too large, the execution time scales up linearly, turning an efficient metric into a severe processing bottleneck that slows down training.</p></li>
</ul>
<p>Stage 9 used rigorous empirical benchmarking to find the exact <strong>Pareto-optimal sweet spot</strong>—the minimum number of projections required to secure stable gradients (<span class="math inline">\(\text{CV} &lt; 5\%\)</span>) without overloading our hardware pipeline.</p>
<p><br></p>
</section>
<section id="key-mathematical-principles-formulations" class="level4">
<h4 class="anchored" data-anchor-id="key-mathematical-principles-formulations">3. Key Mathematical Principles &amp; Formulations</h4>
<p><strong>A. Continuous vs.&nbsp;Discretized Sliced Wasserstein Spaces</strong></p>
<p>The true Sliced Wasserstein Distance of order 2 between two continuous probability measures <span class="math inline">\(P_X\)</span> and <span class="math inline">\(P_Y\)</span> integrated over the uniform unit sphere <span class="math inline">\(\mathbb{S}^{d-1}\)</span> is defined as:</p>
<p><span class="math display">\[\mathcal{W}_2^2(P_X, P_Y) = \int_{\mathbb{S}^{d-1}} \mathcal{W}_2^2(\theta \sharp P_X, \theta \sharp P_Y) \, d\sigma(\theta)\]</span></p>
<p>Where <span class="math inline">\(\theta \sharp P\)</span> denotes the 1D push-forward projection distribution along the unit direction vector <span class="math inline">\(\theta\)</span>. In practice, computing this continuous integral exactly across high-dimensional feature spaces is impossible. We approximate it by sampling a finite set of <span class="math inline">\(L\)</span> random projection vectors uniformly from <span class="math inline">\(\mathbb{S}^{d-1}\)</span>:</p>
<p><span class="math display">\[\widehat{\mathcal{W}}_2^2(P_X, P_Y; L) = \frac{1}{L}\sum_{l=1}^{L} \mathcal{W}_2^2\left(\{\langle x_i, \theta_l \rangle\}_{i=1}^n, \{\langle y_j, \theta_l \rangle\}_{j=1}^n\right)\]</span></p>
<p><br></p>
<p><strong>B. The Central Limit Theorem and Estimator Error Variance</strong></p>
<p>Because our discrete calculation <span class="math inline">\(\widehat{\mathcal{W}}_2^2\)</span> is an unbiased estimator of the true continuous distance, its statistical error variance drops predictably as the sample size <span class="math inline">\(L\)</span> increases. According to the Central Limit Theorem (CLT), the standard error of our estimator scales at the following rate:</p>
<p><span class="math display">\[\sigma_{\text{estimator}}(L) = \sqrt{\text{Var}\left(\widehat{\mathcal{W}}_2^2\right)} \propto \frac{1}{\sqrt{L}}\]</span></p>
<p>This power-law decay means that to cut our estimation error in half, we must quadruple the number of random projections.</p>
<p><br></p>
<p><strong>C. The Coefficient of Variation (<span class="math inline">\(\text{CV}\)</span>)</strong></p>
<p>To measure estimation stability independently of the underlying data scale, we tracked the Coefficient of Variation (<span class="math inline">\(\text{CV}\)</span>), defined as the ratio of the standard deviation to the expected mean:</p>
<p><span class="math display">\[\text{CV}_d(L) = \frac{\sigma_d(L)}{\mu_d(L)} = \frac{\sqrt{\frac{1}{T-1}\sum_{t=1}^{T}\left(W_t - \bar{W}\right)^2}}{\frac{1}{T}\sum_{t=1}^{T}W_t}\]</span></p>
<p>Where <span class="math inline">\(T = 20\)</span> represents the total number of independent trial runs executed per parameter setting.</p>
<p><br></p>
<p><strong>D. Algorithmic Complexity Mapping</strong></p>
<p>The complete computational profile of our Sliced Wasserstein calculation is governed by three primary parameters: batch sample size <span class="math inline">\(n\)</span>, feature dimensionality <span class="math inline">\(d\)</span>, and projection count <span class="math inline">\(L\)</span>. The absolute time complexity scales as:</p>
<p><span class="math display">\[\mathcal{O}\Big(\underbrace{L \cdot d \cdot n}_{\text{Matrix Projection Overhead}} + \underbrace{L \cdot n \log n}_{\text{1D Sorting Operations}}\Big)\]</span></p>
<p>Since sorting and projection operations are highly parallelizable on modern hardware, execution time scales linearly with the number of projections: <span class="math inline">\(\text{Time}(L) \propto L\)</span>.</p>
<p><br></p>
</section>
<section id="technical-insights-deep-dive-analysis-of-the-findings-1" class="level4">
<h4 class="anchored" data-anchor-id="technical-insights-deep-dive-analysis-of-the-findings-1">4. Technical Insights &amp; Deep-Dive Analysis of the Findings</h4>
<p>Our comprehensive empirical sweeps exposed several critical insights regarding the scaling behavior of projection-based optimal transport metrics:</p>
<p><br></p>
<p><strong>Quantifying the <span class="math inline">\(O(1/\sqrt{L})\)</span> Error Decay</strong></p>
<p>Our ablation data provides clear empirical validation for standard Monte Carlo error decay theory. As the number of projections (<span class="math inline">\(L\)</span>) increases, our estimator’s variance drops in a smooth, predictable curve across all tested dimensions.</p>
<p>For example, looking at our target 128-dimensional embedding space:</p>
<ul>
<li><p>At <strong><span class="math inline">\(L=10\)</span></strong>, the estimate is highly volatile (<span class="math inline">\(\text{CV} = 0.3833\)</span>). The distance calculations fluctuate by up to <span class="math inline">\(\pm 38\%\)</span> between runs, which would introduce severe gradient noise into an active training loop.</p></li>
<li><p>At <strong><span class="math inline">\(L=500\)</span></strong>, the variation drops significantly (<span class="math inline">\(\text{CV} = 0.0522\)</span>), narrowing the estimation error down to approximately <span class="math inline">\(\pm 5.2\%\)</span>.</p></li>
<li><p>At <strong><span class="math inline">\(L=5000\)</span></strong>, the variation minimizes further (<span class="math inline">\(\text{CV} = 0.0156\)</span>), tightening our error window to a razor-thin <span class="math inline">\(\pm 1.5\%\)</span>.</p></li>
</ul>
<p><br></p>
<p><strong>The Dimensional Curse of Geometric Dispersion</strong></p>
<p>Comparing results across our dimensional channels (<span class="math inline">\(d=8\)</span> vs.&nbsp;<span class="math inline">\(d=32\)</span> vs.&nbsp;<span class="math inline">\(d=128\)</span>) reveals a key structural challenge: as the dimensionality of our feature space expands, low-resolution projection sets suffer from significantly higher estimation noise.</p>
<pre><code>At L = 10:
  - d = 8:   CV = 0.2730
  - d = 32:  CV = 0.4180
  - d = 128: CV = 0.3833</code></pre>
<p>This trend reflects the geometric properties of high-dimensional unit spheres. As the embedding dimension <span class="math inline">\(d\)</span> scales up, the total volume concentrates heavily along the outer shell, and the number of truly orthogonal axes expands. Consequently, a small pool of random 1D projections leaves large portions of the embedding space unmapped, increasing estimation variance. To maintain stable, reliable loss values across higher-dimensional latent spaces, we must scale up our projection sampling capacity (<span class="math inline">\(L\)</span>).</p>
<p><br></p>
<p><strong>Defining Practical Engineering Convergence</strong></p>
<p>Our ablation study revealed a valuable lesson for system optimization: <strong>demanding absolute mathematical convergence (<span class="math inline">\(\text{CV} &lt; 1\%\)</span>) is computationally impractical</strong>. Even at our highest resolution (<span class="math inline">\(L=5000\)</span>), not a single configuration crossed below the strict <span class="math inline">\(1\%\)</span> convergence line.</p>
<p>Fortunately, deep neural networks don’t actually need flawless precision to optimize effectively. Stochastic Gradient Descent (SGD) and Adam are inherently designed to handle a degree of optimization noise due to mini-batch sampling. By relaxing our requirement to a practical engineering safety threshold (<span class="math inline">\(\text{CV} &lt; 5\%\)</span>), we can secure highly stable gradients while dramatically reducing computational overhead.</p>
<p><br></p>
<p><strong>The Pareto-Optimal Sweet Spot (<span class="math inline">\(L=1000\)</span>)</strong></p>
<p>By mapping our statistical variance metrics directly alongside real-world execution times, we can clearly identify the hardware-performance sweet spot:</p>
<pre><code>     L   mean SWD      std       cv   time(ms)   converged(cv&lt;5%)
--------------------------------------------------------------------
   500     0.2505   0.0131   0.0522      17.42                 no
  1000     0.2520   0.0099   0.0395      35.70                YES
  5000     0.2564   0.0040   0.0156     213.42                YES</code></pre>
<p><br></p>
<ul>
<li><p><strong>Below the Sweet Spot (<span class="math inline">\(L \le 500\)</span>):</strong> While very fast (<span class="math inline">\(\le 17.42 \text{ ms}\)</span>), these settings fail to satisfy our safety threshold (<span class="math inline">\(\text{CV} = 5.22\% &gt; 5\%\)</span>), introducing unwanted volatility into our alignment gradients.</p></li>
<li><p><strong>Above the Sweet Spot (<span class="math inline">\(L = 5000\)</span>):</strong> Pushing the number of projections to 5000 maximizes precision (<span class="math inline">\(\text{CV} = 1.56\%\)</span>), but execution time skyrockets to <strong><span class="math inline">\(213.42 \text{ ms}\)</span></strong> per call. This represents a massive <strong><span class="math inline">\(6\times\)</span> increase in processing cost</strong> for a minor gain in variance reduction, which would severely bottleneck a live training pipeline.</p></li>
<li><p><strong>The Sweet Spot (<span class="math inline">\(L = 1000\)</span>):</strong> This configuration marks our precise <strong>Pareto-optimal milestone</strong>. It satisfies our safety requirement with room to spare (<span class="math inline">\(\text{CV} = 3.95\%\)</span>) while requiring only <strong><span class="math inline">\(35.70 \text{ ms}\)</span></strong> of processing time per batch. This provides a highly stable gradient signal while keeping the computational footprint minimal.</p></li>
</ul>
<p><br></p>
</section>
<section id="summary-of-system-optimization-metrics" class="level4">
<h4 class="anchored" data-anchor-id="summary-of-system-optimization-metrics">5. Summary of System Optimization Metrics</h4>
<p>The complete multi-variable benchmark profile of Stage 9 is aggregated below:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Space Dimension (<span class="math inline">\(d\)</span>)</th>
<th>Projection Slices (<span class="math inline">\(L\)</span>)</th>
<th>Standard Deviation (<span class="math inline">\(\sigma\)</span>)</th>
<th>Coefficient of Variation (<span class="math inline">\(\text{CV}\)</span>)</th>
<th>Execution Speed (ms)</th>
<th>Operational Convergence Status (<span class="math inline">\(\text{CV} &lt; 5\%\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(d=128\)</span></td>
<td><span class="math inline">\(L=10\)</span></td>
<td><span class="math inline">\(0.0944\)</span></td>
<td><span class="math inline">\(38.33\%\)</span></td>
<td><strong>1.13 ms</strong></td>
<td>Fails (Excessive Gradient Noise)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(d=128\)</span></td>
<td><span class="math inline">\(L=50\)</span></td>
<td><span class="math inline">\(0.0367\)</span></td>
<td><span class="math inline">\(13.71\%\)</span></td>
<td>3.48 ms</td>
<td>Fails (High Gradient Noise)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(d=128\)</span></td>
<td><span class="math inline">\(L=100\)</span></td>
<td><span class="math inline">\(0.0286\)</span></td>
<td><span class="math inline">\(11.24\%\)</span></td>
<td>3.83 ms</td>
<td>Fails (Unstable Gradient Floor)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(d=128\)</span></td>
<td><span class="math inline">\(L=500\)</span></td>
<td><span class="math inline">\(0.0131\)</span></td>
<td><span class="math inline">\(5.22\%\)</span></td>
<td>17.42 ms</td>
<td>Fails (Marginal Volatility)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathbf{d=128}\)</span></td>
<td><span class="math inline">\(\mathbf{L=1000}\)</span></td>
<td><span class="math inline">\(\mathbf{0.0099}\)</span></td>
<td><span class="math inline">\(\mathbf{3.95\%}\)</span></td>
<td><strong>35.70 ms</strong></td>
<td><strong>PASSED (Pareto Optimal Target)</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(d=128\)</span></td>
<td><span class="math inline">\(L=2000\)</span></td>
<td><span class="math inline">\(0.0090\)</span></td>
<td><span class="math inline">\(3.55\%\)</span></td>
<td>76.64 ms</td>
<td>PASSED (Diminishing Precision Returns)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(d=128\)</span></td>
<td><span class="math inline">\(L=5000\)</span></td>
<td><span class="math inline">\(0.0040\)</span></td>
<td><span class="math inline">\(1.56\%\)</span></td>
<td>213.42 ms</td>
<td>PASSED (Severe Hardware Bottleneck)</td>
</tr>
</tbody>
</table>
<p><br></p>
</section>
<section id="core-discoveries-technical-takeaways" class="level4">
<h4 class="anchored" data-anchor-id="core-discoveries-technical-takeaways">6. Core Discoveries &amp; Technical Takeaways</h4>
<p>Stage 9 has successfully provided the empirical foundation for our domain adaptation pipeline:</p>
<ol type="1">
<li><p><strong>Unbiased Estimator Stability:</strong> We visually and mathematically proved that our Sliced Wasserstein Distance framework behaves as an unbiased estimator. While small projection sets introduce noise, the calculated distances remain correctly centered around the true continuous expected transport value.</p></li>
<li><p><strong>Empirical Optimization Profiling:</strong> We successfully isolated the relationships between embedding dimensionality, projection sampling, and execution speed. This mapping allows us to avoid arbitrary hyperparameter selection in favor of rigorous, data-driven system design.</p></li>
<li><p><strong>Confirmed Hyperparameter Defaults:</strong> The data explicitly confirms that <strong><span class="math inline">\(L=1000\)</span> serves as the optimal hyperparameter choice</strong> for our 128-dimensional embedding space. It provides a highly stable gradient signal (<span class="math inline">\(\text{CV} = 3.95\%\)</span>) while keeping computational costs low enough to ensure fast training speeds.</p></li>
</ol>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shreeshb51\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Shreesh Bhattarai · GDL &amp; COT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/shreeshb51">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/shreesh-bhattarai-1ba1681bb/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>