<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-06-10">

<title>Score-Based Generative Model on a Real Dataset with OT-Guided Sampling – Shreesh Bhattarai</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f476d09796a223f24f1d84e1ae9c0b0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shreesh Bhattarai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Score-Based Generative Model on a Real Dataset with OT-Guided Sampling</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../catw/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Along the Way</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../papers/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper Comprehensions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notes</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#score-based-generative-modeling-on-cifar-10-ddpm-vs-rectified-flow" id="toc-score-based-generative-modeling-on-cifar-10-ddpm-vs-rectified-flow" class="nav-link active" data-scroll-target="#score-based-generative-modeling-on-cifar-10-ddpm-vs-rectified-flow">Score-Based Generative Modeling on CIFAR-10: DDPM vs Rectified Flow</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#intuitive-explanation" id="toc-intuitive-explanation" class="nav-link" data-scroll-target="#intuitive-explanation">Intuitive Explanation</a></li>
  <li><a href="#mathematical-foundations" id="toc-mathematical-foundations" class="nav-link" data-scroll-target="#mathematical-foundations">Mathematical Foundations</a></li>
  <li><a href="#ddpm-architecture-and-training" id="toc-ddpm-architecture-and-training" class="nav-link" data-scroll-target="#ddpm-architecture-and-training">DDPM — Architecture and Training</a></li>
  <li><a href="#ddpm-as-a-wasserstein-gradient-flow" id="toc-ddpm-as-a-wasserstein-gradient-flow" class="nav-link" data-scroll-target="#ddpm-as-a-wasserstein-gradient-flow">DDPM as a Wasserstein Gradient Flow</a></li>
  <li><a href="#rectified-flow-and-the-push-forward-view" id="toc-rectified-flow-and-the-push-forward-view" class="nav-link" data-scroll-target="#rectified-flow-and-the-push-forward-view">Rectified Flow and the Push-Forward View</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#key-insights" id="toc-key-insights" class="nav-link" data-scroll-target="#key-insights">Key Insights</a></li>
  <li><a href="#implementation-notes" id="toc-implementation-notes" class="nav-link" data-scroll-target="#implementation-notes">Implementation Notes</a></li>
  <li><a href="#dependencies" id="toc-dependencies" class="nav-link" data-scroll-target="#dependencies">Dependencies</a></li>
  <li><a href="#note" id="toc-note" class="nav-link" data-scroll-target="#note">Note</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Score-Based Generative Model on a Real Dataset with OT-Guided Sampling</h1>
  <div class="quarto-categories">
    <div class="quarto-category">GDL + COT</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="score-based-generative-modeling-on-cifar-10-ddpm-vs-rectified-flow" class="level1">
<h1>Score-Based Generative Modeling on CIFAR-10: DDPM vs Rectified Flow</h1>
<p><img src="https://img.shields.io/badge/PyTorch-2.3.1-ee4c2c?logo=pytorch" class="img-fluid" alt="PyTorch"> <img src="https://img.shields.io/badge/CUDA-12.1-76b900?logo=nvidia" class="img-fluid" alt="CUDA"> <img src="https://img.shields.io/badge/Dataset-CIFAR--10-blue.png" class="img-fluid" alt="Dataset"> <img src="https://img.shields.io/badge/RF%20FID%40NFE10-47.39-success" class="img-fluid" alt="FID"> <img src="https://img.shields.io/badge/Parameters-5.05M-lightgrey" class="img-fluid" alt="Params"></p>
<hr>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This project implements two generative models from scratch on CIFAR-10: a Denoising Diffusion Probabilistic Model (DDPM) and a Rectified Flow model. Both are trained on the same U-Net architecture and benchmarked at equal NFE budgets using FID score. The project establishes the mathematical connection between DDPM denoising steps and the JKO proximal scheme in Wasserstein space, and demonstrates empirically that OT-guided straight trajectories (Rectified Flow) achieve significantly lower FID at low NFE than standard Gaussian diffusion.</p>
<p><strong>Core implementations covered:</strong></p>
<ul>
<li>DDPM forward process with linear <span class="math inline">\(\beta\)</span> schedule and closed-form <span class="math inline">\(q(x_t \mid x_0)\)</span> sampling</li>
<li>Denoising score matching loss with noise prediction parameterization</li>
<li>Time-conditioned U-Net with sinusoidal embeddings, GroupNorm, and skip connections</li>
<li>DDPM full and strided reverse samplers</li>
<li>Rectified Flow training objective with straight-line interpolation and Euler ODE sampler</li>
<li>NFE vs FID benchmark across budgets <span class="math inline">\(\{10, 20, 50, 100, 200\}\)</span></li>
<li>JKO / Wasserstein gradient flow framing as explicit notebook markdown</li>
<li>Push-forward unification of both models under <span class="math inline">\(T_\sharp \mu = \nu\)</span></li>
</ul>
<hr>
</section>
<section id="intuitive-explanation" class="level2">
<h2 class="anchored" data-anchor-id="intuitive-explanation">Intuitive Explanation</h2>
<p><strong>1. What is a Score Function?</strong></p>
<p>Imagine you are lost in a hilly landscape in complete fog. You cannot see the peaks, but you can feel the ground slope beneath your feet. The score function is exactly this slope — at any point in space, it tells you which direction leads uphill toward higher probability (more likely images). Formally, the score is <span class="math inline">\(\nabla_x \log p(x)\)</span>: the gradient of the log-probability density at a point <span class="math inline">\(x\)</span>. A generative model that learns this gradient field can start from anywhere (pure noise) and hillclimb toward regions of high data probability, producing realistic images.</p>
<hr>
<p><strong>2. What is the Forward Diffusion Process?</strong></p>
<p>Think of dropping a photograph into a bucket of water. At first the image is clear; gradually ink diffuses outward until the water is uniformly grey. The forward diffusion process does exactly this mathematically — it adds small amounts of Gaussian noise at each of <span class="math inline">\(T=1000\)</span> steps until the image is indistinguishable from pure random noise. Crucially, this process has a closed form: you can jump directly from a clean image <span class="math inline">\(x_0\)</span> to a noisy image <span class="math inline">\(x_t\)</span> at any timestep without simulating every intermediate step. This is what makes training tractable.</p>
<hr>
<p><strong>3. DDPM as a Wasserstein Gradient Flow (the JKO Connection)</strong></p>
<p>Standard intuition says the denoising network is just curve-fitting — learning to subtract noise from pixels. The JKO lens reveals something deeper. Each denoising step is a proximal minimization step in the space of probability distributions, moving the current distribution one step closer to the data distribution <span class="math inline">\(p_\text{data}\)</span> while not straying too far from the previous distribution. The distance used is the Wasserstein-2 distance — the same Earth Mover’s Distance that measures the minimum transport cost between two distributions. Training is therefore not pixel-space regression; it is gradient descent on the Wasserstein manifold.</p>
<hr>
<p><strong>4. Why is Rectified Flow FASTER?</strong></p>
<p>In DDPM, the path from noise to image curves significantly through high-dimensional space — like a river winding through a valley. A numerical solver must take small steps to stay on the curve, requiring hundreds to thousands of NFEs. Rectified Flow instead draws a straight line between each noise vector and its paired data point, training the network to move along this line at constant velocity. A straight path needs far fewer steps to traverse accurately — the same reason you need fewer compass checks walking in a straight line than navigating a winding road. This geometric simplification is the core reason Rectified Flow achieves competitive image quality at NFE=10 where DDPM completely collapses.</p>
<hr>
</section>
<section id="mathematical-foundations" class="level2">
<h2 class="anchored" data-anchor-id="mathematical-foundations">Mathematical Foundations</h2>
<section id="the-forward-process-closed-form-noising" class="level3">
<h3 class="anchored" data-anchor-id="the-forward-process-closed-form-noising">The Forward Process: Closed-Form Noising</h3>
<p>Given a clean image <span class="math inline">\(x_0\)</span>, the forward process defines a sequence of increasingly noisy images. The one-step Markov transition is:</p>
<p><span class="math display">\[q(x_t \mid x_{t-1}) = \mathcal{N}\!\left(x_t;\, \sqrt{1-\beta_t}\, x_{t-1},\, \beta_t \mathbf{I}\right)\]</span></p>
<p>where <span class="math inline">\(\beta_t \in (0,1)\)</span> is the noise schedule. Defining <span class="math inline">\(\alpha_t = 1 - \beta_t\)</span> and <span class="math inline">\(\bar{\alpha}_t = \prod_{s=1}^{t} \alpha_s\)</span>, repeated application of the Gaussian convolution identity yields the closed form:</p>
<p><span class="math display">\[q(x_t \mid x_0) = \mathcal{N}\!\left(x_t;\, \sqrt{\bar{\alpha}_t}\, x_0,\, (1-\bar{\alpha}_t)\mathbf{I}\right)\]</span></p>
<p>which is sampled via the reparameterization:</p>
<p><span class="math display">\[x_t = \sqrt{\bar{\alpha}_t}\, x_0 + \sqrt{1-\bar{\alpha}_t}\, \varepsilon, \qquad \varepsilon \sim \mathcal{N}(0, \mathbf{I})\]</span></p>
<p>This is the key identity: <span class="math inline">\(x_t\)</span> is a deterministic, differentiable function of <span class="math inline">\(x_0\)</span> and <span class="math inline">\(\varepsilon\)</span>. No intermediate steps need to be simulated. With a linear schedule <span class="math inline">\(\beta_1 = 10^{-4}\)</span> to <span class="math inline">\(\beta_T = 0.02\)</span> over <span class="math inline">\(T=1000\)</span> steps, signal collapses to noise after <span class="math inline">\(t \approx 260\)</span> (signal/noise crossover).</p>
<p><img src="signal_noise_coefficient.png" class="img-fluid" alt="Signal vs Noise Coefficient"> <em>Signal coefficient <span class="math inline">\(\sqrt{\bar{\alpha}_t}\)</span> and noise coefficient <span class="math inline">\(\sqrt{1-\bar{\alpha}_t}\)</span> as functions of timestep. They cross at <span class="math inline">\(t=260\)</span>, after which noise dominates.</em></p>
<hr>
</section>
<section id="the-score-function-and-denoising-objective" class="level3">
<h3 class="anchored" data-anchor-id="the-score-function-and-denoising-objective">The Score Function and Denoising Objective</h3>
<p>The score function of the forward process is:</p>
<p><span class="math display">\[\nabla_{x_t} \log q(x_t \mid x_0) = -\frac{x_t - \sqrt{\bar{\alpha}_t}\, x_0}{1 - \bar{\alpha}_t} = -\frac{\varepsilon}{\sqrt{1-\bar{\alpha}_t}}\]</span></p>
<p>where the second equality follows by substituting <span class="math inline">\(x_t - \sqrt{\bar{\alpha}_t} x_0 = \sqrt{1-\bar{\alpha}_t}\,\varepsilon\)</span>. A network <span class="math inline">\(\varepsilon_\theta(x_t, t)\)</span> that predicts <span class="math inline">\(\varepsilon\)</span> therefore estimates the score up to a timestep-dependent scaling factor <span class="math inline">\(-1/\sqrt{1-\bar{\alpha}_t}\)</span>. The training objective is:</p>
<p><span class="math display">\[\mathcal{L}_\text{DDPM} = \mathbb{E}_{t,\, x_0,\, \varepsilon}\!\left[\left\|\varepsilon_\theta(x_t, t) - \varepsilon\right\|^2\right]\]</span></p>
<p>where <span class="math inline">\(t \sim \mathcal{U}[1,T]\)</span>, <span class="math inline">\(x_0 \sim p_\text{data}\)</span>, <span class="math inline">\(\varepsilon \sim \mathcal{N}(0,\mathbf{I})\)</span>, and <span class="math inline">\(x_t\)</span> is constructed via the closed form above.</p>
<hr>
</section>
<section id="the-reverse-process" class="level3">
<h3 class="anchored" data-anchor-id="the-reverse-process">The Reverse Process</h3>
<p>The learned reverse transition is modeled as:</p>
<p><span class="math display">\[p_\theta(x_{t-1} \mid x_t) = \mathcal{N}\!\left(x_{t-1};\, \mu_\theta(x_t, t),\, \sigma_t^2 \mathbf{I}\right)\]</span></p>
<p>The mean is derived by substituting the estimated clean image <span class="math inline">\(\hat{x}_0 = \frac{1}{\sqrt{\bar{\alpha}_t}}\!\left(x_t - \sqrt{1-\bar{\alpha}_t}\,\varepsilon_\theta\right)\)</span> into the true posterior mean <span class="math inline">\(\tilde{\mu}_t(x_t, x_0)\)</span>:</p>
<p><span class="math display">\[\mu_\theta(x_t, t) = \frac{1}{\sqrt{\alpha_t}}\!\left(x_t - \frac{\beta_t}{\sqrt{1-\bar{\alpha}_t}}\,\varepsilon_\theta(x_t, t)\right)\]</span></p>
<p>The variance <span class="math inline">\(\sigma_t^2 = \beta_t\)</span> is fixed (not learned) — the upper bound of the posterior variance under an uninformative prior on <span class="math inline">\(x_0\)</span>.</p>
<hr>
</section>
<section id="the-rectified-flow-objective" class="level3">
<h3 class="anchored" data-anchor-id="the-rectified-flow-objective">The Rectified Flow Objective</h3>
<p>Rectified Flow replaces the stochastic SDE with a deterministic ODE. Training pairs <span class="math inline">\(x_0 \sim p_\text{data}\)</span> with <span class="math inline">\(x_1 \sim \mathcal{N}(0,\mathbf{I})\)</span> and defines the straight-line interpolation:</p>
<p><span class="math display">\[x_t = (1-t)\,x_0 + t\,x_1, \qquad t \sim \mathcal{U}[0,1]\]</span></p>
<p>The velocity network <span class="math inline">\(v_\theta(x_t, t)\)</span> is trained to match the constant target velocity:</p>
<p><span class="math display">\[\mathcal{L}_\text{RF} = \mathbb{E}_{x_0,\, x_1,\, t}\!\left[\left\|v_\theta(x_t, t) - (x_1 - x_0)\right\|^2\right]\]</span></p>
<p>At inference, samples are generated by integrating the learned ODE from <span class="math inline">\(t=1\)</span> to <span class="math inline">\(t=0\)</span>:</p>
<p><span class="math display">\[\frac{dx}{dt} = v_\theta(x, t), \qquad x_1 \sim \mathcal{N}(0,\mathbf{I})\]</span></p>
<p>using Euler steps of size <span class="math inline">\(\Delta t = 1/N\)</span> for <span class="math inline">\(N\)</span> NFEs.</p>
<hr>
</section>
</section>
<section id="ddpm-architecture-and-training" class="level2">
<h2 class="anchored" data-anchor-id="ddpm-architecture-and-training">DDPM — Architecture and Training</h2>
<section id="time-conditioned-u-net" class="level3">
<h3 class="anchored" data-anchor-id="time-conditioned-u-net">Time-Conditioned U-Net</h3>
<p>The score network <span class="math inline">\(\varepsilon_\theta(x_t, t)\)</span> is a U-Net with sinusoidal timestep embeddings. The architecture must be conditioned on <span class="math inline">\(t\)</span> because the same pixel values <span class="math inline">\(x_t\)</span> require different denoising directions at different noise levels — a deterministic network receiving identical inputs must produce different outputs, which is impossible without <span class="math inline">\(t\)</span>.</p>
<p><strong>Sinusoidal timestep embedding:</strong> Timestep <span class="math inline">\(t\)</span> is encoded into a continuous vector via:</p>
<p><span class="math display">\[\text{emb}(t)_i = \begin{cases} \sin\!\left(t / 10000^{2i/d}\right) &amp; i &lt; d/2 \\ \cos\!\left(t / 10000^{2(i-d/2)/d}\right) &amp; i \geq d/2 \end{cases}\]</span></p>
<p>This produces a unique, smooth representation for each noise level, injected additively into every residual block. Embeddings at different timesteps are nearly orthogonal (cosine similarity <span class="math inline">\(t=0\)</span> vs <span class="math inline">\(t=499\)</span>: 0.0918), ensuring the network can distinguish noise levels.</p>
<p><strong>Residual block structure:</strong> Each block applies:</p>
<p><span class="math display">\[h = \text{SiLU}(\text{GroupNorm}(\text{Conv}(x))) + \text{Linear}(t\_\text{emb})\]</span> <span class="math display">\[\text{out} = \text{SiLU}(\text{GroupNorm}(\text{Conv}(h))) + \text{skip}(x)\]</span></p>
<p>where the time embedding is injected additively after the first activation. GroupNorm over 8 groups is used instead of BatchNorm for stability at small batch sizes.</p>
<p><strong>Full architecture:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Channels</th>
<th>Spatial size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input</td>
<td>3</td>
<td>32×32</td>
</tr>
<tr class="even">
<td>Encoder block 1</td>
<td>64</td>
<td>32×32</td>
</tr>
<tr class="odd">
<td>Encoder block 2</td>
<td>128</td>
<td>16×16</td>
</tr>
<tr class="even">
<td>Encoder block 3</td>
<td>256</td>
<td>8×8</td>
</tr>
<tr class="odd">
<td>Bottleneck (×2)</td>
<td>256</td>
<td>4×4</td>
</tr>
<tr class="even">
<td>Decoder block 3</td>
<td>128</td>
<td>8×8</td>
</tr>
<tr class="odd">
<td>Decoder block 2</td>
<td>64</td>
<td>16×16</td>
</tr>
<tr class="even">
<td>Decoder block 1</td>
<td>64</td>
<td>32×32</td>
</tr>
<tr class="odd">
<td>Output projection</td>
<td>3</td>
<td>32×32</td>
</tr>
</tbody>
</table>
<p>Skip connections concatenate encoder features into decoder inputs. Total: <strong>5,053,763 parameters</strong>.</p>
<hr>
</section>
<section id="training" class="level3">
<h3 class="anchored" data-anchor-id="training">Training</h3>
<p>The model was trained on CIFAR-10 (50,000 images, 10 balanced classes of 5,000 each) normalized to <span class="math inline">\([-1,1]\)</span>.</p>
<p><img src="one_sample_per_class.png" class="img-fluid" alt="CIFAR-10 samples"> <em>One sample per class from CIFAR-10. Images are 32×32 RGB.</em></p>
<p><img src="per_channel_intensity_distribution.png" class="img-fluid" alt="Per-channel intensity"> <em>Per-channel pixel intensity distribution. R mean=125.3, G mean=123.0, B mean=113.9. Normalization to <span class="math inline">\([-1,1]\)</span> centers the data distribution at <span class="math inline">\(\approx -0.053\)</span>.</em></p>
<p><strong>Hyperparameters:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Hyperparameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(T\)</span> (diffusion steps)</td>
<td>1000</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_\text{min}\)</span></td>
<td><span class="math inline">\(10^{-4}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_\text{max}\)</span></td>
<td><span class="math inline">\(0.02\)</span></td>
</tr>
<tr class="even">
<td>Batch size</td>
<td>128</td>
</tr>
<tr class="odd">
<td>Optimizer</td>
<td>AdamW</td>
</tr>
<tr class="even">
<td>Learning rate</td>
<td><span class="math inline">\(2 \times 10^{-4}\)</span></td>
</tr>
<tr class="odd">
<td>Epochs</td>
<td>100</td>
</tr>
<tr class="even">
<td>Gradient clipping</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>Random seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p>Gradient clipping at norm 1.0 is essential: the score scaling factor <span class="math inline">\(1/\sqrt{1-\bar{\alpha}_t}\)</span> reaches ~100 at <span class="math inline">\(t=1\)</span>, meaning low-timestep batches can produce large gradient magnitudes that destabilize training without clipping.</p>
<p><strong>Final DDPM training loss: 0.0316</strong></p>
<hr>
</section>
</section>
<section id="ddpm-as-a-wasserstein-gradient-flow" class="level2">
<h2 class="anchored" data-anchor-id="ddpm-as-a-wasserstein-gradient-flow">DDPM as a Wasserstein Gradient Flow</h2>
<section id="the-jko-scheme" class="level3">
<h3 class="anchored" data-anchor-id="the-jko-scheme">The JKO Scheme</h3>
<p>The Jordan-Kinderlehrer-Otto (JKO) scheme is a time-discretization of gradient flow in the space of probability distributions. At each discrete step <span class="math inline">\(k\)</span>, the next distribution is defined by:</p>
<p><span class="math display">\[\rho_{k+1} = \arg\min_{\rho} \left[ \underbrace{\mathrm{KL}(\rho \,\|\, p_{\text{data}})}_{\text{functional to minimize}} + \underbrace{\frac{1}{2\tau} W_2^2(\rho,\, \rho_k)}_{\text{proximal regularizer}} \right]\]</span></p>
<p>The two terms balance competing objectives:</p>
<ul>
<li><span class="math inline">\(\mathrm{KL}(\rho \| p_\text{data})\)</span>: pull the current distribution toward the data distribution.</li>
<li><span class="math inline">\(\frac{1}{2\tau} W_2^2(\rho, \rho_k)\)</span>: prevent the distribution from moving too far in one step, measured in Wasserstein-2 distance (minimum transport cost).</li>
<li><span class="math inline">\(\tau\)</span>: step size — corresponds to <span class="math inline">\(\beta_t\)</span> in the DDPM noise schedule.</li>
</ul>
<p>As <span class="math inline">\(\tau \to 0\)</span> and <span class="math inline">\(T \to \infty\)</span>, the discrete JKO steps converge to the Fokker-Planck equation, whose drift term is exactly the score function <span class="math inline">\(\nabla_x \log p(x_t)\)</span>.</p>
<hr>
</section>
<section id="connection-to-ddpm-denoising-steps" class="level3">
<h3 class="anchored" data-anchor-id="connection-to-ddpm-denoising-steps">Connection to DDPM Denoising Steps</h3>
<p>Each DDPM denoising step implements a JKO update in distribution space:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>JKO term</th>
<th>DDPM equivalent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\rho_k\)</span></td>
<td>noisy distribution <span class="math inline">\(q(x_t)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\rho_{k+1}\)</span></td>
<td>denoised distribution <span class="math inline">\(p_\theta(x_{t-1})\)</span></td>
</tr>
<tr class="odd">
<td>step size <span class="math inline">\(\tau\)</span></td>
<td>noise schedule parameter <span class="math inline">\(\beta_t\)</span></td>
</tr>
<tr class="even">
<td>velocity field</td>
<td>score network <span class="math inline">\(\varepsilon_\theta(x_t, t)\)</span></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="reframing-what-training-does" class="level3">
<h3 class="anchored" data-anchor-id="reframing-what-training-does">Reframing What Training Does</h3>
<p>Viewed naively, minimizing <span class="math inline">\(\mathcal{L}_\text{DDPM} = \mathbb{E}\!\left[\|\varepsilon_\theta - \varepsilon\|^2\right]\)</span> looks like pixel-space regression. The JKO framing reveals the correct interpretation:</p>
<blockquote class="blockquote">
<p><strong>Training is gradient descent in the space of probability distributions.</strong> The score network learns the velocity field of a Wasserstein gradient flow that transports <span class="math inline">\(\mathcal{N}(0,\mathbf{I})\)</span> toward <span class="math inline">\(p_\text{data}\)</span> along the direction of steepest descent of <span class="math inline">\(\mathrm{KL}(\cdot \| p_\text{data})\)</span>.</p>
</blockquote>
<p>This reframing has a direct practical consequence: the step size <span class="math inline">\(\beta_t\)</span> controls the proximal trade-off. Too large and the distribution jumps erratically; too small and convergence requires many NFEs. This is the mathematical reason DDPM needs <span class="math inline">\(T=1000\)</span> steps — and why Rectified Flow, which finds straighter paths in distribution space, can do far better at low NFE.</p>
<hr>
</section>
</section>
<section id="rectified-flow-and-the-push-forward-view" class="level2">
<h2 class="anchored" data-anchor-id="rectified-flow-and-the-push-forward-view">Rectified Flow and the Push-Forward View</h2>
<section id="ot-guided-straight-trajectories" class="level3">
<h3 class="anchored" data-anchor-id="ot-guided-straight-trajectories">OT-Guided Straight Trajectories</h3>
<p>Rectified Flow trains a velocity network <span class="math inline">\(v_\theta(x_t, t)\)</span> on straight-line interpolations between data and noise:</p>
<p><span class="math display">\[x_t = (1-t)\,x_0 + t\,x_1, \qquad x_0 \sim p_\text{data},\quad x_1 \sim \mathcal{N}(0,\mathbf{I}),\quad t \sim \mathcal{U}[0,1]\]</span></p>
<p>This is displacement interpolation — the same geodesic interpolation from Wasserstein geometry. Under independent (random) coupling, trajectories can cross. Under the optimal transport coupling (Monge map), points are paired to minimize total transport cost, eliminating crossings and making the learned velocity field closer to constant. With independent coupling (used here), the network still learns approximately straight trajectories — sufficient to dramatically reduce NFEs.</p>
<hr>
</section>
<section id="the-push-forward-view" class="level3">
<h3 class="anchored" data-anchor-id="the-push-forward-view">The Push-Forward View</h3>
<p>Both models solve the same fundamental problem:</p>
<p><span class="math display">\[T_\sharp\, \mu = \nu, \qquad \mu = \mathcal{N}(0,\mathbf{I}),\quad \nu = p_\text{data}\]</span></p>
<p>They differ only in how the transport map <span class="math inline">\(T\)</span> is parameterized:</p>
<p><strong>Rectified Flow — deterministic push-forward:</strong></p>
<p>The ODE flow map <span class="math inline">\(\varphi_t\)</span> integrates <span class="math inline">\(v_\theta\)</span> from <span class="math inline">\(t=1\)</span> to <span class="math inline">\(t=0\)</span>:</p>
<p><span class="math display">\[T(x) = \varphi_0(x) = x + \int_1^0 v_\theta(x_t, t)\, dt\]</span></p>
<p>The push-forward equation is:</p>
<p><span class="math display">\[(\varphi_0)_\sharp\, \mathcal{N}(0,\mathbf{I}) = p_\text{data}\]</span></p>
<p><span class="math inline">\(v_\theta\)</span> is the infinitesimal generator of <span class="math inline">\(T\)</span> — the network predicts local velocity arrows whose path integral accumulates into the full transport map.</p>
<p><strong>DDPM — stochastic push-forward:</strong></p>
<p><span class="math display">\[T_\sharp\,\mu = (K_1 \circ K_2 \circ \cdots \circ K_T)_\sharp\, \mathcal{N}(0,\mathbf{I})\]</span></p>
<p>where each <span class="math inline">\(K_t\)</span> samples from <span class="math inline">\(p_\theta(x_{t-1} \mid x_t)\)</span>. The transport is not a single deterministic map but a composition of <span class="math inline">\(T\)</span> conditional Gaussians.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Rectified Flow</th>
<th>DDPM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Push-forward type</td>
<td>deterministic</td>
<td>stochastic</td>
</tr>
<tr class="even">
<td>Transport map <span class="math inline">\(T\)</span></td>
<td><span class="math inline">\(\varphi_0\)</span> (ODE flow)</td>
<td><span class="math inline">\(K_1 \circ \cdots \circ K_T\)</span> (Markov chain)</td>
</tr>
<tr class="odd">
<td>Generator</td>
<td><span class="math inline">\(v_\theta\)</span> (velocity field)</td>
<td><span class="math inline">\(\varepsilon_\theta\)</span> (score predictor)</td>
</tr>
<tr class="even">
<td>Path geometry</td>
<td>straight (≈ OT geodesic)</td>
<td>curved (variance-preserving SDE)</td>
</tr>
<tr class="odd">
<td>NFE to approximate <span class="math inline">\(T\)</span></td>
<td>low</td>
<td>high</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="training-and-sampling" class="level3">
<h3 class="anchored" data-anchor-id="training-and-sampling">Training and Sampling</h3>
<p>Both models use the identical U-Net architecture (5,053,763 parameters) trained for 100 epochs with AdamW at <span class="math inline">\(lr = 2\times10^{-4}\)</span>.</p>
<p><strong>RF training loss:</strong> 0.1838 — not comparable to DDPM’s 0.0316. RF targets <span class="math inline">\((x_1 - x_0)\)</span> with variance <span class="math inline">\(\approx 2\)</span>; DDPM targets <span class="math inline">\(\varepsilon\)</span> with variance <span class="math inline">\(1\)</span>. Lower absolute loss does not mean better generative quality.</p>
<p>At inference, RF integrates the ODE using Euler steps:</p>
<p><span class="math display">\[x_{t - \Delta t} = x_t - v_\theta(x_t, t)\cdot \Delta t, \qquad \Delta t = \frac{1}{N}\]</span></p>
<p>for <span class="math inline">\(N\)</span> steps from <span class="math inline">\(t=1\)</span> to <span class="math inline">\(t=0\)</span>. Because trajectories are straight, large <span class="math inline">\(\Delta t\)</span> (few steps) introduces minimal discretization error — unlike DDPM where large steps cause the sampler to fly off curved trajectories.</p>
<hr>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="training-curves" class="level3">
<h3 class="anchored" data-anchor-id="training-curves">Training Curves</h3>
<p>Both models trained for 100 epochs on a Tesla P100-16GB GPU (~22s/epoch).</p>
<p><img src="training_loss_comparison.png" class="img-fluid" alt="Training loss comparison"> <em>DDPM loss converges to 0.0316; RF loss converges to 0.1838. Losses operate on different scales and are not directly comparable — DDPM targets unit-variance noise, RF targets difference vectors with variance ≈ 2.</em></p>
<hr>
</section>
<section id="nfe-vs-fid-benchmark" class="level3">
<h3 class="anchored" data-anchor-id="nfe-vs-fid-benchmark">NFE vs FID Benchmark</h3>
<p>10,000 samples generated per model per NFE budget. FID computed against 10,000 real CIFAR-10 training images using Inception-v3 pool3 features (pytorch-fid). Real vs real FID baseline: <strong>10.27</strong>.</p>
<p><img src="fid_vs_nfe.png" class="img-fluid" alt="FID vs NFE"> <em>FID vs NFE for DDPM and Rectified Flow. Lower is better. DDPM collapses at low NFE; RF remains stable across all budgets.</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>NFE</th>
<th>DDPM FID</th>
<th>RF FID</th>
<th>RF Advantage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10</td>
<td>405.60</td>
<td>47.39</td>
<td>+358.21</td>
</tr>
<tr class="even">
<td>20</td>
<td>431.21</td>
<td>45.37</td>
<td>+385.84</td>
</tr>
<tr class="odd">
<td>50</td>
<td>436.92</td>
<td>43.96</td>
<td>+392.96</td>
</tr>
<tr class="even">
<td>100</td>
<td>435.09</td>
<td>43.01</td>
<td>+392.07</td>
</tr>
<tr class="odd">
<td>200</td>
<td>434.03</td>
<td>43.02</td>
<td>+391.02</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p><strong>DDPM at NFE 10–200:</strong> FID 405–437 — effectively generating near-random noise. The strided sampler skips steps on curved trajectories, accumulating large discretization error. DDPM requires the full <span class="math inline">\(T=1000\)</span> steps for valid sampling; anything less violates the mathematical assumptions of the reverse process.</p>
<p><strong>RF at NFE 10–200:</strong> FID 43–47 — stable and consistent across all budgets. The straight-line trajectory tolerates large Euler steps without significant drift. The gap between NFE=10 (47.39) and NFE=200 (43.02) is only 4.37 FID points — diminishing returns set in quickly.</p>
<p><strong>The core finding:</strong> Rectified Flow achieves competitive sample quality at NFE=10 where DDPM completely fails. The RF advantage exceeds 350 FID points at every tested budget. This directly validates the geometric argument: straight trajectories in distribution space require fewer discretization steps to approximate accurately.</p>
<hr>
</section>
</section>
<section id="key-insights" class="level2">
<h2 class="anchored" data-anchor-id="key-insights">Key Insights</h2>
<p><strong>1. DDPM’S CURVED TRAJECTORIES MAKE LOW-NFE SAMPLING MATHEMATICALLY INVALID</strong></p>
<p>DDPM’s strided sampler does not merely degrade gracefully at low NFE — it collapses catastrophically (FID 405–437). This is not a tuning failure. The reverse process derives its correctness from the assumption that <span class="math inline">\(\beta_t\)</span> is small enough that the reverse of the forward process is approximately Gaussian. Skipping steps violates this assumption entirely: the sampler attempts to jump across regions of distribution space where the score network was never trained to operate. Each skipped step compounds the error, and the trajectory flies off the curved path into regions of near-zero data probability. The mathematical contract of the reverse SDE is broken.</p>
<hr>
<p><strong>2. RECTIFIED FLOW’S STABILITY ACROSS NFE BUDGETS IS A GEOMETRIC PROPERTY, NOT A TUNING ARTIFACT</strong></p>
<p>The 4.37 FID point gap between RF at NFE=10 (47.39) and NFE=200 (43.02) is remarkably small. This flatness is a direct consequence of straight trajectories — Euler integration error on a straight path scales as <span class="math inline">\(O(\Delta t)\)</span> rather than <span class="math inline">\(O(\Delta t^{-1})\)</span> for curved paths where curvature amplifies step error. The network is trained to predict a constant velocity vector <span class="math inline">\((x_1 - x_0)\)</span>; a large Euler step in a constant velocity field lands exactly where a small step would, up to first-order error. This is not an accident of training — it is the geometric payoff of the OT-guided straight-path design.</p>
<hr>
<p><strong>3. THE JKO LENS REVEALS WHY THESE TWO MODELS ARE NOT AS DIFFERENT AS THEY APPEAR</strong></p>
<p>DDPM and Rectified Flow look like fundamentally different algorithms — one stochastic, one deterministic; one score-based, one flow-based. The push-forward framing unifies them: both learn a map <span class="math inline">\(T_\sharp \mu = \nu\)</span> from <span class="math inline">\(\mathcal{N}(0,\mathbf{I})\)</span> to <span class="math inline">\(p_\text{data}\)</span>. The difference is path geometry. DDPM parameterizes <span class="math inline">\(T\)</span> as a composition of <span class="math inline">\(T=1000\)</span> stochastic Markov kernels along a curved, variance-preserving SDE trajectory. Rectified Flow parameterizes <span class="math inline">\(T\)</span> as a single ODE flow map along a straight trajectory. The JKO scheme makes this concrete: DDPM takes many small proximal steps in Wasserstein space; Rectified Flow takes fewer, larger steps because its straighter path requires less proximal regularization to remain stable. Both are gradient flows — one just flows along a more efficient route.</p>
<hr>
</section>
<section id="implementation-notes" class="level2">
<h2 class="anchored" data-anchor-id="implementation-notes">Implementation Notes</h2>
<ul>
<li><strong>No external generative model libraries.</strong> DDPM forward process, score matching loss, reverse sampler, and Rectified Flow training loop are all implemented from scratch in pure PyTorch. No diffusers, no flow matching libraries.</li>
<li><strong>U-Net written explicitly.</strong> Standard PyTorch primitives only (Conv2d, GroupNorm, SiLU). No imported model architectures.</li>
<li><strong>FID via pytorch-fid.</strong> Uses the standard Inception-v3 pool3 feature extractor — the community standard for CIFAR-10 comparisons. CIFAR-10 images upsampled 32→75px before Inception forward pass (minimum input size requirement).</li>
<li><strong>Gradient clipping at norm 1.0.</strong> Essential for DDPM training: the score scaling factor <span class="math inline">\(1/\sqrt{1-\bar{\alpha}_t}\)</span> reaches ~100 at <span class="math inline">\(t=1\)</span>, producing large gradient magnitudes at low-noise timesteps without clipping.</li>
<li><strong>Images normalized to <span class="math inline">\([-1,1]\)</span>.</strong> Centering at zero aligns the data distribution mean with the terminal noise distribution <span class="math inline">\(\mathcal{N}(0,\mathbf{I})\)</span>, eliminating asymmetric bias in score estimates at intermediate timesteps.</li>
<li><strong>Fixed random seed 42</strong> throughout for reproducibility.</li>
<li><strong>Shared architecture.</strong> Both DDPM and RF use the identical U-Net (5,053,763 parameters) for a controlled comparison — architectural differences cannot explain FID differences.</li>
<li><strong>JKO and push-forward framing</strong> documented as explicit markdown cells in the notebook, not comments.</li>
</ul>
<hr>
</section>
<section id="dependencies" class="level2">
<h2 class="anchored" data-anchor-id="dependencies">Dependencies</h2>
<pre><code>torch==2.3.1
torchvision==0.18.1
numpy==2.4.6
matplotlib==3.10.0
pytorch-fid          # fid computation via inception-v3 pool3 features
scipy                # matrix square root for frechet distance
tqdm                 # training and sampling progress bars
</code></pre>
<p><strong>INSTALL COMMANDS [Kaggle Notebook <span class="math inline">\(\rightarrow\)</span> Add-ons <span class="math inline">\(\rightarrow\)</span> Install Dependencies]</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install torch==2.3.1+cu121 torchvision==0.18.1+cu121 <span class="dt">\</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">--index-url</span> https://download.pytorch.org/whl/cu121</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install torch-geometric==2.5.3</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install pyg_lib==0.4.0 torch_scatter==2.1.2 <span class="dt">\</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    torch_sparse==0.6.18 torch_cluster==1.6.3 <span class="dt">\</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">-f</span> https://data.pyg.org/whl/torch-2.3.0+cu121.html</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
<section id="note" class="level2">
<h2 class="anchored" data-anchor-id="note">Note</h2>
<table class="caption-top">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">The notebook was developed and tested on a Kaggle environment with a NVIDIA P100 16GB GPU, Python 3.12, and CUDA 12.1. All cells run end-to-end from a clean kernel without any external dependencies beyond those listed above.</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<hr>
<hr>
<ul>
<li><a href="https://github.com/shreeshb51/shreeshb51.github.io/blob/main/projects/Score-Based%20Generative%20Model%20on%20a%20Real%20Dataset%20with%20OT-Guided%20Sampling/project_4_score_based_gm_with_ot_guided_sampling.ipynb">Project Notebook (Code)</a></li>
<li><a href="../../projects/Score-Based Generative Model on a Real Dataset with OT-Guided Sampling/mathematical_framework.html">Mathematical Framework</a></li>
<li><a href="../../projects/Score-Based Generative Model on a Real Dataset with OT-Guided Sampling/solving_anchor_example.html">Solving an Anchor Example</a></li>
</ul>
<hr>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shreeshb51\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Shreesh Bhattarai · GDL &amp; COT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/shreeshb51">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/shreesh-bhattarai-1ba1681bb/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>