<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mathematical_framework – Shreesh Bhattarai</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-74ba59708be70b1949d5896c354d4bb9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shreesh Bhattarai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../catw/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Along the Way</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../papers/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper Comprehensions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notes</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#mathematical-framework-for-project-5---riemannian-flow-matching-for-protein-backbone-generation" id="toc-mathematical-framework-for-project-5---riemannian-flow-matching-for-protein-backbone-generation" class="nav-link active" data-scroll-target="#mathematical-framework-for-project-5---riemannian-flow-matching-for-protein-backbone-generation">Mathematical Framework for Project 5 - Riemannian Flow Matching for Protein Backbone Generation</a>
  <ul class="collapse">
  <li><a href="#context" id="toc-context" class="nav-link" data-scroll-target="#context">Context</a></li>
  <li><a href="#concepts" id="toc-concepts" class="nav-link" data-scroll-target="#concepts">Concepts</a></li>
  <li><a href="#underlying-mathematics" id="toc-underlying-mathematics" class="nav-link" data-scroll-target="#underlying-mathematics">Underlying Mathematics</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="mathematical-framework-for-project-5---riemannian-flow-matching-for-protein-backbone-generation" class="level1">
<h1>Mathematical Framework for Project 5 - Riemannian Flow Matching for Protein Backbone Generation</h1>
<hr>
<section id="context" class="level2">
<h2 class="anchored" data-anchor-id="context">Context</h2>
<p>Implement Riemannian Flow Matching (RFM) on <span class="math inline">\(SO(3)\)</span> or the torus <span class="math inline">\(T^n\)</span> to generate protein backbone torsion angles (<span class="math inline">\(\phi\)</span>, <span class="math inline">\(\psi\)</span> angles from the Ramachandran plot). The key constraint: generated angles must lie on the manifold, not in ambient Euclidean space. Evaluate using Ramachandran plot coverage of <span class="math inline">\(\alpha\)</span>-helix and <span class="math inline">\(\beta\)</span>-sheet structural regions.</p>
<hr>
</section>
<section id="concepts" class="level2">
<h2 class="anchored" data-anchor-id="concepts">Concepts</h2>
<ul>
<li><p><strong>Torsion Angle (Dihedral Angle):</strong> The angle of rotation around a chemical bond between four connected atoms. <em>Example: Think of a twisted towel; the amount of twist between two ends represents the torsion angle.</em></p></li>
<li><p><strong><span class="math inline">\(\omega\)</span> (Omega) Angle:</strong> The torsion angle of the rigid peptide bond (<span class="math inline">\(C - N\)</span>) connecting two amino acids.</p></li>
<li><p><strong>Ramachandran Plot:</strong> A 2D graph that maps the structural conformations of a protein by plotting the <span class="math inline">\(\phi\)</span> and <span class="math inline">\(\psi\)</span> angles of its amino acids.</p></li>
<li><p><strong>Target Distribution (<span class="math inline">\(\nu\)</span>):</strong> The ideal, real-world data pattern that a machine learning model is trying to copy or learn.</p></li>
<li><p><strong><span class="math inline">\(T^2\)</span> (2-Torus):</strong> A mathematical shape that looks like the surface of a doughnut. It represents a 2D space where both the horizontal and vertical directions loop back on themselves.</p></li>
<li><p><strong>Residue:</strong> A single amino acid unit within a protein chain.</p></li>
<li><p><strong>Protein Backbone:</strong> The repeating main chain of atoms (<span class="math inline">\(\dots - N - C_\alpha - C - N - C_\alpha - C - \dots\)</span>) that forms the structural core of a protein.</p></li>
<li><p><strong>Identification Relations (Equivalence Classes):</strong> A mathematical rule that treats different points as if they are the exact same point. <em>Example: On a clock face, the number 13 is “identified” with the number 1 (<span class="math inline">\(13 \equiv 1 \pmod{12}\)</span>).</em></p></li>
<li><p><strong>Euclidean Flow Matching:</strong> A machine learning method that learns to move data points along straight lines in flat, standard space (<span class="math inline">\(\mathbb{R}^n\)</span>) to match a target distribution.</p></li>
<li><p><strong>Vector Field (<span class="math inline">\(v(x, t)\)</span>):</strong> A map that assigns a directional arrow (velocity and direction) to every point in space at a given time, dictating how data points should move.</p></li>
<li><p><strong>Geodesic:</strong> The shortest, straightest possible path between two points on a curved surface or manifold. <em>Example: On Earth, the geodesic between two cities is a “great-circle” route, not a flat straight line through the dirt.</em></p></li>
<li><p><strong>Exponential Map (<span class="math inline">\(\text{exp}_p(v)\)</span>):</strong> The geometric version of “addition.” It takes a starting point <span class="math inline">\(p\)</span> on a manifold and a direction/velocity vector <span class="math inline">\(v\)</span>, moves along that path for one unit of time, and lands on a new point on the manifold.</p></li>
<li><p><strong>Logarithm Map (<span class="math inline">\(\text{log}_p(q)\)</span>):</strong> The geometric version of “subtraction.” It takes two points <span class="math inline">\(p\)</span> and <span class="math inline">\(q\)</span> on a manifold and returns the exact tangent vector at <span class="math inline">\(p\)</span> that points toward <span class="math inline">\(q\)</span> along the shortest possible path.</p></li>
<li><p><strong><span class="math inline">\(S^1\)</span> (1-Sphere / Circle):</strong> A 1D manifold representing a perfect circle. A torus (<span class="math inline">\(T^2\)</span>) is simply two of these circles combined (<span class="math inline">\(S^1 \times S^1\)</span>).</p></li>
<li><p><strong>Wrapped Displacement:</strong> The true shortest distance and direction between two points on a circle, accounting for the fact that the space loops around.</p></li>
<li><p><strong>Geodesic Interpolation:</strong> The process of finding smooth, shortest-path intermediate points between two positions on a curved surface or manifold. <em>Example: Finding the exact midpoint of a flight path between two cities on a globe.</em></p></li>
<li><p><strong>Naive Midpoint:</strong> The standard Euclidean average (<span class="math inline">\(\dfrac{p_0 + p_1}{2}\)</span>). It assumes the world is flat and draws a straight line straight through the space, ignoring any boundaries or curvature.</p></li>
<li><p><strong>Conditional Flow Matching (CFM):</strong> A generative modeling technique that trains a neural network to predict the straight-line velocity vectors required to push a simple starting data distribution into a complex target distribution.</p></li>
<li><p><strong>Regression Target:</strong> The exact value or vector that a machine learning model is trying to predict for a given input.</p></li>
<li><p><strong>Expectation (<span class="math inline">\(\mathbb{E}\)</span>):</strong> The average value you would expect to get if you repeated an experiment or sampled data points many times.</p></li>
<li><p><strong>Integrator (ODE Solver):</strong> A mathematical algorithm that takes small, sequential steps along a vector field to track and calculate the final path of a moving particle over time.</p></li>
<li><p><strong>Tangent Space (<span class="math inline">\(T_xM\)</span>):</strong> The flat, vector-space plane that sits tangentially against a specific point <span class="math inline">\(x\)</span> on a curved manifold. Velocity vectors must live in this flat tangent space. <em>Example: A flat index card touching the exact top point of a basketball.</em></p></li>
<li><p><strong>Vector Field Projection:</strong> The process of ensuring that a velocity vector aligns properly with the geometry of the manifold at a specific point, preventing the model from predicting directions that point “off” the surface.</p></li>
<li><p><strong>Trajectory Drift:</strong> The gradual accumulation of errors over time during numerical integration, causing the calculated path to wander away from the true, theoretically correct path.</p></li>
<li><p><strong>Manifold-Constrained Integrator:</strong> A step-by-step algorithm designed to track the movement of a particle while strictly forcing its coordinates to remain bound to the geometry of a specific surface (manifold).</p></li>
<li><p><strong>Finite Step Size (<span class="math inline">\(\Delta t\)</span>):</strong> A fixed, discrete chunk of time used during computer simulations to approximate continuous motion.</p></li>
<li><p><strong>Wrap-Around Discontinuity:</strong> The artificial “cliff” created when a flat coordinate system cuts off a continuous, looping space. <em>Example: On a standard flat map of the world, the far-left edge (Alaska) and the far-right edge (Siberia) look like they are separated by an entire ocean, but in reality, they touch. A flat model sees this boundary as a massive cliff or gap rather than a seamless connection.</em></p></li>
<li><p><strong><span class="math inline">\(\alpha\)</span>-helix (Alpha-Helix):</strong> A common, tightly coiled right-handed spiral structural pattern found in proteins.</p></li>
<li><p><strong><span class="math inline">\(\beta\)</span>-sheet (Beta-Sheet):</strong> A common structural pattern in proteins where multiple extended chains of amino acids line up parallel or anti-parallel to each other, forming a pleated sheet.</p></li>
</ul>
<hr>
</section>
<section id="underlying-mathematics" class="level2">
<h2 class="anchored" data-anchor-id="underlying-mathematics">Underlying Mathematics</h2>
<hr>
<section id="stage-1---environment-biological-context" class="level3">
<h3 class="anchored" data-anchor-id="stage-1---environment-biological-context">Stage 1 - Environment &amp; Biological Context</h3>
<p><strong>What are we building?</strong></p>
<p>We’re building the ground-truth reference: loading a real protein torsion angle dataset, inspecting its statistical structure, and producing the Ramachandran plot that our generative model will eventually learn to reproduce.</p>
<p>This plot is the target distribution ν on <span class="math inline">\(T^2\)</span>. Everything downstream — the manifold structure, the flow, the evaluation — is calibrated against it. If we don’t understand what it represents physically, we can’t evaluate whether our model is generating chemically meaningful conformations.</p>
<p><br></p>
</section>
<section id="questions-1" class="level3">
<h3 class="anchored" data-anchor-id="questions-1">Questions [1]</h3>
<ol type="1">
<li><p>What physical rotation does <span class="math inline">\(\phi\)</span> describe, and what does <span class="math inline">\(\psi\)</span> describe? (Name the specific bonds each angle rotates around.)</p></li>
<li><p>Why is the Ramachandran plot not uniformly covered — what causes the forbidden regions, and why do <span class="math inline">\(\alpha\)</span>-helices and <span class="math inline">\(\beta\)</span>-sheets cluster where they do?</p></li>
<li><p>Why does the periodicity of these angles mean the domain is <span class="math inline">\(T^2\)</span> and not just a square in <span class="math inline">\(\mathbb{R}\)</span>?</p></li>
</ol>
<p>Be precise about the geometry.</p>
<p><br></p>
</section>
<section id="answers-1" class="level3">
<h3 class="anchored" data-anchor-id="answers-1">Answers [1]</h3>
<ol type="1">
<li>Which specific bonds do <span class="math inline">\(\phi\)</span> and <span class="math inline">\(\psi\)</span> describe?</li>
</ol>
<p>In the repeating <span class="math inline">\(N - C_\alpha - C\)</span> backbone of a protein:</p>
<ul>
<li><strong><span class="math inline">\(\phi\)</span> (phi)</strong> governs rotation around the <strong><span class="math inline">\(N - C_\alpha\)</span></strong> bond (Nitrogen to Alpha-Carbon).</li>
<li><strong><span class="math inline">\(\psi\)</span> (psi)</strong> governs rotation around the <strong><span class="math inline">\(C_\alpha - C\)</span></strong> bond (Alpha-Carbon to Carbonyl Carbon).</li>
</ul>
<p>While there is a third bond in the backbone—the peptide bond (<span class="math inline">\(C - N\)</span>) governed by the <span class="math inline">\(\omega\)</span> (omega) angle—it is not a true degree of freedom. Due to partial double-bond character, <span class="math inline">\(\omega\)</span> is heavily restricted to a flat plane (usually trans at <span class="math inline">\(180^\circ\)</span> or cis at <span class="math inline">\(0^\circ\)</span>) with only minor thermal fluctuations of about <span class="math inline">\(\pm6^\circ\)</span>. Because this angle is functionally fixed, we can fully parameterize the backbone configuration using just <span class="math inline">\((\phi, \psi)\)</span> per residue, mapping perfectly to a single <span class="math inline">\(T^2\)</span> torus per residue.</p>
<p><br></p>
<ol start="2" type="1">
<li>Why is the Ramachandran plot non-uniform? What physical constraint creates forbidden zones?</li>
</ol>
<p>The plot is mostly empty because of <strong>steric hindrance</strong> (atomic overcrowding). Even though you <em>can</em> mathematically rotate the bonds to any angle, atoms take up physical space. At many <span class="math inline">\((\phi, \psi)\)</span> combinations, atoms try to occupy the exact same physical space and crash into each other.</p>
<p>Crucially, the dominant “forbidden zones” are caused by clashes between <strong>backbone atoms themselves</strong>—specifically, the carbonyl oxygen (<span class="math inline">\(O\)</span>) and the amide hydrogen (<span class="math inline">\(H\)</span>) of adjacent residues bumping into one another.</p>
<p>Because these clashes are built into the backbone itself, even <strong>glycine</strong> (the simplest amino acid, which has no bulky side chain) still features restricted, forbidden zones on the plot. However, because glycine lacks a side chain, it remains far less restricted than other residues. This distinction is vital for machine learning models evaluating data coverage: glycine-rich loops will populate open, unique regions of the <span class="math inline">\(T^2\)</span> space that other amino acids physically cannot enter.</p>
<p><br></p>
<ol start="3" type="1">
<li>Why is <span class="math inline">\(T^2\)</span> the correct manifold? (Periodicity &amp; Boundaries)</li>
</ol>
<p>Angles are periodic, meaning they naturally loop. If you rotate a bond by <span class="math inline">\(+180^\circ\)</span> (<span class="math inline">\(+\pi\)</span>) or <span class="math inline">\(-180^\circ\)</span> (<span class="math inline">\(-\pi\)</span>), you end up at the exact same physical position.</p>
<p>If we plot these angles on a flat square grid from <span class="math inline">\([-\pi, \pi)\)</span>, the top edge is identical to the bottom edge, and the left edge is identical to the right edge.</p>
<p>To represent this without any artificial “walls” or boundaries, you must mathematically “glue” the left edge to the right edge (forming a cylinder), and then glue the top circle of that cylinder to the bottom circle. This geometric gluing results in a <strong>torus (<span class="math inline">\(T^2\)</span>)</strong>, making it the perfect seamless map for two looping angles.</p>
<hr>
</section>
<section id="stage-1-technical-report-synthetic-ramachandran-data-pipeline" class="level3">
<h3 class="anchored" data-anchor-id="stage-1-technical-report-synthetic-ramachandran-data-pipeline">Stage 1 Technical Report: Synthetic Ramachandran Data Pipeline</h3>
<section id="executive-summary" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary">1. Executive Summary</h4>
<p>In Stage 1, we successfully constructed, cleaned, validated, and packaged a highly realistic, synthetic dataset mimicking protein backbone conformation angles. The dataset contains <strong>50,000 residues</strong> defined by two dihedral angles, <span class="math inline">\(\phi\)</span> (phi) and <span class="math inline">\(\psi\)</span> (psi). These angles dictate the local structural folding of a protein’s polypeptide chain. The final artifact is a mathematically verified PyTorch tensor optimized for generative machine learning tasks.</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. The Topology of the Torus (<span class="math inline">\(T^2\)</span>)</strong></p>
<p>Dihedral angles are circular and periodic. An angle of <span class="math inline">\(-180^\circ\)</span> (<span class="math inline">\(\!-\pi\)</span> radians) is identical to <span class="math inline">\(+180^\circ\)</span> (<span class="math inline">\(+\pi\)</span> radians). Because we track <em>two</em> linked angles simultaneously, the data does not exist on a standard flat 2D plane. Instead, it lives on a continuous, wrapped 2D surface known mathematically as a <strong>Torus</strong> (a donut shape, denoted as <span class="math inline">\(T^2\)</span>).</p>
<p><br></p>
<p><strong>B. The Wrapped Normal Distribution</strong></p>
<p>To simulate natural clusters without losing data at the edges, we used a <strong>Wrapped Normal Distribution</strong>. In a standard normal distribution, data can bleed out to infinity. A wrapped distribution captures values that overshoot the angular boundaries and maps them back into the proper range using modulo arithmetic.</p>
<p>Mathematically, a random angular sample <span class="math inline">\(x\)</span> drawn from a normal distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> is mapped onto the interval <span class="math inline">\((\!-\pi, \pi]\)</span> using:</p>
<p><span class="math display">\[x_{\text{wrapped}} = \left( (x + \pi) \pmod{2\pi} \right) - \pi\]</span></p>
<p><br></p>
<p><strong>C. Statistical Populations (The Target Distribution <span class="math inline">\(\nu\)</span>)</strong></p>
<p>Real-world proteins prefer specific combinations of <span class="math inline">\(\phi\)</span> and <span class="math inline">\(\psi\)</span> due to physical constraints (steric hindrance). Our target distribution <span class="math inline">\(\nu\)</span> blends four distinct structural sub-populations derived from empirical literature (Lovell et al., 2003):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Structural Region</th>
<th>Target Fraction</th>
<th><span class="math inline">\(\phi\)</span> Mean, Std (deg)</th>
<th><span class="math inline">\(\psi\)</span> Mean, Std (deg)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><span class="math inline">\(\alpha\)</span>-helix</strong></td>
<td>32%</td>
<td><span class="math inline">\(-63.0^\circ, 7.0^\circ\)</span></td>
<td><span class="math inline">\(-43.0^\circ, 7.0^\circ\)</span></td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(\beta\)</span>-sheet</strong></td>
<td>22%</td>
<td><span class="math inline">\(-119.0^\circ, 8.0^\circ\)</span></td>
<td><span class="math inline">\(130.0^\circ, 8.0^\circ\)</span></td>
</tr>
<tr class="odd">
<td><strong>Left-handed helix</strong></td>
<td>3%</td>
<td><span class="math inline">\(57.0^\circ, 7.0^\circ\)</span></td>
<td><span class="math inline">\(47.0^\circ, 7.0^\circ\)</span></td>
</tr>
<tr class="even">
<td><strong>Loop / Generously Allowed</strong></td>
<td>43%</td>
<td><span class="math inline">\(0.0^\circ, 55.0^\circ\)</span></td>
<td><span class="math inline">\(5.0^\circ, 65.0^\circ\)</span></td>
</tr>
</tbody>
</table>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review">3. Step-by-Step Pipeline Review</h4>
<p>The workflow spanned four core engineering themes:</p>
<pre><code>[Environment Setup] ──&gt; [Data Synthesis &amp; Shuffling] ──&gt; [Rigid Quality Control] ──&gt; [Tensor Packaging]</code></pre>
<ol type="1">
<li><p><strong>Environment Setup &amp; Reproducibility:</strong> Imported core arrays (<code>numpy</code>), dataframes (<code>pandas</code>), plotting tools (<code>matplotlib</code>), and deep learning architectures (<code>torch</code>). Locked the environment’s random states with a dedicated global variable (<code>SEED = 42</code>) to guarantee identical data generation across future runtime instances.</p></li>
<li><p><strong>Data Generation &amp; Shuffling:</strong> Generated a baseline pool of 50,000 data rows split by the population percentages. Because the chunks were generated sequentially, the rows were completely shuffled using an index permutation matrix (<span class="math inline">\(idx\)</span>) to prevent spatial region leakage during downstream training steps.</p></li>
<li><p><strong>Data Cleaning &amp; Filtering:</strong> Dropped any potential missing values (<code>NaN</code>) and reset index rows sequentially. This serves as an automated firewall ensuring exactly <span class="math inline">\(N = 50,000\)</span> clean coordinates are parsed.</p></li>
<li><p><strong>Range &amp; Toroidal Integrity Verification:</strong> Calculated descriptive statistics and visualized the non-uniform, multimodal nature of the structural data via 72-bin marginal histograms.. For instance, the computed sample statistics for the dataset settled at:</p></li>
</ol>
<p><span class="math display">\[\mu_{\phi} \approx -0.781, \sigma_{\phi} \approx 1.080 \quad \Big| \quad \mu_{\psi} \approx 0.313, \sigma_{\psi} \approx 1.339\]</span></p>
<ol start="5" type="1">
<li><strong>Structural Mapping:</strong> Formulated boolean index masks based on rigid biological box constraints to count elements. When forced into strict geometric boundaries, the data yielded:
<ul>
<li><strong><span class="math inline">\(\alpha\)</span>-helix region:</strong> 16,433 residues (32.9%)</li>
<li><strong><span class="math inline">\(\beta\)</span>-sheet region:</strong> 11,075 residues (22.1%)</li>
<li><strong>Unclassified Loops:</strong> 22,492 residues (45.0%)</li>
</ul></li>
<li><strong>PyTorch Packing:</strong> Multi-dimensional arrays were column-stacked and cast into a 32-bit floating-point tensor structure matching dimensions <span class="math inline">\([50000, 2]\)</span>.</li>
</ol>
<p><br></p>
</section>
<section id="key-learnings" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings">4. Key Learnings</h4>
<ul>
<li><strong>The Data is Non-Uniform:</strong> The histograms and scatter plots prove that the dataset is highly clustered, reflecting real physical limitations in protein folding. A naive model assuming uniform data distribution would fail.</li>
<li><strong>The Constraints are Circular:</strong> Because the boundaries are linked (<span class="math inline">\(-\pi \equiv \pi\)</span>), any future predictive model or loss function cannot use basic straight-line Euclidean distance formulas without running into boundary errors.</li>
<li><strong>The Dataset is Ready:</strong> The final tensor successfully cleared the strict mathematical safety gate:</li>
</ul>
<p><span class="math display">\[\forall x \in \text{data}, \quad -\pi \le x &lt; \pi\]</span></p>
<p><br></p>
<p>The system is structurally primed for deep learning models, optimization layers, or generative architectures.</p>
<hr>
</section>
</section>
<section id="stage-2---the-torus-t_2-as-a-riemannian-manifold" class="level3">
<h3 class="anchored" data-anchor-id="stage-2---the-torus-t_2-as-a-riemannian-manifold">Stage 2 - The Torus <span class="math inline">\(T_2\)</span> as a Riemannian Manifold</h3>
<p><strong>What are we building?</strong></p>
<p>We’re building the explicit manifold structure that every downstream component depends on: the metric, the topology, and two visualizations of <span class="math inline">\(T_2\)</span> that make the identification concrete. This is the geometric foundation — without it, “staying on the manifold” is just a phrase.</p>
<p><br></p>
</section>
<section id="questions-2" class="level3">
<h3 class="anchored" data-anchor-id="questions-2">Questions [2]</h3>
<ol type="1">
<li><p>The domain <span class="math inline">\([- \pi, \pi)^2\)</span> becomes <span class="math inline">\(T^2\)</span> by identifying opposite edges. Write down the two identification relations explicitly as equivalence classes — i.e., which points are declared equal, and on which edges.</p></li>
<li><p>Suppose you train a Euclidean flow matching model on this data, treating <span class="math inline">\((\phi, \psi) \in \mathbb{R}^2\)</span>. The model learns a vector field <span class="math inline">\(v(x, t)\)</span> that pushes mass from a source near <span class="math inline">\(\phi = -\pi\)</span> to a target near <span class="math inline">\(\phi = +\pi\)</span>. Describe concretely what goes wrong — where does the vector field point, how long is it, and why is that path geometrically wrong on <span class="math inline">\(T^2\)</span>?</p></li>
</ol>
<p><br></p>
</section>
<section id="answer-2" class="level3">
<h3 class="anchored" data-anchor-id="answer-2">Answer [2]</h3>
<ol type="1">
<li>What are the explicit identification relations for <span class="math inline">\(T^2\)</span>?</li>
</ol>
<p>To turn the flat square domain <span class="math inline">\([-\pi, \pi)^2\)</span> into a seamless torus, we paste the opposite edges together. Let a point in the domain be denoted by <span class="math inline">\((x, y)\)</span>, where <span class="math inline">\(x = \phi\)</span> and <span class="math inline">\(y = \psi\)</span>.</p>
<p>The two explicit equivalence relations are:</p>
<ol type="1">
<li><strong>Left Edge <span class="math inline">\(\sim\)</span> Right Edge (Horizontal gluing):</strong></li>
</ol>
<p><span class="math display">\[(-\pi, y) \sim (\pi, y) \quad \text{for all } y \in [-\pi, \pi)\]</span></p>
<ol start="2" type="1">
<li><strong>Bottom Edge <span class="math inline">\(\sim\)</span> Top Edge (Vertical gluing):</strong></li>
</ol>
<p><span class="math display">\[(x, -\pi) \sim (x, \pi) \quad \text{for all } x \in [-\pi, \pi)\]</span></p>
<p>Mathematically, this partitions <span class="math inline">\(\mathbb{R}^2\)</span> into equivalence classes where two points <span class="math inline">\((x_1, y_1)\)</span> and <span class="math inline">\((x_2, y_2)\)</span> belong to the same class if and only if:</p>
<p><span class="math display">\[(x_1, y_1) \equiv (x_2 + 2\pi k, y_2 + 2\pi m)\]</span></p>
<p>for any integers <span class="math inline">\(k, m \in \mathbb{Z}\)</span>.</p>
<p><br></p>
<ol start="2" type="1">
<li>What goes wrong if you train a standard Euclidean model on <span class="math inline">\(\mathbb{R}^2\)</span>?</li>
</ol>
<p>If you treat the angles as a flat <span class="math inline">\(\mathbb{R}^2\)</span> plane, the model completely ignores the boundary gluing.</p>
<p>If the model needs to move mass from a source at <span class="math inline">\(\phi = -\pi + \epsilon\)</span> (just inside the left edge) to a target at <span class="math inline">\(\phi = \pi - \epsilon\)</span> (just inside the right edge), here is exactly what goes wrong:</p>
<ul>
<li><strong>Where the vector field points:</strong> The Euclidean vector field points <strong>completely to the right</strong>, pointing across the entire width of the square (<span class="math inline">\(x\)</span>-direction).</li>
<li><strong>How long the vector field is:</strong> The path length is roughly <strong><span class="math inline">\(2\pi\)</span></strong> units long, forcing the model to generate a large velocity to push the mass all the way across the domain.</li>
<li><strong>Why this is geometrically wrong on <span class="math inline">\(T^2\)</span>:</strong> On the actual torus manifold, <span class="math inline">\(-\pi\)</span> and <span class="math inline">\(+\pi\)</span> are the exact same line! The source and target are physically sitting right next to each other. The true shortest path (<strong>the geodesic</strong>) is a tiny step <em>backward</em> across the boundary, with a length of only <span class="math inline">\(2\epsilon\)</span>.</li>
</ul>
<p><strong>The Consequence</strong></p>
<p>Because the flat model doesn’t know the edges meet, it takes the longest possible route around the doughnut instead of the shortest. It tries to push data through the “empty” forbidden zones in the middle of the plot, destroying the accuracy of your density estimation.</p>
<p>One addition worth internalizing: this isn’t just an inference problem. The <strong>training loss</strong> is also corrupted. The regression target <code>(x₁ − x₀)</code> in Euclidean CFM near the ±π boundary is a vector of length <span class="math inline">\(\sim2\pi\)</span> pointing the wrong way — so the network is trained to learn the wrong vector field from the start. The wrapping fix at inference time cannot undo damage done during training.</p>
<hr>
</section>
<section id="stage-2-technical-report-differential-geometry-and-toroidal-manifolds" class="level3">
<h3 class="anchored" data-anchor-id="stage-2-technical-report-differential-geometry-and-toroidal-manifolds">Stage 2 Technical Report: Differential Geometry and Toroidal Manifolds</h3>
<section id="executive-summary-1" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary-1">1. Executive Summary</h4>
<p>In Stage 2, we advanced from basic empirical data cleaning to establishing the formal topological and geometric foundations of our dataset. Recognizing that dihedral angle pairs <span class="math inline">\((\phi, \psi)\)</span> form a periodic, edge-locked continuum, we rigorously analyzed the data as existing on a <strong>2D Torus (<span class="math inline">\(T^2\)</span>)</strong>. We established a customized Riemannian metric system, verified its intrinsic flatness, and implemented wrap-around geodesic tracking. This formal mathematical structure eliminates boundary truncation errors, ensuring our data space is fully compatible with advanced manifold-aware machine learning architectures.</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts-1" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts-1">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. Extrinsic vs.&nbsp;Intrinsic Geometry</strong></p>
<p>When visualizing a torus (<span class="math inline">\(T^2\)</span>) inside a three-dimensional Cartesian space (<span class="math inline">\(\mathbb{R}^3\)</span>), we observe a curved surface with variable thickness. This external wrapping is known as <strong>extrinsic geometry</strong>, where the surface exhibits changing localized curves.</p>
<p>However, when measuring distances natively along the surface canvas without leaving the manifold, the space behaves as a perfectly uniform, unwarped plane with periodic boundary conditions. This is known as <strong>intrinsic geometry</strong>. Our pipeline operates entirely within this intrinsic framework.</p>
<p><br></p>
<p><strong>B. The Parametric Embedding Function (<span class="math inline">\(\mathbb{T}^2 \to \mathbb{R}^3\)</span>)</strong></p>
<p>To visually demonstrate that our dataset lives on a seamless manifold without true edges, we map the flat coordinates to three-dimensional Euclidean space using a parametric transformation grid. Given a major radius <span class="math inline">\(R\)</span> (distance from the center of the hole to the center of the tube) and a minor radius <span class="math inline">\(r\)</span> (the thickness of the tube), any coordinate pair <span class="math inline">\((\phi, \psi)\)</span> is projected into <span class="math inline">\(\mathbb{R}^3\)</span> space via:</p>
<p><span class="math display">\[\begin{aligned}
X &amp;= (R + r \cos \psi) \cos \phi \\
Y &amp;= (R + r \cos \psi) \sin \phi \\
Z &amp;= r \sin \psi
\end{aligned}\]</span></p>
<p><br></p>
<p><strong>C. The Riemannian Metric Tensor and Intrinsic Flatness</strong></p>
<p>A <strong>Riemannian metric tensor</strong> <span class="math inline">\(g\)</span> acts as a matrix blueprint defining how to calculate distances, angles, and areas at any point on a manifold. For a product space of two independent circles (<span class="math inline">\(S^1 \times S^1\)</span>), the metric is inherited directly from the flat Euclidean plane.</p>
<p>The metric tensor <span class="math inline">\(g\)</span> is represented everywhere by a <span class="math inline">\(2 \times 2\)</span> identity matrix (<span class="math inline">\(I_2\)</span>). Because this matrix is constant and completely independent of the position coordinate <span class="math inline">\(p\)</span>, the <strong>Gaussian Curvature (<span class="math inline">\(K\)</span>)</strong> of our manifold is identically zero everywhere (<span class="math inline">\(K = 0\)</span>):</p>
<p><span class="math display">\[g = \begin{bmatrix} 1 &amp; 0 \\ 0 &amp; 1 \end{bmatrix} \implies K = 0\]</span></p>
<p>This mathematical reality confirms that the space is an intrinsically <strong>flat torus</strong>, allowing us to bypass heavy non-linear differential mapping equations.</p>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review-1" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review-1">3. Step-by-Step Pipeline Review</h4>
<p>The workflow spanned four core engineering themes:</p>
<pre><code>[Boundary Edge Identification] ──&gt; [3D Manifold Embedding] ──&gt; [Metric Tensor Auditing] ──&gt; [Geodesic Optimization]</code></pre>
<ol type="1">
<li><p><strong>Boundary Edge Identification:</strong> Formulated a unit-square boundary domain locked strictly over the interval <span class="math inline">\([-\pi, \pi] \times [-\pi, \pi]\)</span>. Implemented directional vector markers to map identified edges, establishing the topological rule that the left vertical perimeter matches the right, and the bottom horizontal perimeter matches the top.</p></li>
<li><p><strong>3D Manifold Embedding:</strong> Configured major and minor structural dimensions (<span class="math inline">\(R=2.0, r=0.7\)</span>) to generate a continuous parametric 3D mesh. Randomly sampled <span class="math inline">\(n = 800\)</span> protein residues and projected them onto the outer surface shell of the torus to visually confirm that our dataset naturally conforms to a continuous toroidal shape.</p></li>
<li><p><strong>Metric Tensor Auditing:</strong> Built a coordinate monitoring check to audit random positions across the data plane. The system validated that at every coordinate, the spatial mapping output exactly matches the identity matrix (<span class="math inline">\(g = I_2\)</span>), programmatically verifying that our machine learning workspace is completely flat and free of localized spatial distortion.</p></li>
<li><p><strong>Geodesic Distance Optimization:</strong> Developed an optimized wrap-around distance algorithm (<span class="math inline">\(\text{arc\_length}\)</span>) that replaces flawed Euclidean distance tracking. For instance, when analyzing two points hugging opposite horizons across the boundary line, standard straight-line calculations and our specialized circular metric recorded contrasting values:</p></li>
</ol>
<p><span class="math display">\[\begin{aligned}
d_{\text{Euclidean}} &amp;= \sqrt{(\phi_q - \phi_p)^2 + (\psi_q - \psi_p)^2} \approx 6.0832 \quad \text{(Incorrect)} \\
d_{\text{Toroidal}} &amp;= \left\| \left( (q - p + \pi) \pmod{2\pi} \right) - \pi \right\|_2 = 0.2000 \quad \text{(Correct)}
\end{aligned}\]</span></p>
<p><br></p>
</section>
<section id="key-learnings-1" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-1">4. Key Learnings</h4>
<ul>
<li><p><strong>Geodesics are Linear:</strong> Because our working space has a Gaussian curvature of <span class="math inline">\(K=0\)</span>, the absolute shortest paths (<strong>geodesics</strong>) between data clusters behave as simple straight lines that wrap around the boundaries.</p></li>
<li><p><strong>Projections are Simplified:</strong> The standard geometric transformations used in deep learning on manifolds—specifically the <strong>Exponential Map</strong> (<span class="math inline">\(\text{exp\_map}\)</span>, which projects a directional vector onto the surface) and the <strong>Logarithm Map</strong> (<span class="math inline">\(\text{log\_map}\)</span>, which extracts a displacement vector between two surface points)—reduce to basic addition and wrapped subtraction:</p></li>
</ul>
<p><span class="math display">\[\begin{aligned}
\text{exp\_map}(p, v) &amp;= (p + v) \pmod{2\pi} \\
\text{log\_map}(p, q) &amp;= \left( (q - p + \pi) \pmod{2\pi} \right) - \pi
\end{aligned}\]</span></p>
<p><br></p>
<p>By establishing a flat toroidal metric space, our pipeline is mathematically equipped to handle distance calculations and spatial variations without experiencing disruptive boundary truncation errors.</p>
<hr>
</section>
</section>
<section id="stage-3---exponential-and-logarithm-maps-on-t_2" class="level3">
<h3 class="anchored" data-anchor-id="stage-3---exponential-and-logarithm-maps-on-t_2">Stage 3 - Exponential and Logarithm Maps on <span class="math inline">\(T_2\)</span></h3>
<p><strong>What are we building?</strong></p>
<p>We’re implementing the two core geometric operations that make every downstream component Riemannian: <code>exp_map(p, v)</code> moves from point <code>p</code> along tangent vector <code>v</code> and lands back on T²; <code>log_map(p, q)</code> finds the tangent vector at <code>p</code> pointing toward <code>q</code> along the shortest geodesic.</p>
<p>These replace Euclidean addition and subtraction throughout the entire pipeline.</p>
<p><br></p>
</section>
<section id="questions-3" class="level3">
<h3 class="anchored" data-anchor-id="questions-3">Questions [3]</h3>
<p>Derive <code>log_map(p, q)</code> on <span class="math inline">\(S^1\)</span> explicitly.</p>
<p>Given two angles <code>p, q ∈ [−π, π)</code>, write the closed-form expression for the signed shortest arc from <code>p</code> to <code>q</code>. Then answer:</p>
<ol type="1">
<li>What is the output of naive subtraction <code>q − p</code> when <code>p = −2.9</code> and <code>q = 2.9</code>? What is the correct geodesic displacement, and what is its sign?</li>
<li>What single mathematical operation transforms <code>q − p</code> into the correct wrapped displacement, and why does it work algebraically?</li>
</ol>
<p>Show the arithmetic, not just the formula.</p>
<p><br></p>
</section>
<section id="answer-3" class="level3">
<h3 class="anchored" data-anchor-id="answer-3">Answer [3]</h3>
<p><strong>Derivation of <span class="math inline">\(\text{log}_map(p, q)\)</span> on <span class="math inline">\(S^1\)</span></strong></p>
<p>To find the shortest signed distance between two angles <span class="math inline">\(p, q \in [-\pi, \pi)\)</span>, we start with the naive Euclidean difference <span class="math inline">\(\Delta \theta = q - p\)</span>. To force this difference to respect the wrapping of the circle, we project it into the range <span class="math inline">\([-\pi, \pi)\)</span>.</p>
<p>The closed-form expression for the <span class="math inline">\(S^1\)</span> logarithm map is:</p>
<p><span class="math display">\[\text{log}_p(q) = ((q - p + \pi) \pmod{2\pi}) - \pi\]</span></p>
<p><br></p>
<ol type="1">
<li>Naive Subtraction vs.&nbsp;Geodesic Displacement</li>
</ol>
<p>Let <span class="math inline">\(p = -2.9\)</span> and <span class="math inline">\(q = 2.9\)</span>.</p>
<ul>
<li><strong>Naive Subtraction:</strong></li>
</ul>
<p><span class="math display">\[q - p = 2.9 - (-2.9) = 5.8\]</span></p>
<p><em>The naive model thinks it needs to travel <span class="math inline">\(+5.8\)</span> radians all the way around the long way.</em> * <strong>Correct Geodesic Displacement:</strong> The true shortest path is across the <span class="math inline">\([-\pi, \pi)\)</span> boundary line.</p>
<p><span class="math display">\[\text{Displacement} = -0.4832 \text{ radians (approx)}\]</span></p>
<ul>
<li><strong>Sign:</strong> <strong>Negative (<span class="math inline">\(-\)</span>)</strong>. It is shorter to step <em>backward</em> across the boundary than forward through the center.</li>
</ul>
<p><br></p>
<ol start="2" type="1">
<li>The Transforming Mathematical Operation</li>
</ol>
<p>The single operation that fixes this is the <strong>modulo <span class="math inline">\(2\pi\)</span> operation (with a phase shift)</strong>, often implemented cleanly in programming as a wrapping function or using a modified modulo:</p>
<p><span class="math display">\[\text{wrap}(q - p) = \text{mod}(q - p + \pi, 2\pi) - \pi\]</span></p>
<p>Why it works algebraically:</p>
<p>Adding <span class="math inline">\(\pi\)</span> shifts the domain so that the discontinuity moves away from the center. Applying <span class="math inline">\(\pmod{2\pi}\)</span> maps any large or out-of-bounds angle back into a standard <span class="math inline">\(2\pi\)</span> window <span class="math inline">\([0, 2\pi)\)</span>. Finally, subtracting <span class="math inline">\(\pi\)</span> shifts the window back to centering around zero, <span class="math inline">\([-\pi, \pi)\)</span>. This automatically selects the value with the smallest absolute magnitude, which mathematically corresponds to the shortest path on a circle.</p>
<p><br></p>
<ol start="3" type="1">
<li>Step-by-Step Arithmetic</li>
</ol>
<p>Let’s plug <span class="math inline">\(p = -2.9\)</span> and <span class="math inline">\(q = 2.9\)</span> into the formula to see it work:</p>
<ol type="1">
<li><strong>Find raw difference:</strong></li>
</ol>
<p><span class="math display">\[q - p = 2.9 - (-2.9) = 5.8\]</span></p>
<ol start="2" type="1">
<li><strong>Shift by <span class="math inline">\(+\pi\)</span></strong> (using <span class="math inline">\(\pi \approx 3.14159\)</span>):</li>
</ol>
<p><span class="math display">\[5.8 + 3.14159 = 8.94159\]</span></p>
<ol start="3" type="1">
<li><strong>Apply modulo <span class="math inline">\(2\pi\)</span></strong> (divide by <span class="math inline">\(2\pi \approx 6.28319\)</span> and take the remainder):</li>
</ol>
<p><span class="math display">\[\frac{8.94159}{6.28319} \approx 1.423 \implies \text{Remainder} = 8.94159 - (1 \times 6.28319) = 2.6584\]</span></p>
<ol start="4" type="1">
<li><strong>Shift back by <span class="math inline">\(-\pi\)</span></strong>:</li>
</ol>
<p><span class="math display">\[2.6584 - 3.14159 = -0.48319\]</span></p>
<p><strong>Result:</strong> <span class="math inline">\(\text{log}_{-2.9}(2.9) \approx -0.4832\)</span>. The math successfully bypassed the long Euclidean distance of <span class="math inline">\(5.8\)</span> and found the correct, short backward step.</p>
<p>One thing to state explicitly before code: on <span class="math inline">\(T^2 = S^1 \times S^1\)</span>, both <code>exp_map</code> and <code>log_map</code> decompose component-wise. There is no coupling between <span class="math inline">\(\phi\)</span> and <span class="math inline">\(\psi\)</span> because the metric is diagonal. This is a direct consequence of the product structure and flat metric verified in Stage 2.</p>
<hr>
</section>
<section id="stage-3-technical-report-geodesic-navigation-and-vector-fields-on-t2" class="level3">
<h3 class="anchored" data-anchor-id="stage-3-technical-report-geodesic-navigation-and-vector-fields-on-t2">Stage 3 Technical Report: Geodesic Navigation and Vector Fields on <span class="math inline">\(T^2\)</span></h3>
<section id="executive-summary-2" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary-2">1. Executive Summary</h4>
<p>In Stage 3, we transitioned from the static Riemannian structural definitions of Stage 2 to building an active, operational geometric engine on the <strong>Flat Torus (<span class="math inline">\(T^2\)</span>)</strong>. We successfully implemented and stress-tested the twin pillars of manifold navigation: the <strong>Exponential Map (<span class="math inline">\(\text{exp\_map}\)</span>)</strong> and the <strong>Logarithm Map (<span class="math inline">\(\text{log\_map}\)</span>)</strong>. These mathematical operators allow for precise coordinate projection and shortest-path directional tracking across periodic boundaries. By verifying these operations through automated batch round-trips and visual displacement fields across all 50,000 data rows, we have established a robust, numerically stable toolkit ready to handle gradient steps and spatial optimization in downstream machine learning architectures.</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts-2" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts-2">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. The Geodesic Operators: Exponential and Logarithm Maps</strong></p>
<p>In differential geometry, moving across a curved or bounded manifold requires specialized map operations rather than standard flat vector algebra:</p>
<ul>
<li>The <strong>Exponential Map (<span class="math inline">\(\text{exp\_map}_p(v)\)</span>)</strong> takes a starting base point <span class="math inline">\(p\)</span> on the manifold and a directional velocity vector <span class="math inline">\(v\)</span> residing in the localized tangent space (<span class="math inline">\(v \in T_p T^2\)</span>), projecting forward along a straight-line path (<strong>geodesic</strong>) to calculate a valid destination coordinate.</li>
<li>The <strong>Logarithm Map (<span class="math inline">\(\text{log\_map}(p, q)\)</span>)</strong> acts as the exact inverse, calculating the precise tangent vector <span class="math inline">\(v\)</span> required to travel from a starting position <span class="math inline">\(p\)</span> to a destination target <span class="math inline">\(q\)</span> along the absolute shortest possible path.</li>
</ul>
<p><br></p>
<p><strong>B. The Modulo Shift Transformation</strong></p>
<p>Because we proved in Stage 2 that our torus inherits a completely uniform and flat product metric matrix (<span class="math inline">\(g = I_2\)</span>, Gaussian Curvature <span class="math inline">\(K = 0\)</span>), these complex calculus transformations simplify to basic component-wise vector arithmetic combined with a periodic boundary modulo wrap.</p>
<p>To map any arbitrary directional translation onto the continuous interval <span class="math inline">\([-\pi, \pi)\)</span> without experiencing truncation errors, we utilize the wrapped difference formula:</p>
<p><span class="math display">\[\text{wrap}(\Delta) = \left( (\Delta + \pi) \pmod{2\pi} \right) - \pi\]</span></p>
<p>Applying this component-wise across independent <span class="math inline">\(\phi\)</span> and <span class="math inline">\(\psi\)</span> coordinates guarantees that all computed vectors and coordinate updates automatically respect the topological boundaries.</p>
<p><br></p>
<p><strong>C. Topological Cutoffs and Boundary Maximums</strong></p>
<p>On a circle or continuous loop of total circumference <span class="math inline">\(2\pi\)</span>, a shortest-path trajectory can never exceed half the circumference (<span class="math inline">\(\pi \approx 3.1416\)</span>). If a target sits further away than <span class="math inline">\(\pi\)</span>, the true geodesic instantly switches directions to exploit the boundary shortcut. Consequently:</p>
<ul>
<li>The maximum absolute length of any individual vector component (<span class="math inline">\(\Delta\phi\)</span> or <span class="math inline">\(\Delta\psi\)</span>) is strictly bounded by <span class="math inline">\(\pi\)</span>.</li>
<li>In our two-dimensional coordinate space, the maximum total straight-line distance (<strong>joint Euclidean norm</strong>) occurs along a perfect diagonal shortcut toward the furthest opposite corner. Governed by the Pythagorean theorem, this maximum joint length is defined as:</li>
</ul>
<p><span class="math display">\[\|v\|_{\text{max}} = \sqrt{\pi^2 + \pi^2} = \pi\sqrt{2} \approx 4.4429\]</span></p>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review-2" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review-2">3. Step-by-Step Pipeline Review</h4>
<p>The workflow spanned four core engineering themes:</p>
<pre><code>[Forward Projection Map] ──&gt; [Inverse Geodesic Vectoring] ──&gt; [Batch Scaling &amp; Limits] ──&gt; [Vector Field Auditing]</code></pre>
<ol type="1">
<li><strong>Forward Projection Mapping (<span class="math inline">\(\text{exp\_map}\)</span>):</strong> Formulated the forward movement tracking function using wrapped addition logic. Tested the operator by placing a coordinate near the horizon line (<span class="math inline">\(\phi_p = 2.9\)</span>) and applying a positive shift (<span class="math inline">\(v_{\phi} = 0.5\)</span>). While standard addition would yield an invalid out-of-bounds coordinate (<span class="math inline">\(3.4\)</span>), our system pulled the trajectory back onto the continuous torus grid safely:</li>
</ol>
<p><span class="math display">\[\text{exp\_map}\left(\begin{bmatrix} 2.9 \\ 1.0 \end{bmatrix}, \begin{bmatrix} 0.5 \\ 0.5 \end{bmatrix}\right) = \begin{bmatrix} -2.8832 \\ 1.5000 \end{bmatrix}\]</span></p>
<ol start="2" type="1">
<li><strong>Inverse Geodesic Vectoring (<span class="math inline">\(\text{log\_map}\)</span>):</strong> Developed the inverse tracking operator to isolate directional trajectories between points. When evaluating a point hugging the left edge (<span class="math inline">\(p_{\phi} = -2.9\)</span>) and a target hugging the right edge (<span class="math inline">\(q_{\phi} = 2.9\)</span>), the engine bypassed the long, naive flat path (length <span class="math inline">\(5.8000\)</span>) to isolate the true, boundary-crossing shortest path:</li>
</ol>
<p><span class="math display">\[\text{log\_map}\left(\begin{bmatrix} -2.9 \\ 0.0 \end{bmatrix}, \begin{bmatrix} 2.9 \\ 0.0 \end{bmatrix}\right) = \begin{bmatrix} -0.4832 \\ 0.0000 \end{bmatrix} \quad (\text{Length} = 0.4832)\]</span></p>
<ol start="3" type="1">
<li><strong>Batch Scaling &amp; Boundary Audits:</strong> Scale-tested both operators simultaneously by pairing all 50,000 rows against a row-shifted matrix counterpart. The batch audit confirmed that our maximal component shift settled exactly at <span class="math inline">\(\pi \approx 3.1416\)</span>, and the maximal joint norm reached <span class="math inline">\(4.4287\)</span>, safely under the maximum structural diagonal threshold of <span class="math inline">\(4.4429\)</span>. The batch validation completed with zero coordinate leakage, confirming perfect mathematical identity recovery:</li>
</ol>
<p><span class="math display">\[\text{exp\_map}\big(P, \text{log\_map}(P, Q)\big) \equiv Q \quad \forall \, 50,000 \text{ pairs}\]</span></p>
<ol start="4" type="1">
<li><strong>Vector Field Auditing:</strong> Generated a comprehensive vector displacement grid consisting of 400 uniform test points tracking toward a target placed near the upper-right corner (<span class="math inline">\(2.8, 2.8\)</span>). Renders from the completed quiver plot verified that arrows situated close to the boundaries pointed outward into the edge lines rather than turning backward, visually proving that the trajectory field correctly identifies boundary wrap-arounds.</li>
</ol>
<p><br></p>
</section>
<section id="key-learnings-2" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-2">4. Key Learnings</h4>
<ul>
<li><p><strong>Inversion is Seamless:</strong> The exponential and logarithmic mappings are robustly consistent. The system can freely map points to directional vector fields and back again across the full dataset without accumulating precision loss or causing coordinate drift.</p></li>
<li><p><strong>Vector Fields Flow Continuously:</strong> The fluid directional alignment confirmed by the quiver plot demonstrates that gradient vectors computed on this manifold will remain stable and continuous, avoiding disruptive spikes or artificial edge blockages.</p></li>
</ul>
<p><br></p>
<p>Our data pipeline is no longer just a collection of static points; it is now an active, topologically integrated geometric workspace. The system is structurally primed to handle manifold-aware distance metrics, continuous trajectory modeling, and neural network optimization routines.</p>
<hr>
</section>
</section>
<section id="stage-4---geodesic-interpolation-on-t2" class="level3">
<h3 class="anchored" data-anchor-id="stage-4---geodesic-interpolation-on-t2">Stage 4 - Geodesic Interpolation on <span class="math inline">\(T^2\)</span></h3>
<p><strong>What are we building?</strong></p>
<p>We’re implementing <code>geodesic_interp(p0, p1, t)</code> = <code>exp_map(p0, t · log_map(p0, p1))</code> and using it to interpolate between a β-sheet and an α-helix conformation. Every intermediate point must lie on <span class="math inline">\(T^2\)</span>.</p>
<p><br></p>
</section>
<section id="questions-4" class="level3">
<h3 class="anchored" data-anchor-id="questions-4">Questions [4]</h3>
<p>Take these two specific points:</p>
<ul>
<li><span class="math inline">\(p_0 = (-0.1, -0.1)\)</span> — near the origin</li>
<li><span class="math inline">\(p_1 = (3.0, -3.0)\)</span> — near the <span class="math inline">\((+\pi, -\pi)\)</span> corner</li>
</ul>
<p>Compute <code>geodesic_interp(p0, p1, t=0.5)</code> by hand using your <code>log_map</code> and <code>exp_map</code> formulas. Show each arithmetic step. Then compute the naïve midpoint <code>0.5·p0 + 0.5·p1</code> and state whether it differs — and if so, why.</p>
<p><br></p>
</section>
<section id="answer-4" class="level3">
<h3 class="anchored" data-anchor-id="answer-4">Answer [4]</h3>
<p>To solve this, we will use the <span class="math inline">\(S^1\)</span> operations independently for each coordinate (since <span class="math inline">\(T^2 = S^1 \times S^1\)</span>).</p>
<p>Recall the wrapping formulas from Stage 3:</p>
<ul>
<li><span class="math inline">\(\text{log}_p(q) = \text{mod}(q - p + \pi, 2\pi) - \pi\)</span></li>
<li><span class="math inline">\(\text{exp}_p(v) = \text{mod}(p + v + \pi, 2\pi) - \pi\)</span></li>
</ul>
<p><em>(We use <span class="math inline">\(\pi \approx 3.14159\)</span> and <span class="math inline">\(2\pi \approx 6.28319\)</span>.)</em></p>
<p><br></p>
<ol type="1">
<li>Step-by-Step Geodesic Interpolation (<span class="math inline">\(t = 0.5\)</span>)</li>
</ol>
<p>Given <span class="math inline">\(p_0 = (-0.1, -0.1)\)</span> and <span class="math inline">\(p_1 = (3.0, -3.0)\)</span>.</p>
<p><strong>Step A: Calculate <span class="math inline">\(\text{log}_{p_0}(p_1)\)</span> (The Shortest Vector)</strong></p>
<ul>
<li><strong>For the <span class="math inline">\(x\)</span>-coordinate (<span class="math inline">\(\phi\)</span>):</strong>
<ol type="1">
<li>Raw difference: <span class="math inline">\(q - p = 3.0 - (-0.1) = 3.1\)</span></li>
<li>Shift: <span class="math inline">\(3.1 + 3.14159 = 6.24159\)</span></li>
<li>Modulo <span class="math inline">\(2\pi\)</span>: <span class="math inline">\(\text{mod}(6.24159, 6.28319) = 6.24159\)</span> (since it’s less than <span class="math inline">\(2\pi\)</span>)</li>
<li>Shift back: <span class="math inline">\(6.24159 - 3.14159 = 3.1\)</span> <em>Vector <span class="math inline">\(v_x = 3.1\)</span></em></li>
</ol></li>
<li><strong>For the <span class="math inline">\(y\)</span>-coordinate (<span class="math inline">\(\psi\)</span>):</strong>
<ol type="1">
<li>Raw difference: <span class="math inline">\(q - p = -3.0 - (-0.1) = -2.9\)</span></li>
<li>Shift: <span class="math inline">\(-2.9 + 3.14159 = 0.24159\)</span></li>
<li>Modulo <span class="math inline">\(2\pi\)</span>: <span class="math inline">\(\text{mod}(0.24159, 6.28319) = 0.24159\)</span></li>
<li>Shift back: <span class="math inline">\(0.24159 - 3.14159 = -2.9\)</span> <em>Vector <span class="math inline">\(v_y = -2.9\)</span></em></li>
</ol></li>
</ul>
<p>So, <span class="math inline">\(\text{log}_{p_0}(p_1) = (3.1, -2.9)\)</span>.</p>
<p><br></p>
<p><strong>Step B: Scale the Vector by <span class="math inline">\(t = 0.5\)</span></strong></p>
<p><span class="math display">\[t \cdot \text{log}_{p_0}(p_1) = 0.5 \cdot (3.1, -2.9) = (1.55, -1.45)\]</span></p>
<p><br></p>
<p><strong>Step C: Apply the <span class="math inline">\(\text{exp}_{p_0}\)</span> Map to find the Midpoint</strong></p>
<ul>
<li><strong>For the <span class="math inline">\(x\)</span>-coordinate (<span class="math inline">\(\phi\)</span>):</strong>
<ol type="1">
<li>Raw move: <span class="math inline">\(p + v = -0.1 + 1.55 = 1.45\)</span></li>
<li>Wrap into <span class="math inline">\([-\pi, \pi)\)</span>: <span class="math inline">\(\text{mod}(1.45 + 3.14159, 6.28319) - 3.14159 = 1.45\)</span></li>
</ol></li>
<li><strong>For the <span class="math inline">\(y\)</span>-coordinate (<span class="math inline">\(\psi\)</span>):</strong>
<ol type="1">
<li>Raw move: <span class="math inline">\(p + v = -0.1 + (-1.45) = -1.55\)</span></li>
<li>Wrap into <span class="math inline">\([-\pi, \pi)\)</span>: <span class="math inline">\(\text{mod}(-1.55 + 3.14159, 6.28319) - 3.14159 = -1.55\)</span></li>
</ol></li>
</ul>
<p><strong>Geodesic Midpoint:</strong> <span class="math inline">\((1.45, -1.55)\)</span></p>
<p><br></p>
<ol start="2" type="1">
<li>Naive Euclidean Midpoint Calculation</li>
</ol>
<p><span class="math display">\[\text{Naive Midpoint} = 0.5 \cdot (-0.1, -0.1) + 0.5 \cdot (3.0, -3.0)\]</span></p>
<p><span class="math display">\[\text{Naive Midpoint} = (-0.05, -0.05) + (1.5, -1.5) = (1.45, -1.55)\]</span></p>
<p><strong>Naive Midpoint:</strong> <span class="math inline">\((1.45, -1.55)\)</span></p>
<p><br></p>
<p><strong>Do they differ? Why or why not?</strong></p>
<p>In this specific case, <strong>they do not differ</strong>. Both methods yield exactly <span class="math inline">\((1.45, -1.55)\)</span>.</p>
<p><strong>Why they are identical here:</strong></p>
<p>The naive midpoint and the geodesic midpoint only differ when the shortest path between two points wraps across a boundary line.</p>
<p>For these specific coordinates, the shortest distance in the <span class="math inline">\(x\)</span>-direction (<span class="math inline">\(3.1\)</span> radians) and the <span class="math inline">\(y\)</span>-direction (<span class="math inline">\(-2.9\)</span> radians) are both strictly less than <span class="math inline">\(\pi\)</span> (<span class="math inline">\(\approx 3.14159\)</span>) in absolute magnitude. Because the shortest path naturally stays within the flat inner clearing of the square domain without crossing the edge, the manifold’s wrapping mechanism is never triggered.</p>
<p>If <span class="math inline">\(p_1\)</span> had been set to <span class="math inline">\((3.2, -3.2)\)</span>, the shortest path for <span class="math inline">\(x\)</span> would have looped backward across the boundary, causing the naive and geodesic midpoints to diverge completely.</p>
<hr>
</section>
<section id="stage-4-technical-report-geodesic-interpolation-and-conformational-pathways-on-t2" class="level3">
<h3 class="anchored" data-anchor-id="stage-4-technical-report-geodesic-interpolation-and-conformational-pathways-on-t2">Stage 4 Technical Report: Geodesic Interpolation and Conformational Pathways on <span class="math inline">\(T^2\)</span></h3>
<section id="executive-summary-3" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary-3">1. Executive Summary</h4>
<p>In Stage 4, we advanced from calculating static directional vectors to modeling continuous, multi-frame trajectories across the <strong>Flat Torus (<span class="math inline">\(T^2\)</span>)</strong>. We engineered a <strong>Geodesic Interpolation (<span class="math inline">\(\text{geodesic\_interp}\)</span>)</strong> engine capable of plotting mathematically optimal, boundary-aware pathways between distant coordinate states. This system was validated using standard secondary structure markers from structural biology—specifically transitioning from a <strong><span class="math inline">\(\beta\)</span>-sheet configuration</strong> to an <strong><span class="math inline">\(\alpha\)</span>-helix configuration</strong>.</p>
<p>By evaluating these paths against standard flat-plane linear methods, we confirmed that our manifold-aware engine matches baseline Euclidean math in localized zones while successfully avoiding devastating directional errors across boundary frontiers. This establishes a reliable pathway generator for molecular dynamics emulations, structural morphing, and generative backbone design.</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts-3" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts-3">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. Geodesic Interpolation Equation</strong></p>
<p>Interpolation on a Riemannian manifold cannot be calculated using standard linear blending because a straight coordinate line on a flat map fails to account for periodic boundary wrap-arounds. Instead, a path must follow a <strong>geodesic</strong>—the true path of shortest distance across the surface.</p>
<p>Mathematically, a geodesic pathway <span class="math inline">\(\gamma(t)\)</span> traveling from a starting point <span class="math inline">\(p_0\)</span> to an endpoint <span class="math inline">\(p_1\)</span> over a normalized timeline <span class="math inline">\(t \in [0, 1]\)</span> is constructed by scaling the logarithmic map vector and projecting it back onto the manifold surface via the exponential map:</p>
<p><span class="math display">\[\gamma(t) = \text{exp\_map}\big(p_0, \, t \cdot \text{log\_map}(p_0, p_1)\big)\]</span></p>
<ul>
<li>When <span class="math inline">\(t = 0\)</span>: <span class="math inline">\(\gamma(0) = \text{exp\_map}(p_0, 0) = p_0\)</span> (exact origin match).</li>
<li>When <span class="math inline">\(t = 1\)</span>: <span class="math inline">\(\gamma(1) = \text{exp\_map}(p_0, \text{log\_map}(p_0, p_1)) = p_1\)</span> (exact destination match).</li>
<li>When <span class="math inline">\(0 &lt; t &lt; 1\)</span>: <span class="math inline">\(\gamma(t)\)</span> maps the smooth intermediate coordinate frames along the true shortest shortcut.</li>
</ul>
<p><br></p>
<p><strong>B. The Toroidal Cutoff Condition</strong></p>
<p>Because our flat torus is formed by two independent periodic circles (<span class="math inline">\(S^1 \times S^1\)</span>), the necessity of a boundary-crossing shortcut is dictated independently for the horizontal (<span class="math inline">\(\phi\)</span>) and vertical (<span class="math inline">\(\psi\)</span>) coordinate axes.</p>
<p>The threshold where standard flat calculation and toroidal calculation diverge is exactly half the circumference of the loop, or <span class="math inline">\(180^\circ\)</span> (<span class="math inline">\(\pi\)</span> radians). For any displacement vector <span class="math inline">\(v = \text{log\_map}(p_0, p_1)\)</span>:</p>
<p><span class="math display">\[\begin{aligned}
\text{If } |v_\phi| &lt; 180^\circ \text{ and } |v_\psi| &lt; 180^\circ &amp;\implies \text{No wrap-around occurs } (\text{Geodesic} = \text{Naive Linear}) \\
\text{If } |v_\phi| \ge 180^\circ \text{ or } |v_\psi| \ge 180^\circ &amp;\implies \text{Wrap-around occurs } (\text{Geodesic} \neq \text{Naive Linear})
\end{aligned}\]</span></p>
<p>When a component exceeds <span class="math inline">\(180^\circ\)</span>, naive linear math takes the long way around across the open center of the map, resulting in completely inverted directional trajectory steps.</p>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review-3" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review-3">3. Step-by-Step Pipeline Review</h4>
<p>The workflow spanned four core engineering themes:</p>
<pre><code>[Path Engine Formulation] ──&gt; [Boundary Divergence Auditing] ──&gt; [Biological Structural Tracking] ──&gt; [Manifold Overlays]</code></pre>
<ol type="1">
<li><p><strong>Path Engine Formulation:</strong> Coded the <code>geodesic_interp</code> function by feeding the localized tangent vector output of our established <code>log_map</code> directly into the coordinate projection engine of our <code>exp_map</code>.</p></li>
<li><p><strong>Boundary Divergence Auditing:</strong> Stress-tested the engine against two different configurations. In the local zone, the torus math and flat math matched perfectly. However, when the endpoint was pushed past the map horizon (<span class="math inline">\(p_{1\text{\_wrap}} = [3.2, -3.2]\)</span>), the paths split completely. The naive path calculated an incorrect center coordinate, while our displacement vector correctly tracked a leftward trajectory shortcut:</p></li>
</ol>
<p><span class="math display">\[\text{Naive Step Direction} = \begin{bmatrix} +1.65 \\ -1.55 \end{bmatrix} \quad \longleftrightarrow \quad \text{Geodesic Step Direction} = \begin{bmatrix} -1.49 \\ -1.55 \end{bmatrix}\]</span></p>
<ol start="3" type="1">
<li><p><strong>Biological Structural Tracking:</strong> Generated a smooth 10-frame transition path modeling a protein backbone morphing from a standard <span class="math inline">\(\beta\)</span>-sheet (<span class="math inline">\([-120^\circ, 130^\circ]\)</span>) into an <span class="math inline">\(\alpha\)</span>-helix (<span class="math inline">\([-60^\circ, -45^\circ]\)</span>). The tracking table verified perfectly smooth angular changes with zero coordinate leakage across all frames.</p></li>
<li><p><strong>Manifold Plot Overlays:</strong> Superimposed the generated transition paths directly over the 50,000 empirical ground-truth data points on a custom Ramachandran scatter plot. The plot confirmed that because both structural components fell safely below the <span class="math inline">\(180^\circ\)</span> boundary cutoff (<span class="math inline">\(\Delta\phi = 60^\circ, \Delta\psi = -175^\circ\)</span>), the paths converged cleanly without triggering a wrap-around, cutting directly through naturally allowed structural zones where real protein backbones flex.</p></li>
</ol>
<p><br></p>
</section>
<section id="key-learnings-3" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-3">4. Key Learnings</h4>
<ul>
<li><p><strong>Manifold Invariance Restored:</strong> We learned that geodesic interpolation preserves the structural rules of the manifold space across every intermediate step. Every frame generated along the trajectory path is mathematically locked inside the legal interval boundaries (<span class="math inline">\([-\pi, \pi)\)</span>), eliminating coordinate drift during transitions.</p></li>
<li><p><strong>Naive Averaging Breaks Down Globally:</strong> We proved that standard linear algebra (<span class="math inline">\(0.5p_0 + 0.5p_1\)</span>) is globally invalid on periodic topologies. While it functions fine in small, local neighborhoods, it produces entirely wrong directional coordinates when a path steps over a boundary boundary horizon.</p></li>
<li><p><strong>The System and Data Align:</strong> Evaluating real-world protein conformations confirmed that our mathematical operations map directly to logical molecular structural modifications. The continuous and unwarped trajectory field confirms that optimization pathways generated on this flat torus are physically stable and computationally optimized.</p></li>
</ul>
<hr>
</section>
</section>
<section id="stage-5---conditional-flow-matching-in-mathbbr2-warm-up" class="level3">
<h3 class="anchored" data-anchor-id="stage-5---conditional-flow-matching-in-mathbbr2-warm-up">Stage 5 - Conditional Flow Matching in <span class="math inline">\(\mathbb{R}^2\)</span> (Warm-Up)</h3>
<p><strong>What are we building?</strong></p>
<p>We’re implementing standard Euclidean CFM as a controlled baseline before touching the Riemannian version. The network, optimizer, and training loop built here will be reused exactly in Stage 6 — the only things that change are the loss and the integrator.</p>
<p><br></p>
</section>
<section id="questions-5" class="level3">
<h3 class="anchored" data-anchor-id="questions-5">Questions [5]</h3>
<p>Write the CFM training objective from memory. Given: - Source sample <span class="math inline">\(x_0 \sim \mu\)</span> (uniform on <span class="math inline">\([- \pi, \pi)^2\)</span>) - Target sample <span class="math inline">\(x_1 \sim \nu\)</span> (empirical torsion angles) - Interpolation <span class="math inline">\(x_t = (1-t)x_0 + t \cdot x_1\)</span> - Network <span class="math inline">\(v_\theta(x_t, t)\)</span></p>
<p>Answer these three questions:</p>
<ol type="1">
<li><p>What is the regression target that <span class="math inline">\(v_\theta(x_t, t)\)</span> is trained to match?</p></li>
<li><p>Write the loss function <span class="math inline">\(L(\theta)\)</span> as an expectation.</p></li>
<li><p>Why does minimizing this loss produce a valid generative model — specifically, what does the trained <span class="math inline">\(v_\theta\)</span> define, and how do you use it at inference to generate a sample?</p></li>
</ol>
<p><br></p>
</section>
<section id="answer-5" class="level3">
<h3 class="anchored" data-anchor-id="answer-5">Answer [5]</h3>
<ol type="1">
<li>What is the regression target for <span class="math inline">\(v_\theta(x_t, t)\)</span>?</li>
</ol>
<p>In standard Euclidean CFM, the regression target is the constant velocity vector that points in a straight line from the source sample <span class="math inline">\(x_0\)</span> to the target sample <span class="math inline">\(x_1\)</span>.</p>
<p>By taking the time derivative of the interpolation formula <span class="math inline">\(x_t = (1-t)x_0 + t \cdot x_1\)</span>, we get the target velocity:</p>
<p><span class="math display">\[\text{Target} = x_1 - x_0\]</span></p>
<p><br></p>
<ol start="2" type="1">
<li>The CFM Loss Function <span class="math inline">\(L(\theta)\)</span> as an Expectation</li>
</ol>
<p>The loss function minimizes the mean squared error between the network’s predicted velocity field and the true straight-line velocity target:</p>
<p><span class="math display">\[L(\theta) = \mathbb{E}_{t \sim \mathcal{U}(0,1), \, x_0 \sim \mu, \, x_1 \sim \nu} \left[ \| v_\theta(x_t, t) - (x_1 - x_0) \|^2 \right]\]</span></p>
<p>where <span class="math inline">\(t\)</span> is sampled uniformly between 0 and 1, <span class="math inline">\(x_0\)</span> is your noise sample, and <span class="math inline">\(x_1\)</span> is your real protein torsion angle sample.</p>
<p><br></p>
<ol start="3" type="1">
<li>Why does this produce a valid generative model, and how do you use it?</li>
</ol>
<p><strong>What the trained <span class="math inline">\(v_\theta\)</span> defines:</strong></p>
<p>Minimizing this loss forces the neural network to learn an <strong>average vector field</strong>. While any single <span class="math inline">\(x_0\)</span> is trained to go directly to a single <span class="math inline">\(x_1\)</span>, many paths will cross at the exact same <span class="math inline">\(x_t\)</span> location during training. The network resolves this by averaging all the overlapping trajectories. This aggregate velocity field successfully defines a continuous path (an Ordinary Differential Equation, or ODE) that safely guides the <em>entire probability distribution</em> <span class="math inline">\(\mu\)</span> into the target distribution <span class="math inline">\(\nu\)</span>.</p>
<section id="how-to-use-it-at-inference-to-generate-a-sample" class="level4">
<h4 class="anchored" data-anchor-id="how-to-use-it-at-inference-to-generate-a-sample">How to use it at inference to generate a sample:</h4>
<p>To generate a brand-new pair of protein torsion angles <span class="math inline">\((\phi, \psi)\)</span> at inference, you follow these steps:</p>
<ol type="1">
<li><strong>Sample Noise:</strong> Draw a random starting point <span class="math inline">\(x_0\)</span> from the uniform source distribution <span class="math inline">\(\mu\)</span> on <span class="math inline">\([-\pi, \pi)^2\)</span>.</li>
<li><strong>Set up an ODE Solver:</strong> Feed the starting point <span class="math inline">\(x_0\)</span> and the trained network <span class="math inline">\(v_\theta(x, t)\)</span> into a numerical integrator (like Euler’s method or a Runge-Kutta solver).</li>
<li><strong>Integrate Time:</strong> Compute the path from <span class="math inline">\(t = 0\)</span> to <span class="math inline">\(t = 1\)</span> by taking small steps. At each step, the model calculates the current velocity, and you move the point slightly forward:</li>
</ol>
<p><span class="math display">\[x_{t + \Delta t} \approx x_t + v_\theta(x_t, t) \cdot \Delta t\]</span></p>
<ol start="4" type="1">
<li><strong>Collect the Sample:</strong> The final position at <span class="math inline">\(t = 1\)</span> is your newly generated sample, safely distributed according to the learned Ramachandran target distribution.</li>
</ol>
<p><br></p>
<p>Note: One precision worth adding to Point 3: the averaged vector field doesn’t just “happen to work” — it provably transports <span class="math inline">\(\mu\)</span> to <span class="math inline">\(\nu\)</span> because it matches the marginal vector field of the probability path <span class="math inline">\(p_t = (1-t)\mu + t\nu\)</span> at every <span class="math inline">\(t\)</span>. The MSE loss is minimized exactly when <span class="math inline">\(v_\theta\)</span> equals this marginal field, which is the CFM theorem (Lipman et al.&nbsp;2022).</p>
<hr>
</section>
</section>
<section id="stage-5-technical-report-neural-flow-matching-and-flat-euclidean-baselines" class="level3">
<h3 class="anchored" data-anchor-id="stage-5-technical-report-neural-flow-matching-and-flat-euclidean-baselines">Stage 5 Technical Report: Neural Flow Matching and Flat Euclidean Baselines</h3>
<section id="executive-summary-4" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary-4">1. Executive Summary</h4>
<p>In Stage 5, we progressed from purely algorithmic manifold tools to constructing an operational deep generative model on the <strong>Flat Torus (<span class="math inline">\(T^2\)</span>)</strong>. We engineered a time-dependent deep neural network architecture to act as a parametric vector field engine. Using this network, we established a complete <strong>Conditional Flow Matching (CFM)</strong> training and sampling pipeline.</p>
<p>To create a rigorous benchmark, this pipeline was deliberately executed using flat <strong>Euclidean (<span class="math inline">\(\mathbb{R}^2\)</span>)</strong> definitions for both the loss regression and the Ordinary Differential Equation (ODE) integration. The resulting synthetic coordinates were cross-referenced against our 50,000 real-world protein residue points. This baseline experiment empirically demonstrated that ignoring topological periodic boundaries forces the network to fight artificial boundary cliffs, leading to poor structural learning and low biological generation efficiency (<span class="math inline">\(35.9\%\)</span>).</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts-4" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts-4">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. Continuous Trigonometric Input Encoding</strong></p>
<p>Neural networks are continuous universal function approximators that struggle with hard coordinate step disruptions. On a periodic map spanning <span class="math inline">\([-\pi, \pi)\)</span>, the coordinate value wraps instantly from <span class="math inline">\(+\pi\)</span> to <span class="math inline">\(-\pi\)</span>. A model fed raw coordinates treats these boundary edges as distant extremes, leading to massive gradient calculation spikes (numerical cliffs).</p>
<p>To bypass this discontinuity, we project our 2D raw angular coordinates into a 4D continuous embedding space using independent sine and cosine transformations:</p>
<p><span class="math display">\[x = \begin{bmatrix} \phi \\ \psi \end{bmatrix} \in [-\pi, \pi)^2 \quad \implies \quad \text{enc}(x) = \begin{bmatrix} \sin\phi \\ \cos\phi \\ \sin\psi \\ \cos\psi \end{bmatrix} \in \mathbb{R}^4\]</span></p>
<p>Because <span class="math inline">\(\sin(-\pi) = \sin(\pi) = 0\)</span> and <span class="math inline">\(\cos(-\pi) = \cos(\pi) = -1\)</span>, the geometric boundaries blend seamlessly into a continuous, unbroken circle. This allows the network’s linear layers to learn smooth, edge-invariant structural features.</p>
<p><br></p>
<p><strong>B. The Euclidean Conditional Flow Matching Objective</strong></p>
<p>Conditional Flow Matching aims to train a neural network <span class="math inline">\(v_\theta(x, t)\)</span> to generate a vector field that matches a target probability distribution. During training, we define a pathway that moves from complete chaos (<span class="math inline">\(x_0 \sim \text{Uniform Noise}\)</span>) to a known empirical data point (<span class="math inline">\(x_1 \sim \text{Protein Sample}\)</span>) over a random snapshot of time <span class="math inline">\(t \sim \text{Uniform}(0, 1)\)</span>.</p>
<p>In this Euclidean baseline experiment, the intermediate point <span class="math inline">\(x_t\)</span> is constructed via flat linear interpolation, and the target vector is calculated using raw vector subtraction:</p>
<p><span class="math display">\[\begin{aligned}
x_t &amp;= (1 - t)x_0 + tx_1 \\
u(x_t \mid x_0, x_1) &amp;= x_1 - x_0
\end{aligned}\]</span></p>
<p>The network parameters <span class="math inline">\(\theta\)</span> are optimized by minimizing the Mean Squared Error (MSE) regression loss:</p>
<p><span class="math display">\[\mathcal{L}_{\text{CFM\_Euclid}}(\theta) = \mathbb{E}_{t, x_0, x_1} \left[ \| v_\theta(x_t, t) - (x_1 - x_0) \|^2 \right]\]</span></p>
<p><br></p>
<p><strong>C. Post-Hoc Boundary Adjustments</strong></p>
<p>Because standard Euler integration (<span class="math inline">\(x_{t+\Delta t} = x_t + \Delta t \cdot v_\theta\)</span>) relies on flat addition, coordinates can drift outside the legal boundaries of our coordinate square during generation. The Euclidean baseline attempts to correct this by applying a retroactive <strong>post-hoc modulo patch</strong> at the very end of the 100-step generation loop:</p>
<p><span class="math display">\[x_{\text{final}} = \left( (x_{\text{raw}} + \pi) \pmod{2\pi} \right) - \pi\]</span></p>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review-4" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review-4">3. Step-by-Step Pipeline Review</h4>
<p>The workflow spanned four core engineering themes:</p>
<pre><code>[Trigonometric MLP Design] ──&gt; [Euclidean CFM Loss Formulation] ──&gt; [Model Training &amp; Annealing] ──&gt; [Euler Integration &amp; Auditing]</code></pre>
<ol type="1">
<li><p><strong>Trigonometric MLP Design:</strong> Developed the <code>VectorFieldMLP</code> network. It takes 5 incoming features (<span class="math inline">\(\sin\phi, \cos\phi, \sin\psi, \cos\psi,\)</span> and time <span class="math inline">\(t\)</span>) and processes them through 3 layers of 256 hidden units using SiLU non-linear activations to output a 2D velocity vector. The architecture contains <strong>133,634</strong> learnable parameters.</p></li>
<li><p><strong>Euclidean CFM Loss Formulation:</strong> Built the <code>cfm_loss_euclid</code> function. This module constructs naive flat straight-line pathways connecting uniform background noise blocks to real protein structures to calculate the regression error.</p></li>
<li><p><strong>Model Training &amp; Annealing:</strong> Trained the network over 500 epochs with a batch size of 2,048. We used the Adam optimizer combined with <strong>Cosine Annealing</strong> to smoothly decay the learning rate, and applied <strong>Gradient Clipping</strong> at a threshold of <span class="math inline">\(1.0\)</span> to ensure stability. The training loss successfully converged from an initial value of <code>3.77557</code> down to a stable baseline floor of <code>3.03009</code>.</p></li>
<li><p><strong>Euler Integration &amp; Auditing:</strong> Implemented the <code>sample_euclid</code> function to generate 5,000 synthetic data points using a 100-step Euler integration routine. The generated coordinates were mapped directly onto our empirical Ramachandran plot clusters for evaluation.</p></li>
</ol>
<p><br></p>
</section>
<section id="key-learnings-4" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-4">4. Key Learnings</h4>
<ul>
<li><p><strong>Trigonometric Embeddings Stabilize Learning:</strong> Encoding raw angles into <span class="math inline">\((\sin, \cos)\)</span> pairs eliminates coordinate step disruptions at boundary lines. This allows deep learning models to process wrapping spaces without experiencing numerical overflow or gradient collapse.</p></li>
<li><p><strong>Flat Optimization Conflicts with Periodic Topologies:</strong> While the training loss steadily decreased to <code>3.03009</code>, this score represents an artificial ceiling. Because flat vector subtraction (<span class="math inline">\(x_1 - x_0\)</span>) forces paths to cross right through the open center of the map, the model is forced to learn conflicting paths where boundary shortcuts should exist.</p></li>
<li><p><strong>Post-Hoc Patches Degrade Generative Precision:</strong> Relying on flat integration steps and snapping points back onto the torus at the very end causes significant structural errors. As a result, the model wastes generative capacity, scattering points into invalid regions. The baseline model achieved a structural coverage efficiency of only <strong><span class="math inline">\(35.9\%\)</span></strong>:</p></li>
</ul>
<p><span class="math display">\[\begin{aligned}
\alpha\text{-helix coverage} &amp;= 1,024 / 5,000 \implies \mathbf{20.5\%} \\
\beta\text{-sheet coverage} &amp;= \phantom{0,}770 / 5,000 \implies \mathbf{15.4\%} \\
\text{Total Structural Accuracy} &amp;= \mathbf{35.9\%} \quad (\text{Invalid Scatter} = \mathbf{64.1\%})
\end{aligned}\]</span></p>
<p>This baseline confirms that a generative AI model cannot accurately capture periodic data if its loss function and integration steps ignore the underlying manifold topology. This establishes a clear benchmark to beat as we transition to true, manifold-aware flow matching.</p>
<hr>
</section>
</section>
<section id="stage-6---riemannian-conditional-flow-matching-on-t2" class="level3">
<h3 class="anchored" data-anchor-id="stage-6---riemannian-conditional-flow-matching-on-t2">Stage 6 - Riemannian Conditional Flow Matching on <span class="math inline">\(T^2\)</span></h3>
<p><strong>What are we building?</strong></p>
<p>We now adapt CFM to the Riemannian setting. The key change: replace Euclidean interpolation with geodesic interpolation, and replace the Euclidean regression target <span class="math inline">\((x_1 - x_0)\)</span> with the tangent vector <span class="math inline">\(\log_{\text{map}}(x_t, x_1) / (1-t)\)</span> at each interpolated point. The network <span class="math inline">\(v_\theta(x, t)\)</span> now predicts a tangent vector in <span class="math inline">\(T_{x_t} T^2\)</span>, and the generative ODE is integrated using the <span class="math inline">\(\exp_{\text{map}}\)</span>.</p>
<p><br></p>
</section>
<section id="questions-6" class="level3">
<h3 class="anchored" data-anchor-id="questions-6">Questions [6]</h3>
<p>Identify the two exact lines in <code>cfm_loss_euclid</code> where Euclidean assumptions are baked in, and state their Riemannian replacements.</p>
<p>Be specific: quote the expression, name the assumption it encodes, and write the replacement formula.</p>
<p><br></p>
</section>
<section id="answer-6" class="level3">
<h3 class="anchored" data-anchor-id="answer-6">Answer [6]</h3>
<p>To upgrade your loss function from <span class="math inline">\(\mathbb{R}^2\)</span> to <span class="math inline">\(T^2\)</span>, you must swap <strong>Euclidean addition</strong> (used in interpolation) and <strong>Euclidean subtraction</strong> (used to calculate the target velocity vector).</p>
<ol type="1">
<li>The Interpolation Target (<span class="math inline">\(x_t\)</span>)</li>
</ol>
<ul>
<li><strong>The Euclidean Expression:</strong></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>x_t <span class="op">=</span> (<span class="dv">1</span> <span class="op">-</span> t) <span class="op">*</span> x_0 <span class="op">+</span> t <span class="op">*</span> x_1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><p><strong>The Flat Assumption:</strong> It assumes data moves along a flat, straight line between <span class="math inline">\(x_0\)</span> and <span class="math inline">\(x_1\)</span>. On a torus, this path ignores the boundaries and cuts blindly across the square domain, often tracking straight through the middle of physically impossible “forbidden zones.”</p></li>
<li><p><strong>The Riemannian Replacement:</strong> You must use <strong>Geodesic Interpolation</strong> via the Logarithm and Exponential maps to ensure the path takes the shortest route around the surface of the torus.</p></li>
</ul>
<p><span class="math display">\[x_t = \text{exp}_{x_0}(t \cdot \text{log}_{x_0}(x_1))\]</span></p>
<p>In code, this is implemented component-wise using your Stage 3/4 wrapping functions:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>v_shortest <span class="op">=</span> log_map(x_0, x_1)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>x_t <span class="op">=</span> exp_map(x_0, t <span class="op">*</span> v_shortest)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><br></p>
<ol start="2" type="1">
<li>The Vector Field Regression Target (<span class="math inline">\(\text{Target}\)</span>)</li>
</ol>
<ul>
<li><strong>The Euclidean Expression:</strong></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> x_1 <span class="op">-</span> x_0</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><p><strong>The Flat Assumption:</strong> It assumes that a single, constant velocity vector can be calculated by simple subtraction, and that this vector is globally valid across the entire path. It ignores the fact that the true shortest velocity vector depends heavily on the periodic boundaries.</p></li>
<li><p><strong>The Riemannian Replacement:</strong> The true regression target is the unique tangent vector at the current position <span class="math inline">\(x_t\)</span> that points toward <span class="math inline">\(x_1\)</span> along the shortest geodesic path. You must compute this using the Logarithm map relative to the current time-step <span class="math inline">\(t\)</span>:</p></li>
</ul>
<p><span class="math display">\[\text{Target}_t = \frac{1}{1 - t} \text{log}_{x_t}(x_1)\]</span></p>
<p><em>(Note: Because the geodesic velocity is constant along the shortest path, <span class="math inline">\(\text{log}_{x_t}(x_1)\)</span> shrinks naturally at a rate of <span class="math inline">\((1-t)\)</span> as <span class="math inline">\(x_t\)</span> approaches <span class="math inline">\(x_1\)</span>. Dividing by <span class="math inline">\((1-t)\)</span> keeps the target vector perfectly stable and normalized throughout the trajectory).</em></p>
<p>In code:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> log_map(x_t, x_1) <span class="op">/</span> (<span class="fl">1.0</span> <span class="op">-</span> t)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><br></p>
<p><strong>Summary of the Updated Loss Loop</strong></p>
<p>The upgraded inner loss calculation changes from:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CHOOSE ONE: Flat vs. Torus Geometry</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># EUCLIDEAN</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>x_t <span class="op">=</span> (<span class="dv">1</span> <span class="op">-</span> t) <span class="op">*</span> x_0 <span class="op">+</span> t <span class="op">*</span> x_1</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> x_1 <span class="op">-</span> x_0</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># RIEMANNIAN (T^2)</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>x_t <span class="op">=</span> exp_map(x_0, t <span class="op">*</span> log_map(x_0, x_1))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> log_map(x_t, x_1) <span class="op">/</span> (<span class="fl">1.0</span> <span class="op">-</span> t)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard MSE Loss remains identical</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> torch.mean((v_theta(x_t, t) <span class="op">-</span> target) <span class="op">**</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><br></p>
<p>Note: One note on numerical stability: at <span class="math inline">\(t\)</span> close to <span class="math inline">\(1\)</span>, the division by <span class="math inline">\((1-t)\)</span> can explode. Clamp <span class="math inline">\(t\)</span> to <span class="math inline">\([0, 1-\epsilon]\)</span> during training.</p>
<hr>
</section>
<section id="stage-6-technical-report-riemannian-flow-matching-optimization-and-comparative-analysis" class="level3">
<h3 class="anchored" data-anchor-id="stage-6-technical-report-riemannian-flow-matching-optimization-and-comparative-analysis">Stage 6 Technical Report: Riemannian Flow Matching Optimization and Comparative Analysis</h3>
<section id="executive-summary-5" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary-5">1. Executive Summary</h4>
<p>In Stage 6, we concluded the development phase of our generative pipeline by building a fully topology-aware <strong>Riemannian Conditional Flow Matching (RCFM)</strong> model on the <strong>Flat Torus (<span class="math inline">\(T^2\)</span>)</strong>. By incorporating the logarithmic and exponential maps designed in Stage 3 directly into our deep learning loss architecture, we successfully trained a neural network that natively understands periodic boundary conditions.</p>
<p>To evaluate this new system, we conducted a rigorous comparative analysis against the flat Euclidean baseline engineered in Stage 5. The Riemannian model demonstrated superior optimization efficiency, dropping to a significantly lower final training loss (<strong><span class="math inline">\(2.38184\)</span></strong> vs.&nbsp;<strong><span class="math inline">\(3.03009\)</span></strong>). Tracking snapshots across training checkpoints confirmed that integrating manifold geometry directly into the model allows it to learn structural patterns much more rapidly and concentrate its generated data points cleanly within realistic biological clusters.</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts-5" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts-5">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. The Riemannian Conditional Flow Matching Objective</strong></p>
<p>Standard Flow Matching defines a flat, straight line between starting noise and a target data point. On a manifold, however, the shortest path between two points is a curved <strong>geodesic</strong>. The Riemannian Conditional Flow Matching framework replaces flat linear blending with a time-dependent geodesic vector field.</p>
<p>Given a starting chaotic noise point <span class="math inline">\(x_0 \sim \text{Uniform Noise}\)</span> and a target protein conformation <span class="math inline">\(x_1 \sim \text{Data}\)</span>, the intermediate position <span class="math inline">\(x_t\)</span> at a random time snapshot <span class="math inline">\(t \in [0, 1)\)</span> is determined by projecting a scaled velocity vector from the tangent space back onto the torus using the exponential map:</p>
<p><span class="math display">\[x_t = \text{exp\_map}\big(x_0, \, t \cdot \text{log\_map}(x_0, x_1)\big)\]</span></p>
<p>Unlike the Euclidean baseline, which uses simple subtraction (<span class="math inline">\(x_1 - x_0\)</span>) as a constant velocity target, the true vector field on a manifold changes dynamically depending on the current intermediate position <span class="math inline">\(x_t\)</span>. The target velocity vector <span class="math inline">\(u(x_t \mid x_0, x_1)\)</span> is a tangent vector at the current point <span class="math inline">\(x_t\)</span> that points along the remaining segment of the geodesic toward the destination <span class="math inline">\(x_1\)</span>, scaled by the remaining time <span class="math inline">\((1-t)\)</span>:</p>
<p><span class="math display">\[u(x_t \mid x_0, x_1) = \frac{\text{log\_map}(x_t, x_1)}{1 - t}\]</span></p>
<p>The neural network <span class="math inline">\(v_\theta(x_t, t)\)</span> is then trained by minimizing the expected Mean Squared Error (MSE) against this true manifold target vector:</p>
<p><span class="math display">\[\mathcal{L}_{\text{RCFM}}(\theta) = \mathbb{E}_{t, x_0, x_1} \left[ \left\| v_\theta(x_t, t) - \frac{\text{log\_map}(x_t, x_1)}{1 - t} \right\|^2 \right]\]</span></p>
<p><br></p>
<p><strong>B. Resolving Numerical Instability at <span class="math inline">\(t \to 1\)</span></strong></p>
<p>As the time variable <span class="math inline">\(t\)</span> approaches the final destination of <span class="math inline">\(1.0\)</span>, the remaining time window <span class="math inline">\((1 - t)\)</span> shrinks toward zero. Looking at our target velocity equation, dividing by zero causes a severe numerical explosion:</p>
<p><span class="math display">\[\lim_{t \to 1^{-}} \frac{\text{log\_map}(x_t, x_1)}{1 - t} = \frac{0}{0} \implies \text{NaN / Numerical Explosion}\]</span></p>
<p>To make training stable and prevent these calculation errors, we apply a safety clamp that restricts the upper bound of the random uniform time sampler to exactly <span class="math inline">\(0.999\)</span>:</p>
<p><span class="math display">\[t \sim \text{Uniform}(0, 1) \times 0.999\]</span></p>
<p>This adjustment keeps the division stable while still allowing the model to learn the vector paths right up to the final destination edge.</p>
<p><br></p>
<p><strong>C. Geodesic Euler Integration</strong></p>
<p>During the sampling phase, the Euclidean model allowed coordinates to drift out of bounds before snapping them back at the very end with a retroactive patch. The Riemannian model solves this by embedding a PyTorch-accelerated exponential map (<code>exp_map_torch</code>) directly into each iterative step of the generation loop:</p>
<p><span class="math display">\[x_{t+\Delta t} = \left( \left( x_t + \Delta t \cdot v_\theta(x_t, t) + \pi \right) \pmod{2\pi} \right) - \pi\]</span></p>
<p>By calculating this boundary wrap at every step, the generated data points naturally glide along the continuous, wrapping curves of the torus surface throughout their entire trajectory.</p>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review-5" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review-5">3. Step-by-Step Pipeline Review</h4>
<p>The workflow spanned four core engineering themes:</p>
<pre><code>[Manifold Loss Formulation] ──&gt; [Numerical Sanity Check] ──&gt; [Geodesic Optimization Loop] ──&gt; [Checkpoint Evolution Audit]</code></pre>
<ol type="1">
<li><p><strong>Manifold Loss Formulation:</strong> Coded the <code>cfm_loss_riem</code> function by translating our mathematical manifold equations into a working Python loss engine that uses true torus geodesics.</p></li>
<li><p><strong>Numerical Sanity Check:</strong> Verified the loss function using a micro-batch of 8 real protein data rows. The test returned a valid, finite, and positive error score (<code>3.29888</code>), proving that the boundary-wrapping and time-clamping routines were operating stably without calculation errors.</p></li>
<li><p><strong>Geodesic Optimization Loop:</strong> Instantiated a new network (<code>model_riem</code>) and trained it for 500 epochs using the same hyperparameter setup as the baseline model (Adam optimizer, Cosine Annealing scheduler, Gradient Clamping at <span class="math inline">\(1.0\)</span>, and a batch size of 2,048). The model converged cleanly to a optimized final loss of <strong><span class="math inline">\(2.38184\)</span></strong>.</p></li>
<li><p><strong>Checkpoint Evolution Audit:</strong> Archived 2,000 synthetic sample configurations at epochs 10, 50, 100, and 200 during training. We mapped these snapshots as a 4-panel comparison grid to visually track how effectively the model organized random noise into realistic protein backbone structures over time.</p></li>
</ol>
<p><br></p>
</section>
<section id="key-learnings-5" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-5">4. Key Learnings</h4>
<ul>
<li><p><strong>Topology Alignment Lowers the Optimization Ceiling:</strong> Directly comparing training runs revealed that the Euclidean model hits an artificial performance wall, getting stuck at a high loss floor of <code>3.03009</code>. By switching to our manifold-aware Riemannian loss function, we eliminated boundary conflicts and dropped the final error floor significantly lower to <strong><code>2.38184</code></strong>.</p></li>
<li><p><strong>Manifold-Aware Models Learn Faster:</strong> The Riemannian model achieves high structural accuracy long before training concludes. At just epoch 200 (the halfway mark of training), its generated samples already captured core biological regions with an accuracy of <strong><span class="math inline">\(41.7\%\)</span></strong>:</p></li>
</ul>
<p><span class="math display">\[\begin{aligned}
\alpha\text{-helix snapshot coverage (epoch 200)} &amp;= \mathbf{25.4\%} \\
\beta\text{-sheet snapshot coverage (epoch 200)} &amp;= \mathbf{16.3\%} \\
\text{Total Structural Accuracy (Halfway Point)} &amp;= \mathbf{41.7\%}
\end{aligned}\]</span></p>
<p>This interim score easily outperforms the final, fully completed 500-epoch run of our flat Euclidean model (<span class="math inline">\(35.9\%\)</span>).</p>
<ul>
<li><strong>Seamless Boundary Integration Eliminates Coordinate Artifacts:</strong> Embedding the exponential map wrap directly inside the integration step loops preserves the structural rules of our data space. The model learns to naturally route data across the wrapping boundaries, preventing generated points from scattering into physically impossible or empty zones. This demonstrates that embedding the true mathematical topology of a data space directly into an AI model’s loss equations and generation steps is essential for achieving accurate, reliable results in structural biology.</li>
</ul>
<hr>
</section>
</section>
<section id="stage-7---riemannian-ode-solver-geodesic-integrator" class="level3">
<h3 class="anchored" data-anchor-id="stage-7---riemannian-ode-solver-geodesic-integrator">Stage 7 - Riemannian ODE Solver (Geodesic Integrator)</h3>
<p><strong>What are we building?</strong></p>
<p>We’re implementing the manifold-constrained Euler integrator for sampling. The key change from Stage 5’s Euclidean sampler: instead of <code>x = x + dt·v</code>, each step uses <code>exp_map</code>.</p>
<p><br></p>
</section>
<section id="questions-7" class="level3">
<h3 class="anchored" data-anchor-id="questions-7">Questions [7]</h3>
<p>Answer this precisely: the Euclidean sampler in code uses <code>x = x + dt·v</code> at each step. Explain why this causes trajectory drift off <span class="math inline">\(T^2\)</span> over multiple steps, and why replacing it with `x = _{}(x, dt v)$ prevents drift — even with finite step size <span class="math inline">\(\Delta t\)</span>.</p>
<p>Your answer should address what happens to accumulated floating-point positions after many Euler steps in <span class="math inline">\(\mathbb{ℝ}^2\)</span>, and what geometric property of <code>exp_map</code> guarantees the output is always on <span class="math inline">\(T^2\)</span>.</p>
<p><br></p>
</section>
<section id="answer-7" class="level3">
<h3 class="anchored" data-anchor-id="answer-7">Answer [7]</h3>
<ol type="1">
<li>Why does the Euclidean sampler cause trajectory drift off <span class="math inline">\(T^2\)</span>?</li>
</ol>
<p>The flat-space update rule <code>x = x + dt * v</code> assumes that moving along a velocity vector keeps you in the same space.</p>
<p>On a flat plane (<span class="math inline">\(\mathbb{R}^2\)</span>), this works fine. However, because our domain is bound to the interval <span class="math inline">\([-\pi, \pi)^2\)</span>, a continuous velocity field will eventually push a particle past the boundaries (e.g., <span class="math inline">\(x &gt; \pi\)</span>).</p>
<p><strong>What happens to accumulated floating-point positions:</strong></p>
<p>Without a manifold constraint, a standard computer simulation will just let the numbers grow indefinitely (e.g., <span class="math inline">\(\phi = 3.5, 4.2, 7.1\)</span>). The floating-point positions simply accumulate lineally in <span class="math inline">\(\mathbb{R}^2\)</span>, wandering completely outside the original square domain. While you <em>could</em> try to fix this by clumsily applying a modulo operation at the end of the simulation, the model’s neural network was trained on inputs between <span class="math inline">\([-\pi, \pi)\)</span>. Feeding it raw, un-wrapped coordinates like <span class="math inline">\(7.1\)</span> during intermediate steps will confuse the network, causing it to output garbage velocities and causing the trajectory to drift completely away from the true learned distribution.</p>
<p><br></p>
<ol start="2" type="1">
<li>How does <code>x = exp_map(x, dt * v)</code> prevent drift?</li>
</ol>
<p>Replacing flat addition with the Exponential map completely eliminates drift—even when using a large or finite step size <span class="math inline">\(\Delta t\)</span>.</p>
<p><strong>The Geometric Property that guarantees staying on <span class="math inline">\(T^2\)</span>:</strong></p>
<p>The foundational geometric property of the Exponential map is that <strong>its codomain is strictly defined on the manifold itself</strong> (<span class="math inline">\(\text{exp}_x: T_xM \to M\)</span>).</p>
<p>Algebraically, our specific implementation of <code>exp_map</code> achieves this because it has an internal <strong>modular wrapping mechanism</strong> (<span class="math inline">\(\pmod{2\pi}\)</span> with a phase shift) built directly into its formula.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The geometric shield that prevents drift</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> exp_map(x, v):</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.remainder(x <span class="op">+</span> v <span class="op">+</span> torch.pi, <span class="dv">2</span> <span class="op">*</span> torch.pi) <span class="op">-</span> torch.pi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Instead of letting the coordinates blindy accumulate into large numbers that escape the domain, the <code>exp_map</code> treats the boundary points as equivalent. If a step of size <span class="math inline">\(\Delta t \cdot v\)</span> attempts to push the coordinate past <span class="math inline">\(+\pi\)</span>, the internal modulo operations automatically and flawlessly wrap the point back around to the <span class="math inline">\(-\pi\)</span> side of the torus.</p>
<p>Because this wrapping happens at <em>every single individual step</em> of the solver, the intermediate positions fed back into the neural network are guaranteed to stay perfectly inside the valid <span class="math inline">\([-\pi, \pi)^2\)</span> domain. The simulation physically cannot leave the torus.</p>
<hr>
</section>
<section id="stage-7-technical-report-manifold-constrained-discretization-and-validation" class="level3">
<h3 class="anchored" data-anchor-id="stage-7-technical-report-manifold-constrained-discretization-and-validation">Stage 7 Technical Report: Manifold-Constrained Discretization and Validation</h3>
<section id="executive-summary-6" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary-6">1. Executive Summary</h4>
<p>In Stage 7, we executed the final validation and empirical benchmarking of our <strong>Riemannian Conditional Flow Matching (RCFM)</strong> pipeline on the <strong>Flat Torus (<span class="math inline">\(T^2\)</span>)</strong>. The focus shifted from network training to the mechanics of sample generation, numerical stability under varying time resolutions, and enforcing strict scientific controls.</p>
<p>We implemented a native, GPU-accelerated <strong>Geodesic Euler Integrator</strong> that constrains generated points to the manifold at every infinitesimal tracking interval. Through step-count sensitivity analysis and hyperparameter auditing, we proved that embedding topological invariants directly into the sampling engine yields a generative system that is robust against numerical integration drift and highly stable at low computational budgets. Under a perfectly controlled benchmark, the Riemannian model demonstrated a substantial performance leap over the flat Euclidean baseline, boosting core biological region coverage accuracy from <strong><span class="math inline">\(35.9\%\)</span></strong> to <strong><span class="math inline">\(43.1\%\)</span></strong>.</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts-6" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts-6">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. Geodesic Euler Integration vs.&nbsp;Linear Integration Drift</strong></p>
<p>Standard Euler integration updates a state <span class="math inline">\(x_t\)</span> using flat Euclidean addition: <span class="math inline">\(x_{t+\Delta t} = x_t + \Delta t \cdot v_\theta(x_t, t)\)</span>. When applied to curved surfaces or wrapping maps, this linear projection overshoots the true surface, drifting off the manifold into unmapped coordinate territory.</p>
<p>Our Geodesic Euler Integrator corrects for this by mapping the scaled velocity vector <span class="math inline">\(\Delta t \cdot v_\theta(x_t, t)\)</span> (which exists in the localized tangent space <span class="math inline">\(T_{x_t}T^2\)</span>) directly back onto the surface of the torus at every single micro-step using the exponential map:</p>
<p><span class="math display">\[x_{t+\Delta t} = \text{exp\_map}_{x_t}\big(\Delta t \cdot v_\theta(x_t, t)\big)\]</span></p>
<p>Natively implemented in PyTorch, this operator applies a parallelized, coordinate-wise modulo shift that maps the advanced points seamlessly across the boundary horizons:</p>
<p><span class="math display">\[\text{exp\_map\_torch}(x, \, \Delta t \cdot v) = \Big( \big(x + \Delta t \cdot v + \pi\big) \pmod{2\pi} \Big) - \pi\]</span></p>
<p>Because the codomain of this stepping function is strictly bounded within <span class="math inline">\([-\pi, \pi)^2\)</span>, the generative path is mathematically constrained to the manifold throughout the entire 100-step trajectory, eliminating the need for retroactive post-hoc patches.</p>
<p><br></p>
<p><strong>B. Stability Under Step-Size Discretization (<span class="math inline">\(\Delta t\)</span>)</strong></p>
<p>Numerical integration accuracy depends heavily on the step-size fraction <span class="math inline">\(\Delta t = \frac{1}{n_{\text{steps}}}\)</span>. In standard Euclidean flow models, reducing the step count increases <span class="math inline">\(\Delta t\)</span>, causing the network’s updates to overshoot curved trajectories and degrading sample quality.</p>
<p>The Riemannian integrator exhibits unique numerical stability because the exponential map enforces the manifold constraint regardless of step size. Even when the timeline is compressed to an ultra-low resolution (<span class="math inline">\(n_{\text{steps}} = 10 \implies \Delta t = 0.1\)</span>), the trajectory cannot leak off the torus:</p>
<p><span class="math display">\[\forall \Delta t \in (0, 1], \quad \text{exp\_map}_{x_t}\big(\Delta t \cdot v_\theta(x_t, t)\big) \in T^2\]</span></p>
<p>This geometric constraint preserves vector field orientation across coarse time slices, allowing high-fidelity structural generation at a fraction of the computational cost.</p>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review-6" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review-6">3. Step-by-Step Pipeline Review</h4>
<p>The workflow spanned four core validation procedures:</p>
<pre><code>[Isolating Sampler Utility] ──&gt; [Manifold Auditing (Zero-Violation Proof)] ──&gt; [Sensitivity &amp; Discretization Testing] ──&gt; [Hyperparameter Control Check]</code></pre>
<ol type="1">
<li><p><strong>Isolating Sampler Utility:</strong> Re-engineered the <code>sample_riem</code> utility using GPU-accelerated PyTorch primitives (<code>exp_map_torch</code>). This decoupled the inference engine from the training loop, allowing for independent sampling adjustments.</p></li>
<li><p><strong>Manifold Auditing (Zero-Violation Proof):</strong> Implemented <code>sample_riem_verified</code> as a strict diagnostic gate. It verified 51,200 unique intermediate coordinate states (<span class="math inline">\(512 \text{ samples} \times 100 \text{ steps}\)</span>) against the boundary limits:</p></li>
</ol>
<p><span class="math display">\[\text{Violations} = \sum_{i=1}^{n_{\text{steps}}} \mathbb{I}\Big( \big(x_i \le -\pi\big) \lor \big(x_i &gt; \pi\big) \Big)\]</span></p>
<p>The evaluation returned <strong>exactly 0 violations</strong>, confirming perfect manifold compliance.</p>
<ol start="3" type="1">
<li><p><strong>Sensitivity &amp; Discretization Testing:</strong> Subjected both generative models to a step-count stress test across <span class="math inline">\(10, 25, 50,\)</span> and <span class="math inline">\(100\)</span> steps. The Riemannian model maintained structural accuracy across all step sizes, while the Euclidean baseline degraded due to integration drift.</p></li>
<li><p><strong>Hyperparameter Control Check:</strong> Executed a comprehensive audit to guarantee experimental fairness. We verified that both architectures utilized identical neural capacities, learning rates (<code>1e-3</code>), batch sizes (<code>2048</code>), random seeds (<code>42</code>), and optimization lifetimes (<code>500 epochs</code>), confirming that the performance gap is due solely to the manifold geometry.</p></li>
</ol>
<p><br></p>
</section>
<section id="key-learnings-6" class="level4">
<h4 class="anchored" data-anchor-id="key-learnings-6">4. Key Learnings</h4>
<ul>
<li><p><strong>Manifold-Constrained Integration Eliminates Accumulation Errors:</strong> Auditing every intermediate state proved that applying the exponential map at each micro-step keeps trajectories perfectly on the torus. This prevents the coordinate drift that severely limits flat-plane models.</p></li>
<li><p><strong>Topological Constraints Enable Ultra-Fast Sampling:</strong> The step-count sensitivity test showed that the Riemannian model maintains stable <span class="math inline">\(\alpha\)</span>-helix coverage even at a low resolution of 10 steps (<span class="math inline">\(25.6\%\)</span>), nearly matching its 100-step performance (<span class="math inline">\(26.2\%\)</span>). This allows for significantly faster sample generation without sacrificing structural accuracy, providing a major advantage for large-scale molecular design.</p></li>
<li><p><strong>The Riemannian Paradigm Shifts the Performance Floor:</strong> The hyperparameter audit confirmed a clean, fair comparison. By aligning the loss metrics and integration steps with the true underlying topology of the data, the Riemannian model outperformed the baseline across the board, matching the true ground-truth distribution much more closely:</p></li>
</ul>
<p><span class="math display">\[\begin{aligned}
\text{Total Structural Coverage (Ground Truth)} &amp;= 32.9\%_{\alpha} + 22.1\%_{\beta} = \mathbf{55.0\%} \\
\text{Total Structural Coverage (Euclidean Baseline)} &amp;= 20.5\%_{\alpha} + 15.4\%_{\beta} = \mathbf{35.9\%} \\
\text{Total Structural Coverage (Riemannian Flow)} &amp;= 25.0\%_{\alpha} + 18.1\%_{\beta} = \mathbf{43.1\%}
\end{aligned}\]</span></p>
<p><br></p>
<p>This final benchmark proves that integrating the correct manifold geometry directly into the loss equations and sampling loops of generative AI models is essential for accurately capturing periodic biological structures.</p>
<hr>
</section>
</section>
<section id="stage-8---euclidean-baseline-comparison" class="level3">
<h3 class="anchored" data-anchor-id="stage-8---euclidean-baseline-comparison">Stage 8 - Euclidean Baseline Comparison</h3>
<p><strong>What are we building?</strong></p>
<p>We train an identical MLP using standard Euclidean CFM (Stage 5 architecture) on the same data, treating <span class="math inline">\((\phi, \psi) \in \mathbb{R}^2\)</span>. At inference, wrap generated samples back to <span class="math inline">\([- \pi, \pi)^2\)</span> using modular arithmetic. Compare Ramachandran coverage between Riemannian RFM and the Euclidean baseline — specifically near the <span class="math inline">\(\pm \pi\)</span> boundary where Euclidean flow matching is expected to fail.</p>
<p><br></p>
</section>
<section id="questions-8" class="level3">
<h3 class="anchored" data-anchor-id="questions-8">Questions [8]</h3>
<p>Answer the question: Looking at the region definitions:</p>
<ul>
<li><span class="math inline">\(\alpha\)</span>-helix: <span class="math inline">\(\phi \in [-80^\circ, -40^\circ]\)</span>, <span class="math inline">\(\psi \in [-60^\circ, -20^\circ]\)</span></li>
<li><span class="math inline">\(\beta\)</span>-sheet: <span class="math inline">\(\phi \in [-150^\circ, -90^\circ]\)</span>, <span class="math inline">\(\psi \in [100^\circ, 170^\circ]\)</span></li>
</ul>
<p>In radians: - <span class="math inline">\(\alpha\)</span>-helix: <span class="math inline">\(\phi \in [-1.40, -0.70]\)</span>, <span class="math inline">\(\psi \in [-1.05, -0.35]\)</span> - <span class="math inline">\(\beta\)</span>-sheet: <span class="math inline">\(\phi \in [-2.62, -1.57]\)</span>, <span class="math inline">\(\psi \in [1.75, 2.97]\)</span></p>
<p>The <span class="math inline">\(\pm \pi\)</span> boundary sits at <span class="math inline">\(\pm 3.14159\)</span>. Which region is closest to which boundary, by how many radians, and therefore most damaged by the Euclidean wrap-around discontinuity?</p>
<p><br></p>
</section>
<section id="answer-8" class="level3">
<h3 class="anchored" data-anchor-id="answer-8">Answer [8]</h3>
<p><strong>Distance to Boundaries Analysis</strong></p>
<p>Let’s calculate exactly how close each structural region sits to the boundaries (<span class="math inline">\(\pm \pi \approx \pm 3.14159\)</span>).</p>
<ol type="1">
<li><span class="math inline">\(\alpha\)</span>-helix Region</li>
</ol>
<ul>
<li><strong><span class="math inline">\(\phi\)</span> range:</strong> <span class="math inline">\([-1.40, -0.70]\)</span></li>
<li><strong><span class="math inline">\(\psi\)</span> range:</strong> <span class="math inline">\([-1.05, -0.35]\)</span></li>
<li><strong>Closest Boundary:</strong> The closest boundary to any coordinate here is the <span class="math inline">\(-\pi\)</span> edge.</li>
</ul>
<p><span class="math display">\[\text{Distance} = -0.70 - (-3.14159) = 2.44159 \text{ radians}\]</span></p>
<p><br></p>
<ol start="2" type="1">
<li><span class="math inline">\(\beta\)</span>-sheet Region</li>
</ol>
<ul>
<li><strong><span class="math inline">\(\phi\)</span> range:</strong> <span class="math inline">\([-2.62, -1.57]\)</span></li>
<li><strong><span class="math inline">\(\psi\)</span> range:</strong> <span class="math inline">\([1.75, 2.97]\)</span></li>
<li><strong>Closest Boundary:</strong> Look at the upper bound of the <span class="math inline">\(\psi\)</span> angle (<span class="math inline">\(2.97\)</span>). It sits right next to the <span class="math inline">\(+\pi\)</span> boundary.</li>
</ul>
<p><span class="math display">\[\text{Distance} = 3.14159 - 2.97 = \mathbf{0.17159 \text{ \textbf{radians}}}\]</span></p>
<p><br></p>
<p><strong>Which region is most damaged by the Euclidean assumption?</strong></p>
<p>The <strong><span class="math inline">\(\beta\)</span>-sheet region</strong> is heavily damaged by the Euclidean assumption—specifically along its <strong><span class="math inline">\(\psi\)</span> (psi)</strong> angle coordinate.</p>
<p><br></p>
<p><strong>Why this damage occurs:</strong></p>
<p>The top edge of the <span class="math inline">\(\beta\)</span>-sheet region (<span class="math inline">\(\psi = 2.97\)</span>) sits just <strong>0.17 radians</strong> away from the <span class="math inline">\(+\pi\)</span> boundary. In reality, the protein backbone can easily fluctuate slightly past this line, wrapping over the boundary directly into the <span class="math inline">\(-\pi\)</span> territory (the very bottom of the plot).</p>
<p>A Euclidean model treats <span class="math inline">\(+\pi\)</span> and <span class="math inline">\(-\pi\)</span> as if they are separated by a massive distance of <span class="math inline">\(2\pi \approx 6.28\)</span> radians. Because the flat model cannot see across this boundary, it fails to understand that the data pooling at the very top of the plot is physically connected to the data pooling at the very bottom.</p>
<p>As a result, a Euclidean flow matching model will struggle to generate valid <span class="math inline">\(\beta\)</span>-sheets; it will artificially “slice” the distribution in half, create a massive dead zone near the edges, and fail to model the natural structural transitions that happen across the boundary. The <span class="math inline">\(\alpha\)</span>-helix region, sitting comfortably in the middle of the flat territory, remains completely unaffected by this specific boundary issue.</p>
<hr>
</section>
<section id="stage-8-technical-report-spatial-boundary-diagnostics-and-density-mapping" class="level3">
<h3 class="anchored" data-anchor-id="stage-8-technical-report-spatial-boundary-diagnostics-and-density-mapping">Stage 8 Technical Report: Spatial Boundary Diagnostics and Density Mapping</h3>
<section id="executive-summary-7" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary-7">1. Executive Summary</h4>
<p>In Stage 8, we conducted a rigorous spatial diagnostic audit of our generative pipelines. While previous stages established the global superiority of <strong>Riemannian Conditional Flow Matching (RCFM)</strong> via aggregate loss values and raw region percentages, Stage 8 isolated the exact geographic mechanisms driving these differences.</p>
<p>By writing customized <strong>Kernel Density Estimation (KDE)</strong> evaluation grids and boundary proximity sensors, we numerically and visually mapped the “Edge Effect”—the severe structural breakdown that occurs when flat Euclidean math is forced onto a periodic space. Our diagnostics revealed that the critical <span class="math inline">\(\beta\)</span>-sheet cluster sits a mere <strong>0.175 radians (<span class="math inline">\(10^\circ\)</span>)</strong> away from the coordinate edge, making it highly vulnerable to flat-plane boundary errors. The resulting difference map provided definitive proof that our topology-aware Riemannian model eliminates these boundary artifacts, paving the way for high-fidelity structural generation.</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts-7" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts-7">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. Quantifying Boundary Proximity and the Edge Horizon</strong></p>
<p>To understand why the flat Euclidean model breaks down near the edges of the map, we must measure the exact minimum distance <span class="math inline">\(\Delta_{\partial}\)</span> separating our biological target zones from the coordinate boundaries <span class="math inline">\(\partial \Omega = \{-\pi, \pi\}\)</span>:</p>
<p><span class="math display">\[\Delta_{\partial}(\mathcal{R}_c) = \min \left( \inf_{x \in \mathcal{R}_c} |x - (-\pi)|, \, \inf_{x \in \mathcal{R}_c} |\pi - x| \right)\]</span></p>
<p>where <span class="math inline">\(\mathcal{R}_c\)</span> represents the coordinate range of a target biological region for a specific angular component (<span class="math inline">\(c \in \{\phi, \psi\}\)</span>).</p>
<p>When applied to the vertical component (<span class="math inline">\(\psi\)</span>) of the stable <span class="math inline">\(\beta\)</span>-sheet configuration, the audit exposed an extreme proximity to the edge:</p>
<p><span class="math display">\[\Delta_{\partial}(\psi_{\beta\text{-sheet}}) = \pi - 2.9671 = \mathbf{0.1745 \text{ rad }} (\approx 10.00^\circ)\]</span></p>
<p>In a flat Euclidean system, this boundary acts as a hard, uncrossable wall. As a result, when the baseline model attempts to generate points near this border, its linear trajectories are cut off or split, severely limiting its ability to accurately capture the <span class="math inline">\(\beta\)</span>-sheet structure.</p>
<p><br></p>
<p><strong>B. Kernel Density Derivative Mapping</strong></p>
<p>To isolate exactly where the two models differ across the entire coordinate space, we mapped their distributions into continuous probability surfaces using <strong>Kernel Density Estimation (KDE)</strong>. Given a set of <span class="math inline">\(N\)</span> generated samples, the continuous density function <span class="math inline">\(\hat{f}(x)\)</span> at any coordinate point <span class="math inline">\(x = (\phi, \psi)^T\)</span> on our <span class="math inline">\(100 \times 100\)</span> evaluation grid is defined as:</p>
<p><span class="math display">\[\hat{f}(x) = \frac{1}{N b^2} \sum_{i=1}^{N} \frac{1}{2\pi} \exp\left( -\frac{\|x - x_i\|^2}{2b^2} \right)\]</span></p>
<p>where <span class="math inline">\(b = 0.15\)</span> represents our standard Gaussian smoothing bandwidth.</p>
<p>We then computed a continuous <strong>density difference field</strong> <span class="math inline">\(\mathcal{D}(x)\)</span> by subtracting the Euclidean probability surface from the Riemannian surface:</p>
<p><span class="math display">\[\mathcal{D}(x) = \hat{f}_{\text{Riemannian}}(x) - \hat{f}_{\text{Euclidean}}(x)\]</span></p>
<p>Evaluating this difference field across the coordinate grid yields clear, actionable insights:</p>
<ul>
<li><strong><span class="math inline">\(\mathcal{D}(x) &gt; 0\)</span> (Positive/Red Zones):</strong> Areas where the Riemannian model correctly concentrates its points to match real-world biological data.</li>
<li><strong><span class="math inline">\(\mathcal{D}(x) &lt; 0\)</span> (Negative/Blue Zones):</strong> Areas where the Euclidean baseline over-generates points, wasting its generative capacity by scattering data into unpopulated regions.</li>
</ul>
<p><br></p>
<p><strong>C. Boundary Band Mass Integration</strong></p>
<p>To measure exactly how much data mass each model places along the outermost edges of the map, we isolated a narrow border band <span class="math inline">\(\Omega_{\text{band}}\)</span> stretching <span class="math inline">\(0.3\text{ radians}\)</span> (<span class="math inline">\(\approx 17.2^\circ\)</span>) away from the boundary lines:</p>
<p><span class="math display">\[\Omega_{\text{band}} = \big\{ (\phi, \psi) \in [-\pi, \pi)^2 \ \big| \ \min(|\phi \pm \pi|, \, |\psi \pm \pi|) &lt; 0.3 \big\}\]</span></p>
<p>We then calculated the total probability mass within this edge zone by integrating our sample distributions:</p>
<p><span class="math display">\[M_{\text{band}} = \mathbb{E}_{x \sim p(x)} \big[ \mathbb{I}(x \in \Omega_{\text{band}}) \big] = \frac{1}{N}\sum_{i=1}^N \mathbb{I}(x_i \in \Omega_{\text{band}})\]</span></p>
<p>This metric allowed us to measure the exact surplus density generated by both models relative to the empirical ground truth.</p>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review-7" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review-7">3. Step-by-Step Pipeline Review</h4>
<p>The diagnostic workflow followed four core analytical procedures:</p>
<pre><code>[Boundary Proximity Audit] ──&gt; [Continuous KDE Grid Synthesis] ──&gt; [Differential Spatial Mapping] ──&gt; [Global Mass Integration]</code></pre>
<ol type="1">
<li><p><strong>Boundary Proximity Audit:</strong> Evaluated the coordinate limits of our target regions to measure their exact distance to the borders. This provided the numerical foundation for our edge-failure analysis, exposing the extreme vulnerability of the <span class="math inline">\(\beta\)</span>-sheet region.</p></li>
<li><p><strong>Continuous KDE Grid Synthesis:</strong> Built a unified <span class="math inline">\(100 \times 100\)</span> mesh grid over the entire coordinate space. We evaluated 5,000 samples from each model to convert scattered points into continuous probability density surfaces (<span class="math inline">\(\hat{f}_{\text{Riem}}\)</span> and <span class="math inline">\(\hat{f}_{\text{Euclid}}\)</span>).</p></li>
<li><p><strong>Differential Spatial Mapping:</strong> Subtracted the two density surfaces to compute our difference field <span class="math inline">\(\mathcal{D}(x)\)</span>. We plotted this field as a 20-level contour map, pinpointing exactly where the flat Euclidean framework breaks down near the edges.</p></li>
<li><p><strong>Global Mass Integration:</strong> Isolated a 0.3-radian border band along the outer boundaries of our torus map. We measured the exact percentage of points each model places within this edge zone, confirming that both models generate a slight surplus of points in these sparse regions.</p></li>
</ol>
<p><br></p>
</section>
<section id="what-we-have-learnt-from-stage-8" class="level4">
<h4 class="anchored" data-anchor-id="what-we-have-learnt-from-stage-8">4. What We Have Learnt from Stage 8</h4>
<ul>
<li><p><strong>The <span class="math inline">\(\beta\)</span>-Sheet Cluster is Highly Vulnerable to Flat-Plane Boundary Errors:</strong> The proximity audit delivered a crucial structural insight: the vertical component of the stable <span class="math inline">\(\beta\)</span>-sheet configuration sits just <strong><span class="math inline">\(10^\circ\)</span> (<span class="math inline">\(0.175 \text{ radians}\)</span>)</strong> away from the edge of the map. Because this vital cluster hugs the boundary so closely, treating the space as a flat plane severely disrupts the model’s generation pathways. This explains why our topology-aware model achieved such a massive performance leap in <span class="math inline">\(\beta\)</span>-sheet generation (<span class="math inline">\(18.1\%\)</span> vs <span class="math inline">\(15.4\%\)</span>).</p></li>
<li><p><strong>Flat-Plane Models Create Artificial Structural Tears:</strong> Our difference map provided clear visual proof of our core hypothesis. The map revealed an intense red region right along the top border where the <span class="math inline">\(\beta\)</span>-sheet sits, proving that the flat model treats the edge as a solid wall and fails to generate points near the border. Meanwhile, the Riemannian model easily routes trajectories across this boundary line, capturing the natural shape of the data.</p></li>
<li><p><strong>True Topology Paths Handle Sparse Boundaries Natively:</strong> The global mass integration test showed that both models place a minor surplus of points along the absolute edges of the map (<span class="math inline">\(+1.3\%\)</span> for Euclidean, <span class="math inline">\(+2.0\%\)</span> for Riemannian) compared to the sparse ground truth (<span class="math inline">\(0.6\%\)</span>). However, because the Riemannian model treats the space as a wrapping surface, its trajectories flow naturally across these boundary lines rather than getting blocked by an artificial edge.</p></li>
</ul>
<p><br></p>
<p>This final diagnostic phase confirms that aligning our generative equations with the true mathematical topology of the data space is essential for eliminating boundary artifacts and reliably capturing realistic biological structures.</p>
<hr>
</section>
</section>
<section id="stage-9---ramachandran-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="stage-9---ramachandran-evaluation">Stage 9 - Ramachandran Evaluation</h3>
<p><strong>What are we building?</strong></p>
<p>We’re producing the definitive evaluation figure and the central quantitative result of the project: a 2×2 Ramachandran grid and Jensen-Shannon divergence between generated and ground-truth KDE for both models.</p>
<hr>
</section>
<section id="stage-9-technical-report-unified-visual-integration-statistical-convergence-and-architectural-scaling" class="level3">
<h3 class="anchored" data-anchor-id="stage-9-technical-report-unified-visual-integration-statistical-convergence-and-architectural-scaling">Stage 9 Technical Report: Unified Visual Integration, Statistical Convergence, and Architectural Scaling</h3>
<section id="executive-summary-8" class="level4">
<h4 class="anchored" data-anchor-id="executive-summary-8">1. Executive Summary</h4>
<p>In Stage 9, we completed the final evaluation, benchmarking, and architectural scaling of our generative pipelines on the <strong>Flat Torus (<span class="math inline">\(T^2\)</span>)</strong>. This stage moved beyond localized diagnostics to synthesize a comprehensive, publication-grade visual and statistical proof of our research.</p>
<p>By integrating our data distributions into a unified 4-panel evaluation dashboard, calculating the <strong>Jensen-Shannon Divergence (JSD)</strong> on the continuous density surfaces, and deploying an expanded <strong>Version 2 (v2)</strong> architecture, we achieved major milestones. Under a perfectly controlled audit, our initial Riemannian model cut the baseline distribution error by <strong><span class="math inline">\(43.2\%\)</span></strong>. Removing hyperparameter constraints in Version 2 demonstrated the excellent scalability of our geometric framework, dropping the global JSD to a near-flawless <strong><span class="math inline">\(0.010963\)</span></strong> and matching the structural density of the real-world dataset with exceptional fidelity.</p>
<p><br></p>
</section>
<section id="core-scientific-mathematical-concepts-8" class="level4">
<h4 class="anchored" data-anchor-id="core-scientific-mathematical-concepts-8">2. Core Scientific &amp; Mathematical Concepts</h4>
<p><strong>A. Jensen-Shannon Divergence (JSD) as a Symmetric Statistical Metric</strong></p>
<p>While Kullback-Leibler (KL) Divergence is standard for measuring distance between probability distributions, it is asymmetric (<span class="math inline">\(D_{\text{KL}}(P \parallel Q) \neq D_{\text{KL}}(Q \parallel P)\)</span>) and structurally unstable if the generated model fails to place points where real data exists (<span class="math inline">\(Q(x) \to 0 \implies D_{\text{KL}} \to \infty\)</span>).</p>
<p>To establish absolute mathematical proof of our model’s accuracy, we implemented the <strong>Jensen-Shannon Divergence (JSD)</strong>. The JSD introduces a smoothed midpoint distribution <span class="math inline">\(M = \frac{1}{2}(P + Q)\)</span>, creating a symmetric, bounded metric (<span class="math inline">\(0 \le \text{JSD}(P \parallel Q) \le \ln(2)\)</span>):</p>
<p><span class="math display">\[\text{JSD}(P \parallel Q) = \frac{1}{2} D_{\text{KL}}(P \parallel M) + \frac{1}{2} D_{\text{KL}}(Q \parallel M)\]</span></p>
<p>In our codebase, the continuous 2D Kernel Density Estimation surfaces are flattened and normalized over a unified <span class="math inline">\(100 \times 100\)</span> evaluation mesh grid to form discrete probability masses:</p>
<p><span class="math display">\[P_i = \frac{\hat{f}_{\text{GT}}(x_i) + \epsilon}{\sum_{j} (\hat{f}_{\text{GT}}(x_j) + \epsilon)}, \quad Q_i = \frac{\hat{f}_{\text{Model}}(x_i) + \epsilon}{\sum_{j} (\hat{f}_{\text{Model}}(x_j) + \epsilon)}\]</span></p>
<p>The relative entropy is calculated across all grid points using the standard formula:</p>
<p><span class="math display">\[D_{\text{KL}}(P \parallel M) = \sum_{i=1}^{10000} P_i \ln \left( \frac{P_i}{M_i} \right)\]</span></p>
<p>This metric provides an accurate, stable measure of global distributional similarity, making it the definitive metric for our benchmarking process.</p>
<p><br></p>
<p><strong>B. Capacity Scaling and Discretization Refinement (v2 Mechanics)</strong></p>
<p>To explore the performance limits of the Riemannian framework, the Version 2 (v2) configuration scaled up three core computational dimensions:</p>
<ol type="1">
<li><p><strong>Network Width:</strong> The hidden layer dimension <span class="math inline">\(d_{\text{hidden}}\)</span> was doubled from 256 to 512. Since the layer parameters scale quadratically (<span class="math inline">\(\mathcal{O}(d_{\text{hidden}}^2)\)</span>), this expanded model capacity from 133,634 to <strong>529,410 trainable parameters</strong>, allowing the network to resolve highly complex vector field variations.</p></li>
<li><p><strong>Optimization Lifetime:</strong> Training duration was extended from 500 to 1,000 epochs, allowing the larger network to settle into a significantly lower error floor.</p></li>
<li><p><strong>Time Discretization Resolution:</strong> Sampling path resolution was doubled from 100 to 200 steps (<span class="math inline">\(\Delta t = 0.005\)</span>). This modification minimizes cumulative discretization error during generation, keeping the trajectory exceptionally close to the true continuous flow lines.</p></li>
</ol>
<p><br></p>
</section>
<section id="step-by-step-pipeline-review-8" class="level4">
<h4 class="anchored" data-anchor-id="step-by-step-pipeline-review-8">3. Step-by-Step Pipeline Review</h4>
<p>The final validation and scaling phase followed four core procedures:</p>
<pre><code>[Unified 2x2 Evaluation Synthesis] ──&gt; [Statistical JSD Benchmarking] ──&gt; [Architectural Scaling (v2)] ──&gt; [Ablation Performance Profiling]</code></pre>
<ol type="1">
<li><p><strong>Unified 2x2 Evaluation Synthesis:</strong> Consolidated our data arrays into a publication-grade visual dashboard (<code>ramachandran_eval_2x2.png</code>). This aligned the Ground Truth, Riemannian CFM, Euclidean CFM, and the continuous density difference field side-by-side on identical coordinate axes.</p></li>
<li><p><strong>Statistical JSD Benchmarking:</strong> Evaluated our custom <code>jsd</code> function across the normalized density grids. This provided the strict statistical proof required to confirm the performance leap of our geometric model over the baseline.</p></li>
<li><p><strong>Architectural Scaling (v2):</strong> Initialized and trained the expanded v2 network (<code>model_riem_v2</code>) using gradient norm clipping to ensure optimization stability:</p></li>
</ol>
<p><span class="math display">\[\mathbf{g} \leftarrow \mathbf{g} \cdot \min \left( 1, \, \frac{1.0}{\|\mathbf{g}\|_2} \right)\]</span></p>
<ol start="4" type="1">
<li><strong>Ablation Performance Profiling:</strong> Gathered and printed a comprehensive v1 vs.&nbsp;v2 summary table, documenting exactly how our metrics scale when provided with increased model capacity and training time.</li>
</ol>
<p><br></p>
</section>
<section id="what-we-have-learnt-from-stage-9" class="level4">
<h4 class="anchored" data-anchor-id="what-we-have-learnt-from-stage-9">4. What We Have Learnt from Stage 9</h4>
<ul>
<li><p><strong>Riemannian Flow Eliminates Global Statistical Distance:</strong> The JSD analysis delivered definitive mathematical proof of our core thesis. Under a perfectly controlled experiment, the initial Riemannian model dropped the global divergence from <code>0.044667</code> to <strong><code>0.025385</code></strong>—a massive <strong><span class="math inline">\(43.2\%\)</span> relative reduction</strong> in distributional error caused simply by making the network topology-aware.</p></li>
<li><p><strong>The Riemannian Vector Field Scales Exceptionally Well:</strong> The v2 scaling experiment proved that our manifold framework handles larger architectures smoothly. Doubling network capacity, training time, and time resolution allowed the model to converge onto a highly optimized vector field without encountering overfitting or training instability. The final training loss reached a clear project minimum of <strong><code>2.19546</code></strong>.</p></li>
<li><p><strong>Near-Perfect Biological Distribution Alignment:</strong> By providing our manifold model with appropriate capacity (v2), we nearly bridged the remaining gap to the real-world data distribution. Global divergence dropped to a near-flawless <strong><code>0.010963</code></strong>, while the generated points matched the biological target regions with exceptional accuracy:</p></li>
</ul>
<p><span class="math display">\[\begin{aligned}
\alpha\text{-helix Coverage:} \quad \text{Euclid (v1)}: 20.5\% &amp;\longrightarrow \text{Riem (v1)}: 25.0\% \longrightarrow \mathbf{\text{Riem (v2)}: 30.3\%} \quad \text{[GT Target: 32.9\%]} \\
\beta\text{-sheet Coverage:} \quad \text{Euclid (v1)}: 15.4\% &amp;\longrightarrow \text{Riem (v1)}: 18.1\% \longrightarrow \mathbf{\text{Riem (v2)}: 20.1\%} \quad \text{[GT Target: 22.1\%]}
\end{aligned}\]</span></p>
<p><br></p>
<p>This final phase confirms that embedding the correct mathematical topology directly into generative AI pipelines provides an incredibly robust, highly scalable framework. Given proper optimization capacity, this architecture completely eliminates boundary-tear artifacts, capturing the underlying nature of periodic biological structures with exceptional fidelity.</p>
<hr>
</section>
</section>
<section id="project-summary" class="level3">
<h3 class="anchored" data-anchor-id="project-summary">PROJECT SUMMARY</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Project Phase</th>
<th>Main Objective</th>
<th>Core Computational Tool</th>
<th>Biological Insight Achieved</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Stage 1</strong></td>
<td>Data Cleaning &amp; Parsing</td>
<td>Angular File Conversion &amp; Filtering</td>
<td>Created an uncorrupted dataset of 50,000 structural points.</td>
</tr>
<tr class="even">
<td><strong>Stage 2</strong></td>
<td>Topological Definition</td>
<td>Riemannian Metric Tensor (<span class="math inline">\(g = I_2\)</span>)</td>
<td>Proved the data space is intrinsically a <strong>flat torus</strong> (<span class="math inline">\(K = 0\)</span>).</td>
</tr>
<tr class="odd">
<td><strong>Stage 3</strong></td>
<td>Geometric Navigation</td>
<td>Tangent Space <span class="math inline">\(\text{exp\_map}\)</span> &amp; <span class="math inline">\(\text{log\_map}\)</span></td>
<td>Fixed broken distance calculations across the <span class="math inline">\(\pm\pi\)</span> edge horizons.</td>
</tr>
<tr class="even">
<td><strong>Stage 4</strong></td>
<td>Pathway Generation</td>
<td>Geodesic Path Interpolation (<span class="math inline">\(\gamma(t)\)</span>)</td>
<td>Created smooth, physically accurate molecular morphing paths.</td>
</tr>
<tr class="odd">
<td><strong>Stage 5</strong></td>
<td>Baseline Deep Learning</td>
<td>Trigonometric Vector Field MLP &amp; Euclidean CFM Loss</td>
<td>Proved that flat-plane optimization models split trajectories and yield poor biological generation coverage (<span class="math inline">\(35.9\%\)</span>).</td>
</tr>
<tr class="even">
<td><strong>Stage 6</strong></td>
<td>Manifold Generative Flow</td>
<td>Geodesic Integration Sampler &amp; Riemannian Loss <span class="math inline">\(\mathcal{L}_{\text{RCFM}}\)</span></td>
<td>Breakthrough performance; dropped convergence error floor from <span class="math inline">\(3.03\)</span> to <span class="math inline">\(2.38\)</span>, eliminating boundary artifacts and accelerating structural learning.</td>
</tr>
<tr class="odd">
<td><strong>Stage 7</strong></td>
<td>Discretization Validation</td>
<td>Geodesic Euler Integrator &amp; Step-Count Sensitivity Audit</td>
<td>Proved the manifold framework is robust against integration drift, maintaining high generative accuracy even at an ultra-low budget of 10 steps (<span class="math inline">\(25.6\%\)</span>).</td>
</tr>
<tr class="even">
<td><strong>Stage 8</strong></td>
<td>Spatial Density Diagnostics</td>
<td>Kernel Density Estimation (KDE) Grid Diff Mapping</td>
<td>Discovered that the <span class="math inline">\(\beta\)</span>-sheet is highly vulnerable to flat-plane models due to its proximity to the edge (<strong>0.175 rad</strong>), proving that Riemannian paths natively eliminate boundary-tear artifacts.</td>
</tr>
<tr class="odd">
<td><strong>Stage 9</strong></td>
<td>Comprehensive Evaluation &amp; Scaling</td>
<td>Expanded v2 Model (512 Dim) &amp; Jensen-Shannon Divergence</td>
<td>Proved the scalability of the manifold framework; achieved a <strong>43.2% relative error reduction</strong> in v1, and near-perfectly matched the true biological distribution in v2 (JSD: <strong>0.010963</strong>).</td>
</tr>
</tbody>
</table>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shreeshb51\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Shreesh Bhattarai · GDL &amp; COT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/shreeshb51">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/shreesh-bhattarai-1ba1681bb/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>