# B.Sc. Computational Mathematics
**Total program credits: 144**

---

## Year I

### Semester I

| Code     | Course Title                | Credits |
| -------- | --------------------------- | ------: |
| PHYS 101 | General Physics I           |       3 |
| MATH 101 | Calculus and Linear Algebra |       3 |
| CHEM 101 | General Chemistry           |       3 |
| BIOL 103 | General Biology             |       3 |
| COMP 102 | Computer Programming        |       3 |
| EDRG 101 | Engineering Drawing         |       2 |
| ENGG 101 | Project                     |       2 |
| **Total**|                             |  **19** |

### Semester II

| Code     | Course Title                | Credits |
| -------- | --------------------------- | ------: |
| PHYS 102 | General Physics II          |       3 |
| MATH 103 | Linear Algebra              |       3 |
| CHEM 102 | Inorganic Chemistry         |       2 |
| ENGG 112 | Elements of Engineering II  |       3 |
| COMP 116 | Object Oriented Programming |       3 |
| ENGT 105 | Technical Communication     |       3 |
| EDRG 102 | Engineering Drawing         |       2 |
| ENGG 102 | Project                     |       2 |
| **Total**|                             |  **21** |

---

## Year II

### Semester I

| Code     | Course Title                 | Credits |
| -------- | ---------------------------- | ------: |
| MCSC 201 | Discrete Structure           |       3 |
| MATH 201 | Advanced Calculus            |       3 |
| MATH 204 | Analytical Geometry          |       3 |
| MATH 208 | Statistics & Probability     |       3 |
| COMP 202 | Data Structure and Algorithm |       3 |
| EEEG 202 | Digital Logic                |       3 |
| **Total**|                              |  **18** |

### Semester II

| Code     | Course Title                                | Credits |
| -------- | ------------------------------------------- | ------: |
| MATH 211 | Mechanics                                   |       3 |
| MATH 213 | Analysis I                                  |       3 |
| MSCS 202 | Numerical Methods                           |       3 |
| MATH 217 | Ordinary and Partial Differential Equations |       3 |
| COMP 204 | Communication & Networking                  |       3 |
| COMP 232 | Database Management System                  |       3 |
| MATH 252 | Math Project                                |       1 |
| **Total**|                                             |  **19** |

---

## Year III

### Semester I

| Code     | Course Title                         | Credits |
| -------- | ------------------------------------ | ------: |
| MATH 302 | Matrix Theory                        |       3 |
| MATH 304 | Computational Operations Research    |       3 |
| MATH 326 | Complex Variables                    |       3 |
| MGTS 301 | Economics                            |       3 |
| COMP 315 | Computer Architecture & Organization |       3 |
| COMP 316 | Theory of Computation                |       3 |
| COMP 311 | Combined Project                     |       1 |
| **Total**|                                      |  **19** |

### Semester II

| Code     | Course Title           | Credits |
| -------- | ---------------------- | ------: |
| MATH 322 | Combinatorics          |       3 |
| COMP 323 | Graph Theory           |       3 |
| MATH 325 | Analysis II            |       3 |
| MATH 327 | Number Theory          |       3 |
| COMP 307 | Operating System       |       3 |
| COMP 314 | Algorithm & Complexity |       3 |
| MATH 352 | Math Project           |       1 |
| **Total**|                        |  **19** |

---

## Year IV

### Semester I

| Code     | Course Title             | Credits |
| -------- | ------------------------ | ------: |
| MATH 402 | Modern Algebra           |       3 |
| MATH 403 | Computational Statistics |       3 |
| MGTS 403 | Engineering Management   |       3 |
| COMP 401 | Software Engineering     |       3 |
| COMP 472 | Artificial Intelligence  |       3 |
| MATH 451 | Math Seminar             |       2 |
| **Total**|                          |  **17** |

### Semester II

| Code                | Course Title         | Credits |
| ------------------- | -------------------- | ------: |
| MGTS 402            | Entrepreneurship     |       3 |
| MATH 404            | Mathematical Modeling |       3 |
| MATH 499 | Project  |       6 |
| **Total**           |                      |  **12** |

---

*Source: [Department of Mathematics, Kathmandu University](https://math.ku.edu.np/b-sc-in-computational-mathematics)*
