<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mathematical_framework – Shreesh Bhattarai</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-088498ae819e247f230a120db35b6777.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shreesh Bhattarai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../catw/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Along the Way</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../papers/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper Comprehensions</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#mathematical-framework-for-project-1---wasserstein-distance-as-loss-function-for-image-morphing" id="toc-mathematical-framework-for-project-1---wasserstein-distance-as-loss-function-for-image-morphing" class="nav-link active" data-scroll-target="#mathematical-framework-for-project-1---wasserstein-distance-as-loss-function-for-image-morphing">Mathematical Framework for Project 1 - Wasserstein Distance as Loss Function for Image Morphing</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="mathematical-framework-for-project-1---wasserstein-distance-as-loss-function-for-image-morphing" class="level2">
<h2 class="anchored" data-anchor-id="mathematical-framework-for-project-1---wasserstein-distance-as-loss-function-for-image-morphing">Mathematical Framework for Project 1 - Wasserstein Distance as Loss Function for Image Morphing</h2>
<p>Before any optimal transport can happen, we need two objects to <em>transport between</em>. This code is the moment we reach into a dataset of 60,000 handwritten digits and pull out exactly two images — one “3” and one “8” — that will become the <strong>source and target measures</strong> of our Wasserstein geodesic. Every subsequent computation flows from these two arrays.</p>
<hr>
<p><strong>We take anchor example and use it consistently and cumulatively throughout all subsequent explanations.</strong></p>
<p>We pretend MNIST contains six toy samples, each a 2×2 pixel image. The six images have labels:</p>
<p><span class="math display">\[\mathbf{y} = (3,\ 7,\ 8,\ 3,\ 1,\ 8)\]</span></p>
<p>The two images we care about are:</p>
<p><span class="math display">\[A^{(3)} = \begin{pmatrix} 0 &amp; 180 \\ 200 &amp; 255 \end{pmatrix}, \qquad A^{(8)} = \begin{pmatrix} 210 &amp; 255 \\ 180 &amp; 240 \end{pmatrix}\]</span></p>
<p>Each entry is an integer in <span class="math inline">\(\{0, \ldots, 255\}\)</span>, where 0 is black and 255 is white.</p>
<hr>
<p><strong><code>labels = np.array([label for _, label in mnist])</code></strong></p>
<p>The MNIST dataset returns pairs <span class="math inline">\((\text{image},\ \text{label})\)</span>. This line <strong>throws away every image</strong> and collects only the integer class labels into a single vector. The underscore <code>_</code> is a Python convention for “I am deliberately ignoring this value.”</p>
<p>Mathematically, we are constructing the label sequence:</p>
<p><span class="math display">\[\mathbf{y} = (y_0,\ y_1,\ \ldots,\ y_{N-1}), \qquad y_i \in \{0, 1, \ldots, 9\}, \qquad N = 60000\]</span></p>
<p>Think of <span class="math inline">\(\mathbf{y}\)</span> as a function <span class="math inline">\(\mathbf{y}: \{0,\ldots,N-1\} \to \{0,\ldots,9\}\)</span> — it maps a dataset index to a digit class.</p>
<p>On the anchor: <span class="math inline">\(\mathbf{y} = (3,\ 7,\ 8,\ 3,\ 1,\ 8)\)</span>, so <span class="math inline">\(N = 6\)</span>.</p>
<hr>
<p><strong><code>idx_3 = np.where(labels == 3)[0][0]</code></strong></p>
<p><code>np.where(labels == 3)</code> returns every index <span class="math inline">\(i\)</span> where <span class="math inline">\(y_i = 3\)</span>. We then take <code>[0][0]</code> — the first element of that list — giving us the <strong>earliest occurrence</strong> of a “3” in the dataset.</p>
<p>Mathematically:</p>
<p><span class="math display">\[\mathcal{I}_3 = \{i \in \{0,\ldots,N-1\} : y_i = 3\}, \qquad i_3 = \min(\mathcal{I}_3)\]</span></p>
<p>The set <span class="math inline">\(\mathcal{I}_3\)</span> might contain thousands of elements — there are roughly 6,000 threes in MNIST. We take the minimum purely for <strong>reproducibility</strong>: given the same dataset, we always get the same image. No statistical significance is claimed for this particular “3.”</p>
<p>On the anchor: <span class="math inline">\(\mathcal{I}_3 = \{0, 3\}\)</span>, so <span class="math inline">\(i_3 = \min\{0,3\} = 0\)</span>. Similarly: <span class="math inline">\(\mathcal{I}_8 = \{2, 5\}\)</span>, so <span class="math inline">\(i_8 = \min\{2,5\} = 2\)</span>.</p>
<hr>
<p><strong><code>img_3 = np.array(mnist[idx_3][0], dtype=np.float64)</code></strong></p>
<p><code>mnist[idx_3]</code> retrieves the pair <span class="math inline">\((\text{image},\ \text{label})\)</span> at position <span class="math inline">\(i_3\)</span>. The <code>[0]</code> selects just the image (a PIL Image object).</p>
<p><code>np.array(..., dtype=np.float64)</code> converts it into a 2D NumPy array of <strong>64-bit floating-point numbers</strong>.</p>
<p>This is a <strong>type cast</strong>, not a value change:</p>
<p><span class="math display">\[A^{(3)} \in \{0,\ldots,255\}^{28\times28} \xrightarrow{\ \text{cast}\ } A^{(3)} \in \mathbb{R}^{28\times28}\]</span></p>
<p>The value 180 becomes 180.0 — identical numerically, but now living in <span class="math inline">\(\mathbb{R}\)</span> rather than <span class="math inline">\(\mathbb{Z}\)</span>.</p>
<p><strong>Why does this matter so much?</strong> Consider what is coming:</p>
<ol type="1">
<li><strong>Normalization</strong> requires dividing by the pixel sum. In integer arithmetic, <span class="math inline">\(1 / 635 = 0\)</span> (truncated). In float64, <span class="math inline">\(1.0 / 635.0 = 0.001574\ldots\)</span> — correct.</li>
<li><strong>Sinkhorn iterations</strong> require computing <span class="math inline">\(\log\)</span> of pixel values. <span class="math inline">\(\log\)</span> is not defined on integers in NumPy without a cast.</li>
<li><strong>Barycentric interpolation</strong> produces values like <span class="math inline">\(0.3 \cdot 180.0 + 0.7 \cdot 210.0 = 201.0\)</span> — fractional arithmetic is essential throughout.</li>
</ol>
<p>The choice of <strong>float64</strong> (rather than float32) is deliberate: Sinkhorn iterations involve repeated multiplication of numbers close to zero (exponentials of negative costs scaled by small <span class="math inline">\(\varepsilon\)</span>), and float32’s ~7 decimal digits of precision can cause <strong>numerical underflow</strong> that corrupts the transport plan. float64 gives ~15 digits.</p>
<p>On the anchor, after the cast:</p>
<p><span class="math display">\[A^{(3)} = \begin{pmatrix} 0.0 &amp; 180.0 \\ 200.0 &amp; 255.0 \end{pmatrix}, \qquad A^{(8)} = \begin{pmatrix} 210.0 &amp; 255.0 \\ 180.0 &amp; 240.0 \end{pmatrix}\]</span></p>
<hr>
<pre><code>pixel range before normalization: [0.0, 255.0]</code></pre>
<p>This confirms two facts that will drive the process fowrward:</p>
<ul>
<li>The <strong>minimum is 0.0</strong> — the background pixels. These are <em>problematic</em> for optimal transport, because a pixel with value 0 carries zero mass, and we need to decide how to handle that (you’ll see a small <span class="math inline">\(\epsilon\)</span> regularization added during normalization).</li>
<li>The <strong>maximum is 255.0</strong> — the brightest ink pixel. The <em>ratio</em> between these extremes spans three orders of magnitude, which is why naive normalization (divide by 255) would leave most of the image near zero mass.</li>
</ul>
<hr>
<p>We hold two raw pixel matrices <span class="math inline">\(A^{(3)}, A^{(8)} \in [0.0,\ 255.0]^{28 \times 28}\)</span> as float64 arrays. They are <strong>not yet valid probability measures</strong>: their entries are not normalized (they don’t sum to 1), some entries are exactly zero (which causes <span class="math inline">\(\log(0) = -\infty\)</span> in Sinkhorn), and they are still 2D grids rather than distributions over a metric space. All three of these issues must be resolved before optimal transport is computable.</p>
<p>Right now, the sums of pixels of two selected images: <span class="math inline">\(35867.0\)</span> and <span class="math inline">\(27106.0\)</span> are <strong>unequal</strong>. This is the first concrete signal that the two images, when normalized to probability measures, will have different “mass distributions” — and is precisely why naive pixel blending (which ignores mass geometry entirely) produces different results from Wasserstein interpolation.</p>
<hr>
<p>The raw pixel arrays are just grids of brightness values — they carry no probabilistic structure. Optimal transport is a theory about <em>moving mass between probability measures</em>, so before we can apply a single result from OT theory, we must convert our images into valid probability measures.</p>
<hr>
<p>A <strong>discrete probability measure</strong> on a finite set <span class="math inline">\(\Omega\)</span> is a function <span class="math inline">\(\mu: \Omega \to [0,1]\)</span> satisfying:</p>
<p><span class="math display">\[\mu(i) \geq 0 \quad \forall i \in \Omega, \qquad \sum_{i \in \Omega} \mu(i) = 1\]</span></p>
<p>Here <span class="math inline">\(\Omega = \{0, 1, \ldots, n^2 - 1\}\)</span> is the set of <strong>pixel indices</strong> after flattening the <span class="math inline">\(n \times n\)</span> image into a 1D vector. For MNIST, <span class="math inline">\(n = 28\)</span>, so <span class="math inline">\(|\Omega| = 784\)</span>.</p>
<p>The interpretation is direct: <span class="math inline">\(\mu(i)\)</span> is the <strong>fraction of total ink mass</strong> sitting at pixel <span class="math inline">\(i\)</span>. A bright pixel carries a lot of mass; a background pixel carries none.</p>
<hr>
<p><strong><code>flat = img.flatten().astype(np.float64)</code></strong></p>
<p>Reshapes the 2D pixel grid into a 1D vector, destroying spatial structure in a controlled way:</p>
<p><span class="math display">\[A \in \mathbb{R}^{n \times n} \xrightarrow{\ \text{flatten}\ } \mathbf{a} \in \mathbb{R}^{n^2}\]</span></p>
<p>The mapping is row-major (C-order): row 0 is laid down first, then row 1, etc. Pixel at grid position <span class="math inline">\((r, c)\)</span> lands at index <span class="math inline">\(i = rn + c\)</span>.</p>
<p>On the anchor (<span class="math inline">\(n=2\)</span>):</p>
<p><span class="math display">\[A^{(3)} = \begin{pmatrix} 0.0 &amp; 180.0 \\ 200.0 &amp; 255.0 \end{pmatrix} \xrightarrow{\ \text{flatten}\ } \mathbf{a}^{(3)} = (0.0,\ 180.0,\ 200.0,\ 255.0)\]</span></p>
<p><span class="math display">\[A^{(8)} = \begin{pmatrix} 210.0 &amp; 255.0 \\ 180.0 &amp; 240.0 \end{pmatrix} \xrightarrow{\ \text{flatten}\ } \mathbf{a}^{(8)} = (210.0,\ 255.0,\ 180.0,\ 240.0)\]</span></p>
<p><strong>Why flatten?</strong> Optimal transport operates on measures over a <em>metric space of points</em>. Each pixel index <span class="math inline">\(i\)</span> will later be assigned a 2D coordinate <span class="math inline">\(\mathbf{x}_i = (r_i, c_i) \in \mathbb{R}^2\)</span>, and the cost of transporting mass from <span class="math inline">\(i\)</span> to <span class="math inline">\(j\)</span> will be <span class="math inline">\(\|\mathbf{x}_i - \mathbf{x}_j\|^2\)</span>. The 2D grid structure is preserved through this coordinate system — flattening just gives each pixel a single canonical index.</p>
<hr>
<p><strong><code>total = flat.sum()</code></strong></p>
<p>Computes the total brightness — the sum of all pixel values:</p>
<p><span class="math display">\[Z = \sum_{i=0}^{n^2-1} a_i\]</span></p>
<p>On the code:</p>
<p><span class="math inline">\(Z^{(3)} = 0.0 + 180.0 + 200.0 + 255.0 = 635.0\)</span>, and</p>
<p><span class="math inline">\(Z^{(8)} = 210.0 + 255.0 + 180.0 + 240.0 = 885.0\)</span>.</p>
<p><span class="math inline">\(Z\)</span> is the <strong>normalizing constant</strong> — the total mass before we impose the probability constraint. Notice <span class="math inline">\(Z^{(3)} \neq Z^{(8)}\)</span>: the two images have different total brightness. This is exactly what the print statement in previous output flagged (<span class="math inline">\(35867 \neq 27106\)</span>). After normalization, both measures will sum to 1, so this raw difference is absorbed — each measure describes a <em>shape of mass distribution</em>, not an absolute brightness.</p>
<hr>
<p><strong><code>return flat / total</code></strong></p>
<p>Divides every pixel value by the total, producing the normalized measure:</p>
<p><span class="math display">\[\mu(i) = \frac{a_i^{(3)}}{Z^{(3)}}, \qquad \nu(i) = \frac{a_i^{(8)}}{Z^{(8)}}\]</span></p>
<p>This guarantees <span class="math inline">\(\mu(i) \geq 0\)</span> for all <span class="math inline">\(i\)</span> (since pixel values are non-negative) and <span class="math inline">\(\sum_i \mu(i) = 1\)</span> (by construction).</p>
<p>On the code:</p>
<p><span class="math display">\[\mathbf{m} = \frac{1}{635}(0.0,\ 180.0,\ 200.0,\ 255.0) = (0.0,\ 0.2835,\ 0.3150,\ 0.4016)\]</span></p>
<p><span class="math display">\[\mathbf{v} = \frac{1}{885}(210.0,\ 255.0,\ 180.0,\ 240.0) = (0.2373,\ 0.2881,\ 0.2034,\ 0.2712)\]</span></p>
<p>Verify:</p>
<p><span class="math inline">\(0.0 + 0.2835 + 0.3150 + 0.4016 = 1.0\)</span>, and</p>
<p><span class="math inline">\(0.2373 + 0.2881 + 0.2034 + 0.2712 = 1.0\)</span></p>
<hr>
<section id="the-zero-mass-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-zero-mass-problem">THE ZERO MASS PROBLEM</h3>
<p>The output shows <code>m min: 0.000000</code>. This means <strong>background pixels carry exactly zero mass</strong>: <span class="math inline">\(\mu(i) = 0\)</span>, for every pixel that was black in the original image. This is mathematically valid for a probability measure, but it creates a serious numerical problem in the next stage.</p>
<p>Sinkhorn iterations require computing <span class="math inline">\(\log \mu(i)\)</span> for every <span class="math inline">\(i\)</span>. But:</p>
<p><span class="math display">\[\log(0) = -\infty\]</span></p>
<p>This would immediately produce <code>NaN</code> values and crash the entire computation. Handling this is one of the most important numerical decisions in the pipeline.</p>
<hr>
<p>We now hold two valid discrete probability measures:</p>
<p><span class="math display">\[\mathbf{m} \in \Delta^{783}, \qquad \mathbf{v} \in \Delta^{783}\]</span></p>
<p>where <span class="math inline">\(\Delta^{783} = \{\mathbf{p} \in \mathbb{R}^{784} : p_i \geq 0,\ \sum_i p_i = 1\}\)</span> is the <strong>783-dimensional probability simplex</strong>. The geometric intuition: each measure is a <em>point</em> on this simplex. The Wasserstein geodesic we want to compute is a <em>path</em> connecting these two points, measured with a distance that accounts for the underlying pixel geometry.</p>
<hr>
<p>The probability measures <span class="math inline">\(\mathbf{m}\)</span> and <span class="math inline">\(\mathbf{v}\)</span> currently live on an <strong>abstract index set</strong> <span class="math inline">\(\{0, 1, \ldots, 783\}\)</span> — just a list of 784 slots with no geometry. Optimal transport requires a <em>metric space</em>: we need to know the cost of moving mass from pixel <span class="math inline">\(i\)</span> to pixel <span class="math inline">\(j\)</span>, which requires knowing where <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> actually <em>are</em> in space. Thus, we <strong>embed the abstract index set into <span class="math inline">\(\mathbb{R}^2\)</span></strong> by assigning each pixel index its grid coordinates.</p>
<hr>
<p><strong><code>coords = np.array([[i // 28, i % 28] for i in range(784)], dtype=np.float64)</code></strong></p>
<p>For each flat index <span class="math inline">\(i \in \{0, \ldots, 783\}\)</span>, this recovers the corresponding 2D grid position via integer division and remainder — the exact inverse of the row-major flattening:</p>
<p><span class="math display">\[\mathbf{x}_i = \left(\left\lfloor \frac{i}{28} \right\rfloor,\ i \bmod 28\right) \in \{0,\ldots,27\}^2\]</span></p>
<p>The result is a matrix of pixel coordinates:</p>
<p><span class="math display">\[X = \begin{pmatrix} \mathbf{x}_0 \\ \mathbf{x}_1 \\ \vdots \\ \mathbf{x}_{783} \end{pmatrix} \in \mathbb{R}^{784 \times 2}\]</span></p>
<p>where row <span class="math inline">\(i\)</span> of <span class="math inline">\(X\)</span> is the spatial location of pixel <span class="math inline">\(i\)</span>.</p>
<p>On the anchor example (<span class="math inline">\(n=2\)</span>, so we divide by 2 instead of 28):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(i\)</span></th>
<th><span class="math inline">\(\lfloor i/2 \rfloor\)</span></th>
<th><span class="math inline">\(i \bmod 2\)</span></th>
<th><span class="math inline">\(\mathbf{x}_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>0</td>
<td><span class="math inline">\((0,\ 0)\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td>0</td>
<td>1</td>
<td><span class="math inline">\((0,\ 1)\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\((1,\ 0)\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td>1</td>
<td>1</td>
<td><span class="math inline">\((1,\ 1)\)</span></td>
</tr>
</tbody>
</table>
<p>So <span class="math inline">\(X = \begin{pmatrix} 0 &amp; 0 \\ 0 &amp; 1 \\ 1 &amp; 0 \\ 1 &amp; 1 \end{pmatrix}\)</span>, recovering exactly the four corners of the 2×2 grid. The flattening from code and the coordinate recovery here are <strong>consistent inverses</strong> of each other: pixel <span class="math inline">\((r, c)\)</span> flattens to index <span class="math inline">\(i = 2r + c\)</span>, and index <span class="math inline">\(i\)</span> recovers to <span class="math inline">\(\mathbf{x}_i = (\lfloor i/2 \rfloor, i \bmod 2) = (r, c)\)</span>.</p>
<hr>
<p>With coordinates in hand, we can now define the <strong>ground cost</strong> between any two pixels <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> as squared Euclidean distance:</p>
<p><span class="math display">\[c(i, j) = \|\mathbf{x}_i - \mathbf{x}_j\|^2 = \left(\left\lfloor\frac{i}{n}\right\rfloor - \left\lfloor\frac{j}{n}\right\rfloor\right)^2 + (i \bmod n - j \bmod n)^2\]</span></p>
<p>This is the cost a unit of mass <em>pays</em> to travel from pixel <span class="math inline">\(i\)</span> to pixel <span class="math inline">\(j\)</span>. It encodes the crucial geometric intuition: moving mass between nearby pixels is cheap; moving it across the image is expensive. This is what makes Wasserstein interpolation <strong>geometrically aware</strong> in a way that pixel blending is not — pixel blending has no notion of distance between pixel locations whatsoever.</p>
<p>On the anchor, the cost between pixel 0 (top-left, <span class="math inline">\((0,0)\)</span>) and pixel 3 (bottom-right, <span class="math inline">\((1,1)\)</span>) is:</p>
<p><span class="math display">\[c(0, 3) = (0-1)^2 + (0-1)^2 = 2\]</span></p>
<p>while the cost between pixel 0 and pixel 1 (its immediate neighbor) is:</p>
<p><span class="math display">\[c(0, 1) = (0-0)^2 + (0-1)^2 = 1\]</span></p>
<p>Transporting mass diagonally costs twice as much as transporting it one step horizontally or vertically.</p>
<hr>
<p>We now have three objects: measures <span class="math inline">\(\mathbf{m}, \mathbf{v} \in \Delta^{783}\)</span> and a coordinate matrix <span class="math inline">\(X \in \mathbb{R}^{784 \times 2}\)</span>.</p>
<hr>
<p>The cost matrix <span class="math inline">\(C\)</span> will have <span class="math inline">\(784^2 = 614{,}656\)</span> entries. This part commits to storing that full matrix — a deliberate trade-off we’ll examine. More importantly, it constructs the object that gives Wasserstein distance its geometric meaning: the <strong>ground cost matrix</strong> <span class="math inline">\(C\)</span>, where <span class="math inline">\(C_{ij}\)</span> encodes how expensive it is to move a unit of mass from pixel <span class="math inline">\(i\)</span> to pixel <span class="math inline">\(j\)</span>.</p>
<p>Without <span class="math inline">\(C\)</span>, optimal transport is blind to geometry. With it, the transport plan is forced to respect the spatial structure of the image.</p>
<hr>
<p>The ground cost is the squared Euclidean distance between pixel coordinates:</p>
<p><span class="math display">\[C_{ij} = \|\mathbf{x}_i - \mathbf{x}_j\|^2 = (r_i - r_j)^2 + (c_i - c_j)^2\]</span></p>
<p>for all <span class="math inline">\(i, j \in \{0, \ldots, n^2-1\}\)</span>, where <span class="math inline">\(\mathbf{x}_i = (r_i, c_i)\)</span> are the coordinates obtained earlier. This defines a <span class="math inline">\(784 \times 784\)</span> matrix:</p>
<p><span class="math display">\[C \in \mathbb{R}^{784 \times 784}_{\geq 0}, \qquad C_{ij} = C_{ji}, \qquad C_{ii} = 0\]</span></p>
<p>The symmetry <span class="math inline">\(C_{ij} = C_{ji}\)</span> reflects the fact that distance is symmetric — moving mass from <span class="math inline">\(i\)</span> to <span class="math inline">\(j\)</span> costs the same as the reverse. The zero diagonal <span class="math inline">\(C_{ii} = 0\)</span> reflects the fact that keeping mass in place is free.</p>
<hr>
<p><strong><code>diff = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]</code></strong></p>
<p>This is the key broadcasting step. Let’s unpack it carefully.</p>
<p><code>coords</code> has shape <span class="math inline">\((784, 2)\)</span>. The two index manipulations reshape it for broadcasting:</p>
<p><span class="math display">\[\texttt{coords[:, np.newaxis, :]} \quad \text{has shape } (784, 1, 2) \quad \longleftrightarrow \quad \mathbf{x}_i \text{ varies along axis 0}\]</span></p>
<p><span class="math display">\[\texttt{coords[np.newaxis, :, :]} \quad \text{has shape } (1, 784, 2) \quad \longleftrightarrow \quad \mathbf{x}_j \text{ varies along axis 1}\]</span></p>
<p>NumPy broadcasts these to shape <span class="math inline">\((784, 784, 2)\)</span>, computing:</p>
<p><span class="math display">\[\texttt{diff}[i, j, :] = \mathbf{x}_i - \mathbf{x}_j = \begin{pmatrix} r_i - r_j \\ c_i - c_j \end{pmatrix}\]</span></p>
<p>simultaneously for all <span class="math inline">\(784 \times 784\)</span> pairs <span class="math inline">\((i,j)\)</span> — no Python loop required.</p>
<p>On the anchor example (<span class="math inline">\(n=2\)</span>, four pixels with coordinates <span class="math inline">\((0,0),(0,1),(1,0),(1,1)\)</span>):</p>
<p><span class="math display">\[\texttt{diff}[0, 3, :] = (0,0) - (1,1) = (-1, -1)\]</span> <span class="math display">\[\texttt{diff}[0, 1, :] = (0,0) - (0,1) = (0, -1)\]</span> <span class="math display">\[\texttt{diff}[2, 1, :] = (1,0) - (0,1) = (1, -1)\]</span></p>
<hr>
<p><strong><code>C = np.sum(diff ** 2, axis=-1)</code></strong></p>
<p>Squares each component and sums along the last axis (the 2D coordinate axis), collapsing shape <span class="math inline">\((784, 784, 2) \to (784, 784)\)</span>:</p>
<p><span class="math display">\[C_{ij} = \sum_{k \in \{0,1\}} \texttt{diff}[i,j,k]^2 = (r_i - r_j)^2 + (c_i - c_j)^2\]</span></p>
<p>On the anchor, we have four pixels with coordinates:</p>
<p><span class="math display">\[\mathbf{x}_0 = (0,0), \quad \mathbf{x}_1 = (0,1), \quad \mathbf{x}_2 = (1,0), \quad \mathbf{x}_3 = (1,1)\]</span></p>
<p>Each entry <span class="math inline">\(C_{ij} = (r_i - r_j)^2 + (c_i - c_j)^2\)</span>. Work through row 0 explicitly:</p>
<p><span class="math display">\[C_{00} = (0-0)^2 + (0-0)^2 = 0\]</span> <span class="math display">\[C_{01} = (0-0)^2 + (0-1)^2 = 0 + 1 = 1\]</span> <span class="math display">\[C_{02} = (0-1)^2 + (0-0)^2 = 1 + 0 = 1\]</span> <span class="math display">\[C_{03} = (0-1)^2 + (0-1)^2 = 1 + 1 = 2\]</span></p>
<p>All obtained through broadcasting step stated earlier. The full <span class="math inline">\(4\times 4\)</span> cost matrix is:</p>
<p><span class="math display">\[C = \begin{pmatrix} 0 &amp; 1 &amp; 1 &amp; 2 \\ 1 &amp; 0 &amp; 2 &amp; 1 \\ 1 &amp; 2 &amp; 0 &amp; 1 \\ 2 &amp; 1 &amp; 1 &amp; 0 \end{pmatrix}\]</span></p>
<p>Read this as: moving mass from pixel 0 (top-left) to pixel 3 (bottom-right) costs 2; moving it one step right or down costs 1; staying put costs 0. The maximum cost is 2, achieved by the diagonal traversal — consistent with <span class="math inline">\(c(0,3) = (-1)^2 + (-1)^2 = 2\)</span>.</p>
<p>The print statement verifies this on the real grid: <span class="math inline">\(C_{0,27} = 27^2 = 729\)</span> (moving across an entire row) and <span class="math inline">\(C_{0,783} = 27^2 + 27^2 = 1458\)</span> (moving corner to corner).</p>
<hr>
<p>Using <span class="math inline">\(\|\mathbf{x}_i - \mathbf{x}_j\|^2\)</span> rather than <span class="math inline">\(\|\mathbf{x}_i - \mathbf{x}_j\|\)</span> gives us the <strong><span class="math inline">\(W_2\)</span> Wasserstein distance</strong> (the “2” refers to this exponent). This choice has deep consequences:</p>
<ul>
<li>It makes the optimization problem strongly convex (a line connecting any two points on the graph always sits above or on the graph), which improves numerical behavior.</li>
<li>The <span class="math inline">\(W_2\)</span> geodesic between two measures has a clean characterization via <strong>displacement interpolation</strong> — mass moves in straight lines in <span class="math inline">\(\mathbb{R}^2\)</span>, which is precisely what will give us the morphing effect.</li>
<li>It connects to a rich mathematical theory (Brenier’s theorem, McCann’s interpolation) that <span class="math inline">\(W_1\)</span> (with linear cost) does not enjoy in the same form.</li>
</ul>
<hr>
<p>The <span class="math inline">\(784^2 \approx 614\text{K}\)</span> entries as a concern. At float64, this is <span class="math inline">\(614656 \times 8 \approx 4.9\ \text{MB}\)</span> — large but manageable on modern hardware for a one-time computation. The alternative (computing <span class="math inline">\(C_{ij}\)</span> on the fly during each Sinkhorn iteration) would be slower. This is a classic <strong>memory-vs-compute trade-off</strong>, and here memory wins because <span class="math inline">\(C\)</span> is used repeatedly across many iterations.</p>
<hr>
<p>We now hold the complete problem specification for discrete optimal transport:</p>
<ul>
<li>Source measure: <span class="math inline">\(\mathbf{m} \in \Delta^{783}\)</span></li>
<li>Target measure: <span class="math inline">\(\mathbf{v} \in \Delta^{783}\)</span><br>
</li>
<li>Ground cost: <span class="math inline">\(C \in \mathbb{R}^{784 \times 784}_{\geq 0}\)</span></li>
</ul>
<hr>
<p>The unregularized OT problem is:</p>
<p><span class="math display">\[\min_{\gamma \geq 0} \sum_{ij} C_{ij} \gamma_{ij} \qquad \text{subject to} \qquad \gamma \mathbf{1} = \mathbf{m}, \quad \gamma^\top \mathbf{1} = \mathbf{v}\]</span></p>
<p>The entropy-regularized version adds a penalty that discourages <span class="math inline">\(\gamma\)</span> from being too “concentrated”:</p>
<p><span class="math display">\[\min_{\gamma \geq 0} \sum_{ij} C_{ij} \gamma_{ij} - \varepsilon \underbrace{\sum_{ij} \gamma_{ij} \log \gamma_{ij}}_{-H(\gamma)} \qquad \text{subject to} \qquad \gamma \mathbf{1} = \mathbf{m}, \quad \gamma^\top \mathbf{1} = \mathbf{v}\]</span></p>
<p>where <span class="math inline">\(H(\gamma) = -\sum_{ij} \gamma_{ij} \log \gamma_{ij}\)</span> is the <strong>entropy</strong> of <span class="math inline">\(\gamma\)</span>. Maximizing entropy means spreading mass as diffusely as possible. The <span class="math inline">\(-\varepsilon H(\gamma)\)</span> term therefore fights against concentration — and <span class="math inline">\(\varepsilon &gt; 0\)</span> controls how hard it fights.</p>
<p>Two effects follow immediately:</p>
<ol type="1">
<li><strong>Convexity:</strong> <span class="math inline">\(-H(\gamma)\)</span> is strictly convex, so the full objective is strictly convex — unique minimizer guaranteed.</li>
<li><strong>Smoothness:</strong> The entropic term is differentiable everywhere, unlike the linear program’s sharp corners. Iterative algorithms converge smoothly rather than bouncing between vertices of a polytope.</li>
</ol>
<p>The trade-off: the solution <span class="math inline">\(\gamma_\varepsilon\)</span> is a <strong>blurred approximation</strong> of the true OT plan. As <span class="math inline">\(\varepsilon \to 0\)</span>, <span class="math inline">\(\gamma_\varepsilon \to \gamma^*\)</span>. As <span class="math inline">\(\varepsilon \to \infty\)</span>, <span class="math inline">\(\gamma_\varepsilon \to \mathbf{m}\mathbf{v}^\top\)</span> — the independent coupling, which ignores cost entirely.</p>
<hr>
<p>The key insight that makes Sinkhorn work is that this regularized problem has an <strong>analytical solution</strong> in terms of its Lagrange multipliers. Setting up the Lagrangian for the marginal constraints and solving gives:</p>
<p><span class="math display">\[\gamma_{ij} = \exp\!\left(\frac{f_i + g_j - C_{ij}}{\varepsilon}\right)\]</span></p>
<p>where <span class="math inline">\(\mathbf{f} \in \mathbb{R}^{784}\)</span> and <span class="math inline">\(\mathbf{g} \in \mathbb{R}^{784}\)</span> are the <strong>dual potentials</strong> — one scalar per source pixel, one per target pixel. They are the Lagrange multipliers for the marginal constraints, and they play the role of “prices”: <span class="math inline">\(f_i\)</span> is the price of shipping mass <em>out of</em> pixel <span class="math inline">\(i\)</span>, <span class="math inline">\(g_j\)</span> is the price of receiving mass <em>into</em> pixel <span class="math inline">\(j\)</span>.</p>
<p>The marginal constraints then become:</p>
<p><span class="math display">\[\sum_j \exp\!\left(\frac{f_i + g_j - C_{ij}}{\varepsilon}\right) = m_i \qquad \forall i\]</span></p>
<p><span class="math display">\[\sum_i \exp\!\left(\frac{f_i + g_j - C_{ij}}{\varepsilon}\right) = v_j \qquad \forall j\]</span></p>
<p>Sinkhorn solves these two equations by <strong>alternating</strong>: fix <span class="math inline">\(\mathbf{g}\)</span>, solve for <span class="math inline">\(\mathbf{f}\)</span>; fix <span class="math inline">\(\mathbf{f}\)</span>, solve for <span class="math inline">\(\mathbf{g}\)</span>; repeat until convergence. Each step has a closed form — that’s why the algorithm is so efficient.</p>
<hr>
<p><strong><code>log_mu = np.log(m + 1e-300)</code></strong></p>
<p>Computes <span class="math inline">\(\log m_i\)</span> for every pixel, with a numerical guard:</p>
<p><span class="math display">\[\tilde{\ell}_i = \log(m_i + \epsilon_{\text{guard}}), \qquad \epsilon_{\text{guard}} = 10^{-300}\]</span></p>
<p><span class="math inline">\(10^{-300}\)</span> is chosen to be smaller than any meaningful pixel mass (the smallest nonzero value in <span class="math inline">\(\mathbf{m}\)</span> is <span class="math inline">\(1/35867 \approx 2.8 \times 10^{-5}\)</span>) but large enough to keep <span class="math inline">\(\log\)</span> finite. It doesn’t alter any nonzero value — <span class="math inline">\(\log(2.8\times10^{-5} + 10^{-300}) \approx \log(2.8\times10^{-5})\)</span> to full float64 precision. It only saves the zero-mass background pixels from producing <span class="math inline">\(-\infty\)</span>.</p>
<p>On the anchor, <span class="math inline">\(\mathbf{m} = (0.0,\ 0.2835,\ 0.3150,\ 0.4016)\)</span>:</p>
<p><span class="math display">\[\log_{mu} = (\log(10^{-300}),\ \log(0.2835),\ \log(0.3150),\ \log(0.4016)) \approx (-690.8,\ -1.261,\ -1.155,\ -0.912)\]</span></p>
<hr>
<p><strong><code>f = np.zeros(len(m))</code></strong><br>
<strong><code>g = np.zeros(len(v))</code></strong></p>
<p>Initializes both dual potentials to zero:</p>
<p><span class="math display">\[\mathbf{f}^{(0)} = \mathbf{0} \in \mathbb{R}^{784}, \qquad \mathbf{g}^{(0)} = \mathbf{0} \in \mathbb{R}^{784}\]</span></p>
<p>With <span class="math inline">\(\mathbf{f} = \mathbf{g} = \mathbf{0}\)</span>, the transport plan formula gives <span class="math inline">\(\gamma_{ij} = \exp(-C_{ij}/\varepsilon)\)</span> — mass is distributed according to cost alone, with no marginal constraints enforced yet. Sinkhorn iterations will progressively correct this.</p>
<hr>
<p><strong><code>f = epsilon * log_mu - epsilon * scipy_logsumexp((g[np.newaxis, :] - C) / epsilon, axis=1)</code></strong></p>
<p>This is the Sinkhorn <span class="math inline">\(\mathbf{f}\)</span>-update. To derive it: the marginal constraint <span class="math inline">\(\sum_j \gamma_{ij} = m_i\)</span> with <span class="math inline">\(\gamma_{ij} = \exp((f_i + g_j - C_{ij})/\varepsilon)\)</span> gives:</p>
<p><span class="math display">\[\exp\!\left(\frac{f_i}{\varepsilon}\right) \sum_j \exp\!\left(\frac{g_j - C_{ij}}{\varepsilon}\right) = m_i\]</span></p>
<p>Taking <span class="math inline">\(\varepsilon \log\)</span> of both sides:</p>
<p><span class="math display">\[f_i = \varepsilon \log m_i - \varepsilon \log \sum_j \exp\!\left(\frac{g_j - C_{ij}}{\varepsilon}\right)\]</span></p>
<p>The second term is a <strong>log-sum-exp</strong> (LSE) — numerically unstable if computed naively (exponentials of large numbers overflow). <code>scipy_logsumexp</code> computes <span class="math inline">\(\log\sum_j \exp(z_j)\)</span> by factoring out <span class="math inline">\(\max_j z_j\)</span>, keeping everything finite. In compact notation:</p>
<p><span class="math display">\[f_i \leftarrow \varepsilon \log m_i - \varepsilon \operatorname{LSE}_j\!\left(\frac{g_j - C_{ij}}{\varepsilon}\right)\]</span></p>
<p>On the anchor at iteration 0 (with <span class="math inline">\(\mathbf{g} = \mathbf{0}\)</span>, <span class="math inline">\(\varepsilon = 0.01\)</span>, using <span class="math inline">\(C\)</span>):</p>
<p><span class="math display">\[f_0 \leftarrow \varepsilon \log m_0 - \varepsilon \operatorname{LSE}_j\!\left(\frac{0 - C_{0j}}{\varepsilon}\right) = 0.01 \cdot (-690.8) - 0.01 \cdot \operatorname{LSE}(0,\ -100,\ -100,\ -200)\]</span></p>
<p>The LSE is dominated by its largest argument (0), so <span class="math inline">\(\approx 0.01\cdot(-690.8) - 0.01\cdot 0 = -6.908\)</span>. The zero-mass pixel immediately gets a very negative potential — it will contribute negligible mass to the transport plan, as it should.</p>
<hr>
<p><strong><code>g = epsilon * log_nu - epsilon * scipy_logsumexp((f[:, np.newaxis] - C) / epsilon, axis=0)</code></strong></p>
<p>Identical structure, now enforcing the <em>target</em> marginal constraint <span class="math inline">\(\sum_i \gamma_{ij} = v_j\)</span>:</p>
<p><span class="math display">\[g_j \leftarrow \varepsilon \log \nu_j - \varepsilon \operatorname{LSE}_i\!\left(\frac{f_i - C_{ij}}{\varepsilon}\right)\]</span></p>
<p>Note <code>axis=0</code> — we sum over source pixels <span class="math inline">\(i\)</span> (rows) rather than target pixels <span class="math inline">\(j\)</span> (columns). The updated <span class="math inline">\(\mathbf{f}\)</span> from the previous line feeds directly into this computation, which is why the two updates are <strong>sequential within each iteration</strong>, not simultaneous.</p>
<hr>
<p><strong><code>if np.max(np.abs(f - f_prev)) &lt; tol: break</code></strong></p>
<p>Convergence check: if the largest change in any component of <span class="math inline">\(\mathbf{f}\)</span> between iterations is smaller than <span class="math inline">\(10^{-9}\)</span>, the potentials have stabilized and further iterations won’t change the transport plan meaningfully:</p>
<p><span class="math display">\[\|\mathbf{f}^{(k)} - \mathbf{f}^{(k-1)}\|_\infty &lt; 10^{-9} \implies \text{stop}\]</span></p>
<p>Only <span class="math inline">\(\mathbf{f}\)</span> is checked — because the two updates are coupled, convergence of <span class="math inline">\(\mathbf{f}\)</span> implies convergence of <span class="math inline">\(\mathbf{g}\)</span>.</p>
<hr>
<p><strong><code>log_pi = (f[:, np.newaxis] + g[np.newaxis, :] - C) / epsilon</code></strong><br>
<strong><code>pi = np.exp(log_pi)</code></strong></p>
<p>Once the potentials have converged, the transport plan is recovered via the analytical solution derived earlier:</p>
<p><span class="math display">\[\log \pi_{ij} = \frac{f_i + g_j - C_{ij}}{\varepsilon}, \qquad \pi_{ij} = \exp\!\left(\frac{f_i + g_j - C_{ij}}{\varepsilon}\right)\]</span></p>
<p>Computing in log-space first and exponentiating once at the end is critical — computing <span class="math inline">\(\exp(f_i/\varepsilon)\cdot\exp(g_j/\varepsilon)\cdot\exp(-C_{ij}/\varepsilon)\)</span> directly would overflow for small <span class="math inline">\(\varepsilon\)</span>.</p>
<p>On the anchor, after convergence, <span class="math inline">\(\pi\)</span> is a <span class="math inline">\(4\times4\)</span> matrix where <span class="math inline">\(\pi_{ij}\)</span> tells us exactly how much mass flows from source pixel <span class="math inline">\(i\)</span> to target pixel <span class="math inline">\(j\)</span>. Its row sums equal <span class="math inline">\(\mathbf{m}\)</span> and its column sums equal <span class="math inline">\(\mathbf{v}\)</span> — the marginal constraints are satisfied.</p>
<hr>
<p>The function <code>sinkhorn_log</code> is defined but not yet called — <span class="math inline">\(\varepsilon\)</span> hasn’t been chosen and no transport plan has been computed yet.</p>
<hr>
<p><strong><code>C_norm = C / C.max()</code></strong></p>
<p>Divides every entry of <span class="math inline">\(C\)</span> by its maximum value, rescaling the cost matrix to <span class="math inline">\([0, 1]\)</span>:</p>
<p><span class="math display">\[\tilde{C}_{ij} = \frac{C_{ij}}{\max_{kl} C_{kl}} = \frac{\|\mathbf{x}_i - \mathbf{x}_j\|^2}{1458}\]</span></p>
<p>On the anchor, <span class="math inline">\(\max C = 2\)</span> (top-left to bottom-right), so:</p>
<p><span class="math display">\[\tilde{C} = \frac{1}{2}\begin{pmatrix} 0 &amp; 1 &amp; 1 &amp; 2 \\ 1 &amp; 0 &amp; 2 &amp; 1 \\ 1 &amp; 2 &amp; 0 &amp; 1 \\ 2 &amp; 1 &amp; 1 &amp; 0 \end{pmatrix} = \begin{pmatrix} 0 &amp; 0.5 &amp; 0.5 &amp; 1 \\ 0.5 &amp; 0 &amp; 1 &amp; 0.5 \\ 0.5 &amp; 1 &amp; 0 &amp; 0.5 \\ 1 &amp; 0.5 &amp; 0.5 &amp; 0 \end{pmatrix}\]</span></p>
<p><strong>Why does this matter?</strong> Recall the Sinkhorn update involves <span class="math inline">\(\exp(g_j - C_{ij})/\varepsilon\)</span>. The argument of the exponential is <span class="math inline">\(C_{ij}/\varepsilon\)</span>. Without normalization, the maximum cost is 1458 and <span class="math inline">\(\varepsilon = 0.01\)</span>, giving exponent magnitudes up to <span class="math inline">\(1458/0.01 = 145800\)</span> — catastrophic overflow even in float64, whose maximum exponent is <span class="math inline">\(\approx 709\)</span>. After normalization the maximum is <span class="math inline">\(1/0.01 = 100\)</span> — well within float64 range. Normalizing <span class="math inline">\(C\)</span> effectively makes <span class="math inline">\(\varepsilon\)</span> meaningful as a fraction of the total cost scale.</p>
<hr>
<p><strong><code>pi, f, g = sinkhorn_log(m, v, C_norm, epsilon=epsilon, n_iter=1000)</code></strong></p>
<p>Executes the Sinkhorn iterations defined earlier with <span class="math inline">\(\varepsilon = 0.01\)</span>. This <span class="math inline">\(\varepsilon\)</span> sits close to the “sharp” end of the spectrum — recall that <span class="math inline">\(\varepsilon \to 0\)</span> recovers the true OT plan while <span class="math inline">\(\varepsilon \to \infty\)</span> gives the independent coupling <span class="math inline">\(\mathbf{m}\mathbf{v}^\top\)</span>. At <span class="math inline">\(\varepsilon = 0.01\)</span>, the transport plan is a good approximation of the true <span class="math inline">\(W_2\)</span> plan with only mild entropic blur.</p>
<hr>
<p>The print statements check the <strong>defining properties</strong> of a valid transport plan. Let’s state what each one is actually asserting mathematically.</p>
<p><code>pi row sums ≈ mu</code> checks the <strong>source marginal constraint</strong>:</p>
<p><span class="math display">\[\sum_{j=0}^{783} \pi_{ij} = m_i \quad \forall i\]</span></p>
<p>Every unit of mass that leaves source pixel <span class="math inline">\(i\)</span> must equal <span class="math inline">\(m_i\)</span> — nothing is created or destroyed.</p>
<p><code>pi col sums ≈ nu</code> checks the <strong>target marginal constraint</strong>:</p>
<p><span class="math display">\[\sum_{i=0}^{783} \pi_{ij} = v_j \quad \forall j\]</span></p>
<p>Every unit of mass arriving at target pixel <span class="math inline">\(j\)</span> must equal <span class="math inline">\(v_j\)</span>.</p>
<p><code>pi total mass: 1.0</code> follows directly from either marginal: <span class="math inline">\(\sum_{ij} \pi_{ij} = \sum_i m_i = 1\)</span>.</p>
<p>Together, these three constraints define the <strong>transport polytope</strong>:</p>
<p><span class="math display">\[\Pi(\mathbf{m}, \mathbf{v}) = \{\gamma \in \mathbb{R}^{784\times784}_{\geq 0} : \gamma\mathbf{1} = \mathbf{m},\ \gamma^\top\mathbf{1} = \mathbf{v}\}\]</span></p>
<p>The output confirms <span class="math inline">\(\pi \in \Pi(\mathbf{m}, \mathbf{v})\)</span> to tolerance <span class="math inline">\(10^{-6}\)</span> — Sinkhorn has found a valid coupling.</p>
<hr>
<p>We now hold the <strong>regularized optimal transport plan</strong> <span class="math inline">\(\pi \in \Pi(\mathbf{m}, \mathbf{v})\)</span>, a <span class="math inline">\(784 \times 784\)</span> matrix encoding how mass flows from every pixel of the “3” to every pixel of the “8”. This is the core geometric object the entire project was building toward.</p>
<hr>
<p>A <strong>one-line verification</strong> of solution quality outputs: <span class="math inline">\(0.009719\)</span>. It computes the total transport cost paid by the plan <span class="math inline">\(\pi\)</span> — the inner product of the cost matrix and the transport plan.</p>
<hr>
<p><strong><code>primal_cost = np.sum(C_norm * pi)</code></strong></p>
<p>Computes the elementwise product and sums all entries:</p>
<p><span class="math display">\[\langle C, \pi \rangle = \sum_{i=0}^{783} \sum_{j=0}^{783} \tilde{C}_{ij}\, \pi_{ij}\]</span></p>
<p>Each term <span class="math inline">\(\tilde{C}_{ij}\, \pi_{ij}\)</span> is the <strong>cost contribution</strong> of moving mass <span class="math inline">\(\pi_{ij}\)</span> from pixel <span class="math inline">\(i\)</span> to pixel <span class="math inline">\(j\)</span> at unit cost <span class="math inline">\(\tilde{C}_{ij}\)</span>. Summing over all pairs gives the total cost paid by the entire transport plan.</p>
<p>On the anchor, after convergence:</p>
<p><span class="math display">\[\langle C, \pi \rangle = \sum_{i,j} \tilde{C}_{ij}\,\pi_{ij} = 0 \cdot \pi_{00} + 0.5 \cdot \pi_{01} + 0.5 \cdot \pi_{02} + 1 \cdot \pi_{03} + \cdots\]</span></p>
<p>Each nonzero <span class="math inline">\(\tilde{C}_{ij}\)</span> penalizes mass that travels — the further it travels, the more it contributes to this sum.</p>
<hr>
<p><strong>What <span class="math inline">\(0.009719\)</span> means?</strong></p>
<p>This is the <strong>regularized Wasserstein cost</strong> — the objective value of the entropy-regularized OT problem evaluated at the solution <span class="math inline">\(\pi\)</span>. It is <em>not</em> quite the true <span class="math inline">\(W_2^2(\mu, \nu)\)</span>, because entropic regularization biases the cost downward (the entropy term encourages spreading, which moves some mass along cheaper-than-optimal paths). As <span class="math inline">\(\varepsilon \to 0\)</span>, this value converges to the true <span class="math inline">\(W_2^2\)</span>.</p>
<p>The value itself — <span class="math inline">\(0.009719\)</span> — is meaningful relative to the normalized cost scale <span class="math inline">\([0,1]\)</span>: it tells us the “3” and “8” are separated by a moderate transport distance, not trivially close and not maximally far.</p>
<hr>
<p><span class="math inline">\(\pi\)</span> is verified as both feasible and low-cost (primal cost is small relative to the cost scale). We now have full confidence in the transport plan. In figure, the log scale is necessary because most entries of <span class="math inline">\(\pi\)</span> are extremely close to zero — only pixels that are spatially near each other in the two images exchange significant mass. The sparsity structure of <span class="math inline">\(\pi\)</span> is itself a geometric statement: the transport plan concentrates mass along a narrow band near the diagonal, meaning the “3” and “8” are not wildly different in their spatial mass distributions.</p>
<hr>
<p>An empirical study of the <span class="math inline">\(\varepsilon\)</span> trade-off described is presented. Three values are tested; the primal cost strictly decreases as <span class="math inline">\(\varepsilon\)</span> decreases. This output makes the theoretical claim concrete.</p>
<hr>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\varepsilon\)</span></th>
<th>Primal cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(1.00\)</span></td>
<td><span class="math inline">\(0.063129\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.10\)</span></td>
<td><span class="math inline">\(0.040568\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0.01\)</span></td>
<td><span class="math inline">\(0.009719\)</span></td>
</tr>
</tbody>
</table>
<p>Each tenfold decrease in <span class="math inline">\(\varepsilon\)</span> pulls the cost significantly downward. The interpretation: at <span class="math inline">\(\varepsilon = 1.0\)</span>, the entropy term dominates and forces <span class="math inline">\(\pi\)</span> to spread mass diffusely — even expensive long-distance transport paths get used, inflating the cost. At <span class="math inline">\(\varepsilon = 0.01\)</span>, the cost term dominates and <span class="math inline">\(\pi\)</span> concentrates mass on cheap short-distance paths, approaching the true <span class="math inline">\(W_2\)</span> plan.</p>
<p>Mathematically, the regularized objective is:</p>
<p><span class="math display">\[\mathcal{L}_\varepsilon(\gamma) = \underbrace{\langle C, \gamma \rangle}_{\text{transport cost}} - \varepsilon \underbrace{H(\gamma)}_{\text{entropy}}\]</span></p>
<p>As <span class="math inline">\(\varepsilon\)</span> grows, maximizing <span class="math inline">\(H(\gamma)\)</span> increasingly overrides minimizing <span class="math inline">\(\langle C, \gamma \rangle\)</span>, pulling the solution toward the maximum-entropy coupling <span class="math inline">\(\mathbf{m}\mathbf{v}^\top\)</span>. Its cost on the anchor would be:</p>
<p><span class="math display">\[\langle C, \mathbf{m}\mathbf{v}^\top \rangle = \sum_{ij} C_{ij} m_i v_j\]</span></p>
<p>— a weighted average of all pairwise costs, with no geometric preference whatsoever.</p>
<hr>
<pre><code>print(f"epsilon={eps:.2f} -&gt; primal cost: {cost:.6f} | "
          f"marginals OK: {np.allclose(pi_eps.sum(axis=1), m, atol=1e-5)}")</code></pre>
<p>Outputs <code>marginals OK: True</code> across all three values. This is not a coincidence — the Sinkhorn updates are derived by enforcing the marginal constraints exactly at each step, regardless of <span class="math inline">\(\varepsilon\)</span>. The regularization affects <em>which</em> feasible point is selected, not whether the marginal constraints are satisfied.</p>
<hr>
<p>The choice <span class="math inline">\(\varepsilon = 0.01\)</span> used is now justified empirically: it gives the sharpest transport plan while remaining numerically stable after <span class="math inline">\(C\)</span> normalization.</p>
<hr>
<p>We further alias <code>f</code> and <code>g</code> to <code>phi</code> and <code>psi</code> — no computation. However, this reveals something worth examining carefully before we reach the interpolation.</p>
<hr>
<p>The dual potentials are the Lagrange multipliers from the regularized OT problem. Recall from previous statement that the transport plan is recovered as:</p>
<p><span class="math display">\[\pi_{ij} = \exp\!\left(\frac{\phi_i + \psi_j - \tilde{C}_{ij}}{\varepsilon}\right)\]</span></p>
<p>The range of <span class="math inline">\(\phi\)</span> is <span class="math inline">\([-6.9562,\ -0.0750]\)</span> — entirely negative. Think about what that means for a pixel with very negative <span class="math inline">\(\phi_i\)</span>, say <span class="math inline">\(\phi_i = -6.9562\)</span>.</p>
<p>Plugging into the formula: the numerator <span class="math inline">\(\phi_i + \psi_j - \tilde{C}_{ij}\)</span> is pulled very negative, so <span class="math inline">\(\pi_{ij} \approx \exp(-\text{large number}) \approx 0\)</span> for all <span class="math inline">\(j\)</span>.</p>
<p>Which pixels would have <span class="math inline">\(\phi_i \approx -6.9562\)</span>? Recall that the first Sinkhorn update is:</p>
<p><span class="math display">\[\phi_i \leftarrow \varepsilon \log m_i - \varepsilon \operatorname{LSE}_j\!\left(\frac{\psi_j - \tilde{C}_{ij}}{\varepsilon}\right)\]</span></p>
<p>The <span class="math inline">\(\varepsilon \log m_i\)</span> term dominates the initialization. For zero-mass background pixels, <span class="math inline">\(m_i \approx 10^{-300}\)</span>, giving <span class="math inline">\(\varepsilon \log m_i \approx 0.01 \times (-690) = -6.9\)</span>. So the most negative values of <span class="math inline">\(\phi\)</span> correspond precisely to background pixels — they are priced out of the transport plan, carrying negligible mass exactly as intended.</p>
<hr>
<p><span class="math inline">\(\phi\)</span> and <span class="math inline">\(\psi\)</span> are extracted and ready. They are not used directly in the interpolation — <span class="math inline">\(\pi\)</span> carries all the information needed. Their role here is interpretive: they confirm the dual certificate of optimality.</p>
<hr>
<p>We now compute the full regularized objective function — not just the transport cost, but the complete quantity that Sinkhorn actually minimized. It puts concrete numbers on the trade-off between cost and entropy that has been discussed theoretically.</p>
<hr>
<p><strong><code>H_pi = -np.sum(pi * np.log(pi + 1e-300))</code></strong></p>
<p>Computes the <strong>Shannon entropy</strong> of the transport plan:</p>
<p><span class="math display">\[H(\pi) = -\sum_{i,j} \pi_{ij} \log \pi_{ij}\]</span></p>
<p>Entropy measures how <em>spread out</em> <span class="math inline">\(\pi\)</span> is. If all mass were concentrated on a single <span class="math inline">\((i,j)\)</span> pair, <span class="math inline">\(H(\pi) = 0\)</span> — maximally concentrated. If mass were spread uniformly across all <span class="math inline">\(784^2\)</span> pairs, <span class="math inline">\(H(\pi) = \log(784^2) \approx 13.4\)</span> — maximally diffuse. The output <span class="math inline">\(H(\pi) = 8.95\)</span> sits between these extremes, reflecting a plan that is spread but not uniform — consistent with <span class="math inline">\(\varepsilon = 0.01\)</span> being small but nonzero.</p>
<hr>
<p><strong><code>primal_obj = np.sum(C_norm * pi) - epsilon * H_pi</code></strong></p>
<p>Evaluates the full regularized objective at the solution:</p>
<p><span class="math display">\[\mathcal{L}_\varepsilon(\pi) = \langle \tilde{C}, \pi \rangle - \varepsilon H(\pi) = 0.00971915 - 0.01 \times 8.94968029 = 0.00971915 - 0.08949680 = -0.07977765\]</span></p>
<p>The objective is <strong>negative</strong> — which is initially surprising. How can a minimization problem have a negative optimal value?</p>
<p>The answer: <span class="math inline">\(-\varepsilon H(\pi)\)</span> is always negative (entropy is non-negative, multiplied by <span class="math inline">\(-\varepsilon\)</span>), and for small <span class="math inline">\(\varepsilon\)</span> and a sufficiently diffuse <span class="math inline">\(\pi\)</span>, this entropy bonus can outweigh the transport cost. The negativity is not pathological — it simply reflects that the entropy regularization has shifted the objective below zero. As <span class="math inline">\(\varepsilon \to 0\)</span>, the entropy term vanishes and the objective returns to the non-negative transport cost <span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span>.</p>
<hr>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span></td>
<td><span class="math inline">\(0.00972\)</span></td>
<td>Cost paid to move mass geometrically</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\varepsilon H(\pi)\)</span></td>
<td><span class="math inline">\(0.08950\)</span></td>
<td>Entropy bonus collected for spreading</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathcal{L}_\varepsilon(\pi)\)</span></td>
<td><span class="math inline">\(-0.07978\)</span></td>
<td>Net objective — what Sinkhorn minimized</td>
</tr>
</tbody>
</table>
<p>The entropy bonus is nearly <strong>ten times larger</strong> than the transport cost at <span class="math inline">\(\varepsilon = 0.01\)</span>. This might seem to contradict the earlier claim that <span class="math inline">\(\varepsilon = 0.01\)</span> is “close to the sharp OT plan.” It doesn’t — the transport cost being small means the plan is geometrically efficient. The large entropy bonus is a separate statement: the plan is also quite spread, because even at <span class="math inline">\(\varepsilon = 0.01\)</span> there are <span class="math inline">\(784^2 \approx 614\text{K}\)</span> entries contributing to <span class="math inline">\(H(\pi)\)</span>.</p>
<hr>
<p>The solution is fully characterized: feasible (marginals match), geometrically efficient (low transport cost), and optimal for the regularized objective.</p>
<hr>
<p>As <span class="math inline">\(\varepsilon \to 0\)</span>, the plan <span class="math inline">\(\pi\)</span> sharpens toward a sparse deterministic map, <span class="math inline">\(H(\pi)\)</span> shrinks, and the entropy bonus collapses. The objective converges to the bare transport cost <span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span>.</p>
<hr>
<p>Now we verifiy one of the deepest theoretical guarantees in convex optimization: <strong>strong duality</strong>. The primal and dual objectives agree to within <span class="math inline">\(1.79 \times 10^{-10}\)</span> — essentially machine precision.</p>
<hr>
<p><strong><code>dual_obj = np.dot(phi, m) + np.dot(psi, v)</code></strong></p>
<p>Computes the <strong>dual objective</strong>:</p>
<p><span class="math display">\[\mathcal{D}(\phi, \psi) = \langle \phi, \mathbf{m} \rangle + \langle \psi, \mathbf{v} \rangle = \sum_{i} \phi_i m_i + \sum_j \psi_j v_j\]</span></p>
<p>Each term has a clean economic interpretation: <span class="math inline">\(\phi_i m_i\)</span> is the “revenue” collected at source pixel <span class="math inline">\(i\)</span> — the price <span class="math inline">\(\phi_i\)</span> times the mass <span class="math inline">\(m_i\)</span> available there. <span class="math inline">\(\psi_j v_j\)</span> is the revenue collected at target pixel <span class="math inline">\(j\)</span>. The dual objective is the total revenue across both sides of the transport market.</p>
<p>On the anchor:</p>
<p><span class="math display">\[\mathcal{D}(\phi, \psi) = \phi_0 \cdot 0.0 + \phi_1 \cdot 0.2835 + \phi_2 \cdot 0.3150 + \phi_3 \cdot 0.4016 + \psi_0 \cdot 0.2373 + \cdots\]</span></p>
<hr>
<p>The duality gap is <span class="math inline">\(|\mathcal{L}_\varepsilon(\pi) - \mathcal{D}(\phi,\psi)| = 1.79 \times 10^{-10} \approx 0\)</span>. This confirms:</p>
<p><span class="math display">\[\mathcal{L}_\varepsilon(\pi) = \mathcal{D}(\phi, \psi)\]</span></p>
<p>Why does this hold? The regularized OT problem is <strong>strictly convex</strong> with a compact feasible set — by strong duality theory (Fenchel-Rockafellar), the primal and dual optima coincide exactly. The tiny residual gap is purely numerical, not mathematical.</p>
<p>The practical significance: the potentials <span class="math inline">\(\phi, \psi\)</span> returned by Sinkhorn are not just algorithmic byproducts — they are the <strong>true dual optimizers</strong>, certifying that <span class="math inline">\(\pi\)</span> is the globally optimal primal solution. No other transport plan in <span class="math inline">\(\Pi(\mathbf{m}, \mathbf{v})\)</span> achieves a lower regularized cost.</p>
<hr>
<p>The transport plan <span class="math inline">\(\pi\)</span> is fully certified from both primal and dual perspectives.</p>
<hr>
<p>Now we verifies the <strong>optimality conditions</strong> of the regularized OT problem geometrically. Strong duality ocd confirmed the objectives match. Complementary slackness goes further — it specifies <em>where</em> in the <span class="math inline">\((i,j)\)</span> plane the transport plan is allowed to place mass.</p>
<hr>
<p><strong><code>slack = C_norm - (phi[:, np.newaxis] + psi[np.newaxis, :])</code></strong></p>
<p>Computes the <strong>slack</strong> at every <span class="math inline">\((i,j)\)</span> pair:</p>
<p><span class="math display">\[s_{ij} = \tilde{C}_{ij} - (\phi_i + \psi_j)\]</span></p>
<p>Recall that at optimality:</p>
<p><span class="math display">\[\pi_{ij} = \exp\!\left(\frac{\phi_i + \psi_j - \tilde{C}_{ij}}{\varepsilon}\right) = \exp\!\left(\frac{-s_{ij}}{\varepsilon}\right)\]</span></p>
<p>So <span class="math inline">\(s_{ij}\)</span> directly controls how much mass flows along path <span class="math inline">\((i,j)\)</span>: when <span class="math inline">\(s_{ij} = 0\)</span>, the path is “free” and <span class="math inline">\(\pi_{ij}\)</span> is maximized; when <span class="math inline">\(s_{ij}\)</span> is large, <span class="math inline">\(\pi_{ij} \approx 0\)</span> and the path is effectively closed.</p>
<p><code>slack.min() = 0.074001 &gt; 0</code> confirms <span class="math inline">\(s_{ij} \geq 0\)</span> everywhere — the dual constraint <span class="math inline">\(\phi_i + \psi_j \leq \tilde{C}_{ij}\)</span> holds globally. This is the dual feasibility condition.</p>
<p>On the anchor: <span class="math inline">\(s_{03} = \tilde{C}_{03} - (\phi_0 + \psi_3)\)</span>. If <span class="math inline">\(\phi_0 + \psi_3 &lt; \tilde{C}_{03} = 1\)</span>, then <span class="math inline">\(s_{03} &gt; 0\)</span> and very little mass travels the expensive diagonal path.</p>
<hr>
<p><strong><code>weighted_slack = slack * pi</code></strong></p>
<p>Computes <span class="math inline">\(s_{ij} \cdot \pi_{ij}\)</span> at every pair — the complementary slackness product:</p>
<p><span class="math display">\[s_{ij} \cdot \pi_{ij} \approx 0 \quad \forall i,j\]</span></p>
<p>In unregularized OT, complementary slackness is exact: <span class="math inline">\(s_{ij} \cdot \pi_{ij} = 0\)</span> everywhere, meaning mass only flows along paths where <span class="math inline">\(\phi_i + \psi_j = \tilde{C}_{ij}\)</span> exactly. The regularized version softens this — mass can flow along slightly suboptimal paths, but exponentially suppressed by <span class="math inline">\(\exp(-s_{ij}/\varepsilon)\)</span>. The output confirms this: <code>weighted_slack.max() = 4.52e-05</code> and <code>mean = 1.46e-07</code> — both negligible.</p>
<hr>
<p>These three conditions together — primal feasibility (<span class="math inline">\(\pi \in \Pi(\mathbf{m},\mathbf{v})\)</span>), dual feasibility (<span class="math inline">\(s_{ij} \geq 0\)</span>), and complementary slackness (<span class="math inline">\(s_{ij}\pi_{ij} \approx 0\)</span>) — are the <strong>KKT conditions</strong> for the regularized OT problem. Satisfying all three simultaneously is both necessary and sufficient for global optimality. Sinkhorn has found the exact solution.</p>
<hr>
<p><span class="math inline">\(\pi\)</span> is certified optimal from every angle: primal feasibility, primal-dual objective match, and KKT conditions. The mathematical groundwork is complete. Everything from here is about <em>using</em> <span class="math inline">\(\pi\)</span> to build the geodesic.</p>
<hr>
<p>The geometric payoff of everything built so far: the transport plan <span class="math inline">\(\pi\)</span> tells us <em>how much mass</em> moves from pixel <span class="math inline">\(i\)</span> to pixel <span class="math inline">\(j\)</span>. This asks: what does the mass distribution look like <em>mid-journey</em>? The answer is the <strong>Wasserstein geodesic</strong> — the mathematically correct “straight line” between <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span> in the space of probability measures.</p>
<hr>
<p>At time <span class="math inline">\(t \in [0,1]\)</span>, define the interpolation map:</p>
<p><span class="math display">\[T_t(\mathbf{x}_i, \mathbf{x}_j) = (1-t)\,\mathbf{x}_i + t\,\mathbf{x}_j\]</span></p>
<p>This moves each unit of mass linearly from its source position <span class="math inline">\(\mathbf{x}_i\)</span> toward its target position <span class="math inline">\(\mathbf{x}_j\)</span>. At <span class="math inline">\(t=0\)</span>: mass stays at <span class="math inline">\(\mathbf{x}_i\)</span> — we recover <span class="math inline">\(\mu\)</span>. At <span class="math inline">\(t=1\)</span>: mass arrives at <span class="math inline">\(\mathbf{x}_j\)</span> — we recover <span class="math inline">\(\nu\)</span>. At <span class="math inline">\(t=0.5\)</span>: mass sits at the midpoint <span class="math inline">\(\frac{\mathbf{x}_i + \mathbf{x}_j}{2}\)</span> — the intermediate frame.</p>
<p>The resulting measure at time <span class="math inline">\(t\)</span> is the <strong>pushforward</strong> of <span class="math inline">\(\pi\)</span> under <span class="math inline">\(T_t\)</span>:</p>
<p><span class="math display">\[\mu_t = (T_t)_\sharp \pi\]</span></p>
<p>Formally, for any pixel location <span class="math inline">\(\mathbf{x}_k\)</span>:</p>
<p><span class="math display">\[\mu_t(k) = \sum_{\substack{i,j \\ T_t(\mathbf{x}_i,\mathbf{x}_j) = \mathbf{x}_k}} \pi_{ij}\]</span></p>
<p>In words: accumulate all mass <span class="math inline">\(\pi_{ij}\)</span> whose interpolated position lands at pixel <span class="math inline">\(k\)</span> at time <span class="math inline">\(t\)</span>.</p>
<hr>
<p><strong><code>frame = np.zeros(784)</code></strong></p>
<p>Initializes a blank canvas — the measure <span class="math inline">\(\mu_t\)</span> before any mass has been placed:</p>
<p><span class="math display">\[\mu_t^{(0)} = \mathbf{0} \in \mathbb{R}^{784}\]</span></p>
<hr>
<p><strong><code>if pi[i].sum() &lt; 1e-12: continue</code></strong></p>
<p>Skips source pixel <span class="math inline">\(i\)</span> if it carries no outgoing mass. Background pixels satisfy <span class="math inline">\(m_i \approx 0\)</span>, so <span class="math inline">\(\sum_j \pi_{ij} \approx 0\)</span> — computing their interpolation would waste time and contribute nothing.</p>
<hr>
<p><strong><code>interp_coords = (1 - t) * coords[i] + t * coords</code></strong></p>
<p>For fixed source pixel <span class="math inline">\(i\)</span> and all target pixels <span class="math inline">\(j\)</span> simultaneously, computes the interpolated 2D position:</p>
<p><span class="math display">\[\mathbf{z}_{ij}(t) = (1-t)\,\mathbf{x}_i + t\,\mathbf{x}_j \in \mathbb{R}^2\]</span></p>
<p><code>coords[i]</code> has shape <span class="math inline">\((2,)\)</span> and <code>coords</code> has shape <span class="math inline">\((784, 2)\)</span>, so broadcasting gives <code>interp_coords</code> shape <span class="math inline">\((784, 2)\)</span> — one interpolated coordinate per target pixel <span class="math inline">\(j\)</span>.</p>
<p>On the anchor at <span class="math inline">\(t = 0.5\)</span>, for source pixel <span class="math inline">\(i=0\)</span> at <span class="math inline">\((0,0)\)</span>:</p>
<p><span class="math display">\[\mathbf{z}_{00}(0.5) = 0.5(0,0) + 0.5(0,0) = (0,0)\]</span> <span class="math display">\[\mathbf{z}_{01}(0.5) = 0.5(0,0) + 0.5(0,1) = (0,\ 0.5)\]</span> <span class="math display">\[\mathbf{z}_{02}(0.5) = 0.5(0,0) + 0.5(1,0) = (0.5,\ 0)\]</span> <span class="math display">\[\mathbf{z}_{03}(0.5) = 0.5(0,0) + 0.5(1,1) = (0.5,\ 0.5)\]</span></p>
<hr>
<p><strong><code>rows = np.clip(np.round(interp_coords[:, 0]).astype(int), 0, 27)</code></strong></p>
<p>Rounds each interpolated coordinate to the nearest integer pixel, then clamps to <span class="math inline">\([0, 27]\)</span>:</p>
<p><span class="math display">\[r_{ij} = \text{clip}\!\left(\text{round}(z_{ij}^{(0)}),\ 0,\ 27\right), \qquad c_{ij} = \text{clip}\!\left(\text{round}(z_{ij}^{(1)}),\ 0,\ 27\right)\]</span></p>
<p>On the anchor at <span class="math inline">\(t=0.5\)</span>: <span class="math inline">\((0, 0.5, 0.5, 0.5) \xrightarrow{\text{round}} (0, 1, 1, 1)\)</span> for rows… wait — let’s be precise. <span class="math inline">\(z_{01}^{(0)} = 0\)</span> rounds to 0; <span class="math inline">\(z_{02}^{(0)} = 0.5\)</span> rounds to 0 or 1 depending on rounding rule (NumPy uses banker’s rounding — 0.5 rounds to 0). This is a subtle discretization artifact: two continuously distinct positions can collapse onto the same pixel after rounding, which is why the next line uses <code>np.add.at</code> rather than direct assignment.</p>
<hr>
<p><strong><code>target_indices = rows * 28 + cols</code></strong></p>
<p>Converts 2D rounded coordinates back to flat indices:</p>
<p><span class="math display">\[k_{ij} = 28\, r_{ij} + c_{ij} \in \{0,\ldots,783\}\]</span></p>
<hr>
<p><strong><code>np.add.at(frame, target_indices, pi[i])</code></strong></p>
<p>Deposits mass <span class="math inline">\(\pi_{ij}\)</span> at pixel <span class="math inline">\(k_{ij}\)</span> for all <span class="math inline">\(j\)</span> simultaneously:</p>
<p><span class="math display">\[\mu_t(k_{ij}) \mathrel{+}= \pi_{ij} \quad \forall j\]</span></p>
<p>The critical word is <code>add.at</code> rather than <code>frame[target_indices] += pi[i]</code>. Standard NumPy indexing with repeated indices is <strong>not atomic</strong> — if <span class="math inline">\(k_{i,j_1} = k_{i,j_2}\)</span> (two paths land on the same pixel), only one increment would register. <code>np.add.at</code> guarantees all contributions are accumulated correctly, regardless of collisions.</p>
<hr>
<p>The output confirms <code>frames sum ≈ 1.0</code> for every <span class="math inline">\(t\)</span>. This is not accidental — it follows directly from the marginal constraints on <span class="math inline">\(\pi\)</span>:</p>
<p><span class="math display">\[\sum_k \mu_t(k) = \sum_{i,j} \pi_{ij} = 1 \quad \forall t\]</span></p>
<p>Mass is neither created nor destroyed during transport — it only moves.</p>
<hr>
<p>In the space of probability measures equipped with the <span class="math inline">\(W_2\)</span> metric, the curve <span class="math inline">\(t \mapsto \mu_t\)</span> is the <strong>unique constant-speed geodesic</strong> connecting <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span>. This is McCann’s interpolation theorem (1997). The key property: each particle of mass travels in a straight line in <span class="math inline">\(\mathbb{R}^2\)</span> at constant speed. No other interpolation scheme — including pixel blending — produces straight-line trajectories for individual mass particles.</p>
<hr>
<p>We now hold 10 frames <span class="math inline">\(\{\mu_t\}_{t=0}^{1}\)</span> — the Wasserstein geodesic sampled at uniform time steps. Pixel blending is linear interpolation on the simplex; Wasserstein is linear interpolation in <span class="math inline">\(\mathbb{R}^2\)</span> for each mass particle. The geometry lives in the image plane, not in intensity space.</p>
<hr>
<p>We simply confirms that the geodesic has the correct endpoints:</p>
<p><span class="math display">\[\mu_0 = \mu \qquad \text{and} \qquad \mu_1 = \nu\]</span></p>
<p>Both output hold to tolerance <span class="math inline">\(10^{-5}\)</span>. The small residual is purely from the pixel rounding — <span class="math inline">\(T_t\)</span> at <span class="math inline">\(t=0\)</span> maps every mass particle to <span class="math inline">\(\mathbf{x}_i\)</span> exactly, but <code>np.round</code> can introduce sub-pixel error at intermediate <span class="math inline">\(t\)</span> values. At the endpoints <span class="math inline">\(t \in \{0,1\}\)</span> no rounding ambiguity occurs since <span class="math inline">\((1-t)\mathbf{x}_i + t\mathbf{x}_j\)</span> lands exactly on a grid point.</p>
<hr>
<p>Naive Pixel Blending Baseline: constructs the <strong>straw man</strong> that the Wasserstein geodesic is contrasted against. The formula is as simple as it looks — and that simplicity is precisely its flaw.</p>
<hr>
<p><strong><code>(1-t) * m.reshape(28, 28) + t * v.reshape(28, 28)</code></strong></p>
<p>A convex combination of the two measures, computed pointwise at each pixel:</p>
<p><span class="math display">\[\mu_t^{\text{blend}}(k) = (1-t)\,m_k + t\,v_k \qquad \forall k \in \{0,\ldots,783\}\]</span></p>
<p>This is a straight line on the probability simplex <span class="math inline">\(\Delta^{783}\)</span> — linear interpolation between two points in intensity space, with no reference to pixel coordinates whatsoever.</p>
<p>On the anchor at <span class="math inline">\(t = 0.5\)</span>:</p>
<p><span class="math display">\[\mu_{0.5}^{\text{blend}} = 0.5\,(0.0,\ 0.2835,\ 0.3150,\ 0.4016) + 0.5\,(0.2373,\ 0.2881,\ 0.2034,\ 0.2712)\]</span> <span class="math display">\[= (0.1186,\ 0.2858,\ 0.2592,\ 0.3364)\]</span></p>
<p>No pixel moves. Pixel 0 goes from mass <span class="math inline">\(0.0\)</span> to mass <span class="math inline">\(0.1186\)</span> purely by arithmetic averaging — no mass traveled there from anywhere.</p>
<hr>
<p>Mass conservation holds trivially by linearity:</p>
<p><span class="math display">\[\sum_k \mu_t^{\text{blend}}(k) = (1-t)\sum_k m_k + t\sum_k v_k = (1-t)\cdot 1 + t \cdot 1 = 1\]</span></p>
<hr>
<p>The contrast: At <span class="math inline">\(t=0.5\)</span> on the real images, consider a pixel in the middle of a stroke of the “3” that has no corresponding ink in the “8”:</p>
<ul>
<li><strong>Blending:</strong> <span class="math inline">\(\mu_{0.5}^{\text{blend}}(k) = 0.5\,m_k + 0\cdot v_k = 0.5\,m_k\)</span> — the stroke simply fades to half intensity. No mass moves; the stroke just dims.</li>
<li><strong>Wasserstein:</strong> <span class="math inline">\(\mu_{0.5}(k)\)</span> accumulates mass from all <span class="math inline">\((i,j)\)</span> pairs whose midpoint <span class="math inline">\(\frac{\mathbf{x}_i + \mathbf{x}_j}{2}\)</span> lands at <span class="math inline">\(k\)</span> — mass physically migrates from the “3” stroke toward wherever the “8” needs it.</li>
</ul>
<hr>
<p>Both methods produce valid probability measures at every <span class="math inline">\(t\)</span>, and both have correct boundary conditions. The Wasserstein geodesic maintains spatial correlation, ensuring mass physically travels through intermediate coordinates rather than simply fading out in one spot and fading in at another.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Shreesh Bhattarai · GDL &amp; COT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/shreeshb51">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/shreesh-bhattarai-1ba1681bb/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>