<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>solving_anchor_example – Shreesh Bhattarai</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-088498ae819e247f230a120db35b6777.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shreesh Bhattarai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../catw/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Along the Way</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../papers/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper Comprehensions</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#anchor-example-complete-step-by-step-solution" id="toc-anchor-example-complete-step-by-step-solution" class="nav-link active" data-scroll-target="#anchor-example-complete-step-by-step-solution">Anchor Example — Complete Step-by-Step Solution</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="anchor-example-complete-step-by-step-solution" class="level2">
<h2 class="anchored" data-anchor-id="anchor-example-complete-step-by-step-solution">Anchor Example — Complete Step-by-Step Solution</h2>
<hr>
<section id="step-1-label-vector-and-index-selection" class="level3">
<h3 class="anchored" data-anchor-id="step-1-label-vector-and-index-selection">Step 1: Label vector and index selection</h3>
<p><span class="math display">\[\mathbf{y} = (3,\ 7,\ 8,\ 3,\ 1,\ 8), \quad N = 6\]</span></p>
<section id="taking-first-occurrence-of-chosen-labels-3-and-8" class="level4">
<h4 class="anchored" data-anchor-id="taking-first-occurrence-of-chosen-labels-3-and-8">Taking first occurrence of chosen labels: 3 and 8</h4>
<p><span class="math display">\[\mathcal{I}_3 = \{i : y_i = 3\} = \{0, 3\} \implies i_3 = \min\{0,3\} = 0\]</span></p>
<p><span class="math display">\[\mathcal{I}_8 = \{i : y_i = 8\} = \{2, 5\} \implies i_8 = \min\{2,5\} = 2\]</span></p>
<hr>
</section>
</section>
<section id="step-2-cast-images-to-float64" class="level3">
<h3 class="anchored" data-anchor-id="step-2-cast-images-to-float64">Step 2: Cast images to float64</h3>
<p><span class="math display">\[A^{(3)} = \begin{pmatrix} 0 &amp; 180 \\ 200 &amp; 255 \end{pmatrix} \xrightarrow{\text{cast}} \begin{pmatrix} 0.0 &amp; 180.0 \\ 200.0 &amp; 255.0 \end{pmatrix}, \qquad A^{(8)} = \begin{pmatrix} 210 &amp; 255 \\ 180 &amp; 240 \end{pmatrix} \xrightarrow{\text{cast}} \begin{pmatrix} 210.0 &amp; 255.0 \\ 180.0 &amp; 240.0 \end{pmatrix}\]</span></p>
<hr>
</section>
<section id="step-3-flatten" class="level3">
<h3 class="anchored" data-anchor-id="step-3-flatten">Step 3: Flatten</h3>
<p><span class="math display">\[A^{(3)} \xrightarrow{\text{flatten}} \mathbf{a}^{(3)} = (0.0,\ 180.0,\ 200.0,\ 255.0)\]</span></p>
<p><span class="math display">\[A^{(8)} \xrightarrow{\text{flatten}} \mathbf{a}^{(8)} = (210.0,\ 255.0,\ 180.0,\ 240.0)\]</span></p>
<hr>
</section>
<section id="step-4-normalize-to-probability-measures" class="level3">
<h3 class="anchored" data-anchor-id="step-4-normalize-to-probability-measures">Step 4: Normalize to probability measures</h3>
<p><span class="math display">\[Z^{(3)} = 0.0 + 180.0 + 200.0 + 255.0 = 635.0\]</span></p>
<p><span class="math display">\[Z^{(8)} = 210.0 + 255.0 + 180.0 + 240.0 = 885.0\]</span></p>
<p><span class="math display">\[\mathbf{m} = \frac{\mathbf{a}^{(3)}}{635.0} = \left(\frac{0.0}{635},\ \frac{180.0}{635},\ \frac{200.0}{635},\ \frac{255.0}{635}\right) = (0.0000,\ 0.2835,\ 0.3150,\ 0.4016)\]</span></p>
<p><span class="math display">\[\mathbf{v} = \frac{\mathbf{a}^{(8)}}{885.0} = \left(\frac{210.0}{885},\ \frac{255.0}{885},\ \frac{180.0}{885},\ \frac{240.0}{885}\right) = (0.2373,\ 0.2881,\ 0.2034,\ 0.2712)\]</span></p>
<p>Verify:</p>
<p><span class="math display">\[0.0000 + 0.2835 + 0.3150 + 0.4016 = 1.0000\ \checkmark\]</span></p>
<p><span class="math display">\[0.2373 + 0.2881 + 0.2034 + 0.2712 = 1.0000\ \checkmark\]</span></p>
<hr>
</section>
<section id="step-5-pixel-coordinates" class="level3">
<h3 class="anchored" data-anchor-id="step-5-pixel-coordinates">Step 5: Pixel coordinates</h3>
<p>For <span class="math inline">\(n=2\)</span>: <span class="math inline">\(\mathbf{x}_i = (\lfloor i/2 \rfloor,\ i \bmod 2)\)</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(i\)</span></th>
<th><span class="math inline">\(\lfloor i/2 \rfloor\)</span></th>
<th><span class="math inline">\(i \bmod 2\)</span></th>
<th><span class="math inline">\(\mathbf{x}_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>0</td>
<td><span class="math inline">\((0,0)\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td>0</td>
<td>1</td>
<td><span class="math inline">\((0,1)\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\((1,0)\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td>1</td>
<td>1</td>
<td><span class="math inline">\((1,1)\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[X = \begin{pmatrix} 0 &amp; 0 \\ 0 &amp; 1 \\ 1 &amp; 0 \\ 1 &amp; 1 \end{pmatrix}\]</span></p>
<hr>
</section>
<section id="step-6-cost-matrix" class="level3">
<h3 class="anchored" data-anchor-id="step-6-cost-matrix">Step 6: Cost matrix</h3>
<p><span class="math inline">\(C_{ij} = (r_i - r_j)^2 + (c_i - c_j)^2\)</span>. All 16 entries:</p>
<p><strong>Row 0</strong> — source <span class="math inline">\(\mathbf{x}_0 = (0,0)\)</span>:</p>
<p><span class="math display">\[C_{00} = (0-0)^2+(0-0)^2 = 0\]</span> <span class="math display">\[C_{01} = (0-0)^2+(0-1)^2 = 1\]</span> <span class="math display">\[C_{02} = (0-1)^2+(0-0)^2 = 1\]</span> <span class="math display">\[C_{03} = (0-1)^2+(0-1)^2 = 2\]</span></p>
<p><strong>Row 1</strong> — source <span class="math inline">\(\mathbf{x}_1 = (0,1)\)</span>:</p>
<p><span class="math display">\[C_{10} = (0-0)^2+(1-0)^2 = 1\]</span> <span class="math display">\[C_{11} = (0-0)^2+(1-1)^2 = 0\]</span> <span class="math display">\[C_{12} = (0-1)^2+(1-0)^2 = 2\]</span> <span class="math display">\[C_{13} = (0-1)^2+(1-1)^2 = 1\]</span></p>
<p><strong>Row 2</strong> — source <span class="math inline">\(\mathbf{x}_2 = (1,0)\)</span>:</p>
<p><span class="math display">\[C_{20} = (1-0)^2+(0-0)^2 = 1\]</span> <span class="math display">\[C_{21} = (1-0)^2+(0-1)^2 = 2\]</span> <span class="math display">\[C_{22} = (1-1)^2+(0-0)^2 = 0\]</span> <span class="math display">\[C_{23} = (1-1)^2+(0-1)^2 = 1\]</span></p>
<p><strong>Row 3</strong> — source <span class="math inline">\(\mathbf{x}_3 = (1,1)\)</span>:</p>
<p><span class="math display">\[C_{30} = (1-0)^2+(1-0)^2 = 2\]</span> <span class="math display">\[C_{31} = (1-0)^2+(1-1)^2 = 1\]</span> <span class="math display">\[C_{32} = (1-1)^2+(1-0)^2 = 1\]</span> <span class="math display">\[C_{33} = (1-1)^2+(1-1)^2 = 0\]</span></p>
<p><span class="math display">\[C = \begin{pmatrix} 0 &amp; 1 &amp; 1 &amp; 2 \\ 1 &amp; 0 &amp; 2 &amp; 1 \\ 1 &amp; 2 &amp; 0 &amp; 1 \\ 2 &amp; 1 &amp; 1 &amp; 0 \end{pmatrix}\]</span></p>
<hr>
</section>
<section id="step-7-normalize-cost-matrix" class="level3">
<h3 class="anchored" data-anchor-id="step-7-normalize-cost-matrix">Step 7: Normalize cost matrix</h3>
<p><span class="math display">\[\max(C) = 2 \implies \tilde{C} = \frac{C}{2} = \begin{pmatrix} 0 &amp; 0.5 &amp; 0.5 &amp; 1 \\ 0.5 &amp; 0 &amp; 1 &amp; 0.5 \\ 0.5 &amp; 1 &amp; 0 &amp; 0.5 \\ 1 &amp; 0.5 &amp; 0.5 &amp; 0 \end{pmatrix}\]</span></p>
<hr>
</section>
<section id="step-8-log-measures" class="level3">
<h3 class="anchored" data-anchor-id="step-8-log-measures">Step 8: Log-measures</h3>
<p><span class="math inline">\(\mathbf{m} = (0.0000,\ 0.2835,\ 0.3150,\ 0.4016)\)</span></p>
<p><span class="math inline">\(\log_{mu} = (\log(10^{-300}),\ \log(0.2835),\ \log(0.3150),\ \log(0.4016)) = (-690.78,\ -1.261,\ -1.155,\ -0.912)\)</span></p>
<p><br></p>
<p><span class="math inline">\(\mathbf{v} = (0.2373,\ 0.2881,\ 0.2034,\ 0.2712)\)</span></p>
<p><span class="math inline">\(\log_{nu} = (\log(0.2373),\ \log(0.2881),\ \log(0.2034),\ \log(0.2712)) = (-1.438,\ -1.244,\ -1.594,\ -1.305)\)</span></p>
<hr>
</section>
<section id="step-9-initialize-potentials" class="level3">
<h3 class="anchored" data-anchor-id="step-9-initialize-potentials">Step 9: Initialize potentials</h3>
<p><span class="math display">\[\mathbf{f}^{(0)} = (0,\ 0,\ 0,\ 0), \qquad \mathbf{g}^{(0)} = (0,\ 0,\ 0,\ 0)\]</span></p>
<hr>
</section>
<section id="step-10-f-update---iteration-1" class="level3">
<h3 class="anchored" data-anchor-id="step-10-f-update---iteration-1">Step 10: f-update -&gt; Iteration 1</h3>
<p><span class="math display">\[\varepsilon = 0.01, \quad \mathbf{g} = \mathbf{0}\]</span></p>
<p>Formula: <span class="math inline">\(f_i \leftarrow \varepsilon\log m_i - \varepsilon\operatorname{LSE}_j\!\left(\dfrac{g_j - \tilde{C}_{ij}}{\varepsilon}\right)\)</span></p>
<p>With <span class="math inline">\(\mathbf{g} = \mathbf{0}\)</span>, the LSE argument for row <span class="math inline">\(i\)</span> is <span class="math inline">\(\dfrac{0 - \tilde{C}_{ij}}{0.01} = -100\tilde{C}_{ij}\)</span>.</p>
<p><strong>Row 0:</strong> argument vector <span class="math inline">\(= -100\tilde{C}_{ij} = -100\cdot(0,\ 0.5,\ 0.5,\ 1) = (0,\ -50,\ -50,\ -100)\)</span></p>
<p><span class="math display">\[\operatorname{LSE} = \log(e^0 + e^{-50} + e^{-50} + e^{-100}) \approx \log(1 + 0 + 0 + 0) = 0\]</span></p>
<p><span class="math display">\[f_0 \leftarrow 0.01\cdot(-690.78) - 0.01\cdot 0 = -6.9078\]</span></p>
<p><strong>Row 1:</strong> argument vector <span class="math inline">\(= -100\cdot(0.5,\ 0,\ 1,\ 0.5) = (-50,\ 0,\ -100,\ -50)\)</span></p>
<p><span class="math display">\[\operatorname{LSE} \approx \log(e^0) = 0\]</span></p>
<p><span class="math display">\[f_1 \leftarrow 0.01\cdot(-1.261) - 0.01\cdot 0 = -0.01261\]</span></p>
<p><strong>Row 2:</strong> argument vector <span class="math inline">\(= -100\cdot(0.5,\ 1,\ 0,\ 0.5) = (-50,\ -100,\ 0,\ -50)\)</span></p>
<p><span class="math display">\[\operatorname{LSE} \approx 0\]</span></p>
<p><span class="math display">\[f_2 \leftarrow 0.01\cdot(-1.155) - 0.01\cdot 0 = -0.01155\]</span></p>
<p><strong>Row 3:</strong> argument vector <span class="math inline">\(= -100\cdot(1,\ 0.5,\ 0.5,\ 0) = (-100,\ -50,\ -50,\ 0)\)</span></p>
<p><span class="math display">\[\operatorname{LSE} \approx 0\]</span></p>
<p><span class="math display">\[f_3 \leftarrow 0.01\cdot(-0.912) - 0.01\cdot 0 = -0.00912\]</span></p>
<p><span class="math display">\[\mathbf{f}^{(1)} = (-6.9078,\ -0.01261,\ -0.01155,\ -0.00912)\]</span></p>
<hr>
</section>
<section id="step-11-g-update---iteration-1" class="level3">
<h3 class="anchored" data-anchor-id="step-11-g-update---iteration-1">Step 11: g-update -&gt; Iteration 1</h3>
<p>Formula: <span class="math inline">\(g_j \leftarrow \varepsilon\log\nu_j - \varepsilon\operatorname{LSE}_i\!\left(\dfrac{f_i - \tilde{C}_{ij}}{\varepsilon}\right)\)</span></p>
<p>Argument for column <span class="math inline">\(j\)</span>: <span class="math inline">\(\dfrac{f_i - \tilde{C}_{ij}}{0.01}\)</span></p>
<p><strong>Column 0:</strong> <span class="math inline">\(\tilde{C}_{i0} = (0,\ 0.5,\ 0.5,\ 1)\)</span> &amp; <span class="math inline">\(v_j = -1.438\)</span> (from <span class="math inline">\(\log_{nu}\)</span>)</p>
<p><span class="math display">\[\frac{f_i - \tilde{C}_{i0}}{0.01} = \frac{(-6.9078-0,\ -0.01261-0.5,\ -0.01155-0.5,\ -0.00912-1)}{0.01}\]</span> <span class="math display">\[= (-690.78,\ -51.261,\ -51.155,\ -100.912)\]</span></p>
<p><span class="math display">\[\operatorname{LSE} \approx \log(e^{-51.155}) = -51.155 \quad \text{(largest argument)}\]</span></p>
<p><span class="math display">\[g_0 \leftarrow 0.01\cdot(-1.438) - 0.01\cdot(-51.155) = -0.01438 + 0.51155 = 0.49717\]</span></p>
<p><strong>Column 1:</strong> <span class="math inline">\(\tilde{C}_{i1} = (0.5,\ 0,\ 1,\ 0.5)\)</span></p>
<p><span class="math display">\[\frac{f_i - \tilde{C}_{i1}}{0.01} = \frac{(-6.9078-0.5,\ -0.01261-0,\ -0.01155-1,\ -0.00912-0.5)}{0.01}\]</span> <span class="math display">\[= (-740.78,\ -1.261,\ -101.155,\ -50.912)\]</span></p>
<p><span class="math display">\[\operatorname{LSE} \approx \log(e^{-1.261}) = -1.261\]</span></p>
<p><span class="math display">\[g_1 \leftarrow 0.01\cdot(-1.244) - 0.01\cdot(-1.261) = -0.01244 + 0.01261 = 0.00017\]</span></p>
<p><strong>Column 2:</strong> <span class="math inline">\(\tilde{C}_{i2} = (0.5,\ 1,\ 0,\ 0.5)\)</span></p>
<p><span class="math display">\[\frac{f_i - \tilde{C}_{i2}}{0.01} = \frac{(-6.9078-0.5,\ -0.01261-1,\ -0.01155-0,\ -0.00912-0.5)}{0.01}\]</span> <span class="math display">\[= (-740.78,\ -101.261,\ -1.155,\ -50.912)\]</span></p>
<p><span class="math display">\[\operatorname{LSE} \approx -1.155\]</span></p>
<p><span class="math display">\[g_2 \leftarrow 0.01\cdot(-1.594) - 0.01\cdot(-1.155) = -0.01594 + 0.01155 = -0.00439\]</span></p>
<p><strong>Column 3:</strong> <span class="math inline">\(\tilde{C}_{i3} = (1,\ 0.5,\ 0.5,\ 0)\)</span></p>
<p><span class="math display">\[\frac{f_i - \tilde{C}_{i3}}{0.01} = \frac{(-6.9078-1,\ -0.01261-0.5,\ -0.01155-0.5,\ -0.00912-0)}{0.01}\]</span> <span class="math display">\[= (-790.78,\ -51.261,\ -51.155,\ -0.912)\]</span></p>
<p><span class="math display">\[\operatorname{LSE} \approx -0.912\]</span></p>
<p><span class="math display">\[g_3 \leftarrow 0.01\cdot(-1.305) - 0.01\cdot(-0.912) = -0.01305 + 0.00912 = -0.00393\]</span></p>
<p><span class="math display">\[\mathbf{g}^{(1)} = (0.49717,\ 0.00017,\ -0.00439,\ -0.00393)\]</span></p>
<hr>
</section>
<section id="step-12-transport-plan-after-convergence" class="level3">
<h3 class="anchored" data-anchor-id="step-12-transport-plan-after-convergence">Step 12: Transport plan after convergence</h3>
<p>After many iterations, potentials converge to <span class="math inline">\(\mathbf{f}^*\)</span>, <span class="math inline">\(\mathbf{g}^*\)</span>. The transport plan is then recovered as:</p>
<p><span class="math display">\[\log\pi_{ij} = \frac{f^*_i + g^*_j - \tilde{C}_{ij}}{\varepsilon}, \qquad \pi_{ij} = \exp(\log\pi_{ij})\]</span></p>
<p>For example, using iteration-1 values as approximation for entry <span class="math inline">\((1,1)\)</span>:</p>
<p><span class="math display">\[\log\pi_{11} = \frac{-0.01261 + 0.00017 - 0}{0.01} = \frac{-0.01244}{0.01} = -1.244\]</span></p>
<p><span class="math display">\[\pi_{11} = e^{-1.244} = 0.2884\]</span></p>
<p><strong>This entry is large so mass stays put cheaply.</strong></p>
<p>This is consistent with <span class="math inline">\(\tilde{C}_{11} = 0\)</span>, i.e., <span class="math inline">\(\pi_{11}\)</span> should be large (not zero) precisely because <span class="math inline">\(\tilde{C}_{11} = 0\)</span>. Zero cost means the Sinkhorn formula assigns no exponential penalty to <span class="math inline">\(\pi_{11}\)</span>​, so it receives maximum mass — mass simply stays in place.</p>
<p><strong>What <span class="math inline">\(\pi_{11} = e^{-1.244} = 0.2884\)</span> actually means?</strong></p>
<p><span class="math inline">\(\pi_{11}\)</span> is the amount of mass transported from source pixel 1 to target pixel 1. The value <span class="math inline">\(0.2884\)</span> means roughly 28.8% of total mass flows from pixel 1 of the “3” directly into pixel 1 of the “8” — staying at coordinate <span class="math inline">\((0,1)\)</span> because of <span class="math inline">\(\Big\{ \mathbf{x}_i = \left(\left\lfloor \frac{i}{28} \right\rfloor,\ i \bmod 28\right) \Big\}\)</span> without moving. This is expected and correct: both pixels share the same location, so the optimal plan preferentially routes mass there rather than paying travel cost.</p>
<p><strong>What <span class="math inline">\(\tilde{C}_{11} = 0\)</span> means?</strong></p>
<p><span class="math inline">\(\tilde{C}_{11} = 0\)</span> means pixel 1 in the source and pixel 1 in the target occupy the <strong>same spatial location</strong> — both sit at coordinate <span class="math inline">\((0,1)\)</span>. Moving mass from source pixel 1 to target pixel 1 requires zero travel. It costs nothing.</p>
<p><strong>What does <span class="math inline">\(\tilde{C}_{11} = 0\)</span> vs <span class="math inline">\(\tilde{C}_{12} = 1\)</span> mean?</strong></p>
<p>Think of <span class="math inline">\(\tilde{C}_{ij}\)</span> as a toll charge for shipping mass from pixel <span class="math inline">\(i\)</span> to pixel <span class="math inline">\(j\)</span>.</p>
<ul>
<li><span class="math inline">\(\tilde{C}_{11} = 0\)</span>: zero toll — shipping from pixel 1 to pixel 1 is free because they’re at the same address. The Sinkhorn formula charges <span class="math inline">\(e^{-0/0.01} = e^0 = 1\)</span> — no penalty at all. So <span class="math inline">\(\pi_{11}\)</span> stays as large as the available mass allows.</li>
<li><span class="math inline">\(\tilde{C}_{12} = 1\)</span>: maximum toll — pixel 1 and pixel 2 are diagonally opposite corners. The formula charges <span class="math inline">\(e^{-1/0.01} = e^{-100} \approx 0\)</span> — an astronomically large penalty that makes it essentially impossible for mass to travel that route.</li>
</ul>
<p>The cost matrix is literally a dial that opens or closes transport paths: zero cost opens them fully, maximum cost shuts them completely.</p>
<hr>
</section>
<section id="step-12.5-transport-plan-after-convergence-full-computation" class="level3">
<h3 class="anchored" data-anchor-id="step-12.5-transport-plan-after-convergence-full-computation">Step 12.5: Transport Plan After Convergence — Full Computation</h3>
<p><strong>Assumed converged potentials</strong> (realistic values consistent with the anchor measures and <span class="math inline">\(\tilde{C}\)</span>):</p>
<p><span class="math display">\[\mathbf{f}^* = (-6.9100,\ -0.0130,\ -0.0120,\ -0.0095)\]</span></p>
<p><span class="math display">\[\mathbf{g}^* = (0.4900,\ 0.0002,\ -0.0045,\ -0.0040)\]</span></p>
<p><br></p>
<p><strong>All 16 entries of <span class="math inline">\(\pi\)</span>:</strong></p>
<p><span class="math display">\[\log\pi_{ij} = \frac{f^*_i + g^*_j - \tilde{C}_{ij}}{0.01}\]</span></p>
<p><br></p>
<p><strong>Row 0</strong> — <span class="math inline">\(f^*_0 = -6.9100\)</span>, pixel 0 is zero-mass background:</p>
<p><span class="math display">\[\log\pi_{00} = \frac{-6.9100 + 0.4900 - 0}{0.01} = \frac{-6.4200}{0.01} = -642.0 \implies \pi_{00} = e^{-642.0} \approx 0\]</span></p>
<p><span class="math display">\[\log\pi_{01} = \frac{-6.9100 + 0.0002 - 0.5}{0.01} = \frac{-7.4098}{0.01} = -740.98 \implies \pi_{01} \approx 0\]</span></p>
<p><span class="math display">\[\log\pi_{02} = \frac{-6.9100 - 0.0045 - 0.5}{0.01} = \frac{-7.4145}{0.01} = -741.45 \implies \pi_{02} \approx 0\]</span></p>
<p><span class="math display">\[\log\pi_{03} = \frac{-6.9100 - 0.0040 - 1}{0.01} = \frac{-7.9140}{0.01} = -791.40 \implies \pi_{03} \approx 0\]</span></p>
<p>Row 0 is entirely zero — pixel 0 has <span class="math inline">\(m_0 = 0\)</span>, so no mass ships from it anywhere. <span class="math inline">\(f^*_0 \approx -6.91\)</span> prices it completely out of the plan.</p>
<p><strong>“Prices it completely out of the plan”</strong></p>
<p><span class="math inline">\(f^*_0 \approx -6.91\)</span> makes the numerator <span class="math inline">\(f^*_0 + g^*_j - \tilde{C}_{ij}\)</span> so negative that <span class="math inline">\(\exp(\text{numerator}/\varepsilon) \approx 0\)</span> for every <span class="math inline">\(j\)</span> — the pixel is effectively banned from participating in transport.</p>
<p><br></p>
<p><strong>Row 1</strong> — <span class="math inline">\(f^*_1 = -0.0130\)</span>, pixel 1 carries mass <span class="math inline">\(m_1 = 0.2835\)</span>:</p>
<p><span class="math display">\[\log\pi_{10} = \frac{-0.0130 + 0.4900 - 0.5}{0.01} = \frac{-0.0230}{0.01} = -2.30 \implies \pi_{10} = e^{-2.30} = 0.1003\]</span></p>
<p><span class="math display">\[\log\pi_{11} = \frac{-0.0130 + 0.0002 - 0}{0.01} = \frac{-0.0128}{0.01} = -1.28 \implies \pi_{11} = e^{-1.28} = 0.2780\]</span></p>
<p><span class="math display">\[\log\pi_{12} = \frac{-0.0130 - 0.0045 - 1}{0.01} = \frac{-1.0175}{0.01} = -101.75 \implies \pi_{12} \approx 0\]</span></p>
<p><span class="math display">\[\log\pi_{13} = \frac{-0.0130 - 0.0040 - 0.5}{0.01} = \frac{-0.5170}{0.01} = -51.70 \implies \pi_{13} \approx 0\]</span></p>
<p>Row 1 sum <span class="math inline">\(\approx 0.1003 + 0.2780 = 0.3783 \approx m_1 = 0.2835\)</span> (from: <span class="math inline">\(\mathbf{m} = (0.0000,\ 0.2835,\ 0.3150,\ 0.4016)\)</span>). Close — small discrepancy because these are assumed, not exactly converged, potentials. Meaning, the row sum should equal <span class="math inline">\(m_1=0.2835\)</span> exactly at true convergence; the overshoot to <span class="math inline">\(0.37830\)</span> is an artifact of using assumed rather than exactly converged potentials.</p>
<p><br></p>
<p><strong>Row 2</strong> — <span class="math inline">\(f^*_2 = -0.0120\)</span>, pixel 2 carries mass <span class="math inline">\(m_2 = 0.3150\)</span>:</p>
<p><span class="math display">\[\log\pi_{20} = \frac{-0.0120 + 0.4900 - 0.5}{0.01} = \frac{-0.0220}{0.01} = -2.20 \implies \pi_{20} = e^{-2.20} = 0.1108\]</span></p>
<p><span class="math display">\[\log\pi_{21} = \frac{-0.0120 + 0.0002 - 1}{0.01} = \frac{-1.0118}{0.01} = -101.18 \implies \pi_{21} \approx 0\]</span></p>
<p><span class="math display">\[\log\pi_{22} = \frac{-0.0120 - 0.0045 - 0}{0.01} = \frac{-0.0165}{0.01} = -1.65 \implies \pi_{22} = e^{-1.65} = 0.1920\]</span></p>
<p><span class="math display">\[\log\pi_{23} = \frac{-0.0120 - 0.0040 - 0.5}{0.01} = \frac{-0.5160}{0.01} = -51.60 \implies \pi_{23} \approx 0\]</span></p>
<p><br></p>
<p><strong>Row 3</strong> — <span class="math inline">\(f^*_3 = -0.0095\)</span>, pixel 3 carries mass <span class="math inline">\(m_3 = 0.4016\)</span>:</p>
<p><span class="math display">\[\log\pi_{30} = \frac{-0.0095 + 0.4900 - 1}{0.01} = \frac{-0.5195}{0.01} = -51.95 \implies \pi_{30} \approx 0\]</span></p>
<p><span class="math display">\[\log\pi_{31} = \frac{-0.0095 + 0.0002 - 0.5}{0.01} = \frac{-0.5093}{0.01} = -50.93 \implies \pi_{31} \approx 0\]</span></p>
<p><span class="math display">\[\log\pi_{32} = \frac{-0.0095 - 0.0045 - 0.5}{0.01} = \frac{-0.5140}{0.01} = -51.40 \implies \pi_{32} \approx 0\]</span></p>
<p><span class="math display">\[\log\pi_{33} = \frac{-0.0095 - 0.0040 - 0}{0.01} = \frac{-0.0135}{0.01} = -1.35 \implies \pi_{33} = e^{-1.35} = 0.2592\]</span></p>
<p><br></p>
<p><strong>Full transport plan (approximate):</strong></p>
<p><span class="math display">\[\pi \approx \begin{pmatrix} 0 &amp; 0 &amp; 0 &amp; 0 \\ 0.1003 &amp; 0.2780 &amp; 0 &amp; 0 \\ 0.1108 &amp; 0 &amp; 0.1920 &amp; 0 \\ 0 &amp; 0 &amp; 0 &amp; 0.2592 \end{pmatrix}\]</span></p>
<hr>
</section>
<section id="further-clarifaction" class="level3">
<h3 class="anchored" data-anchor-id="further-clarifaction">FURTHER CLARIFACTION:</h3>
<p><strong>Mass, cost, and <span class="math inline">\(\pi\)</span> behavior:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th><span class="math inline">\(\pi_{ij}\)</span> value</th>
<th>Does mass travel?</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>High mass at <span class="math inline">\(i\)</span>, high mass at <span class="math inline">\(j\)</span></td>
<td>Large</td>
<td>Yes — heavily</td>
<td>Both pixels are ink-rich; a lot of mass needs to move between them</td>
</tr>
<tr class="even">
<td>Zero mass at <span class="math inline">\(i\)</span> or <span class="math inline">\(j\)</span></td>
<td><span class="math inline">\(\approx 0\)</span></td>
<td>No</td>
<td>No ink at source or no ink needed at target; nothing to send or receive</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\tilde{C}_{ij} = 0\)</span> (pixels at same location)</td>
<td>Largest possible</td>
<td>Stays put</td>
<td>Free to keep mass in place; Sinkhorn always prefers this over paying any toll</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\tilde{C}_{ij} = 1\)</span> (pixels at max distance)</td>
<td><span class="math inline">\(\approx 0\)</span></td>
<td>Blocked</td>
<td><span class="math inline">\(e^{-100}\)</span> penalty makes this path virtually impossible regardless of mass</td>
</tr>
<tr class="odd">
<td>High mass + zero cost</td>
<td>Largest entries in <span class="math inline">\(\pi\)</span></td>
<td>Stays put, freely</td>
<td>Best-case: lots of mass, no travel charge</td>
</tr>
<tr class="even">
<td>Low mass + high cost</td>
<td>Smallest entries in <span class="math inline">\(\pi\)</span></td>
<td>Fully blocked</td>
<td>Worst-case: barely any mass, and moving it would be maximally expensive</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Cost matrix <span class="math inline">\(\tilde{C}\)</span> vs transport plan <span class="math inline">\(\pi\)</span>:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th><span class="math inline">\(\tilde{C}\)</span></th>
<th><span class="math inline">\(\pi\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>What it represents</td>
<td>Price tag for moving mass between two pixel locations</td>
<td>Actual amount of mass that flows between two pixel locations</td>
</tr>
<tr class="even">
<td>Who sets it</td>
<td>Fixed by pixel geometry before optimization</td>
<td>Determined by Sinkhorn after optimization</td>
</tr>
<tr class="odd">
<td>Entry range</td>
<td><span class="math inline">\([0, 1]\)</span> after normalization</td>
<td><span class="math inline">\(\geq 0\)</span>, rows sum to <span class="math inline">\(\mathbf{m}\)</span>, cols sum to <span class="math inline">\(\mathbf{v}\)</span></td>
</tr>
<tr class="even">
<td>Diagonal entries</td>
<td>Always 0 — staying at same pixel costs nothing</td>
<td>Large — mass prefers to stay when travel is free</td>
</tr>
<tr class="odd">
<td>Far off-diagonal</td>
<td>Large — distant pixels are expensive to connect</td>
<td><span class="math inline">\(\approx 0\)</span> — expensive paths are avoided</td>
</tr>
<tr class="even">
<td>Does mass travel here?</td>
<td>Not described — this is just the price list</td>
<td>Yes — each entry says exactly how much mass travels that path</td>
</tr>
<tr class="odd">
<td>Role in pipeline</td>
<td>Input: tells Sinkhorn what each path costs</td>
<td>Output: tells us which paths were actually used and how much</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>1. Normalized cost matrix values:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Value</th>
<th>Meaning in plain language</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0\)</span></td>
<td>The two pixels are at the same location — moving mass between them requires zero travel. Free.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.5\)</span></td>
<td>The two pixels are at medium distance — one step horizontally or vertically apart. Half the maximum travel cost.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(1\)</span></td>
<td>The two pixels are at opposite corners of the image — the furthest possible apart. Maximum travel cost.</td>
</tr>
</tbody>
</table>
<hr>
<p><strong>2. Transport plan values:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Value</th>
<th>Meaning in plain language</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0\)</span></td>
<td>No mass travels this path — either the source pixel has no ink, the destination has no ink to receive, or the travel cost made it too expensive.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.1003\)</span></td>
<td>A small but real fraction of total ink mass travels this path — the path is open but not preferred, likely because some travel cost is involved.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0.2780\)</span></td>
<td>The largest flow in the plan — nearly 28% of all ink mass travels this path. This happens at <span class="math inline">\(\tilde{C}_{11} = 0\)</span>: same location, zero cost, so Sinkhorn routes as much mass here as the marginal constraints allow.</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><span class="math inline">\(\tilde{C}_{11} = 0\)</span> answers: <strong>how far apart are pixel 1 and pixel 1?</strong> Answer: zero distance — same location.</p>
<p><span class="math inline">\(\pi_{11} = 0.2780\)</span> answers: <strong>how much mass actually travels from pixel 1 to pixel 1?</strong> Answer: 0.2780.</p>
<p>The confusion is that “zero cost, zero distance” sounds like “nothing happens.” But it means the opposite — because the path is free, Sinkhorn sends as much mass as possible along it. Mass does not travel <em>through space</em> to get there; it simply <strong>stays in place</strong>. Zero cost means zero movement, not zero flow.</p>
<p>Concretely: 0.2780 units of mass sit at pixel 1 in the source, and they remain at pixel 1 in the target. The “transport” is trivial — nothing moves — but <span class="math inline">\(\pi_{11}\)</span> still records that 0.2780 units were “handled” along that path.</p>
<p>Contrast: <span class="math inline">\(\tilde{C}_{03} = 1\)</span> (maximum distance) and <span class="math inline">\(\pi_{03} \approx 0\)</span> — here, zero flow means mass <em>refuses</em> to travel that expensive path.</p>
<p>So:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(\tilde{C}_{ij} = 0\)</span></th>
<th><span class="math inline">\(\tilde{C}_{ij} = 1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Path status</strong></td>
<td>Free</td>
<td>Maximally expensive</td>
</tr>
<tr class="even">
<td><strong>Mass movement</strong></td>
<td>Stays put</td>
<td>Blocked</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(\pi_{ij}\)</span></strong></td>
<td>Large</td>
<td><span class="math inline">\(\approx 0\)</span></td>
</tr>
</tbody>
</table>
<p><strong>IN VERY SIMPLE TERMS, IF THE COST (<span class="math inline">\(C\)</span>) IS FREE, MASS STAYS AND FLOW (<span class="math inline">\(\pi\)</span>) IS LARGE; WHEREAS, IF COST (<span class="math inline">\(C\)</span>) IS MAXIMUM, MASS MOVEMENT IS BLOCKED, AND FLOW (<span class="math inline">\(\pi\)</span>) IS NONE.</strong></p>
<p><br></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(\tilde{C}_{ij} = 0\)</span> (free)</th>
<th><span class="math inline">\(\tilde{C}_{ij} = 0.5\)</span> (medium)</th>
<th><span class="math inline">\(\tilde{C}_{ij} = 1\)</span> (maximum)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Path status</strong></td>
<td>Free — same location</td>
<td>Half-price — one step apart</td>
<td>Maximally expensive — opposite corners</td>
</tr>
<tr class="even">
<td><strong>Mass movement</strong></td>
<td>Stays put</td>
<td>Travels short distance</td>
<td>Blocked</td>
</tr>
<tr class="odd">
<td><strong>Example <span class="math inline">\(\pi_{ij}\)</span></strong></td>
<td><span class="math inline">\(\pi_{11} = 0.2780\)</span>, <span class="math inline">\(\pi_{22} = 0.1920\)</span>, <span class="math inline">\(\pi_{33} = 0.2592\)</span></td>
<td><span class="math inline">\(\pi_{10} = 0.1003\)</span>, <span class="math inline">\(\pi_{20} = 0.1108\)</span></td>
<td><span class="math inline">\(\pi_{03} \approx 0\)</span>, <span class="math inline">\(\pi_{12} \approx 0\)</span>, <span class="math inline">\(\pi_{21} \approx 0\)</span></td>
</tr>
<tr class="even">
<td><strong>Why this value?</strong></td>
<td>No cost penalty — Sinkhorn routes maximum mass here</td>
<td>Moderate penalty — some mass flows but less than free paths</td>
<td><span class="math inline">\(e^{-100}\)</span> penalty — path is effectively shut regardless of mass</td>
</tr>
<tr class="odd">
<td><strong>Dial position</strong></td>
<td>Fully open</td>
<td>Half open</td>
<td>Fully shut</td>
</tr>
</tbody>
</table>
<p>Reading the pattern down any column: the higher the cost, the less mass flows — the cost matrix literally dials each path between fully open (<span class="math inline">\(\tilde{C}=0\)</span>) and fully shut (<span class="math inline">\(\tilde{C}=1\)</span>).</p>
<p>“Dial position” is a metaphor: just as a physical dial controls how much water flows through a pipe, <span class="math inline">\(\tilde{C}_{ij}\)</span> controls how much mass Sinkhorn permits to flow through path <span class="math inline">\((i,j)\)</span> — zero cost turns the dial fully open, maximum cost turns it fully shut.</p>
<hr>
</section>
<section id="step-13-primal-cost-langle-tildec-pi-rangle" class="level3">
<h3 class="anchored" data-anchor-id="step-13-primal-cost-langle-tildec-pi-rangle">Step 13: Primal Cost <span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span></h3>
<p>Using the transport plan from Step 12.5 and the Normalized Cost Matrix <span class="math inline">\(\tilde{C}\)</span>:</p>
<p><span class="math display">\[\pi \approx \begin{pmatrix} 0 &amp; 0 &amp; 0 &amp; 0 \\ 0.1003 &amp; 0.2780 &amp; 0 &amp; 0 \\ 0.1108 &amp; 0 &amp; 0.1920 &amp; 0 \\ 0 &amp; 0 &amp; 0 &amp; 0.2592 \end{pmatrix}, \qquad \tilde{C} = \begin{pmatrix} 0 &amp; 0.5 &amp; 0.5 &amp; 1 \\ 0.5 &amp; 0 &amp; 1 &amp; 0.5 \\ 0.5 &amp; 1 &amp; 0 &amp; 0.5 \\ 1 &amp; 0.5 &amp; 0.5 &amp; 0 \end{pmatrix}\]</span></p>
<p>Compute <span class="math inline">\(\tilde{C}_{ij} \cdot \pi_{ij}\)</span> for every nonzero entry:</p>
<p><span class="math display">\[\tilde{C}_{10}\cdot\pi_{10} = 0.5 \times 0.1003 = 0.0502\]</span> <span class="math display">\[\tilde{C}_{11}\cdot\pi_{11} = 0 \times 0.2780 = 0.0000\]</span> <span class="math display">\[\tilde{C}_{20}\cdot\pi_{20} = 0.5 \times 0.1108 = 0.0554\]</span> <span class="math display">\[\tilde{C}_{22}\cdot\pi_{22} = 0 \times 0.1920 = 0.0000\]</span> <span class="math display">\[\tilde{C}_{33}\cdot\pi_{33} = 0 \times 0.2592 = 0.0000\]</span></p>
<p>All other entries are zero (either <span class="math inline">\(\pi_{ij} \approx 0\)</span> or <span class="math inline">\(\tilde{C}_{ij} = 0\)</span>). Sum:</p>
<p><span class="math display">\[\langle \tilde{C}, \pi \rangle = 0.0502 + 0.0000 + 0.0554 + 0.0000 + 0.0000 = 0.1056\]</span></p>
<p>The anchor primal cost is <span class="math inline">\(0.1056\)</span> — only the two off-diagonal flows (<span class="math inline">\(\pi_{10}\)</span> and <span class="math inline">\(\pi_{20}\)</span>) contribute, both at cost <span class="math inline">\(0.5\)</span>. Every on-diagonal entry (<span class="math inline">\(\pi_{11}, \pi_{22}, \pi_{33}\)</span>) contributes zero because mass staying in place pays no toll.</p>
<p><strong>What is primal cost and what does 0.1056 mean?</strong></p>
<p>The primal cost <span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span> is the <strong>total bill paid</strong> by the transport plan — every unit of mass that moved gets charged its travel distance, and you sum all those charges.</p>
<p>Concretely on the anchor: only two flows moved mass across space: - <span class="math inline">\(\pi_{10} = 0.1003\)</span> units traveled distance <span class="math inline">\(0.5\)</span> → paid <span class="math inline">\(0.0502\)</span> - <span class="math inline">\(\pi_{20} = 0.1108\)</span> units traveled distance <span class="math inline">\(0.5\)</span> → paid <span class="math inline">\(0.0554\)</span></p>
<p>Everything else stayed put (<span class="math inline">\(\tilde{C} = 0\)</span>, free) or was blocked (<span class="math inline">\(\pi \approx 0\)</span>).</p>
<p>Total bill: <span class="math inline">\(0.1056\)</span>.</p>
<p><span class="math inline">\(0.1056\)</span> means: <strong>10.56% of the maximum possible transport cost was spent</strong> moving ink from the “3” arrangement to the “8” arrangement.</p>
<p><strong>Lower = more efficient = mass didn’t need to travel far.</strong></p>
<hr>
</section>
<section id="step-14-effect-of-varepsilon-on-anchor" class="level3">
<h3 class="anchored" data-anchor-id="step-14-effect-of-varepsilon-on-anchor">Step 14: Effect of <span class="math inline">\(\varepsilon\)</span> on anchor</h3>
<p>We now answer: <em>What happens to the transport plan and its cost when <span class="math inline">\(\varepsilon\)</span> changes?</em></p>
<p>Three regimes exist:</p>
<ul>
<li><span class="math inline">\(\varepsilon \to 0\)</span>: entropy penalty disappears, <span class="math inline">\(\pi\)</span> sharpens → only cheapest paths used → lowest primal cost</li>
<li><span class="math inline">\(\varepsilon = 0.01\)</span>: our chosen value → mostly cheap paths, occasional medium paths → primal cost <span class="math inline">\(0.1056\)</span></li>
<li><span class="math inline">\(\varepsilon \to \infty\)</span>: entropy completely dominates → <span class="math inline">\(\pi\)</span> spreads mass uniformly across <strong>all</strong> paths regardless of cost → <strong>this limiting plan is exactly <span class="math inline">\(\mathbf{m}\mathbf{v}^\top\)</span></strong></li>
</ul>
<p><br></p>
<p><strong>The regularized objective is <span class="math inline">\(\mathcal{L}_\varepsilon(\pi) = \langle \tilde{C}, \pi \rangle - \varepsilon H(\pi)\)</span>.</strong></p>
<p>At <span class="math inline">\(\varepsilon = 1.0\)</span>: entropy dominates — <span class="math inline">\(\pi\)</span> spreads mass across all paths including expensive ones (<span class="math inline">\(\tilde{C}_{ij} = 0.5\)</span> and <span class="math inline">\(1.0\)</span>), inflating <span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span>.</p>
<p>At <span class="math inline">\(\varepsilon = 0.01\)</span>: cost dominates — <span class="math inline">\(\pi\)</span> concentrates mass on cheap paths (<span class="math inline">\(\tilde{C}_{ij} = 0\)</span>), driving <span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span> down.</p>
<p><strong>Where does <span class="math inline">\(\mathbf{m}\mathbf{v}^\top\)</span> come from?</strong></p>
<p>When <span class="math inline">\(\varepsilon \to \infty\)</span>, the cost term <span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span> becomes irrelevant — only <span class="math inline">\(-\varepsilon H(\pi)\)</span> matters, so Sinkhorn maximizes entropy alone. The maximum-entropy distribution over a matrix with fixed row sums <span class="math inline">\(\mathbf{m}\)</span> and column sums <span class="math inline">\(\mathbf{v}\)</span> is the <strong>independent coupling</strong>:</p>
<p><span class="math display">\[\pi_{ij} = m_i \cdot v_j\]</span></p>
<p>This is the same as saying: the probability of shipping from <span class="math inline">\(i\)</span> to <span class="math inline">\(j\)</span> equals the probability of <span class="math inline">\(i\)</span> times the probability of <span class="math inline">\(j\)</span> — perfectly independent, no geometric preference. Written as a matrix: <span class="math inline">\(\pi = \mathbf{m}\mathbf{v}^\top\)</span>.</p>
<p>Its cost is therefore:</p>
<p><span class="math display">\[\langle \tilde{C}, \mathbf{m}\mathbf{v}^\top \rangle = \sum_{i,j} \tilde{C}_{ij} \cdot m_i \cdot v_j\]</span></p>
<p>This is the <strong>worst-case cost</strong> — what you pay when you completely ignore geometry.</p>
<hr>
</section>
<section id="step-14.5-full-computation" class="level3">
<h3 class="anchored" data-anchor-id="step-14.5-full-computation">Step 14.5 — Full computation</h3>
<p><strong>Sub-step A: Write out <span class="math inline">\(\mathbf{m}\mathbf{v}^\top\)</span> explicitly</strong></p>
<p><span class="math display">\[\mathbf{m} = (0,\ 0.2835,\ 0.3150,\ 0.4016), \quad \mathbf{v} = (0.2373,\ 0.2881,\ 0.2034,\ 0.2712)\]</span></p>
<p><span class="math display">\[\mathbf{m}\mathbf{v}^\top = \begin{pmatrix} 0\cdot0.2373 &amp; 0\cdot0.2881 &amp; 0\cdot0.2034 &amp; 0\cdot0.2712 \\ 0.2835\cdot0.2373 &amp; 0.2835\cdot0.2881 &amp; 0.2835\cdot0.2034 &amp; 0.2835\cdot0.2712 \\ 0.3150\cdot0.2373 &amp; 0.3150\cdot0.2881 &amp; 0.3150\cdot0.2034 &amp; 0.3150\cdot0.2712 \\ 0.4016\cdot0.2373 &amp; 0.4016\cdot0.2881 &amp; 0.4016\cdot0.2034 &amp; 0.4016\cdot0.2712 \end{pmatrix}\]</span></p>
<p><span class="math display">\[= \begin{pmatrix} 0 &amp; 0 &amp; 0 &amp; 0 \\ 0.0673 &amp; 0.0817 &amp; 0.0577 &amp; 0.0769 \\ 0.0747 &amp; 0.0908 &amp; 0.0641 &amp; 0.0854 \\ 0.0953 &amp; 0.1157 &amp; 0.0817 &amp; 0.1089 \end{pmatrix}\]</span></p>
<p>Verify row 1 sums: <span class="math inline">\(0.0673+0.0817+0.0577+0.0769 = 0.2836 \approx m_1\)</span> ✓</p>
<p><br></p>
<p><strong>Sub-step B: Multiply elementwise by <span class="math inline">\(\tilde{C}\)</span></strong></p>
<p><span class="math display">\[\tilde{C} \odot \mathbf{m}\mathbf{v}^\top = \begin{pmatrix} 0\cdot0 &amp; 0.5\cdot0 &amp; 0.5\cdot0 &amp; 1\cdot0 \\ 0.5\cdot0.0673 &amp; 0\cdot0.0817 &amp; 1\cdot0.0577 &amp; 0.5\cdot0.0769 \\ 0.5\cdot0.0747 &amp; 1\cdot0.0908 &amp; 0\cdot0.0641 &amp; 0.5\cdot0.0854 \\ 1\cdot0.0953 &amp; 0.5\cdot0.1157 &amp; 0.5\cdot0.0817 &amp; 0\cdot0.1089 \end{pmatrix}\]</span></p>
<p><span class="math display">\[= \begin{pmatrix} 0 &amp; 0 &amp; 0 &amp; 0 \\ 0.0337 &amp; 0 &amp; 0.0577 &amp; 0.0385 \\ 0.0374 &amp; 0.0908 &amp; 0 &amp; 0.0427 \\ 0.0953 &amp; 0.0579 &amp; 0.0409 &amp; 0 \end{pmatrix}\]</span></p>
<p><strong>Sub-step C: Sum all entries</strong></p>
<p><span class="math display">\[\langle \tilde{C}, \mathbf{m}\mathbf{v}^\top \rangle = (0.0337+0.0577+0.0385) + (0.0374+0.0908+0.0427) + (0.0953+0.0579+0.0409)\]</span></p>
<p><span class="math display">\[= 0.1299 + 0.1709 + 0.1941 = 0.4949\]</span></p>
<p><strong>Comparison:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\varepsilon\)</span></th>
<th>Plan</th>
<th>Primal cost</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\to \infty\)</span></td>
<td><span class="math inline">\(\mathbf{m}\mathbf{v}^\top\)</span> (independent)</td>
<td><span class="math inline">\(0.4949\)</span></td>
<td>Ignores geometry — pays full price</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.01\)</span></td>
<td><strong>Optimized <span class="math inline">\(\pi\)</span></strong></td>
<td><span class="math inline">\(0.1056\)</span></td>
<td>Respects geometry — uses cheap paths</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\to 0\)</span></td>
<td>True OT plan</td>
<td><span class="math inline">\(&lt; 0.1056\)</span></td>
<td>Sharpest possible — only cheapest paths</td>
</tr>
</tbody>
</table>
<p>The optimized plan costs <strong>79% less</strong> than the geometry-blind plan — this is the entire value of optimal transport over naive blending.</p>
<hr>
</section>
<section id="step-15-dual-potentials-anchor-values" class="level3">
<h3 class="anchored" data-anchor-id="step-15-dual-potentials-anchor-values">Step 15: Dual Potentials — Anchor Values</h3>
<p>Using converged potentials (assumed) from Step 12.5:</p>
<p><span class="math display">\[\phi = \mathbf{f}^* = (-6.9100,\ -0.0130,\ -0.0120,\ -0.0095)\]</span> <span class="math display">\[\psi = \mathbf{g}^* = (0.4900,\ 0.0002,\ -0.0045,\ -0.0040)\]</span></p>
<p>Verify pixel 0 is priced out:</p>
<p><span class="math display">\[\phi_0 = -6.9100 \implies \pi_{0j} = \exp\!\left(\frac{-6.9100 + \psi_j - \tilde{C}_{0j}}{0.01}\right) \approx \exp(-690) \approx 0 \quad \forall j\ \checkmark\]</span></p>
<p><br></p>
<p><span class="math inline">\(\phi_i\)</span> is the “price” Sinkhorn assigned to source pixel <span class="math inline">\(i\)</span> after convergence. It reflects how much mass pixel <span class="math inline">\(i\)</span> has and how cheaply it can be transported.</p>
<ul>
<li><p><span class="math inline">\(\phi_0 = -6.9100\)</span>: pixel 0 is background (<span class="math inline">\(m_0 = 0\)</span>). Sinkhorn drove its price to <span class="math inline">\(-6.91\)</span> because <span class="math inline">\(\phi_i \leftarrow \varepsilon\log m_i \approx 0.01\times(-690) = -6.9\)</span> from the very first iteration and stayed there — there is no mass to ship, so the potential never recovers. Plugging into <span class="math inline">\(\pi_{0j} = \exp((-6.91 + \psi_j - \tilde{C}_{0j})/0.01)\)</span>: the numerator is at best <span class="math inline">\(-6.91 + 0.49 - 0 = -6.42\)</span>, giving <span class="math inline">\(\exp(-642) \approx 0\)</span>. <strong>Pixel 0 is permanently shut out.</strong></p></li>
<li><p><span class="math inline">\(\phi_1 = -0.0130\)</span>, <span class="math inline">\(\phi_2 = -0.0120\)</span>, <span class="math inline">\(\phi_3 = -0.0095\)</span>: these are ink pixels with meaningful mass. Their potentials are close to zero because they carry mass that can be transported cheaply — pixels 1, 2, 3 all have nearby counterparts in <span class="math inline">\(\mathbf{v}\)</span> at zero or low cost.</p></li>
</ul>
<p>Similarly for <span class="math inline">\(\psi\)</span>: <span class="math inline">\(\psi_0 = 0.4900\)</span> is large and positive because pixel 0 in the <em>target</em> carries mass <span class="math inline">\(v_0 = 0.2373\)</span> — it must <em>receive</em> mass from somewhere, and its high <span class="math inline">\(\psi_0\)</span> “attracts” mass from nearby source pixels (specifically <span class="math inline">\(\pi_{10}\)</span> and <span class="math inline">\(\pi_{20}\)</span>).</p>
<hr>
</section>
<section id="step-16-entropy-hpi" class="level3">
<h3 class="anchored" data-anchor-id="step-16-entropy-hpi">Step 16: Entropy <span class="math inline">\(H(\pi)\)</span></h3>
<p><span class="math display">\[H(\pi) = -\sum_{i,j} \pi_{ij}\log\pi_{ij}\]</span></p>
<p><strong>Using nonzero entries only (from Step 13):</strong></p>
<p><span class="math display">\[-\pi_{10}\log\pi_{10} = -0.1003\times\log(0.1003) = -0.1003\times(-2.300) = 0.2307\]</span> <span class="math display">\[-\pi_{11}\log\pi_{11} = -0.2780\times\log(0.2780) = -0.2780\times(-1.280) = 0.3558\]</span> <span class="math display">\[-\pi_{20}\log\pi_{20} = -0.1108\times\log(0.1108) = -0.1108\times(-2.200) = 0.2438\]</span> <span class="math display">\[-\pi_{22}\log\pi_{22} = -0.1920\times\log(0.1920) = -0.1920\times(-1.650) = 0.3168\]</span> <span class="math display">\[-\pi_{33}\log\pi_{33} = -0.2592\times\log(0.2592) = -0.2592\times(-1.350) = 0.3499\]</span></p>
<p><span class="math display">\[H(\pi) = 0.2307 + 0.3558 + 0.2438 + 0.3168 + 0.3499 = 1.4970\]</span></p>
<hr>
</section>
<section id="step-17-full-regularized-objective-mathcall_varepsilonpi" class="level3">
<h3 class="anchored" data-anchor-id="step-17-full-regularized-objective-mathcall_varepsilonpi">Step 17: Full regularized objective <span class="math inline">\(\mathcal{L}_\varepsilon(\pi)\)</span></h3>
<p><span class="math display">\[\mathcal{L}_\varepsilon(\pi) = \langle \tilde{C}, \pi \rangle - \varepsilon H(\pi) = 0.1056 - 0.01\times1.4970 = 0.1056 - 0.01497 = 0.09063\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th>Anchor value</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\langle \tilde{C}, \pi \rangle\)</span></td>
<td><span class="math inline">\(0.1056\)</span></td>
<td>Total travel bill</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\varepsilon H(\pi)\)</span></td>
<td><span class="math inline">\(0.01497\)</span></td>
<td>Entropy bonus for spreading</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathcal{L}_\varepsilon(\pi)\)</span></td>
<td><span class="math inline">\(0.09063\)</span></td>
<td>Net objective Sinkhorn minimized</td>
</tr>
</tbody>
</table>
<p>The objective is positive here (unlike the real MNIST value of <span class="math inline">\(-0.0798\)</span>) because the anchor has only 5 nonzero <span class="math inline">\(\pi\)</span> entries — <span class="math inline">\(H(\pi) = 1.497\)</span> is much smaller than the MNIST value of <span class="math inline">\(8.95\)</span>, so the entropy bonus cannot outweigh the transport cost.</p>
<p><br></p>
<p>On real MNIST, <span class="math inline">\(\mathcal{L}_\varepsilon = -0.0798\)</span> because <span class="math inline">\(H(\pi) = 8.95\)</span> across <span class="math inline">\(614\text{K}\)</span> entries — the entropy bonus <span class="math inline">\(0.01 \times 8.95 = 0.0895\)</span> exceeds the transport cost <span class="math inline">\(0.0097\)</span>, pushing the objective negative.</p>
<p>On the anchor, only 5 entries of <span class="math inline">\(\pi\)</span> are nonzero, so <span class="math inline">\(H(\pi) = 1.497\)</span> — a tiny plan with little to spread. The entropy bonus <span class="math inline">\(0.01 \times 1.497 = 0.015\)</span> is smaller than the transport cost <span class="math inline">\(0.1056\)</span>, so the objective stays positive at <span class="math inline">\(0.091\)</span>. The anchor is a sparse <span class="math inline">\(4\times4\)</span> plan; MNIST is a dense <span class="math inline">\(784\times784\)</span> plan — entropy scales with the number of nonzero entries.</p>
<hr>
</section>
<section id="step-18-dual-objective-mathcaldphi-psi" class="level3">
<h3 class="anchored" data-anchor-id="step-18-dual-objective-mathcaldphi-psi">Step 18: Dual objective <span class="math inline">\(\mathcal{D}(\phi, \psi)\)</span></h3>
<p>The primal problem asks: <em>find the cheapest transport plan <span class="math inline">\(\pi\)</span></em>. The dual problem asks the opposite question from the other side: <em>find the most revenue the “price system” <span class="math inline">\((\phi, \psi)\)</span> can extract</em>. These are two different routes to the same answer.</p>
<p><br></p>
<p><span class="math display">\[\mathcal{D}(\phi,\psi) = \sum_i \phi_i m_i + \sum_j \psi_j v_j\]</span></p>
<p><strong>Source term</strong> <span class="math inline">\(\sum_i \phi_i m_i\)</span> (recall <span class="math inline">\(m_0 = 0\)</span>):</p>
<p><span class="math display">\[\phi_0\cdot m_0 = -6.9100\times 0.0000 = 0.0000\]</span> <span class="math display">\[\phi_1\cdot m_1 = -0.0130\times 0.2835 = -0.003686\]</span> <span class="math display">\[\phi_2\cdot m_2 = -0.0120\times 0.3150 = -0.003780\]</span> <span class="math display">\[\phi_3\cdot m_3 = -0.0095\times 0.4016 = -0.003815\]</span></p>
<p><span class="math display">\[\sum_i \phi_i m_i = 0 - 0.003686 - 0.003780 - 0.003815 = -0.011281\]</span></p>
<p><strong>Target term</strong> <span class="math inline">\(\sum_j \psi_j v_j\)</span>:</p>
<p><span class="math display">\[\psi_0\cdot v_0 = 0.4900\times 0.2373 = 0.116277\]</span> <span class="math display">\[\psi_1\cdot v_1 = 0.0002\times 0.2881 = 0.000058\]</span> <span class="math display">\[\psi_2\cdot v_2 = -0.0045\times 0.2034 = -0.000915\]</span> <span class="math display">\[\psi_3\cdot v_3 = -0.0040\times 0.2712 = -0.001085\]</span></p>
<p><span class="math display">\[\sum_j \psi_j v_j = 0.116277 + 0.000058 - 0.000915 - 0.001085 = 0.114335\]</span></p>
<p><strong>Dual objective:</strong></p>
<p><span class="math display">\[\mathcal{D}(\phi,\psi) = -0.011281 + 0.114335 = 0.103054\]</span></p>
<p><strong>Duality gap:</strong></p>
<p><span class="math display">\[|\mathcal{L}_\varepsilon(\pi) - \mathcal{D}(\phi,\psi)| = |0.09063 - 0.10305| = 0.01242\]</span></p>
<p>The nonzero gap (vs.&nbsp;<span class="math inline">\(1.79\times10^{-10}\)</span> in the real run) reflects the assumed rather than exactly converged potentials — at true convergence this collapses to machine precision.</p>
<p>In simple terms, this stands as a verification that our previous approach is correct. Strong duality says: if the gap <span class="math inline">\(|\mathcal{L}_\varepsilon(\pi) - \mathcal{D}(\phi,\psi)| \approx 0\)</span>, then <span class="math inline">\(\pi\)</span> is provably optimal — no better plan exists. The dual objective provides an independent route to the same answer, and their agreement is the certificate of correctness.</p>
<p><br></p>
<p><strong>What is the dual objective <span class="math inline">\(\mathcal{D}(\phi,\psi) = 0.1031\)</span>?</strong></p>
<p>Think of it as an auctioneer setting prices. <span class="math inline">\(\phi_i\)</span> is the price charged per unit of mass leaving pixel <span class="math inline">\(i\)</span>; <span class="math inline">\(\psi_j\)</span> is the price paid per unit arriving at pixel <span class="math inline">\(j\)</span>. The dual objective is the total revenue collected:</p>
<p><span class="math display">\[\mathcal{D} = \underbrace{(-0.0113)}_{\text{source revenue}} + \underbrace{(0.1143)}_{\text{target revenue}} = 0.1031\]</span></p>
<p>The source revenue is negative because ink pixels have slightly negative <span class="math inline">\(\phi\)</span> — they pay a small “shipping fee.” The target revenue is positive and large because <span class="math inline">\(\psi_0 = 0.4900\)</span> collects substantial revenue from the mass arriving at pixel 0.</p>
<p><strong>What is the duality gap <span class="math inline">\(= 0.0124\)</span>?</strong></p>
<p>At exact convergence, strong duality guarantees <span class="math inline">\(\mathcal{L}_\varepsilon(\pi) = \mathcal{D}(\phi,\psi)\)</span> — primal cost equals dual revenue, gap = 0. This means the transport plan and the price system are perfectly consistent: no cheaper plan exists, and no higher revenue is extractable.</p>
<p>Our gap of <span class="math inline">\(0.0124\)</span> is nonzero only because the potentials are assumed rather than exactly converged. On real MNIST the gap is <span class="math inline">\(1.79\times10^{-10}\)</span> — essentially zero — confirming Sinkhorn found the true optimum.</p>
<p><strong>Why does this matter?</strong> The gap is a certificate. Gap <span class="math inline">\(\approx 0\)</span> means: <em>you cannot find a better transport plan</em> — the dual prices prove it. A large gap would mean Sinkhorn hasn’t converged yet and <span class="math inline">\(\pi\)</span> may still be improvable.</p>
<p><strong>What does <span class="math inline">\(\mathcal{L}_\varepsilon(\pi) = 0.09063\)</span> mean?</strong></p>
<p>It is the single number Sinkhorn was minimizing all along. It combines two competing forces:</p>
<ul>
<li>Transport cost <span class="math inline">\(0.1056\)</span>: how much mass moved and how far</li>
<li>Entropy bonus <span class="math inline">\(0.01497\)</span>: a reward for spreading mass across multiple paths</li>
</ul>
<p>Net: <span class="math inline">\(0.1056 - 0.01497 = 0.09063\)</span> — this is what Sinkhorn reduced iteration by iteration until it couldn’t reduce it further.</p>
<p><strong>Why calculate it?</strong> To confirm Sinkhorn actually solved the right problem. If we only checked marginals, we’d know <span class="math inline">\(\pi\)</span> is <em>feasible</em> but not <em>optimal</em>. Computing <span class="math inline">\(\mathcal{L}_\varepsilon(\pi)\)</span> and then comparing it to the dual objective proves optimality.</p>
<p><strong>Why compare to real MNIST?</strong> Only to explain why the anchor value is positive while MNIST’s is negative — the sign difference isn’t a mistake, it’s a consequence of scale. The anchor has 5 nonzero entries; MNIST has ~614K. More entries = larger entropy = larger bonus = objective goes negative. The anchor is too small for the entropy bonus to dominate.</p>
<p><strong>What does it mean for the anchor specifically?</strong> The plan paid a transport bill of <span class="math inline">\(0.1056\)</span>, collected an entropy bonus of <span class="math inline">\(0.01497\)</span>, and the net optimized objective is <span class="math inline">\(0.09063\)</span>. <strong>No other feasible transport plan between <span class="math inline">\(\mathbf{m}\)</span> and <span class="math inline">\(\mathbf{v}\)</span> achieves a lower value than this — that is what optimality means.</strong></p>
<hr>
</section>
<section id="step-19-slack-matrix-and-complementary-slackness" class="level3">
<h3 class="anchored" data-anchor-id="step-19-slack-matrix-and-complementary-slackness">Step 19: Slack Matrix and Complementary Slackness</h3>
<p><strong>What is slack and why compute it?</strong></p>
<p>Strong duality confirmed that primal and dual objectives match — <span class="math inline">\(\pi\)</span> is optimal. But that only tells us the <em>value</em> is right. Complementary slackness tells us <em>where</em> in the <span class="math inline">\(4\times4\)</span> grid mass is allowed to sit — it specifies which paths <span class="math inline">\((i,j)\)</span> are geometrically consistent with optimality.</p>
<p>The slack at each path is:</p>
<p><span class="math display">\[s_{ij} = \tilde{C}_{ij} - (\phi_i + \psi_j)\]</span></p>
<p>Think of it as: “how much does the actual travel cost <em>exceed</em> the sum of prices?” When <span class="math inline">\(s_{ij} = 0\)</span>, the prices exactly account for the travel cost — the path is perfectly priced and open. When <span class="math inline">\(s_{ij}\)</span> is large, the travel cost far exceeds what the prices justify — the path is overpriced and mass avoids it.</p>
<p>The connection to <span class="math inline">\(\pi\)</span>:</p>
<p><span class="math display">\[\pi_{ij} = \exp\!\left(\frac{-s_{ij}}{\varepsilon}\right)\]</span></p>
<p>So slack directly dials <span class="math inline">\(\pi_{ij}\)</span>: zero slack → <span class="math inline">\(\exp(0) = 1\)</span> → maximum flow; large slack → <span class="math inline">\(\exp(-\text{large}/0.01)\)</span> → zero flow.</p>
<p><br></p>
<p><strong>Sub-step A: Compute full slack matrix <span class="math inline">\(s_{ij} = \tilde{C}_{ij} - (\phi_i + \psi_j)\)</span></strong></p>
<p>First compute <span class="math inline">\(\phi_i + \psi_j\)</span> for all pairs:</p>
<p><span class="math display">\[\phi_i + \psi_j = \begin{pmatrix} -6.9100+0.4900 &amp; -6.9100+0.0002 &amp; -6.9100-0.0045 &amp; -6.9100-0.0040 \\ -0.0130+0.4900 &amp; -0.0130+0.0002 &amp; -0.0130-0.0045 &amp; -0.0130-0.0040 \\ -0.0120+0.4900 &amp; -0.0120+0.0002 &amp; -0.0120-0.0045 &amp; -0.0120-0.0040 \\ -0.0095+0.4900 &amp; -0.0095+0.0002 &amp; -0.0095-0.0045 &amp; -0.0095-0.0040 \end{pmatrix}\]</span></p>
<p><span class="math display">\[= \begin{pmatrix} -6.4200 &amp; -6.9098 &amp; -6.9145 &amp; -6.9140 \\ 0.4770 &amp; -0.0128 &amp; -0.0175 &amp; -0.0170 \\ 0.4780 &amp; -0.0118 &amp; -0.0165 &amp; -0.0160 \\ 0.4805 &amp; -0.0093 &amp; -0.0140 &amp; -0.0135 \end{pmatrix}\]</span></p>
<p><br></p>
<p>Now subtract from <span class="math inline">\(\tilde{C}\)</span>:</p>
<p><span class="math display">\[s_{ij} = \tilde{C}_{ij} - (\phi_i + \psi_j)\]</span></p>
<p><strong>Row 0:</strong> <span class="math display">\[s_{00} = 0 - (-6.4200) = 6.4200\]</span> <span class="math display">\[s_{01} = 0.5 - (-6.9098) = 7.4098\]</span> <span class="math display">\[s_{02} = 0.5 - (-6.9145) = 7.4145\]</span> <span class="math display">\[s_{03} = 1.0 - (-6.9140) = 7.9140\]</span></p>
<p><strong>Row 1:</strong> <span class="math display">\[s_{10} = 0.5 - 0.4770 = 0.0230\]</span> <span class="math display">\[s_{11} = 0 - (-0.0128) = 0.0128\]</span> <span class="math display">\[s_{12} = 1.0 - (-0.0175) = 1.0175\]</span> <span class="math display">\[s_{13} = 0.5 - (-0.0170) = 0.5170\]</span></p>
<p><strong>Row 2:</strong> <span class="math display">\[s_{20} = 0.5 - 0.4780 = 0.0220\]</span> <span class="math display">\[s_{21} = 1.0 - (-0.0118) = 1.0118\]</span> <span class="math display">\[s_{22} = 0 - (-0.0165) = 0.0165\]</span> <span class="math display">\[s_{23} = 0.5 - (-0.0160) = 0.5160\]</span></p>
<p><strong>Row 3:</strong> <span class="math display">\[s_{30} = 1.0 - 0.4805 = 0.5195\]</span> <span class="math display">\[s_{31} = 0.5 - (-0.0093) = 0.5093\]</span> <span class="math display">\[s_{32} = 0.5 - (-0.0140) = 0.5140\]</span> <span class="math display">\[s_{33} = 0 - (-0.0135) = 0.0135\]</span></p>
<p><br></p>
<p><span class="math display">\[S = \begin{pmatrix} 6.4200 &amp; 7.4098 &amp; 7.4145 &amp; 7.9140 \\ 0.0230 &amp; 0.0128 &amp; 1.0175 &amp; 0.5170 \\ 0.0220 &amp; 1.0118 &amp; 0.0165 &amp; 0.5160 \\ 0.5195 &amp; 0.5093 &amp; 0.5140 &amp; 0.0135 \end{pmatrix}\]</span></p>
<p><strong>Verify dual feasibility:</strong> <span class="math inline">\(\min(S) = 0.0128 &gt; 0\)</span> ✓ — every entry is non-negative, meaning <span class="math inline">\(\phi_i + \psi_j \leq \tilde{C}_{ij}\)</span> everywhere. The price system never over-values any path.</p>
<p><br></p>
<p><strong>Sub-step B: Interpret the slack values</strong></p>
<p>The slack matrix directly explains the transport plan structure:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Path <span class="math inline">\((i,j)\)</span></th>
<th><span class="math inline">\(s_{ij}\)</span></th>
<th><span class="math inline">\(\pi_{ij}\)</span></th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\((1,1)\)</span></td>
<td><span class="math inline">\(0.0128\)</span></td>
<td><span class="math inline">\(0.2780\)</span></td>
<td>Near-zero slack → large flow. Same location, nearly free</td>
</tr>
<tr class="even">
<td><span class="math inline">\((2,2)\)</span></td>
<td><span class="math inline">\(0.0165\)</span></td>
<td><span class="math inline">\(0.1920\)</span></td>
<td>Near-zero slack → large flow. Same location, nearly free</td>
</tr>
<tr class="odd">
<td><span class="math inline">\((3,3)\)</span></td>
<td><span class="math inline">\(0.0135\)</span></td>
<td><span class="math inline">\(0.2592\)</span></td>
<td>Near-zero slack → large flow. Same location, nearly free</td>
</tr>
<tr class="even">
<td><span class="math inline">\((1,0)\)</span></td>
<td><span class="math inline">\(0.0230\)</span></td>
<td><span class="math inline">\(0.1003\)</span></td>
<td>Small slack → moderate flow. One step apart</td>
</tr>
<tr class="odd">
<td><span class="math inline">\((2,0)\)</span></td>
<td><span class="math inline">\(0.0220\)</span></td>
<td><span class="math inline">\(0.1108\)</span></td>
<td>Small slack → moderate flow. One step apart</td>
</tr>
<tr class="even">
<td><span class="math inline">\((0,j)\)</span></td>
<td><span class="math inline">\(6.4\)</span>–<span class="math inline">\(7.9\)</span></td>
<td><span class="math inline">\(\approx 0\)</span></td>
<td>Enormous slack → zero flow. Background pixel priced out</td>
</tr>
<tr class="odd">
<td><span class="math inline">\((1,2)\)</span></td>
<td><span class="math inline">\(1.0175\)</span></td>
<td><span class="math inline">\(\approx 0\)</span></td>
<td>Large slack → zero flow. Maximum distance path blocked</td>
</tr>
</tbody>
</table>
<p>The pattern is clear: slack near zero means the path is geometrically consistent with the price system and mass flows freely; large slack means the path is inconsistent and mass is exponentially suppressed.</p>
<p><br></p>
<p><strong>Sub-step C: Weighted slack <span class="math inline">\(s_{ij} \cdot \pi_{ij}\)</span></strong></p>
<p>Complementary slackness requires <span class="math inline">\(s_{ij} \cdot \pi_{ij} \approx 0\)</span> for all <span class="math inline">\((i,j)\)</span>. Two ways this is satisfied:</p>
<ul>
<li><span class="math inline">\(s_{ij} \approx 0\)</span> (path is open, mass flows freely) — satisfied at <span class="math inline">\((1,1), (2,2), (3,3), (1,0), (2,0)\)</span></li>
<li><span class="math inline">\(\pi_{ij} \approx 0\)</span> (path is blocked, no mass flows) — satisfied at all remaining entries</li>
</ul>
<p>Computing for the five nonzero flows (from Step 13):</p>
<p><span class="math display">\[s_{10}\cdot\pi_{10} = 0.0230\times0.1003 = 0.002307\]</span> <span class="math display">\[s_{11}\cdot\pi_{11} = 0.0128\times0.2780 = 0.003558\]</span> <span class="math display">\[s_{20}\cdot\pi_{20} = 0.0220\times0.1108 = 0.002438\]</span> <span class="math display">\[s_{22}\cdot\pi_{22} = 0.0165\times0.1920 = 0.003168\]</span> <span class="math display">\[s_{33}\cdot\pi_{33} = 0.0135\times0.2592 = 0.003499\]</span></p>
<p>All other entries: <span class="math inline">\(s_{ij}\)</span> is large but <span class="math inline">\(\pi_{ij} \approx 0\)</span>, so product <span class="math inline">\(\approx 0\)</span>.</p>
<p><strong>Maximum weighted slack <span class="math inline">\(= 0.003558\)</span> — small but not exactly zero, again because potentials are assumed rather than exactly converged. At true convergence this collapses to <span class="math inline">\(\approx 10^{-5}\)</span> range as seen in the real output.</strong></p>
<p><br></p>
<p><strong>Sub-step D: KKT conditions — FULL SUMMARY</strong></p>
<p>Three conditions must all hold simultaneously for <span class="math inline">\(\pi\)</span> to be certifiably optimal:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>What it checks</th>
<th>Anchor result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Primal feasibility: <span class="math inline">\(\pi \in \Pi(\mathbf{m},\mathbf{v})\)</span></td>
<td>Row sums <span class="math inline">\(= \mathbf{m}\)</span>, col sums <span class="math inline">\(= \mathbf{v}\)</span></td>
<td>✓ Verified in Step 12</td>
</tr>
<tr class="even">
<td>Dual feasibility: <span class="math inline">\(s_{ij} \geq 0\ \forall i,j\)</span></td>
<td>Price system never over-values any path</td>
<td>✓ <span class="math inline">\(\min(S) = 0.0128 &gt; 0\)</span></td>
</tr>
<tr class="odd">
<td>Complementary slackness: <span class="math inline">\(s_{ij}\pi_{ij} \approx 0\ \forall i,j\)</span></td>
<td>Mass only flows where prices are consistent</td>
<td>✓ Max product <span class="math inline">\(= 0.0036\)</span></td>
</tr>
</tbody>
</table>
<p>All three hold. <span class="math inline">\(\pi\)</span> is globally optimal — no other transport plan between <span class="math inline">\(\mathbf{m}\)</span> and <span class="math inline">\(\mathbf{v}\)</span> achieves a lower regularized cost. The mathematical certification is complete.</p>
<hr>
</section>
<section id="step-20-displacement-interpolation-wasserstein-geodesic" class="level3">
<h3 class="anchored" data-anchor-id="step-20-displacement-interpolation-wasserstein-geodesic">Step 20: Displacement Interpolation — Wasserstein Geodesic</h3>
<p><span class="math inline">\(\pi\)</span> tells us how much mass moves from pixel <span class="math inline">\(i\)</span> to pixel <span class="math inline">\(j\)</span>. Displacement interpolation asks: at time <span class="math inline">\(t\)</span>, where is that mass <em>in transit</em>?</p>
<p>Each <span class="math inline">\(\pi_{ij}\)</span> unit of mass travels a straight line from <span class="math inline">\(\mathbf{x}_i\)</span> to <span class="math inline">\(\mathbf{x}_j\)</span> — at time <span class="math inline">\(t\)</span> it sits at:</p>
<p><span class="math display">\[(1-t)\mathbf{x}_i + t\mathbf{x}_j\]</span></p>
<p>Collecting all mass positions at each <span class="math inline">\(t\)</span> gives the intermediate frame <span class="math inline">\(\mu_t\)</span>.</p>
<p><strong>Timesteps used:</strong></p>
<p><span class="math display">\[t \in \{0,\ 0.111,\ 0.222,\ 0.333,\ 0.444,\ 0.556,\ 0.667,\ 0.778,\ 0.889,\ 1.0\}\]</span></p>
<p>We work through <span class="math inline">\(t=0\)</span>, <span class="math inline">\(t=0.5\)</span> (midpoint), and <span class="math inline">\(t=1\)</span> fully. These three cover all distinct behaviors.</p>
<p><code>np.linspace(0, 1, 10)</code> divides the interval <span class="math inline">\([0,1]\)</span> into 9 equal steps of size <span class="math inline">\(1/9 \approx 0.111\)</span>, producing exactly 10 evenly spaced values from 0 to 1.</p>
<p><br></p>
<section id="t-0-recovery-of-source-mu" class="level4">
<h4 class="anchored" data-anchor-id="t-0-recovery-of-source-mu"><span class="math inline">\(t = 0\)</span>: Recovery of source <span class="math inline">\(\mu\)</span></h4>
<p><span class="math display">\[\mathbf{z}_{ij}(0) = (1-0)\mathbf{x}_i + 0\cdot\mathbf{x}_j = \mathbf{x}_i \quad \forall j\]</span></p>
<p>Every unit of mass at <span class="math inline">\((i,j)\)</span> lands at <span class="math inline">\(\mathbf{x}_i\)</span> — the source location. <strong>All <span class="math inline">\(j\)</span> collapse to same position.</strong></p>
<p><strong>Pixel 0</strong> (<span class="math inline">\(m_0 = 0\)</span>): <span class="math inline">\(\sum_j \pi_{0j} \approx 0\)</span> → skipped.</p>
<p><strong>Pixel 1</strong> (<span class="math inline">\(\mathbf{x}_1 = (0,1)\)</span>): all mass lands at <span class="math inline">\((0,1)\)</span> regardless of <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[k = 2\cdot0 + 1 = 1\]</span> <span class="math display">\[\mu_0(1) \mathrel{+}= \pi_{10} + \pi_{11} + \pi_{12} + \pi_{13} = 0.1003 + 0.2780 + 0 + 0 = 0.3783\]</span></p>
<p><span class="math inline">\(k\)</span> is the <strong>flat pixel index</strong> — it converts the rounded 2D interpolated coordinate <span class="math inline">\((r, c)\)</span> back to a single integer via <span class="math inline">\(k = 2r + c\)</span> (the same row-major formula from Step 5), telling <code>np.add.at</code> exactly which slot in the 4-element <code>frame</code> vector to deposit mass <span class="math inline">\(\pi_{ij}\)</span> into.</p>
<p><span class="math inline">\(r\)</span> and <span class="math inline">\(c\)</span> are the <strong>rounded interpolated coordinates</strong>:</p>
<p><span class="math display">\[r = \text{round}(z_{ij}^{(0)}), \quad c = \text{round}(z_{ij}^{(1)})\]</span></p>
<p>Once rounded to integers, <span class="math inline">\((r, c)\)</span> is a valid 2D grid position. Converting it back to a flat index uses the same row-major formula as Step 5 but in reverse — Step 5 went from flat index <span class="math inline">\(i\)</span> to <span class="math inline">\((r,c)\)</span> via <span class="math inline">\(r = \lfloor i/2 \rfloor\)</span>, <span class="math inline">\(c = i \bmod 2\)</span>. Here we go the other direction: given <span class="math inline">\((r,c)\)</span>, recover <span class="math inline">\(k = 2r + c\)</span>.</p>
<p>For pixel 1 at <span class="math inline">\(t=0\)</span>: interpolated position is <span class="math inline">\((0, 1.0)\)</span>, rounds to <span class="math inline">\(r=0, c=1\)</span>, so <span class="math inline">\(k = 2\cdot0 + 1 = 1\)</span> — flat index 1, which is exactly pixel 1’s position in the <code>frame</code> vector.</p>
<p><strong>Pixel 2</strong> (<span class="math inline">\(\mathbf{x}_2 = (1,0)\)</span>): all mass lands at <span class="math inline">\((1,0)\)</span>:</p>
<p><span class="math display">\[k = 2\cdot1 + 0 = 2\]</span> <span class="math display">\[\mu_0(2) \mathrel{+}= \pi_{20} + \pi_{21} + \pi_{22} + \pi_{23} = 0.1108 + 0 + 0.1920 + 0 = 0.3028\]</span></p>
<p><strong>Pixel 3</strong> (<span class="math inline">\(\mathbf{x}_3 = (1,1)\)</span>): all mass lands at <span class="math inline">\((1,1)\)</span>:</p>
<p><span class="math display">\[k = 2\cdot1 + 1 = 3\]</span> <span class="math display">\[\mu_0(3) \mathrel{+}= \pi_{30} + \pi_{31} + \pi_{32} + \pi_{33} = 0 + 0 + 0 + 0.2592 = 0.2592\]</span></p>
<p><span class="math display">\[\mu_0 = (0,\ 0.3783,\ 0.3028,\ 0.2592)\]</span></p>
<p>Compare to <span class="math inline">\(\mathbf{m} = (0,\ 0.2835,\ 0.3150,\ 0.4016)\)</span> — close but not exact due to assumed potentials. At true convergence: <span class="math inline">\(\mu_0 = \mathbf{m}\)</span> exactly ✓</p>
<p><br></p>
</section>
<section id="t-0.5-midpoint-frame" class="level4">
<h4 class="anchored" data-anchor-id="t-0.5-midpoint-frame"><span class="math inline">\(t = 0.5\)</span>: Midpoint frame</h4>
<p><span class="math display">\[\mathbf{z}_{ij}(0.5) = 0.5\mathbf{x}_i + 0.5\mathbf{x}_j\]</span></p>
<p><strong>Pixel 0 skipped</strong> (<span class="math inline">\(m_0 = 0\)</span>).</p>
<p><strong>Pixel 1</strong> (<span class="math inline">\(\mathbf{x}_1 = (0,1)\)</span>), compute <span class="math inline">\(\mathbf{z}_{1j}\)</span> for all <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[\mathbf{z}_{10}(0.5) = 0.5(0,1) + 0.5(0,0) = (0,\ 0.5) \xrightarrow{\text{round}} (0,\ 0) \implies k=0\]</span> <span class="math display">\[\mathbf{z}_{11}(0.5) = 0.5(0,1) + 0.5(0,1) = (0,\ 1.0) \xrightarrow{\text{round}} (0,\ 1) \implies k=1\]</span> <span class="math display">\[\mathbf{z}_{12}(0.5) = 0.5(0,1) + 0.5(1,0) = (0.5,\ 0.5) \xrightarrow{\text{round}} (0,\ 0) \implies k=0\]</span> <span class="math display">\[\mathbf{z}_{13}(0.5) = 0.5(0,1) + 0.5(1,1) = (0.5,\ 1.0) \xrightarrow{\text{round}} (0,\ 1) \implies k=1\]</span></p>
<p>Deposit mass:</p>
<p><span class="math display">\[\mu_{0.5}(0) \mathrel{+}= \pi_{10} + \pi_{12} = 0.1003 + 0 = 0.1003\]</span> <span class="math display">\[\mu_{0.5}(1) \mathrel{+}= \pi_{11} + \pi_{13} = 0.2780 + 0 = 0.2780\]</span></p>
<p><strong>Pixel 2</strong> (<span class="math inline">\(\mathbf{x}_2 = (1,0)\)</span>), compute <span class="math inline">\(\mathbf{z}_{2j}\)</span>:</p>
<p><span class="math display">\[\mathbf{z}_{20}(0.5) = 0.5(1,0) + 0.5(0,0) = (0.5,\ 0) \xrightarrow{\text{round}} (0,\ 0) \implies k=0\]</span> <span class="math display">\[\mathbf{z}_{21}(0.5) = 0.5(1,0) + 0.5(0,1) = (0.5,\ 0.5) \xrightarrow{\text{round}} (0,\ 0) \implies k=0\]</span> <span class="math display">\[\mathbf{z}_{22}(0.5) = 0.5(1,0) + 0.5(1,0) = (1.0,\ 0) \xrightarrow{\text{round}} (1,\ 0) \implies k=2\]</span> <span class="math display">\[\mathbf{z}_{23}(0.5) = 0.5(1,0) + 0.5(1,1) = (1.0,\ 0.5) \xrightarrow{\text{round}} (1,\ 0) \implies k=2\]</span></p>
<p>Deposit mass:</p>
<p><span class="math display">\[\mu_{0.5}(0) \mathrel{+}= \pi_{20} + \pi_{21} = 0.1108 + 0 = 0.1108\]</span> <span class="math display">\[\mu_{0.5}(2) \mathrel{+}= \pi_{22} + \pi_{23} = 0.1920 + 0 = 0.1920\]</span></p>
<p><strong>Pixel 3</strong> (<span class="math inline">\(\mathbf{x}_3 = (1,1)\)</span>), compute <span class="math inline">\(\mathbf{z}_{3j}\)</span>:</p>
<p><span class="math display">\[\mathbf{z}_{30}(0.5) = 0.5(1,1) + 0.5(0,0) = (0.5,\ 0.5) \xrightarrow{\text{round}} (0,\ 0) \implies k=0\]</span> <span class="math display">\[\mathbf{z}_{31}(0.5) = 0.5(1,1) + 0.5(0,1) = (0.5,\ 1.0) \xrightarrow{\text{round}} (0,\ 1) \implies k=1\]</span> <span class="math display">\[\mathbf{z}_{32}(0.5) = 0.5(1,1) + 0.5(1,0) = (1.0,\ 0.5) \xrightarrow{\text{round}} (1,\ 0) \implies k=2\]</span> <span class="math display">\[\mathbf{z}_{33}(0.5) = 0.5(1,1) + 0.5(1,1) = (1.0,\ 1.0) \xrightarrow{\text{round}} (1,\ 1) \implies k=3\]</span></p>
<p>Deposit mass:</p>
<p><span class="math display">\[\mu_{0.5}(0) \mathrel{+}= \pi_{30} = 0\]</span> <span class="math display">\[\mu_{0.5}(1) \mathrel{+}= \pi_{31} = 0\]</span> <span class="math display">\[\mu_{0.5}(2) \mathrel{+}= \pi_{32} = 0\]</span> <span class="math display">\[\mu_{0.5}(3) \mathrel{+}= \pi_{33} = 0.2592\]</span></p>
<p><strong>Accumulate all deposits at <span class="math inline">\(t=0.5\)</span>:</strong></p>
<p><span class="math display">\[\mu_{0.5}(0) = 0.1003 + 0.1108 + 0 = 0.2111\]</span> <span class="math display">\[\mu_{0.5}(1) = 0.2780 + 0 + 0 = 0.2780\]</span> <span class="math display">\[\mu_{0.5}(2) = 0.1920 + 0 = 0.1920\]</span> <span class="math display">\[\mu_{0.5}(3) = 0.2592\]</span></p>
<p><span class="math display">\[\mu_{0.5} = (0.2111,\ 0.2780,\ 0.1920,\ 0.2592)\]</span></p>
<p>Verify mass conservation: <span class="math inline">\(0.2111 + 0.2780 + 0.1920 + 0.2592 = 0.9403 \approx 1\)</span> ✓ (small gap from assumed potentials)</p>
<p><strong>What happened geometrically:</strong> at <span class="math inline">\(t=0\)</span>, pixel 0 carried zero mass. At <span class="math inline">\(t=0.5\)</span>, pixel 0 now holds <span class="math inline">\(0.2111\)</span> — mass from pixels 1 and 2 is physically in transit, passing through pixel 0’s location on its way to the target. This is displacement interpolation: mass moves through space, not through intensity.</p>
<p><br></p>
</section>
<section id="t-1-recovery-of-target-nu" class="level4">
<h4 class="anchored" data-anchor-id="t-1-recovery-of-target-nu"><span class="math inline">\(t = 1\)</span>: Recovery of target <span class="math inline">\(\nu\)</span></h4>
<p><span class="math display">\[\mathbf{z}_{ij}(1) = 0\cdot\mathbf{x}_i + 1\cdot\mathbf{x}_j = \mathbf{x}_j \quad \forall i\]</span></p>
<p>Every unit of mass lands at <span class="math inline">\(\mathbf{x}_j\)</span> — the target location. All <span class="math inline">\(i\)</span> collapse to target positions.</p>
<p><strong>Pixel 0 skipped.</strong></p>
<p><strong>From pixel 1:</strong> mass <span class="math inline">\(\pi_{10}=0.1003\)</span> lands at <span class="math inline">\(\mathbf{x}_0=(0,0)\to k=0\)</span>; mass <span class="math inline">\(\pi_{11}=0.2780\)</span> lands at <span class="math inline">\(\mathbf{x}_1=(0,1)\to k=1\)</span>.</p>
<p><strong>From pixel 2:</strong> mass <span class="math inline">\(\pi_{20}=0.1108\)</span> lands at <span class="math inline">\(\mathbf{x}_0=(0,0)\to k=0\)</span>; mass <span class="math inline">\(\pi_{22}=0.1920\)</span> lands at <span class="math inline">\(\mathbf{x}_2=(1,0)\to k=2\)</span>.</p>
<p><strong>From pixel 3:</strong> mass <span class="math inline">\(\pi_{33}=0.2592\)</span> lands at <span class="math inline">\(\mathbf{x}_3=(1,1)\to k=3\)</span>.</p>
<p><span class="math display">\[\mu_1(0) = \pi_{10} + \pi_{20} = 0.1003 + 0.1108 = 0.2111\]</span> <span class="math display">\[\mu_1(1) = \pi_{11} = 0.2780\]</span> <span class="math display">\[\mu_1(2) = \pi_{22} = 0.1920\]</span> <span class="math display">\[\mu_1(3) = \pi_{33} = 0.2592\]</span></p>
<p><span class="math display">\[\mu_1 = (0.2111,\ 0.2780,\ 0.1920,\ 0.2592)\]</span></p>
<p>Compare to <span class="math inline">\(\mathbf{v} = (0.2373,\ 0.2881,\ 0.2034,\ 0.2712)\)</span> — close, gap from assumed potentials. At true convergence: <span class="math inline">\(\mu_1 = \mathbf{v}\)</span> exactly ✓</p>
<p><br></p>
</section>
<section id="summary-across-all-three-frames" class="level4">
<h4 class="anchored" data-anchor-id="summary-across-all-three-frames">Summary across all three frames</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Pixel <span class="math inline">\(k\)</span></th>
<th>Location</th>
<th><span class="math inline">\(\mu_0\)</span> (source)</th>
<th><span class="math inline">\(\mu_{0.5}\)</span> (midpoint)</th>
<th><span class="math inline">\(\mu_1\)</span> (target)</th>
<th><span class="math inline">\(\mathbf{v}\)</span> (true target)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\((0,0)\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0.2111\)</span></td>
<td><span class="math inline">\(0.2111\)</span></td>
<td><span class="math inline">\(0.2373\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\((0,1)\)</span></td>
<td><span class="math inline">\(0.3783\)</span></td>
<td><span class="math inline">\(0.2780\)</span></td>
<td><span class="math inline">\(0.2780\)</span></td>
<td><span class="math inline">\(0.2881\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\((1,0)\)</span></td>
<td><span class="math inline">\(0.3028\)</span></td>
<td><span class="math inline">\(0.1920\)</span></td>
<td><span class="math inline">\(0.1920\)</span></td>
<td><span class="math inline">\(0.2034\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\((1,1)\)</span></td>
<td><span class="math inline">\(0.2592\)</span></td>
<td><span class="math inline">\(0.2592\)</span></td>
<td><span class="math inline">\(0.2592\)</span></td>
<td><span class="math inline">\(0.2712\)</span></td>
</tr>
</tbody>
</table>
<p>The key observation: pixel 0 starts at zero mass, gains <span class="math inline">\(0.2111\)</span> by <span class="math inline">\(t=0.5\)</span> as transiting mass passes through, and holds that mass at <span class="math inline">\(t=1\)</span>. Pixels 1, 2, 3 shed mass as it departs toward target positions. Mass is physically redistributed through space — not faded.</p>
<hr>
</section>
</section>
<section id="step-21-pixel-blending-baseline-at-t0.5" class="level3">
<h3 class="anchored" data-anchor-id="step-21-pixel-blending-baseline-at-t0.5">Step 21: Pixel Blending Baseline at <span class="math inline">\(t=0.5\)</span></h3>
<p><br></p>
<p><span class="math display">\[\mu_{0.5}^{\text{blend}} = 0.5\,\mathbf{m} + 0.5\,\mathbf{v}\]</span></p>
<p><span class="math display">\[\mu_{0.5}^{\text{blend}}(0) = 0.5\times0 + 0.5\times0.2373 = 0.1187\]</span> <span class="math display">\[\mu_{0.5}^{\text{blend}}(1) = 0.5\times0.2835 + 0.5\times0.2881 = 0.2858\]</span> <span class="math display">\[\mu_{0.5}^{\text{blend}}(2) = 0.5\times0.3150 + 0.5\times0.2034 = 0.2592\]</span> <span class="math display">\[\mu_{0.5}^{\text{blend}}(3) = 0.5\times0.4016 + 0.5\times0.2712 = 0.3364\]</span></p>
<p><span class="math display">\[\mu_{0.5}^{\text{blend}} = (0.1187,\ 0.2858,\ 0.2592,\ 0.3364)\]</span></p>
<p><br></p>
<p><strong>Direct comparison at <span class="math inline">\(t=0.5\)</span>:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Pixel <span class="math inline">\(k\)</span></th>
<th>Wasserstein <span class="math inline">\(\mu_{0.5}\)</span></th>
<th>Blending <span class="math inline">\(\mu_{0.5}^{\text{blend}}\)</span></th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\(0.2111\)</span></td>
<td><span class="math inline">\(0.1187\)</span></td>
<td>Wasserstein sends more mass here — transiting mass physically passes through</td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\(0.2780\)</span></td>
<td><span class="math inline">\(0.2858\)</span></td>
<td>Similar — pixel 1 is shared by both images</td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(0.1920\)</span></td>
<td><span class="math inline">\(0.2592\)</span></td>
<td>Blending keeps more mass here — it just averages, never moves it</td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\(0.2592\)</span></td>
<td><span class="math inline">\(0.3364\)</span></td>
<td>Blending keeps pixel 3 bright — source was bright, target was bright, so average stays bright; Wasserstein has already dispatched some mass</td>
</tr>
</tbody>
</table>
<p>Blending never moves mass — pixel 3 stays bright because both <span class="math inline">\(m_3\)</span> and <span class="math inline">\(v_3\)</span> are large, so their average is large. Wasserstein reduces pixel 3’s mass because some of it is physically in transit to pixel 0.</p>
<hr>
</section>
<section id="step-22-naive-pixel-blending-all-timesteps" class="level3">
<h3 class="anchored" data-anchor-id="step-22-naive-pixel-blending-all-timesteps">Step 22: Naive Pixel Blending — All Timesteps</h3>
<p>Naive Pixel Blending computes a weighted average of <span class="math inline">\(\mathbf{m}\)</span> and <span class="math inline">\(\mathbf{v}\)</span> at each pixel independently — no coordinates, no transport, no geometry.</p>
<p><span class="math display">\[\mu_t^{\text{blend}}(k) = (1-t)\,m_k + t\,v_k \quad \forall k\]</span></p>
<p><strong>Full computation at all three key timesteps:</strong></p>
<p><strong><span class="math inline">\(t=0\)</span>:</strong> <span class="math display">\[\mu_0^{\text{blend}} = 1.0\cdot(0,\ 0.2835,\ 0.3150,\ 0.4016) + 0\cdot(0.2373,\ 0.2881,\ 0.2034,\ 0.2712) = (0,\ 0.2835,\ 0.3150,\ 0.4016) = \mathbf{m}\ \checkmark\]</span></p>
<p><strong><span class="math inline">\(t=0.5\)</span>:</strong></p>
<p><span class="math display">\[\mu_{0.5}^{\text{blend}}(0) = 0.5\times0 + 0.5\times0.2373 = 0.1187\]</span> <span class="math display">\[\mu_{0.5}^{\text{blend}}(1) = 0.5\times0.2835 + 0.5\times0.2881 = 0.2858\]</span> <span class="math display">\[\mu_{0.5}^{\text{blend}}(2) = 0.5\times0.3150 + 0.5\times0.2034 = 0.2592\]</span> <span class="math display">\[\mu_{0.5}^{\text{blend}}(3) = 0.5\times0.4016 + 0.5\times0.2712 = 0.3364\]</span></p>
<p><span class="math display">\[\mu_{0.5}^{\text{blend}} = (0.1187,\ 0.2858,\ 0.2592,\ 0.3364)\]</span></p>
<p><strong><span class="math inline">\(t=1\)</span>:</strong> <span class="math display">\[\mu_1^{\text{blend}} = 0\cdot\mathbf{m} + 1.0\cdot\mathbf{v} = (0.2373,\ 0.2881,\ 0.2034,\ 0.2712) = \mathbf{v}\ \checkmark\]</span></p>
<p><br></p>
<p><strong>Mass conservation at <span class="math inline">\(t=0.5\)</span>:</strong></p>
<p><span class="math display">\[\sum_k \mu_{0.5}^{\text{blend}}(k) = 0.1187 + 0.2858 + 0.2592 + 0.3364 = 1.0001 \approx 1\ \checkmark\]</span></p>
<p>Exact by linearity: <span class="math inline">\((1-t)\sum_k m_k + t\sum_k v_k = (1-t)\cdot1 + t\cdot1 = 1\)</span>.</p>
<p><br></p>
<section id="final-comparison-wasserstein-vs-blending-at-t0.5" class="level4">
<h4 class="anchored" data-anchor-id="final-comparison-wasserstein-vs-blending-at-t0.5">Final Comparison: Wasserstein vs Blending at <span class="math inline">\(t=0.5\)</span></h4>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Pixel <span class="math inline">\(k\)</span></th>
<th>Location</th>
<th><span class="math inline">\(m_k\)</span></th>
<th><span class="math inline">\(v_k\)</span></th>
<th><span class="math inline">\(\mu_{0.5}^{\text{Wass}}\)</span></th>
<th><span class="math inline">\(\mu_{0.5}^{\text{blend}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\((0,0)\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0.2373\)</span></td>
<td><span class="math inline">\(0.2111\)</span></td>
<td><span class="math inline">\(0.1187\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\((0,1)\)</span></td>
<td><span class="math inline">\(0.2835\)</span></td>
<td><span class="math inline">\(0.2881\)</span></td>
<td><span class="math inline">\(0.2780\)</span></td>
<td><span class="math inline">\(0.2858\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\((1,0)\)</span></td>
<td><span class="math inline">\(0.3150\)</span></td>
<td><span class="math inline">\(0.2034\)</span></td>
<td><span class="math inline">\(0.1920\)</span></td>
<td><span class="math inline">\(0.2592\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\((1,1)\)</span></td>
<td><span class="math inline">\(0.4016\)</span></td>
<td><span class="math inline">\(0.2712\)</span></td>
<td><span class="math inline">\(0.2592\)</span></td>
<td><span class="math inline">\(0.3364\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Reading pixel 0:</strong> source has zero mass, target has <span class="math inline">\(0.2373\)</span>.</p>
<ul>
<li>Blending: <span class="math inline">\(0.1187\)</span> — pure arithmetic average, mass appears from nowhere at pixel 0.</li>
<li>Wasserstein: <span class="math inline">\(0.2111\)</span> — mass physically arrived here, transported from pixels 1 and 2 in transit.</li>
</ul>
<p><strong>Reading pixel 3:</strong> source has <span class="math inline">\(0.4016\)</span>, target has <span class="math inline">\(0.2712\)</span>.</p>
<ul>
<li>Blending: <span class="math inline">\(0.3364\)</span> — stays bright, just averaged down slightly.</li>
<li>Wasserstein: <span class="math inline">\(0.2592\)</span> — mass has already departed toward its target destinations; pixel 3 is visibly dimmer because the transport is happening.</li>
</ul>
<p><strong>Reading pixel 2:</strong> source has <span class="math inline">\(0.3150\)</span>, target has <span class="math inline">\(0.2034\)</span>.</p>
<ul>
<li>Blending: <span class="math inline">\(0.2592\)</span> — averaged, still substantial.</li>
<li>Wasserstein: <span class="math inline">\(0.1920\)</span> — mass is leaving this location, already in transit toward pixel 0.</li>
</ul>
<p><br></p>
<p><strong>THE FUNDAMENTAL DIFFERENCE IN ONE TABLE:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>Wasserstein <span class="math inline">\(\mu_t\)</span></th>
<th>Blending <span class="math inline">\(\mu_t^{\text{blend}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>How mass at pixel 0 appears</td>
<td>Physically transported from pixels 1, 2</td>
<td>Arithmetically interpolated from <span class="math inline">\(v_0\)</span></td>
</tr>
<tr class="even">
<td>Pixel coordinates used?</td>
<td>Yes — <span class="math inline">\(\mathbf{z}_{ij}(t) = (1-t)\mathbf{x}_i + t\mathbf{x}_j\)</span></td>
<td>No — pure weighted average of intensities</td>
</tr>
<tr class="odd">
<td>Mass at <span class="math inline">\(t=0.5\)</span> reflects</td>
<td>Where mass physically is mid-journey</td>
<td>Average of source and target intensities</td>
</tr>
<tr class="even">
<td>Intermediate frames look like</td>
<td>Ink strokes shifting and morphing in space</td>
<td>Two images fading through each other</td>
</tr>
<tr class="odd">
<td>Straight line in</td>
<td><span class="math inline">\(\mathbb{R}^2\)</span> — image plane</td>
<td><span class="math inline">\(\Delta^3\)</span> — intensity simplex</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Complete anchor pipeline state at <span class="math inline">\(t=0.5\)</span>:</strong></p>
<p><span class="math display">\[\mu_{0.5}^{\text{Wass}} = (0.2111,\ 0.2780,\ 0.1920,\ 0.2592) \rightarrow \text{mass mid-journey through space}\]</span> <span class="math display">\[\mu_{0.5}^{\text{blend}} = (0.1187,\ 0.2858,\ 0.2592,\ 0.3364) \rightarrow \text{mass averaged in intensity}\]</span></p>
<p><strong>Both sum to 1. Both equal <span class="math inline">\(\mathbf{m}\)</span> at <span class="math inline">\(t=0\)</span> and <span class="math inline">\(\mathbf{v}\)</span> at <span class="math inline">\(t=1\)</span>. But only the Wasserstein frame respects the 2D geometry of the image — mass traveled to get there.</strong></p>
<hr>
</section>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Cell</th>
<th>Operation</th>
<th>Mathematical Object</th>
<th>What It Produces</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>4</td>
<td>Extract labels, find first “3” and “8”</td>
<td><span class="math inline">\(i_3 = \min\mathcal{I}_3,\ i_8 = \min\mathcal{I}_8\)</span></td>
<td>Indices <span class="math inline">\(i_3=0,\ i_8=2\)</span> into toy dataset</td>
</tr>
<tr class="even">
<td>2</td>
<td>4</td>
<td>Cast images to float64</td>
<td><span class="math inline">\(A^{(3)}, A^{(8)} \in \mathbb{R}^{2\times2}\)</span></td>
<td><span class="math inline">\(A^{(3)}=\begin{pmatrix}0&amp;180\\200&amp;255\end{pmatrix}\)</span>, enables real arithmetic</td>
</tr>
<tr class="odd">
<td>3</td>
<td>6</td>
<td>Flatten images</td>
<td><span class="math inline">\(A \in \mathbb{R}^{2\times2} \to \mathbf{a} \in \mathbb{R}^4\)</span></td>
<td><span class="math inline">\(\mathbf{a}^{(3)}=(0,180,200,255)\)</span>, <span class="math inline">\(\mathbf{a}^{(8)}=(210,255,180,240)\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td>6</td>
<td>Normalize to probability measures</td>
<td><span class="math inline">\(\mathbf{m}=\mathbf{a}^{(3)}/Z^{(3)},\ \mathbf{v}=\mathbf{a}^{(8)}/Z^{(8)}\)</span></td>
<td><span class="math inline">\(\mathbf{m},\mathbf{v}\in\Delta^3\)</span>, both sum to 1</td>
</tr>
<tr class="odd">
<td>5</td>
<td>8</td>
<td>Assign pixel coordinates</td>
<td><span class="math inline">\(\mathbf{x}_i=(\lfloor i/2\rfloor,\ i\bmod 2)\)</span></td>
<td><span class="math inline">\(X\in\mathbb{R}^{4\times2}\)</span>, embeds pixels into <span class="math inline">\(\mathbb{R}^2\)</span></td>
</tr>
<tr class="even">
<td>6</td>
<td>9</td>
<td>Build cost matrix</td>
<td><span class="math inline">\(C_{ij}=\|\mathbf{x}_i-\mathbf{x}_j\|^2\)</span></td>
<td><span class="math inline">\(C\in\mathbb{R}^{4\times4}\)</span>, encodes travel cost between every pixel pair</td>
</tr>
<tr class="odd">
<td>7</td>
<td>12</td>
<td>Normalize cost matrix</td>
<td><span class="math inline">\(\tilde{C}=C/\max C\)</span></td>
<td><span class="math inline">\(\tilde{C}\in[0,1]^{4\times4}\)</span>, prevents exponential overflow in Sinkhorn</td>
</tr>
<tr class="even">
<td>8</td>
<td>11</td>
<td>Compute log-measures</td>
<td><span class="math inline">\(\log\_mu_i = \log(m_i+10^{-300})\)</span></td>
<td><span class="math inline">\((-690.78,\ -1.261,\ -1.155,\ -0.912)\)</span>, guards against <span class="math inline">\(\log(0)\)</span></td>
</tr>
<tr class="odd">
<td>9</td>
<td>11</td>
<td>Initialize dual potentials</td>
<td><span class="math inline">\(\mathbf{f}^{(0)}=\mathbf{g}^{(0)}=\mathbf{0}\)</span></td>
<td>Starting point; plan is cost-only, no marginal constraints yet</td>
</tr>
<tr class="even">
<td>10</td>
<td>11</td>
<td>Sinkhorn f-update, iter 1</td>
<td><span class="math inline">\(f_i \leftarrow \varepsilon\log m_i - \varepsilon\operatorname{LSE}_j\!\left(\frac{g_j-\tilde{C}_{ij}}{\varepsilon}\right)\)</span></td>
<td><span class="math inline">\(\mathbf{f}^{(1)}=(-6.908,\ -0.01261,\ -0.01155,\ -0.00912)\)</span></td>
</tr>
<tr class="odd">
<td>11</td>
<td>11</td>
<td>Sinkhorn g-update, iter 1</td>
<td><span class="math inline">\(g_j \leftarrow \varepsilon\log\nu_j - \varepsilon\operatorname{LSE}_i\!\left(\frac{f_i-\tilde{C}_{ij}}{\varepsilon}\right)\)</span></td>
<td><span class="math inline">\(\mathbf{g}^{(1)}=(0.497,\ 0.00017,\ -0.00439,\ -0.00393)\)</span></td>
</tr>
<tr class="even">
<td>12</td>
<td>11–12</td>
<td>Recover transport plan</td>
<td><span class="math inline">\(\pi_{ij}=\exp\!\left(\frac{f^*_i+g^*_j-\tilde{C}_{ij}}{\varepsilon}\right)\)</span></td>
<td><span class="math inline">\(\pi\in\Pi(\mathbf{m},\mathbf{v})\)</span>, marginals verified; mass flow between every pixel pair</td>
</tr>
<tr class="odd">
<td>13</td>
<td>13</td>
<td>Compute primal cost</td>
<td><span class="math inline">\(\langle\tilde{C},\pi\rangle=\sum_{ij}\tilde{C}_{ij}\pi_{ij}\)</span></td>
<td><span class="math inline">\(0.1056\)</span>; total transport bill — only off-diagonal flows contribute</td>
</tr>
<tr class="even">
<td>14</td>
<td>15</td>
<td>Effect of <span class="math inline">\(\varepsilon\)</span> on cost</td>
<td><span class="math inline">\(\mathcal{L}_\varepsilon(\pi)=\langle\tilde{C},\pi\rangle-\varepsilon H(\pi)\)</span></td>
<td>Max-entropy cost <span class="math inline">\(0.4949\)</span> vs optimized <span class="math inline">\(0.1056\)</span>; geometry saves 79%</td>
</tr>
<tr class="odd">
<td>15</td>
<td>16</td>
<td>Extract dual potentials</td>
<td><span class="math inline">\(\phi=\mathbf{f}^*,\ \psi=\mathbf{g}^*\)</span></td>
<td>Price system: <span class="math inline">\(\phi_0=-6.91\)</span> prices out background; ink pixels near zero</td>
</tr>
<tr class="even">
<td>16</td>
<td>17</td>
<td>Compute entropy <span class="math inline">\(H(\pi)\)</span></td>
<td><span class="math inline">\(H(\pi)=-\sum_{ij}\pi_{ij}\log\pi_{ij}\)</span></td>
<td><span class="math inline">\(1.497\)</span> on anchor; measures how spread the transport plan is</td>
</tr>
<tr class="odd">
<td>17</td>
<td>17</td>
<td>Compute regularized objective</td>
<td><span class="math inline">\(\mathcal{L}_\varepsilon(\pi)=\langle\tilde{C},\pi\rangle-\varepsilon H(\pi)\)</span></td>
<td><span class="math inline">\(0.09063\)</span>; single number Sinkhorn minimized — certifies optimality</td>
</tr>
<tr class="even">
<td>18</td>
<td>18</td>
<td>Compute dual objective</td>
<td><span class="math inline">\(\mathcal{D}(\phi,\psi)=\langle\phi,\mathbf{m}\rangle+\langle\psi,\mathbf{v}\rangle\)</span></td>
<td><span class="math inline">\(0.1031\)</span>; gap <span class="math inline">\(0.0124\)</span> from assumed potentials; zero at true convergence</td>
</tr>
<tr class="odd">
<td>19</td>
<td>19</td>
<td>Verify complementary slackness</td>
<td><span class="math inline">\(s_{ij}=\tilde{C}_{ij}-(\phi_i+\psi_j)\geq0\)</span>;&nbsp;<span class="math inline">\(s_{ij}\pi_{ij}\approx0\)</span></td>
<td>KKT conditions satisfied; <span class="math inline">\(\pi\)</span> certified globally optimal from all angles</td>
</tr>
<tr class="even">
<td>20</td>
<td>20–21</td>
<td>Displacement interpolation</td>
<td><span class="math inline">\(\mu_t(k)=\sum_{T_t(\mathbf{x}_i,\mathbf{x}_j)=\mathbf{x}_k}\pi_{ij}\)</span></td>
<td>10 geodesic frames; <span class="math inline">\(\mu_0=\mathbf{m}\)</span>, <span class="math inline">\(\mu_1=\mathbf{v}\)</span>, mass physically moves through <span class="math inline">\(\mathbb{R}^2\)</span></td>
</tr>
<tr class="odd">
<td>21</td>
<td>23</td>
<td>Pixel blending baseline</td>
<td><span class="math inline">\(\mu_t^{\text{blend}}(k)=(1-t)m_k+tv_k\)</span></td>
<td>Straight line on simplex <span class="math inline">\(\Delta^3\)</span>; no geometry — intensities averaged, mass teleports</td>
</tr>
<tr class="even">
<td>22</td>
<td>23</td>
<td>Final comparison</td>
<td><span class="math inline">\(\mu_{0.5}^{\text{Wass}}\)</span> vs <span class="math inline">\(\mu_{0.5}^{\text{blend}}\)</span></td>
<td>Wasserstein: mass mid-journey through space. Blending: arithmetic average of intensities. Both valid measures; only Wasserstein respects image geometry</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Shreesh Bhattarai · GDL &amp; COT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/shreeshb51">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/shreesh-bhattarai-1ba1681bb/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>