<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>solving_anchor_example – Shreesh Bhattarai</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-74ba59708be70b1949d5896c354d4bb9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shreesh Bhattarai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../catw/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Along the Way</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../papers/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper Comprehensions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notes</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#anchor-example-complete-step-by-step-solution" id="toc-anchor-example-complete-step-by-step-solution" class="nav-link active" data-scroll-target="#anchor-example-complete-step-by-step-solution">Anchor Example — Complete Step-by-Step Solution</a>
  <ul class="collapse">
  <li><a href="#step-1-constructing-x-and-a-from-coo-format" id="toc-step-1-constructing-x-and-a-from-coo-format" class="nav-link" data-scroll-target="#step-1-constructing-x-and-a-from-coo-format">Step 1: Constructing X and A from COO Format</a></li>
  <li><a href="#step-2-degree-matrix-d-and-graph-laplacian-l" id="toc-step-2-degree-matrix-d-and-graph-laplacian-l" class="nav-link" data-scroll-target="#step-2-degree-matrix-d-and-graph-laplacian-l">Step 2: Degree Matrix D and Graph Laplacian L</a></li>
  <li><a href="#step-3-signed-incidence-matrix-b-and-the-factorization-l-bbt" id="toc-step-3-signed-incidence-matrix-b-and-the-factorization-l-bbt" class="nav-link" data-scroll-target="#step-3-signed-incidence-matrix-b-and-the-factorization-l-bbt">Step 3: Signed Incidence Matrix B and the Factorization <span class="math inline">\(L = BB^T\)</span></a></li>
  <li><a href="#step-4-eigenspectrum-of-l" id="toc-step-4-eigenspectrum-of-l" class="nav-link" data-scroll-target="#step-4-eigenspectrum-of-l">Step 4: Eigenspectrum of L</a></li>
  <li><a href="#step-5-laplacian-eigenmap-embedding" id="toc-step-5-laplacian-eigenmap-embedding" class="nav-link" data-scroll-target="#step-5-laplacian-eigenmap-embedding">Step 5: Laplacian Eigenmap Embedding</a></li>
  <li><a href="#step-6-bfs-graph-distance-vs-embedding-distance-pearson-correlation" id="toc-step-6-bfs-graph-distance-vs-embedding-distance-pearson-correlation" class="nav-link" data-scroll-target="#step-6-bfs-graph-distance-vs-embedding-distance-pearson-correlation">Step 6: BFS Graph Distance vs Embedding Distance (Pearson Correlation)</a></li>
  <li><a href="#step-7-mpnn-message-passing-layer" id="toc-step-7-mpnn-message-passing-layer" class="nav-link" data-scroll-target="#step-7-mpnn-message-passing-layer">Step 7: MPNN Message Passing Layer</a></li>
  <li><a href="#step-8-full-mpnn-input-projection-stacked-layers-readout" id="toc-step-8-full-mpnn-input-projection-stacked-layers-readout" class="nav-link" data-scroll-target="#step-8-full-mpnn-input-projection-stacked-layers-readout">Step 8: Full MPNN: Input Projection, Stacked Layers, Readout</a></li>
  <li><a href="#step-9-permutation-invariance-verification" id="toc-step-9-permutation-invariance-verification" class="nav-link" data-scroll-target="#step-9-permutation-invariance-verification">Step 9: Permutation Invariance Verification</a></li>
  <li><a href="#step-10-permutation-invariance-numerical-test" id="toc-step-10-permutation-invariance-numerical-test" class="nav-link" data-scroll-target="#step-10-permutation-invariance-numerical-test">Step 10: Permutation Invariance Numerical Test</a></li>
  <li><a href="#step-11-chebnet-spectral-convolution" id="toc-step-11-chebnet-spectral-convolution" class="nav-link" data-scroll-target="#step-11-chebnet-spectral-convolution">Step 11: ChebNet Spectral Convolution</a></li>
  <li><a href="#step-12-full-chebnet-model" id="toc-step-12-full-chebnet-model" class="nav-link" data-scroll-target="#step-12-full-chebnet-model">Step 12: Full ChebNet Model</a></li>
  <li><a href="#step-13-chebnet-permutation-invariance-why-lambda_max-must-be-precomputed" id="toc-step-13-chebnet-permutation-invariance-why-lambda_max-must-be-precomputed" class="nav-link" data-scroll-target="#step-13-chebnet-permutation-invariance-why-lambda_max-must-be-precomputed">Step 13: ChebNet Permutation Invariance + Why <span class="math inline">\(\lambda_{\max}\)</span> must be precomputed</a></li>
  <li><a href="#step-14-chebyshev-filter-locality-delta-signal-propagation" id="toc-step-14-chebyshev-filter-locality-delta-signal-propagation" class="nav-link" data-scroll-target="#step-14-chebyshev-filter-locality-delta-signal-propagation">Step 14: Chebyshev Filter Locality: Delta Signal Propagation</a></li>
  <li><a href="#step-15-wl-color-refinement-on-c_4" id="toc-step-15-wl-color-refinement-on-c_4" class="nav-link" data-scroll-target="#step-15-wl-color-refinement-on-c_4">Step 15: WL Color Refinement on <span class="math inline">\(C_4\)</span></a></li>
  <li><a href="#step-16-wl-indistinguishable-graphs-k_33-vs-prism" id="toc-step-16-wl-indistinguishable-graphs-k_33-vs-prism" class="nav-link" data-scroll-target="#step-16-wl-indistinguishable-graphs-k_33-vs-prism">Step 16: WL-Indistinguishable Graphs: <span class="math inline">\(K_{3,3}\)</span> vs Prism</a></li>
  <li><a href="#step-17-atomic-reference-energies-and-baseline-subtraction" id="toc-step-17-atomic-reference-energies-and-baseline-subtraction" class="nav-link" data-scroll-target="#step-17-atomic-reference-energies-and-baseline-subtraction">Step 17: Atomic Reference Energies and Baseline Subtraction</a></li>
  <li><a href="#step-18-target-normalization" id="toc-step-18-target-normalization" class="nav-link" data-scroll-target="#step-18-target-normalization">Step 18: Target Normalization</a></li>
  <li><a href="#step-19-training-loop-residual-targets-normalization-mae-loss" id="toc-step-19-training-loop-residual-targets-normalization-mae-loss" class="nav-link" data-scroll-target="#step-19-training-loop-residual-targets-normalization-mae-loss">Step 19: Training Loop: Residual Targets, Normalization, MAE Loss</a></li>
  <li><a href="#step-20-training-loop-adam-reducelronplateau" id="toc-step-20-training-loop-adam-reducelronplateau" class="nav-link" data-scroll-target="#step-20-training-loop-adam-reducelronplateau">Step 20: Training Loop: Adam + ReduceLROnPlateau</a></li>
  <li><a href="#code-output" id="toc-code-output" class="nav-link" data-scroll-target="#code-output">Code Output</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="anchor-example-complete-step-by-step-solution" class="level1">
<h1>Anchor Example — Complete Step-by-Step Solution</h1>
<hr>
<section id="step-1-constructing-x-and-a-from-coo-format" class="level2">
<h2 class="anchored" data-anchor-id="step-1-constructing-x-and-a-from-coo-format">Step 1: Constructing X and A from COO Format</h2>
<p>We first materialize two foundational objects from PyG’s sparse storage: the dense node feature matrix <strong>X</strong> and the dense adjacency matrix <strong>A</strong>. Every subsequent spectral and message-passing operation in this project operates on these two objects.</p>
<p><strong>Graph:</strong> <span class="math inline">\(C_4\)</span> — cycle on 4 nodes <span class="math inline">\(\{0,1,2,3\}\)</span>, edges <span class="math inline">\(\{(0,1),(1,2),(2,3),(3,0)\}\)</span></p>
<p><strong>Node features:</strong> <span class="math inline">\(\mathbf{x} = [2, 1, 1, 1]^\top\)</span> (scalar for clarity; QM9 uses 11-dim vectors)</p>
<p>The number of nodes: <span class="math inline">\(N = 4\)</span>.</p>
<p><span class="math inline">\(\mathbf{X} \in \mathbb{R}^{N \times F}\)</span> is the node feature matrix, where row <span class="math inline">\(i\)</span> is the feature vector of node <span class="math inline">\(i\)</span>.</p>
<p>Scalar features, <span class="math inline">\(F=1\)</span>:</p>
<p><span class="math display">\[\mathbf{X} = \begin{bmatrix} 2 \\\\ 1 \\\\ 1 \\\\ 1 \end{bmatrix} \in \mathbb{R}^{4 \times 1}\]</span></p>
<p>PyG stores edges in <strong>COO (coordinate) format</strong>: a <span class="math inline">\(2 \times 2E\)</span> integer tensor where column <span class="math inline">\(k\)</span> encodes directed edge <span class="math inline">\((u_k \to v_k)\)</span>.</p>
<p><br></p>
<p><strong>1. What is COO format?</strong></p>
<p><strong>COO = Coordinate format.</strong> It’s simply a list of (row, column) pairs that tells you <em>where</em> the non-zero entries of a matrix live.</p>
<p>For an adjacency matrix, a non-zero entry at position <span class="math inline">\((i, j)\)</span> means “there is an edge from node <span class="math inline">\(i\)</span> to node <span class="math inline">\(j\)</span>.” So instead of storing the full <span class="math inline">\(N \times N\)</span> matrix (mostly zeros), you just store the list of edges as two parallel arrays:</p>
<ul>
<li><strong>Array 1:</strong> all the source nodes (row indices)</li>
<li><strong>Array 2:</strong> all the destination nodes (column indices)</li>
</ul>
<p>No values array needed here because every edge has value 1.</p>
<p><span class="math inline">\(C_4\)</span> has <span class="math inline">\(E=4\)</span> undirected edges, so <span class="math inline">\(2E=8\)</span> directed edges. The COO tensor is:</p>
<p><span class="math display">\[\text{edge\_index} = \begin{bmatrix} 0&amp;1&amp;1&amp;2&amp;2&amp;3&amp;3&amp;0 \\\\ 1&amp;0&amp;2&amp;1&amp;3&amp;2&amp;0&amp;3 \end{bmatrix}\]</span></p>
<p>Simply: Row 0 = sources, Row 1 = destinations.</p>
<pre><code>In 'edge_index' tensor: node 0 is connected to node 1 (first column); node 1 is connected to node 0 (second column)... and so on.</code></pre>
<p><span class="math inline">\(C_4\)</span> has 4 undirected edges. PyG stores <strong>both directions</strong>, giving 8 directed edges:</p>
<p><span class="math display">\[\{0{\to}1,\ 1{\to}0,\ 1{\to}2,\ 2{\to}1,\ 2{\to}3,\ 3{\to}2,\ 3{\to}0,\ 0{\to}3\}\]</span></p>
<p>Laid out as a <span class="math inline">\(2 \times 8\)</span> tensor, column by column:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Column <span class="math inline">\(k\)</span></th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Row 0 (source <span class="math inline">\(u\)</span>)</strong></td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>3</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>Row 1 (dest <span class="math inline">\(v\)</span>)</strong></td>
<td>1</td>
<td>0</td>
<td>2</td>
<td>1</td>
<td>3</td>
<td>2</td>
<td>0</td>
<td>3</td>
</tr>
</tbody>
</table>
<p>Each column <span class="math inline">\(k\)</span> encodes one directed edge: “node <code>edge_index[0,k]</code> sends to node <code>edge_index[1,k]</code>.”</p>
<ul>
<li>Column 0: <span class="math inline">\(0 \to 1\)</span></li>
<li>Column 1: <span class="math inline">\(1 \to 0\)</span> ← the reverse</li>
<li>Column 6: <span class="math inline">\(3 \to 0\)</span></li>
<li>Column 7: <span class="math inline">\(0 \to 3\)</span> ← the reverse</li>
</ul>
<p><br></p>
<p><strong>2. Why two rows and not two columns?</strong></p>
<p>PyTorch’s advanced indexing <code>A[edge_index[0], edge_index[1]] = 1</code> needs sources and destinations as two separate 1-D index arrays — that’s exactly what the two rows provide.</p>
<p><br></p>
<p>Moving on to <strong>index scatter</strong>, for every column <span class="math inline">\(k\)</span> in <code>edge_index</code>, set <span class="math inline">\(A[u_k, v_k] = 1\)</span>.</p>
<p><span class="math display">\[A_{ij} = \begin{cases} 1 &amp; \text{if } (i,j) \in \mathcal{E} \\\\ 0 &amp; \text{otherwise} \end{cases}\]</span></p>
<p><span class="math inline">\(\mathcal{E}\)</span> is the set of all edges in the graph — on the anchor, <span class="math inline">\(\mathcal{E}\)</span> = {(0,1),(1,0),(1,2),(2,1),(2,3),(3,2),(3,0),(0,3)}</p>
<p>Computing entry-by-entry on the anchor from the 8 directed edges above:</p>
<p><span class="math display">\[\mathbf{A} = \begin{bmatrix} 0&amp;1&amp;0&amp;1 \\\\ 1&amp;0&amp;1&amp;0 \\\\ 0&amp;1&amp;0&amp;1 \\\\ 1&amp;0&amp;1&amp;0 \end{bmatrix}\]</span></p>
<p><strong>Symmetry check:</strong> <span class="math inline">\(A_{ij} = A_{ji}\)</span> for all <span class="math inline">\(i,j\)</span> ✓ — because PyG stores both <span class="math inline">\((u,v)\)</span> and <span class="math inline">\((v,u)\)</span>.</p>
<p><strong>No self-loops:</strong> <span class="math inline">\(A_{ii} = 0\)</span> for all <span class="math inline">\(i\)</span> ✓ — diagonal is all zero.</p>
<p><br></p>
<p><strong>3. Why COO → dense matrix matters?</strong></p>
<p>Spectral methods (Laplacian, eigendecomposition) require dense matrices. Message passing can work directly on COO, but making <span class="math inline">\(\mathbf{A}\)</span> explicit here lets us verify structure before building <span class="math inline">\(\mathbf{L}\)</span> in later steps.</p>
<p><strong>Two objects are now established:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Object</th>
<th>Shape</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathbf{X}\)</span></td>
<td><span class="math inline">\(N \times F\)</span></td>
<td>Per-node input features</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathbf{A}\)</span></td>
<td><span class="math inline">\(N \times N\)</span></td>
<td>Graph connectivity</td>
</tr>
</tbody>
</table>
<p>All downstream operations — degree matrix <span class="math inline">\(\mathbf{D}\)</span>, Laplacian <span class="math inline">\(\mathbf{L}\)</span>, message passing — derive from exactly these two.</p>
<hr>
</section>
<section id="step-2-degree-matrix-d-and-graph-laplacian-l" class="level2">
<h2 class="anchored" data-anchor-id="step-2-degree-matrix-d-and-graph-laplacian-l">Step 2: Degree Matrix D and Graph Laplacian L</h2>
<p>We sum each row of <strong>A</strong>. Since <span class="math inline">\(A_{ij} \in \{0,1\}\)</span>, the row sum of row <span class="math inline">\(i\)</span> counts how many neighbors node <span class="math inline">\(i\)</span> has — its <strong>degree</strong> <span class="math inline">\(d_i\)</span>.</p>
<p><span class="math display">\[d_i = \sum_{j=0}^{N-1} A_{ij}\]</span></p>
<ul>
<li><span class="math inline">\(d_0 = A_{00}+A_{01}+A_{02}+A_{03} = 0+1+0+1 = 2\)</span></li>
<li><span class="math inline">\(d_1 = 0+0+1+0+1 = 2\)</span></li>
</ul>
<p>From <span class="math inline">\(\mathbf{A}\)</span> directly:</p>
<p><span class="math display">\[\mathbf{A} = \begin{bmatrix} 0&amp;1&amp;0&amp;1 \\\\ 1&amp;0&amp;1&amp;0 \\\\ 0&amp;1&amp;0&amp;1 \\\\ 1&amp;0&amp;1&amp;0 \end{bmatrix}\]</span></p>
<ul>
<li><span class="math inline">\(d_0 = 0+1+0+1 = 2\)</span></li>
<li><span class="math inline">\(d_1 = 1+0+1+0 = 2\)</span></li>
<li><span class="math inline">\(d_2 = 0+1+0+1 = 2\)</span></li>
<li><span class="math inline">\(d_3 = 1+0+1+0 = 2\)</span></li>
</ul>
<p>Expected — every node in <span class="math inline">\(C_4\)</span> has exactly 2 neighbors.</p>
<p><span class="math display">\[\mathbf{degrees} = [2, 2, 2, 2]\]</span></p>
<p><br></p>
<p>Placing the degree vector on the diagonal of an <span class="math inline">\(N\times N\)</span> matrix, zeros elsewhere.</p>
<p><span class="math display">\[\mathbf{D} = \begin{bmatrix} d_0&amp;0&amp;0&amp;0 \\\\ 0&amp;d_1&amp;0&amp;0 \\\\ 0&amp;0&amp;d_2&amp;0 \\\\ 0&amp;0&amp;0&amp;d_3 \end{bmatrix} = \begin{bmatrix} 2&amp;0&amp;0&amp;0 \\\\ 0&amp;2&amp;0&amp;0 \\\\ 0&amp;0&amp;2&amp;0 \\\\ 0&amp;0&amp;0&amp;2 \end{bmatrix}\]</span></p>
<p><br></p>
<p>The <strong>combinatorial graph Laplacian</strong>:</p>
<p><span class="math display">\[\mathbf{L} = \mathbf{D} - \mathbf{A}\]</span></p>
<p>Entry-by-entry:</p>
<p><span class="math display">\[L_{ij} = \begin{cases} d_i &amp; i = j \\\\ -1 &amp; (i,j) \in \mathcal{E} \\\\ 0 &amp; \text{otherwise} \end{cases}\]</span></p>
<p>On the anchor:</p>
<p><span class="math display">\[\mathbf{L} = \begin{bmatrix} 2&amp;0&amp;0&amp;0 \\\\ 0&amp;2&amp;0&amp;0 \\\\ 0&amp;0&amp;2&amp;0 \\\\ 0&amp;0&amp;0&amp;2 \end{bmatrix} - \begin{bmatrix} 0&amp;1&amp;0&amp;1 \\\\ 1&amp;0&amp;1&amp;0 \\\\ 0&amp;1&amp;0&amp;1 \\\\ 1&amp;0&amp;1&amp;0 \end{bmatrix} = \begin{bmatrix} 2&amp;-1&amp;0&amp;-1 \\\\ -1&amp;2&amp;-1&amp;0 \\\\ 0&amp;-1&amp;2&amp;-1 \\\\ -1&amp;0&amp;-1&amp;2 \end{bmatrix}\]</span></p>
<p><br></p>
<p><strong>Verification — <code>L @ ones = 0</code>:</strong> The sum of any row in a valid Laplacian must be zero because the degree on the diagonal cancels out the −1 entries in that row.</p>
<p>The all-ones vector <span class="math inline">\(\mathbf{1} = [1,1,1,1]^\top\)</span> must be in the null space of <span class="math inline">\(\mathbf{L}\)</span>.</p>
<p><span class="math display">\[\mathbf{L}\mathbf{1} = \begin{bmatrix} 2(1)+(-1)(1)+0(1)+(-1)(1) \\\\ (-1)(1)+2(1)+(-1)(1)+0(1) \\\\ 0(1)+(-1)(1)+2(1)+(-1)(1) \\\\ (-1)(1)+0(1)+(-1)(1)+2(1) \end{bmatrix} = \begin{bmatrix} 2-1-1 \\\\ -1+2-1 \\\\ -1+2-1 \\\\ -1-1+2 \end{bmatrix} = \begin{bmatrix} 0 \\\\ 0 \\\\ 0 \\\\ 0 \end{bmatrix} ✓\]</span></p>
<p><strong>4. Why is this always true?</strong></p>
<p>Each row <span class="math inline">\(i\)</span> of <span class="math inline">\(\mathbf{L}\)</span> has one <span class="math inline">\(+d_i\)</span> on the diagonal and exactly <span class="math inline">\(d_i\)</span> entries of <span class="math inline">\(-1\)</span> off-diagonal. They cancel exactly.</p>
<p><br></p>
<p><strong>5. Why <span class="math inline">\(\mathbf{L}\)</span> matters?</strong></p>
<p><span class="math inline">\(\mathbf{L}\)</span> encodes the graph’s <em>smoothness operator</em>. For any signal <span class="math inline">\(\mathbf{f} \in \mathbb{R}^N\)</span> on the nodes:</p>
<p><span class="math display">\[\mathbf{f}^\top \mathbf{L} \mathbf{f} = \sum_{(i,j)\in\mathcal{E}} (f_i - f_j)^2 \geq 0\]</span></p>
<p>This is the sum of squared differences across every edge — a measure of how much <span class="math inline">\(\mathbf{f}\)</span> varies over the graph. The eigenvalues of <span class="math inline">\(\mathbf{L}\)</span> quantify the <em>frequencies</em> of the graph, which ChebNet (later in this project) operates on directly.</p>
<p><br></p>
<p>A <strong>signal</strong> <span class="math inline">\(\mathbf{f}\)</span> is just a number assigned to each node.</p>
<p>On <span class="math inline">\(C_4\)</span>, suppose <span class="math inline">\(\mathbf{f} = [2, 1, 1, 1]^\top\)</span> — exactly the node features from <strong>X</strong> Node 0 has value 2, the rest have value 1.</p>
<p><span class="math display">\[\mathbf{f}^\top \mathbf{L} \mathbf{f} = \sum_{(i,j)\in\mathcal{E}}(f_i - f_j)^2\]</span></p>
<p>The 4 undirected edges of <span class="math inline">\(C_4\)</span> give:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Edge</th>
<th><span class="math inline">\(f_i - f_j\)</span></th>
<th><span class="math inline">\((f_i-f_j)^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\((0,1)\)</span></td>
<td><span class="math inline">\(2-1=1\)</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\((1,2)\)</span></td>
<td><span class="math inline">\(1-1=0\)</span></td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\((2,3)\)</span></td>
<td><span class="math inline">\(1-1=0\)</span></td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\((3,0)\)</span></td>
<td><span class="math inline">\(1-2=-1\)</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\mathbf{f}^\top \mathbf{L} \mathbf{f} = 1+0+0+1 = 2\]</span></p>
<p>The result is <strong>small</strong> because the signal is nearly flat — only node 0 differs. If instead <span class="math inline">\(\mathbf{f} = [2,1,2,1]^\top\)</span> (alternating), every edge would contribute 1, giving a score of 4 — a <em>rougher</em> signal on the same graph.</p>
<p>This is exactly the sense in which <span class="math inline">\(\mathbf{L}\)</span> measures smoothness: <strong>larger <span class="math inline">\(\mathbf{f}^\top \mathbf{L} \mathbf{f}\)</span> = more variation across edges.</strong></p>
<p><strong>Variation across an edge</strong> = how different the signal values are at its two endpoints.</p>
<p>On <span class="math inline">\(C_4\)</span> with <span class="math inline">\(\mathbf{f} = [2,1,1,1]^\top\)</span>:</p>
<ul>
<li>Edge <span class="math inline">\((0,1)\)</span> has variation <span class="math inline">\(|2-1|=1\)</span> — the signal <em>jumps</em>.</li>
<li>Edge <span class="math inline">\((1,2)\)</span> has variation <span class="math inline">\(|1-1|=0\)</span> — the signal is <em>flat</em>.</li>
</ul>
<p><strong>Smoothness</strong> means most edges look like <span class="math inline">\((1,2)\)</span>, not <span class="math inline">\((0,1)\)</span>. A smooth signal changes slowly as you walk along the graph.</p>
<hr>
</section>
<section id="step-3-signed-incidence-matrix-b-and-the-factorization-l-bbt" class="level2">
<h2 class="anchored" data-anchor-id="step-3-signed-incidence-matrix-b-and-the-factorization-l-bbt">Step 3: Signed Incidence Matrix B and the Factorization <span class="math inline">\(L = BB^T\)</span></h2>
<p>Now we construct <strong>B</strong>, the signed incidence matrix, and verify that <span class="math inline">\(\mathbf{L} = \mathbf{B}\mathbf{B}^\top\)</span> — proving the Laplacian is always positive semi-definite.</p>
<p><strong>Extracting undirected edges:</strong> <code>edge_index</code> stores both <span class="math inline">\((i,j)\)</span> and <span class="math inline">\((j,i)\)</span>. The mask <code>source &lt; distance</code> keeps only one copy per edge — the one where the source index is smaller.</p>
<p>The 8 directed edges filtered by <code>source &lt; distance</code>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Directed edge</th>
<th><span class="math inline">\(i &lt; j\)</span>?</th>
<th>Keep?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0\to1\)</span></td>
<td><span class="math inline">\(0&lt;1\)</span> ✓</td>
<td>yes</td>
</tr>
<tr class="even">
<td><span class="math inline">\(1\to0\)</span></td>
<td><span class="math inline">\(1&lt;0\)</span> ✗</td>
<td>no</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(1\to2\)</span></td>
<td><span class="math inline">\(1&lt;2\)</span> ✓</td>
<td>yes</td>
</tr>
<tr class="even">
<td><span class="math inline">\(2\to1\)</span></td>
<td><span class="math inline">\(2&lt;1\)</span> ✗</td>
<td>no</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(2\to3\)</span></td>
<td><span class="math inline">\(2&lt;3\)</span> ✓</td>
<td>yes</td>
</tr>
<tr class="even">
<td><span class="math inline">\(3\to2\)</span></td>
<td><span class="math inline">\(3&lt;2\)</span> ✗</td>
<td>no</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(3\to0\)</span></td>
<td><span class="math inline">\(3&lt;0\)</span> ✗</td>
<td>no</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0\to3\)</span></td>
<td><span class="math inline">\(0&lt;3\)</span> ✓</td>
<td>yes</td>
</tr>
</tbody>
</table>
<p>So <span class="math inline">\(E=4\)</span> undirected edges: <span class="math inline">\((0,1),\ (1,2),\ (2,3),\ (0,3)\)</span>.</p>
<p><br></p>
<p><span class="math inline">\(\mathbf{B} \in \mathbb{R}^{N \times E}\)</span>. Each column <span class="math inline">\(e\)</span> corresponds to one undirected edge <span class="math inline">\((i,j)\)</span>:</p>
<p><span class="math display">\[B_{ke} = \begin{cases} +1 &amp; k = i \text{ (source)} \\\\ -1 &amp; k = j \text{ (destination)} \\\\ 0 &amp; \text{otherwise} \end{cases}\]</span></p>
<p>On the anchor, labeling columns by edge index <span class="math inline">\(e \in \{0,1,2,3\}\)</span> for edges <span class="math inline">\((0,1),(1,2),(2,3),(0,3)\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(e=0\)</span>: <span class="math inline">\((0,1)\)</span></th>
<th><span class="math inline">\(e=1\)</span>: <span class="math inline">\((1,2)\)</span></th>
<th><span class="math inline">\(e=2\)</span>: <span class="math inline">\((2,3)\)</span></th>
<th><span class="math inline">\(e=3\)</span>: <span class="math inline">\((0,3)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>node 0</td>
<td><span class="math inline">\(+1\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(+1\)</span></td>
</tr>
<tr class="even">
<td>node 1</td>
<td><span class="math inline">\(-1\)</span></td>
<td><span class="math inline">\(+1\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="odd">
<td>node 2</td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(-1\)</span></td>
<td><span class="math inline">\(+1\)</span></td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td>node 3</td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(-1\)</span></td>
<td><span class="math inline">\(-1\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\mathbf{B} = \begin{bmatrix} +1 &amp; 0 &amp; 0 &amp; +1 \\\\ -1 &amp; +1 &amp; 0 &amp; 0 \\\\ 0 &amp; -1 &amp; +1 &amp; 0 \\\\ 0 &amp; 0 &amp; -1 &amp; -1 \end{bmatrix}\]</span></p>
<p><br></p>
<p>Computing <span class="math inline">\(\mathbf{B}\mathbf{B}^\top\)</span> [<code>L_from_B = B @ B.T</code>] entry <span class="math inline">\((i,j)\)</span>:</p>
<p><span class="math display">\[(\mathbf{B}\mathbf{B}^\top)_{ij} = \sum_{e=0}^{E-1} B_{ie} \cdot B_{je}\]</span></p>
<p><br></p>
<p><strong>Diagonal entry <span class="math inline">\((0,0)\)</span>:</strong> node 0 appears in edges <span class="math inline">\(e=0\)</span> and <span class="math inline">\(e=3\)</span>: <span class="math display">\[B_{00}^2 + B_{01}^2 + B_{02}^2 + B_{03}^2 = 1^2+0^2+0^2+1^2 = 2 = d_0 ✓\]</span></p>
<p><strong>Off-diagonal entry <span class="math inline">\((0,1)\)</span>:</strong> only edge <span class="math inline">\(e=0\)</span> involves both nodes 0 and 1: <span class="math display">\[B_{00}B_{10} + B_{01}B_{11} + B_{02}B_{12} + B_{03}B_{13} = (+1)(-1)+0+0+0 = -1 = -A_{01} ✓\]</span></p>
<p><strong>Off-diagonal entry <span class="math inline">\((0,2)\)</span>:</strong> no edge connects nodes 0 and 2 directly: <span class="math display">\[B_{00}B_{20}+B_{01}B_{21}+B_{02}B_{22}+B_{03}B_{23} = 0+0+0+0 = 0 = -A_{02} ✓\]</span></p>
<p>The <em>answer</em> in each case recovers exactly the corresponding entry of <span class="math inline">\(\mathbf{L} = \mathbf{D} - \mathbf{A}\)</span>, which is the whole point — we’re not computing <span class="math inline">\(\mathbf{B}\mathbf{B}^\top\)</span> to get a new matrix, we’re verifying that the structure of <span class="math inline">\(\mathbf{B}\)</span> algebraically forces the result to equal <span class="math inline">\(\mathbf{L}\)</span></p>
<p><br></p>
<p>Full result:</p>
<p><span class="math display">\[\mathbf{B}\mathbf{B}^\top = \begin{bmatrix} 2&amp;-1&amp;0&amp;-1 \\\\ -1&amp;2&amp;-1&amp;0 \\\\ 0&amp;-1&amp;2&amp;-1 \\\\ -1&amp;0&amp;-1&amp;2 \end{bmatrix} = \mathbf{L} ✓\]</span></p>
<p><strong>6. Why this factorization matters?</strong></p>
<p><span class="math inline">\(\mathbf{L} = \mathbf{B}\mathbf{B}^\top\)</span> immediately proves <span class="math inline">\(\mathbf{L}\)</span> is <strong>positive semi-definite</strong>: for any <span class="math inline">\(\mathbf{f}\)</span>,</p>
<p><span class="math display">\[\mathbf{f}^\top \mathbf{L} \mathbf{f} = \mathbf{f}^\top \mathbf{B}\mathbf{B}^\top \mathbf{f} = \|\mathbf{B}^\top \mathbf{f}\|^2 \geq 0\]</span></p>
<p>The vector <span class="math inline">\(\mathbf{B}^\top\mathbf{f}\)</span> has one entry per edge: <span class="math inline">\((\mathbf{B}^\top\mathbf{f})_e = f_i - f_j\)</span>. Squaring and summing recovers exactly the edge-variation interpretation from Step 2 — the two views are identical.</p>
<p><br></p>
<p><strong>Positive semi-definite matrix:</strong></p>
<p>A positive semi-definite matrix is a symmetric matrix whose quadratic form is always non-negative for any vector (<span class="math inline">\(x\)</span>), i.e., <span class="math inline">\(x^T A x \ge 0\)</span>; for example the following matrix <span class="math inline">\(A\)</span> is positive semi-definite.</p>
<p><span class="math display">\[A=\begin{pmatrix} 1 &amp; 0 \\\\ 0 &amp; 0 \end{pmatrix}\]</span></p>
<hr>
</section>
<section id="step-4-eigenspectrum-of-l" class="level2">
<h2 class="anchored" data-anchor-id="step-4-eigenspectrum-of-l">Step 4: Eigenspectrum of L</h2>
<p>We now perform eigendecomposition of the Graph Laplacian <span class="math inline">\(L\)</span> to find its eigenvalues (the spectrum) and eigenvectors.</p>
<p>The eigenspectrum reveals the fundamental topological properties of the molecule, such as connectivity and “bottlenecks.” These values are often used as structural descriptors in machine learning models for chemistry.</p>
<p><code>eigh</code> (vs <code>eig</code>) exploits the fact that <span class="math inline">\(\mathbf{L}\)</span> is <strong>real symmetric</strong> — it guarantees real eigenvalues and orthonormal eigenvectors, and is numerically faster. The decomposition is:</p>
<p><span class="math display">\[\mathbf{L} = \mathbf{U} \mathbf{\Lambda} \mathbf{U}^\top\]</span></p>
<p>where <span class="math inline">\(\mathbf{\Lambda} = \text{diag}(\lambda_0, \lambda_1, \ldots, \lambda_{N-1})\)</span> and columns of <span class="math inline">\(\mathbf{U}\)</span> are eigenvectors.</p>
<p><br></p>
<p><strong>Eigenvalues of <span class="math inline">\(C_4\)</span>:</strong></p>
<p>We solve <span class="math inline">\(\det(\mathbf{L} - \lambda \mathbf{I}) = 0\)</span>:</p>
<p><span class="math display">\[\mathbf{L} - \lambda\mathbf{I} = \begin{bmatrix} 2-\lambda&amp;-1&amp;0&amp;-1 \\\\ -1&amp;2-\lambda&amp;-1&amp;0 \\\\ 0&amp;-1&amp;2-\lambda&amp;-1 \\\\ -1&amp;0&amp;-1&amp;2-\lambda \end{bmatrix}\]</span></p>
<p><span class="math inline">\(C_4\)</span> is a circulant graph — eigenvalues are known analytically:</p>
<p><span class="math display">\[\lambda_k = 2 - 2\cos\!\left(\frac{2\pi k}{N}\right), \quad k = 0,1,2,3\]</span></p>
<p>an <span class="math inline">\(N \times N\)</span> matrix has <span class="math inline">\(N\)</span> eigenvalues, so a <span class="math inline">\(4 \times 4\)</span> Laplacian produces <span class="math inline">\(4\)</span>, indexed <span class="math inline">\(k = 0,1,2,3\)</span>.</p>
<p>Computing each:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(k\)</span></th>
<th><span class="math inline">\(\cos(2\pi k/4)\)</span></th>
<th><span class="math inline">\(\lambda_k = 2 - 2\cos(2\pi k/4)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\(\cos(0) = 1\)</span></td>
<td><span class="math inline">\(2 - 2 = 0\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\(\cos(\pi/2) = 0\)</span></td>
<td><span class="math inline">\(2 - 0 = 2\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(\cos(\pi) = -1\)</span></td>
<td><span class="math inline">\(2 + 2 = 4\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\(\cos(3\pi/2) = 0\)</span></td>
<td><span class="math inline">\(2 - 0 = 2\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\boxed{\lambda_0=0,\quad \lambda_1=2,\quad \lambda_2=2,\quad \lambda_3=4}\]</span></p>
<p><br></p>
<p><strong>7. Why <span class="math inline">\(\lambda_0 = 0\)</span> always?</strong></p>
<p>From Step 3: <span class="math inline">\(\mathbf{L}\mathbf{1} = \mathbf{0}\)</span>, so <span class="math inline">\(\mathbf{1}\)</span> is an eigenvector with eigenvalue 0. For a <strong>connected</strong> graph, this is the <em>only</em> zero eigenvalue.</p>
<p><br></p>
<p><strong>8. What is Fiedler value and vector?</strong></p>
<p><strong>Fiedler value:</strong></p>
<p><span class="math inline">\(\lambda_1 = 2\)</span> is the smallest <em>nonzero</em> eigenvalue. It measures graph connectivity — larger value means harder to cut.</p>
<p><strong>Fiedler vector</strong></p>
<p><span class="math inline">\(\mathbf{u}_1\)</span> is the corresponding eigenvector. Solving <span class="math inline">\((\mathbf{L} - 2\mathbf{I})\mathbf{u} = \mathbf{0}\)</span>:</p>
<p><span class="math display">\[\mathbf{L} - 2\mathbf{I} = \begin{bmatrix} 0&amp;-1&amp;0&amp;-1 \\\\ -1&amp;0&amp;-1&amp;0 \\\\ 0&amp;-1&amp;0&amp;-1 \\\\ -1&amp;0&amp;-1&amp;0 \end{bmatrix}\]</span></p>
<p><strong>Row reduction of <span class="math inline">\((\mathbf{L} - 2\mathbf{I})\)</span></strong></p>
<p>We’re solving <span class="math inline">\((\mathbf{L} - 2\mathbf{I})\mathbf{u} = \mathbf{0}\)</span> for the unknown vector <span class="math inline">\(\mathbf{u}\)</span>. That unknown vector has 4 entries — we just call them <span class="math inline">\(u_0, u_1, u_2, u_3\)</span> (one per node). So:</p>
<p><span class="math display">\[\mathbf{u} = \begin{bmatrix} u_0 \\\\ u_1 \\\\ u_2 \\\\ u_3 \end{bmatrix}\]</span></p>
<p>Multiplying row 0 of <span class="math inline">\((\mathbf{L}-2\mathbf{I})\)</span> by <span class="math inline">\(\mathbf{u}\)</span> is just the standard <span class="math inline">\(A\mathbf{x}=\mathbf{0}\)</span> system.</p>
<p><br></p>
<p>Rows 0 and 2 are identical; rows 1 and 3 are identical. So there are independent constraints from Row 0 and Row 1 only.</p>
<p><strong>Equations from Row 0 and Row 1</strong></p>
<p>Row 0: <span class="math inline">\((0)u_0 + (-1)u_1 + (0)u_2 + (-1)u_3 = 0\)</span> <span class="math display">\[- u_1 - u_3 = 0\]</span> <span class="math display">\[u_1 + u_3 = 0\]</span> <span class="math display">\[u_1 = -u_3\]</span></p>
<p>Row 1: <span class="math inline">\((-1)u_0 + (0)u_1 (-1)u_2 + (0)u_3 = 0\)</span> <span class="math display">\[- u_0 - u_2 = 0\]</span> <span class="math display">\[u_0 + u_2 = 0\]</span> <span class="math display">\[u_0 = -u_2\]</span></p>
<p>The two unique equations are:</p>
<ol type="1">
<li><span class="math inline">\(u_1 = -u_3\)</span></li>
<li><span class="math inline">\(u_0 = -u_2\)</span></li>
</ol>
<p>Every other equation is a repeat, so <strong>no new constraints emerge</strong>.</p>
<p><span class="math display">\[u_0, u_1 \text{ are free parameters, and } u_2, u_3 \text{ are determined.}\]</span></p>
<p>Pick <span class="math inline">\(u_0 = 1, \; u_1 = 0\)</span>:</p>
<ul>
<li><span class="math inline">\(u_2 = -u_0 = -1\)</span></li>
<li><span class="math inline">\(u_3 = -u_1 = 0\)</span></li>
</ul>
<p>So, <span class="math display">\[\mathbf{u} = \begin{bmatrix} 1 \\\\ 0 \\\\ -1 \\\\ 0 \end{bmatrix}\]</span></p>
<p><strong>HENCE,</strong></p>
<p>In conclusion, we only have two unique equations:</p>
<p><span class="math display">\[-u_1 - u_3 = 0 \implies u_1 = -u_3\]</span> <span class="math display">\[-u_0 - u_2 = 0 \implies u_0 = -u_2\]</span></p>
<p><span class="math inline">\(u_0\)</span> and <span class="math inline">\(u_1\)</span> are free. Setting <span class="math inline">\(u_0=1, u_1=0\)</span> gives <span class="math inline">\(\mathbf{u} = [1, 0, -1, 0]^\top\)</span>.</p>
<p><strong>Normalization:</strong> divide by <span class="math inline">\(\|\mathbf{u}\| = \sqrt{1^2+0^2+(-1)^2+0^2} = \sqrt{2}\)</span>:</p>
<p><span class="math display">\[\mathbf{u}_1 = \frac{1}{\sqrt{2}}[1,0,-1,0]^\top \approx [0.707,\ 0,\ -0.707,\ 0]\]</span></p>
<p><br></p>
<p><strong>Why pick <span class="math inline">\(u_0=1, u_1=0\)</span> specifically?</strong></p>
<p>We have two equations and four unknowns — the system is <strong>underdetermined</strong>, meaning infinitely many vectors satisfy it. Any scalar multiple of a solution is also a solution (eigenvectors have no fixed scale).</p>
<p>So we’re free to <strong>choose</strong> <span class="math inline">\(u_0\)</span> and <span class="math inline">\(u_1\)</span> to be anything convenient. We pick <span class="math inline">\(u_0=1, u_1=0\)</span> simply because it’s the cleanest choice — small integers, easy arithmetic. We could equally have picked <span class="math inline">\(u_0=2, u_1=0\)</span>, giving <span class="math inline">\(\mathbf{u}=[2,0,-2,0]^\top\)</span> — same eigenvector direction, just unscaled.</p>
<p>After picking, the two equations fully determine <span class="math inline">\(u_2\)</span> and <span class="math inline">\(u_3\)</span>: - <span class="math inline">\(u_2 = -u_0 = -1\)</span> - <span class="math inline">\(u_3 = -u_1 = 0\)</span></p>
<p>The final normalization step removes the arbitrary scale entirely, giving a unique unit vector.</p>
<p><br></p>
<p><strong>Bisection</strong></p>
<p>The Fiedler vector partitions nodes by sign:</p>
<ul>
<li><span class="math inline">\(u_0 = +0.707\)</span> → node 0 in partition <span class="math inline">\(\mathcal{A}\)</span></li>
<li><span class="math inline">\(u_2 = -0.707\)</span> → node 2 in partition <span class="math inline">\(\mathcal{B}\)</span></li>
<li><span class="math inline">\(u_1 = u_3 = 0\)</span> → nodes 1 and 3 sit exactly on the boundary</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th><span class="math inline">\(u_1\)</span> value</th>
<th>Sign</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\(+0.707\)</span></td>
<td><span class="math inline">\(+\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\(0\)</span></td>
<td>boundary</td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(-0.707\)</span></td>
<td><span class="math inline">\(-\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\(0\)</span></td>
<td>boundary</td>
</tr>
</tbody>
</table>
<p>The Fiedler vector bisects <span class="math inline">\(C_4\)</span> into <span class="math inline">\(\{0\}\)</span> vs <span class="math inline">\(\{2\}\)</span>, with nodes 1 and 3 on the boundary — the natural <strong>spectral cut</strong> of the cycle.</p>
<p>Visually on <span class="math inline">\(C_4\)</span>: <span class="math inline">\(0 \to 1 \to 2 \to 3 \to 0\)</span>. <br> Cutting edges <span class="math inline">\((0,1),(1,2)\)</span> on one side and <span class="math inline">\((2,3),(3,0)\)</span> on the other separates <span class="math inline">\(\{0\}\)</span> from <span class="math inline">\(\{2\}\)</span> — the two most <em>opposite</em> nodes on the cycle.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fiedler_vector_spectral_cut.png" class="img-fluid figure-img"></p>
<figcaption>Fiedler Vector</figcaption>
</figure>
</div>
<p><strong>Graph frequency intuition</strong></p>
<p>Think of the eigenvalues as measuring <em>how fast</em> a signal oscillates as you walk around the graph:</p>
<ul>
<li><span class="math inline">\(\lambda_0=0\)</span>: signal <span class="math inline">\([1,1,1,1]\)</span> — constant everywhere, zero variation across every edge — <strong>DC (constant signal)</strong>.</li>
<li><span class="math inline">\(\lambda_3=4\)</span>: signal <span class="math inline">\([1,-1,1,-1]\)</span> — flips sign at every step around the cycle — <strong>maximum oscillation</strong>.</li>
<li><span class="math inline">\(\lambda_1=\lambda_2=2\)</span>: intermediate — signal changes on opposite sides but not every step.</li>
</ul>
<p>ChebNet learns polynomial filters <span class="math inline">\(\sum_k \theta_k \lambda^k\)</span> in this frequency domain, exactly as a classical filter would in signal processing.</p>
<p><br></p>
<p><strong>9. What the full spectrum means?</strong></p>
<p>Each eigenvalue <span class="math inline">\(\lambda_k\)</span> is a <strong>graph frequency</strong>: <span class="math inline">\(\lambda_0=0\)</span> is DC, <span class="math inline">\(\lambda_3=4\)</span> is the highest-frequency mode (maximally alternating). ChebNet, coming later, will filter signals in this spectral domain.</p>
<hr>
</section>
<section id="step-5-laplacian-eigenmap-embedding" class="level2">
<h2 class="anchored" data-anchor-id="step-5-laplacian-eigenmap-embedding">Step 5: Laplacian Eigenmap Embedding</h2>
<p>We wrap Step 4’s eigendecomposition into a reusable function that embeds any molecule into <span class="math inline">\(\mathbb{R}^k\)</span> by taking the <span class="math inline">\(k\)</span> smallest non-trivial eigenvectors of <span class="math inline">\(\mathbf{L}\)</span> — this is the <strong>Laplacian Eigenmap</strong> algorithm.</p>
<p><strong>10. Why discard eigenvector 0?</strong></p>
<p>From Step 4, <span class="math inline">\(\lambda_0 = 0\)</span> always, with eigenvector <span class="math inline">\(\mathbf{u}_0 = \frac{1}{\sqrt{N}}\mathbf{1}\)</span> — a constant vector. It carries <strong>no structural information</strong> (every node maps to the same coordinate), so it is discarded.</p>
<p>The embedding uses columns <span class="math inline">\(1\)</span> through <span class="math inline">\(k\)</span> of <span class="math inline">\(\mathbf{U}\)</span>:</p>
<p><span class="math display">\[\text{embedding} = \mathbf{U}_{:,\,1:k+1} \in \mathbb{R}^{N \times k}\]</span></p>
<p><br></p>
<p><strong><span class="math inline">\(C_4\)</span> with <span class="math inline">\(k=2\)</span></strong></p>
<p>From Step 4, the eigenvectors corresponding to <span class="math inline">\(\lambda_1=2\)</span> and <span class="math inline">\(\lambda_2=2\)</span> are:</p>
<p><span class="math display">\[\mathbf{u}_1 = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 \\\\ 0 \\\\ -1 \\\\ 0 \end{bmatrix}, \qquad \mathbf{u}_2 = \frac{1}{\sqrt{2}}\begin{bmatrix} 0 \\\\ 1 \\\\ 0 \\\\ -1 \end{bmatrix}\]</span></p>
<p>The embedding matrix is:</p>
<p><span class="math display">\[\text{embedding} = \begin{bmatrix} 1/\sqrt{2} &amp; 0 \\\\ 0 &amp; 1/\sqrt{2} \\\\ -1/\sqrt{2} &amp; 0 \\\\ 0 &amp; -1/\sqrt{2} \end{bmatrix} \approx \begin{bmatrix} 0.707 &amp; 0 \\\\ 0 &amp; 0.707 \\\\ -0.707 &amp; 0 \\\\ 0 &amp; -0.707 \end{bmatrix}\]</span></p>
<p>Each row is a 2D coordinate for that node. Plotting these four points:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th><span class="math inline">\((x_1, x_2)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\((+0.707,\ 0)\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\((0,\ +0.707)\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\((-0.707,\ 0)\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\((0,\ -0.707)\)</span></td>
</tr>
</tbody>
</table>
<p>These four points lie on a circle — correctly recovering the <strong>cyclic geometry</strong> of <span class="math inline">\(C_4\)</span> purely from the Laplacian, with no coordinate input.</p>
<p><br></p>
<p><strong>11. Why this is geometrically meaningful</strong></p>
<p>The eigenvectors minimize the embedding distortion objective:</p>
<p><span class="math display">\[\min_{\mathbf{Y} \in \mathbb{R}^{N\times k}} \sum_{(i,j)\in\mathcal{E}} \|\mathbf{y}_i - \mathbf{y}_j\|^2 = \text{tr}(\mathbf{Y}^\top \mathbf{L} \mathbf{Y})\]</span></p>
<p>Connected nodes are pulled close together in the embedding. The solution is exactly <span class="math inline">\(\mathbf{U}_{:,1:k+1}\)</span> — the spectral embedding places nodes such that neighbors are geometrically nearby.</p>
<p><strong>12. Why embed at all?</strong></p>
<p>A molecule is a graph — nodes and edges, no coordinates. A neural network or any downstream algorithm needs <em>numbers in a vector</em> to work with. Embedding converts “node 0 is connected to nodes 1 and 3” into an actual coordinate like <span class="math inline">\((0.707, 0)\)</span> that captures where node 0 sits <em>relative to the rest of the graph</em>.</p>
<p>For QM9, the end goal is predicting <span class="math inline">\(U_0\)</span> (a single number per molecule). To do that, you need a fixed-size representation of the whole molecule. Embeddings are the first step: give each atom a position in space that reflects graph structure, then aggregate those positions into a molecule-level prediction.</p>
<p><strong>13. What the embedding matrix actually is</strong></p>
<p>Each <strong>row</strong> = one node’s coordinates in 2D space. That’s it.</p>
<p>On <span class="math inline">\(C_4\)</span>, row 0 is <span class="math inline">\((0.707, 0)\)</span> — that’s where node 0 gets placed. Row 2 is <span class="math inline">\((-0.707, 0)\)</span> — node 2 lands on the opposite side. The matrix is just a table of 2D positions, one per atom.</p>
<p>The remarkable thing: we never told the algorithm any geometry. We only gave it connectivity (who is bonded to whom). Yet the output positions correctly place the four nodes at 90° intervals around a circle — because that <em>is</em> the shape of a 4-cycle.</p>
<p><br></p>
<p><strong>The minimization objective — in plain terms</strong></p>
<p><span class="math display">\[\min \sum_{(i,j)\in\mathcal{E}} \|\mathbf{y}_i - \mathbf{y}_j\|^2\]</span></p>
<p>This says: <em>find coordinates such that bonded atoms land as close together as possible.</em> It’s a spring system — every edge is a spring pulling its two nodes together. The eigenvectors give the positions where all springs are simultaneously as relaxed as possible.</p>
<p>On <span class="math inline">\(C_4\)</span>: nodes 0 and 1 are bonded, so they get pulled close → <span class="math inline">\((0.707,0)\)</span> and <span class="math inline">\((0, 0.707)\)</span>, distance <span class="math inline">\(= 1\)</span>. Nodes 0 and 2 are <em>not</em> bonded, so nothing pulls them together → they end up far apart at distance <span class="math inline">\(\sqrt{2}\)</span>. The geometry emerges entirely from connectivity.</p>
<hr>
</section>
<section id="step-6-bfs-graph-distance-vs-embedding-distance-pearson-correlation" class="level2">
<h2 class="anchored" data-anchor-id="step-6-bfs-graph-distance-vs-embedding-distance-pearson-correlation">Step 6: BFS Graph Distance vs Embedding Distance (Pearson Correlation)</h2>
<p>Step 5 claimed that the Laplacian eigenmap places nearby nodes (in graph terms) close together in 2D. This cell <strong>tests that claim quantitatively</strong> by comparing two distance measures for every pair of nodes:</p>
<ul>
<li><strong>Graph distance:</strong> shortest path in hops (BFS)</li>
<li><strong>Embedding distance:</strong> Euclidean distance between 2D coordinates</li>
</ul>
<p><strong>BFS: <span class="math inline">\(C_4\)</span> – Source <span class="math inline">\(\to\)</span> Node 0</strong></p>
<p>The adjacency list:</p>
<ul>
<li>node 0 connected to nodes: [1, 3]</li>
<li>node 1 connected to nodes: [0, 2]</li>
<li>node 2 connected to nodes: [1, 3]</li>
<li>node 3 connected to nodes: [2, 0]</li>
</ul>
<p><br></p>
<p><strong>BFS from node 0</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Step</th>
<th>Queue</th>
<th>Node visited</th>
<th>Distance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>init</td>
<td>[0]</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>pop 0</td>
<td>[1, 3]</td>
<td>1, 3</td>
<td>1</td>
</tr>
<tr class="odd">
<td>pop 1</td>
<td>[3, 2]</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="even">
<td>pop 3</td>
<td>[2]</td>
<td>already visited</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{dist}(0\to0)=0,\quad\text{dist}(0\to1)=1,\quad\text{dist}(0\to2)=2,\quad\text{dist}(0\to3)=1\]</span></p>
<p><br></p>
<p><strong>Embedding distances from node 0</strong></p>
<p>From Step 5, the 2D coordinates are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th>coords</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\((0.707, 0)\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\((0, 0.707)\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\((-0.707, 0)\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\((0, -0.707)\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><span class="math inline">\(\|emb_0 - emb_1\| = \sqrt{(0.707)^2 + (0.707)^2} = \sqrt{1} = 1.0\)</span></li>
<li><span class="math inline">\(\|emb_0 - emb_2\| = \sqrt{(1.414)^2 + 0^2} = 1.414\)</span></li>
<li><span class="math inline">\(\|emb_0 - emb_3\| = \sqrt{(0.707)^2 + (0.707)^2} = 1.0\)</span></li>
</ul>
<p><br></p>
<p><strong>All pairs on <span class="math inline">\(C_4\)</span></strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Pair</th>
<th>Graph dist</th>
<th>Embed dist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\((0,1)\)</span></td>
<td>1</td>
<td>1.0</td>
</tr>
<tr class="even">
<td><span class="math inline">\((0,2)\)</span></td>
<td>2</td>
<td>1.414</td>
</tr>
<tr class="odd">
<td><span class="math inline">\((0,3)\)</span></td>
<td>1</td>
<td>1.0</td>
</tr>
<tr class="even">
<td><span class="math inline">\((1,2)\)</span></td>
<td>1</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\((1,3)\)</span></td>
<td>2</td>
<td>1.414</td>
</tr>
<tr class="even">
<td><span class="math inline">\((2,3)\)</span></td>
<td>1</td>
<td>1.0</td>
</tr>
</tbody>
</table>
<p>The pattern is perfectly monotone: graph distance 1 <span class="math inline">\(\to\)</span> embed distance 1.0, graph distance 2 <span class="math inline">\(\to\)</span> embed distance 1.414 — the embedding <strong>preserves graph distance ordering exactly</strong> on <span class="math inline">\(C_4\)</span>.</p>
<p><br></p>
<p><strong>Pearson correlation</strong></p>
<p><span class="math display">\[r = \frac{\sum_i (g_i - \bar{g})(e_i - \bar{e})}{\sqrt{\sum_i(g_i-\bar{g})^2}\sqrt{\sum_i(e_i-\bar{e})^2}}\]</span></p>
<p>On <span class="math inline">\(C_4\)</span>:</p>
<ul>
<li>graph distances <span class="math inline">\(= [1,2,1,1,2,1]\)</span> &amp; <br></li>
<li>embed distances <span class="math inline">\(= [1.0, 1.414, 1.0, 1.0, 1.414, 1.0]\)</span>.</li>
</ul>
<p>Since embed distance is a strict monotone function of graph distance here, <span class="math inline">\(r = 1.0\)</span>: perfect correlation.</p>
<p>Real molecules won’t hit 1.0 exactly — the 2D embedding compresses <span class="math inline">\(N\)</span>-dimensional structure — but strong <span class="math inline">\(r &gt; 0.6\)</span> confirms the eigenmap is geometrically faithful.</p>
<p><br></p>
<p><strong>14. Why graph distance 2 produces a larger embedding distance than graph distance 1 on <span class="math inline">\(C_4\)</span>? What property of the eigenvectors guarantees this?</strong></p>
<p>The eigenvectors minimize <span class="math inline">\(\sum_{(i,j)\in\mathcal{E}}\|\mathbf{y}_i - \mathbf{y}_j\|^2\)</span> — they pull <strong>directly connected</strong> nodes close. Nodes at graph distance 2 have no direct spring pulling them together, so they naturally land further apart.</p>
<p>The guaranteeing property is <strong>orthogonality</strong>: eigenvectors <span class="math inline">\(\mathbf{u}_1\)</span> and <span class="math inline">\(\mathbf{u}_2\)</span> are orthogonal, which forces the 2D embedding to spread nodes out in independent directions. If two nodes share no edge, nothing contracts their distance — orthogonality ensures the embedding has enough “room” to place them further away rather than collapsing them together.</p>
<p>On <span class="math inline">\(C_4\)</span> specifically: nodes 0 and 2 are non-adjacent and their coordinates <span class="math inline">\((0.707, 0)\)</span> and <span class="math inline">\((-0.707, 0)\)</span> are exactly opposite — maximum possible separation given the unit-norm constraint on eigenvectors.</p>
<hr>
</section>
<section id="step-7-mpnn-message-passing-layer" class="level2">
<h2 class="anchored" data-anchor-id="step-7-mpnn-message-passing-layer">Step 7: MPNN Message Passing Layer</h2>
<p>We now implement one full round of <strong>message passing</strong> from scratch: every node collects information from its neighbors, aggregates it, and updates its own state. This is the core computational primitive of all GNNs.</p>
<p>Three steps: <strong>compute <span class="math inline">\(\to\)</span> aggregate <span class="math inline">\(\to\)</span> update.</strong></p>
<p><strong>Message computation</strong></p>
<p>For every directed edge <span class="math inline">\(i \to j\)</span>:</p>
<p><span class="math display">\[\mathbf{m}_{ij} = \text{MLP}_{\text{msg}}\left([\mathbf{h}_i \| \mathbf{h}_j \| \mathbf{e}_{ij}]\right)\]</span></p>
<p><span class="math inline">\([\cdot\|\cdot]\)</span> denotes concatenation. The message depends on <strong>both</strong> endpoints plus the edge feature — this is richer than classic GCN which only uses the neighbor’s features.</p>
<p>For <span class="math inline">\(C_4\)</span> with scalar features <span class="math inline">\(\mathbf{h} = [2,1,1,1]^\top\)</span> and no edge features:</p>
<ul>
<li>For edge <span class="math inline">\(0\to1\)</span>:</li>
</ul>
<p><span class="math display">\[\mathbf{m}_{01} = \text{MLP}_{\text{msg}}([h_0 \| h_1]) = \text{MLP}_{\text{msg}}([2, 1])\]</span></p>
<ul>
<li>For edge <span class="math inline">\(0\to3\)</span>:</li>
</ul>
<p><span class="math display">\[\mathbf{m}_{03} = \text{MLP}_{\text{msg}}([2, 1])\]</span></p>
<p>Both messages are identical here because nodes 1 and 3 have the same feature — this foreshadows the <strong>WL expressiveness limit</strong> explored later in the project.</p>
<p><br></p>
<p><strong>Aggregation via <code>scatter_add_</code></strong></p>
<p><span class="math display">\[\mathbf{M}_i = \sum_{j \in \mathcal{N}(i)} \mathbf{m}_{ji}\]</span></p>
<p><code>scatter_add_</code> accumulates messages by destination node index. For <span class="math inline">\(C_4\)</span>, node 0 receives from nodes 1 and 3:</p>
<p><span class="math display">\[\mathbf{M}_0 = \mathbf{m}_{10} + \mathbf{m}_{30}\]</span></p>
<p>Since <span class="math inline">\(h_1 = h_3 = 1\)</span>, both incoming messages are identical → <span class="math inline">\(\mathbf{M}_0 = 2 \cdot \mathbf{m}_{10}\)</span>.</p>
<p><br></p>
<p><strong>15. Why <code>dst.unsqueeze(-1).expand_as(messages)</code>?</strong></p>
<p><code>dst</code> is a 1D index vector of shape <span class="math inline">\([2E]\)</span>. Each message is <code>hidden_dim</code>-dimensional. The expand broadcasts the scalar destination index across all hidden dimensions so <code>scatter_add_</code> knows which row of <code>agg</code> to accumulate into.</p>
<p><br></p>
<p><strong>Node update</strong></p>
<p><span class="math display">\[\mathbf{h}_i' = \text{MLP}_{\text{update}}\left([\mathbf{h}_i \| \mathbf{M}_i]\right)\]</span></p>
<p>For node 0 on the anchor:</p>
<p><span class="math display">\[\mathbf{h}_0' = \text{ReLU}\left(\mathbf{W}_{\text{update}}[h_0 \| \mathbf{M}_0]\right) = \text{ReLU}\left(\mathbf{W}_{\text{update}}[2 \| \mathbf{M}_0]\right)\]</span></p>
<p>The node retains its own state <span class="math inline">\(\mathbf{h}_i\)</span> alongside the aggregated neighborhood summary <span class="math inline">\(\mathbf{M}_i\)</span> — this prevents the node from “forgetting” who it is after aggregation.</p>
<p><br></p>
<p><strong>Full data flow summary</strong></p>
<p><span class="math display">\[[N, F] \xrightarrow{\text{concat neighbors+edges}} [2E,\ 2F+F_e] \xrightarrow{\text{MLP}_{\text{msg}}} [2E, H] \xrightarrow{\text{scatter\_add}} [N, H] \xrightarrow{\text{MLP}_{\text{update}}} [N, H]\]</span></p>
<p><br></p>
<p><strong>16. In Step 1, we obtained <span class="math inline">\(m_{01}\)</span> and <span class="math inline">\(m_{03}\)</span>. In Step 2, we used <span class="math inline">\(m_{10}\)</span> and <span class="math inline">\(m_{30}\)</span>. There seems to be mismatch of subscript. Is that a typo or does it not matter in which order we write?</strong></p>
<p>Not a typo — it matters and here’s why.</p>
<p>In Step 1, <span class="math inline">\(\mathbf{m}_{ij}\)</span> means “message <strong>from</strong> <span class="math inline">\(i\)</span> <strong>to</strong> <span class="math inline">\(j\)</span>” — so <span class="math inline">\(\mathbf{m}_{01}\)</span> is the message node 0 sends <em>to</em> node 1.</p>
<p>In Step 2, node 0 <strong>receives</strong> messages — meaning we want messages whose destination is node 0. Those are <span class="math inline">\(\mathbf{m}_{10}\)</span> (from node 1 to node 0) and <span class="math inline">\(\mathbf{m}_{30}\)</span> (from node 3 to node 0).</p>
<p>The subscript convention is <span class="math inline">\(\mathbf{m}_{\text{source} \to \text{destination}}\)</span>. Step 1 computes all messages in both directions; Step 2 filters to only those <em>arriving at</em> node 0. The subscript flip is intentional, not a typo.</p>
<p><br></p>
<p><strong>17. Node 0 in the anchor receives identical messages from nodes 1 and 3 after one round. After two rounds, will node 0 be able to distinguish them? What would need to change in the architecture for it to do so?</strong></p>
<p>After two rounds, node 0 <strong>still cannot distinguish</strong> nodes 1 and 3.</p>
<p>Here’s why: in round 2, nodes 1 and 3 each look at <em>their</em> neighborhoods. Node 1’s neighbors are <span class="math inline">\(\{0, 2\}\)</span> and node 3’s neighbors are <span class="math inline">\(\{2, 0\}\)</span> — identical sets, identical features. So after round 2, nodes 1 and 3 produce identical updated states, and node 0 again receives two identical messages.</p>
<p>This is the <strong>WL expressiveness limit</strong> — the 1-Weisfeiler-Lehman graph isomorphism test, which standard message passing exactly simulates, cannot distinguish nodes with symmetric neighborhoods. On <span class="math inline">\(C_4\)</span> with uniform features, nodes 1 and 3 are structurally indistinguishable by any number of rounds.</p>
<p><em>What would need to change:</em></p>
<ul>
<li><strong>Unique node identifiers</strong> — inject positional encodings (e.g.&nbsp;Laplacian eigenvectors from Step 5) so nodes 1 and 3 start with different initial features. This breaks symmetry at round 0, propagating distinct messages immediately.</li>
<li><strong>Distance encoding</strong> — explicitly encode the hop-distance from each node to others as an input feature.</li>
<li><strong>Higher-order GNNs</strong> — consider tuples of nodes rather than individual nodes (k-WL hierarchy), breaking symmetries that 1-WL cannot.</li>
</ul>
<p>In QM9 specifically, the node feature matrix <span class="math inline">\(\mathbf{X}\)</span> already contains atom-type one-hots — if nodes 1 and 3 are different atom types, the problem vanishes naturally. The WL limit bites hardest on symmetric molecules with identical atom types at symmetric positions.</p>
<p><br></p>
<blockquote class="blockquote">
<p>THE COMPLETE CHRONOLOGICAL FLOW OF GNN MESSAGE PASSING WITH ITS UNDERLYING MATHEMATICS IS EXPLAINED IN <a href="https://shreeshb51.github.io/catw/GNN%20Message%20Passing/">CATW/GNN Message Passing</a></p>
</blockquote>
<hr>
</section>
<section id="step-8-full-mpnn-input-projection-stacked-layers-readout" class="level2">
<h2 class="anchored" data-anchor-id="step-8-full-mpnn-input-projection-stacked-layers-readout">Step 8: Full MPNN: Input Projection, Stacked Layers, Readout</h2>
<p>We assemble three stages into a complete graph-level regression model:</p>
<p><span class="math display">\[\underbrace{\mathbf{X}}_{\text{atom features}} \xrightarrow{\text{project}} \underbrace{\mathbf{H}^{(0)}}_{\text{hidden}} \xrightarrow{L \times \text{MPNN}} \underbrace{\mathbf{H}^{(L)}}_{\text{rich node states}} \xrightarrow{\text{mean pool}} \underbrace{\mathbf{g}}_{\text{graph vector}} \xrightarrow{\text{MLP}} \underbrace{\hat{y}}_{\text{predicted } U_0}\]</span></p>
<section id="stage-1-input-projection" class="level3">
<h3 class="anchored" data-anchor-id="stage-1-input-projection">Stage 1 — Input projection</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>h <span class="op">=</span> F.relu(<span class="va">self</span>.input_proj(x)) <span class="co"># [N, hidden_dim]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="math display">\[\mathbf{H}^{(0)} = \text{ReLU}(\mathbf{X}\mathbf{W}_{\text{in}})\]</span></p>
<p>Projects 11-dim QM9 atom features into <code>hidden_dim=64</code>. On <span class="math inline">\(C_4\)</span>, <span class="math inline">\(\mathbf{x}_0 = [2]\)</span> (scalar) maps to a 64-dim vector. All subsequent layers operate in this uniform space.</p>
<p><br></p>
</section>
<section id="stage-2-stacked-message-passing" class="level3">
<h3 class="anchored" data-anchor-id="stage-2-stacked-message-passing">Stage 2 — Stacked message passing</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> layer <span class="kw">in</span> <span class="va">self</span>.layers:</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> layer(h, edge_index, edge_attr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="math display">\[\mathbf{H}^{(l+1)} = \text{MPNNLayer}\left(\mathbf{H}^{(l)}, \mathcal{E}, \mathbf{E}\right), \quad l = 0,1,2\]</span></p>
<p>Each layer expands the <strong>receptive field</strong> by one hop. After <span class="math inline">\(L=3\)</span> layers, node 0 on <span class="math inline">\(C_4\)</span> has seen information from all nodes within 3 hops — the entire graph.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Layer</th>
<th>Node 0 sees</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>itself only</td>
</tr>
<tr class="even">
<td>1</td>
<td>nodes 1, 3</td>
</tr>
<tr class="odd">
<td>2</td>
<td>nodes 2 (via 1 and 3)</td>
</tr>
<tr class="even">
<td>3</td>
<td>full graph</td>
</tr>
</tbody>
</table>
<p><br></p>
</section>
<section id="stage-3-global-mean-pooling" class="level3">
<h3 class="anchored" data-anchor-id="stage-3-global-mean-pooling">Stage 3 — Global mean pooling</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>out.scatter_add_(<span class="dv">0</span>, batch.unsqueeze(<span class="op">-</span><span class="dv">1</span>).expand_as(h), h)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>graph_emb <span class="op">=</span> out <span class="op">/</span> count</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="math display">\[\mathbf{g}_b = \frac{1}{|\mathcal{V}_b|}\sum_{i \in \mathcal{V}_b} \mathbf{h}_i^{(L)}\]</span></p>
<p>The <code>batch</code> tensor maps each node to its graph index. For a batch of two graphs where graph 0 has nodes <span class="math inline">\(\{0,1,2\}\)</span> and graph 1 has nodes <span class="math inline">\(\{3,4\}\)</span>:</p>
<p><span class="math display">\[\texttt{batch} = [0,0,0,1,1]\]</span></p>
<p><code>scatter_add_</code> sums node vectors by graph index, then divides by node count — yielding one 64-dim vector per molecule.</p>
<p>On <span class="math inline">\(C_4\)</span> (single graph, <span class="math inline">\(N=4\)</span>):</p>
<p><span class="math display">\[\mathbf{g} = \frac{1}{4}\left(\mathbf{h}_0^{(L)} + \mathbf{h}_1^{(L)} + \mathbf{h}_2^{(L)} + \mathbf{h}_3^{(L)}\right) \in \mathbb{R}^{64}\]</span></p>
<p><strong>18. Why mean and not sum?</strong></p>
<p>Mean is invariant to graph size — a 5-atom and 10-atom molecule both produce vectors of the same scale, making training more stable across QM9’s variable-size molecules.</p>
<p><br></p>
</section>
<section id="stage-4-readout-mlp" class="level3">
<h3 class="anchored" data-anchor-id="stage-4-readout-mlp">Stage 4 — Readout MLP</h3>
<p><span class="math display">\[\hat{y} = \mathbf{W}_2\,\text{ReLU}(\mathbf{W}_1 \mathbf{g} + \mathbf{b}_1) + \mathbf{b}_2 \in \mathbb{R}\]</span></p>
<p>A two-layer MLP compresses the 64-dim graph embedding to a scalar <span class="math inline">\(U_0\)</span> prediction.</p>
<p><br></p>
<p><strong>19. Why this architecture is permutation invariant?</strong></p>
<p>If you relabel node 0→2→1→3, the mean pool produces the same <span class="math inline">\(\mathbf{g}\)</span> — addition commutes. This is essential: a molecule’s energy doesn’t depend on how you number its atoms.</p>
<hr>
</section>
</section>
<section id="step-9-permutation-invariance-verification" class="level2">
<h2 class="anchored" data-anchor-id="step-9-permutation-invariance-verification">Step 9: Permutation Invariance Verification</h2>
<p>We now construct a relabeled copy of <span class="math inline">\(C_4\)</span> — same graph, different node indices — to verify that the MPNN produces identical predictions regardless of atom ordering.</p>
<p><strong>The permutation operator</strong></p>
<p>A permutation <span class="math inline">\(\pi\)</span> on <span class="math inline">\(N\)</span> nodes is a bijection <span class="math inline">\(\{0,\ldots,N-1\} \to \{0,\ldots,N-1\}\)</span>. It acts on three objects:</p>
<p><strong>1. Node features:</strong> <span class="math display">\[\mathbf{X}_\pi = \mathbf{P}_\pi \mathbf{X}\]</span> where <span class="math inline">\(\mathbf{P}_\pi\)</span> is the <span class="math inline">\(N\times N\)</span> permutation matrix with <span class="math inline">\((\mathbf{P}_\pi)_{ij} = 1\)</span> iff <span class="math inline">\(\pi(j) = i\)</span>.</p>
<p><span class="math inline">\(\mathbf{P}\)</span> is an <span class="math inline">\(N\times N\)</span> binary matrix with exactly one 1 per row and column:</p>
<p><span class="math display">\[P_{ij} = \begin{cases} 1 &amp; \text{if } \pi(j) = i \\\\ 0 &amp; \text{otherwise} \end{cases}\]</span></p>
<p>In code: <code>x_perm = mol.x[pi]</code> — row <span class="math inline">\(i\)</span> of <code>x_perm</code> is row <span class="math inline">\(\pi(i)\)</span> of <code>mol.x</code>.</p>
<p><strong>2. Adjacency matrix:</strong> <span class="math display">\[\mathbf{A}_\pi = \mathbf{P}_\pi \mathbf{A} \mathbf{P}_\pi^\top\]</span></p>
<p><strong>3. Edge index (COO):</strong> each node id <span class="math inline">\(i\)</span> in <code>edge_index</code> is replaced by <span class="math inline">\(\pi(i)\)</span>: <span class="math display">\[\texttt{edge\_index\_perm} = \pi(\texttt{edge\_index})\]</span></p>
<p><br></p>
<p><strong>On the anchor <span class="math inline">\(C_4\)</span></strong></p>
<p>Let <span class="math inline">\(\pi = [2, 0, 3, 1]\)</span> — meaning node 0 becomes node 2, node 1 becomes node 0, etc.</p>
<p>This sets <span class="math inline">\(P_{\pi(j), j} = 1\)</span> for each <span class="math inline">\(j\)</span>. Column <span class="math inline">\(j\)</span> of <span class="math inline">\(\mathbf{P}\)</span> has a single 1 in row <span class="math inline">\(\pi(j)\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(j\)</span></th>
<th><span class="math inline">\(\pi(j)\)</span></th>
<th>1 placed at <span class="math inline">\(\mathbf{P}\)</span>’s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>2</td>
<td>row 2, col 0</td>
</tr>
<tr class="even">
<td>1</td>
<td>0</td>
<td>row 0, col 1</td>
</tr>
<tr class="odd">
<td>2</td>
<td>3</td>
<td>row 3, col 2</td>
</tr>
<tr class="even">
<td>3</td>
<td>1</td>
<td>row 1, col 3</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\mathbf{P} = \begin{bmatrix} 0&amp;1&amp;0&amp;0 \\\\ 0&amp;0&amp;0&amp;1 \\\\ 1&amp;0&amp;0&amp;0 \\\\ 0&amp;0&amp;1&amp;0 \end{bmatrix}\]</span></p>
<p><strong>Sanity check:</strong> each row and column has exactly one 1 — it’s a valid permutation matrix. ✓</p>
<p><br></p>
<p><strong>The invariance claim</strong></p>
<p>A model <span class="math inline">\(f\)</span> is <strong>permutation invariant</strong> iff:</p>
<p><span class="math display">\[f(\mathbf{X}_\pi, \mathbf{A}_\pi) = f(\mathbf{X}, \mathbf{A}) \quad \forall\, \pi\]</span></p>
<p><br></p>
<p><strong>Computing <span class="math inline">\(\mathbf{P}\mathbf{A}\mathbf{P}^\top\)</span></strong></p>
<p>Recall from Step 1:</p>
<p><span class="math display">\[\mathbf{A} = \begin{bmatrix} 0&amp;1&amp;0&amp;1 \\\\ 1&amp;0&amp;1&amp;0 \\\\ 0&amp;1&amp;0&amp;1 \\\\ 1&amp;0&amp;1&amp;0 \end{bmatrix}\]</span></p>
<p><strong>First, <span class="math inline">\(\mathbf{P}\mathbf{A}\)</span></strong> — permutes the <em>rows</em> of <span class="math inline">\(\mathbf{A}\)</span>. Row <span class="math inline">\(i\)</span> of <span class="math inline">\(\mathbf{P}\mathbf{A}\)</span> = row <span class="math inline">\(\pi^{-1}(i)\)</span> of <span class="math inline">\(\mathbf{A}\)</span>… equivalently, row <span class="math inline">\(\pi(j)\)</span> of the result gets row <span class="math inline">\(j\)</span> of <span class="math inline">\(\mathbf{A}\)</span>:</p>
<ul>
<li>Row 2 of <span class="math inline">\(\mathbf{PA}\)</span> ← row 0 of <span class="math inline">\(\mathbf{A}\)</span>: <span class="math inline">\([0,1,0,1]\)</span></li>
<li>Row 0 of <span class="math inline">\(\mathbf{PA}\)</span> ← row 1 of <span class="math inline">\(\mathbf{A}\)</span>: <span class="math inline">\([1,0,1,0]\)</span></li>
<li>Row 3 of <span class="math inline">\(\mathbf{PA}\)</span> ← row 2 of <span class="math inline">\(\mathbf{A}\)</span>: <span class="math inline">\([0,1,0,1]\)</span></li>
<li>Row 1 of <span class="math inline">\(\mathbf{PA}\)</span> ← row 3 of <span class="math inline">\(\mathbf{A}\)</span>: <span class="math inline">\([1,0,1,0]\)</span></li>
</ul>
<p><em>In simple terms, just multiply <span class="math inline">\(\mathbf{P}\)</span> and <span class="math inline">\(\mathbf{A}\)</span>.</em></p>
<p><span class="math display">\[\mathbf{PA} = \begin{bmatrix} 1&amp;0&amp;1&amp;0 \\\\ 1&amp;0&amp;1&amp;0 \\\\ 0&amp;1&amp;0&amp;1 \\\\ 0&amp;1&amp;0&amp;1 \end{bmatrix}\]</span></p>
<p><strong>Then <span class="math inline">\((\mathbf{PA})\mathbf{P}^\top\)</span></strong> — permutes the <em>columns</em>. Column <span class="math inline">\(\pi(j)\)</span> of the result gets column <span class="math inline">\(j\)</span>:</p>
<ul>
<li>Col 2 ← col 0: <span class="math inline">\([1,1,0,0]^\top\)</span></li>
<li>Col 0 ← col 1: <span class="math inline">\([0,0,1,1]^\top\)</span></li>
<li>Col 3 ← col 2: <span class="math inline">\([1,1,0,0]^\top\)</span></li>
<li>Col 1 ← col 3: <span class="math inline">\([0,0,1,1]^\top\)</span></li>
</ul>
<p><span class="math display">\[\mathbf{PAP}^\top = \begin{bmatrix} 0&amp;0&amp;1&amp;1 \\\\ 0&amp;0&amp;1&amp;1 \\\\ 1&amp;1&amp;0&amp;0 \\\\ 1&amp;1&amp;0&amp;0 \end{bmatrix}\]</span></p>
<p><br></p>
<p><strong>Building <span class="math inline">\(\mathbf{A}_\pi\)</span> directly from permuted edge_index</strong></p>
<p>Applying <span class="math inline">\(\pi = [2,0,3,1]\)</span> to the original <span class="math inline">\(C_4\)</span> edge_index:</p>
<p>Original 8 directed edges and their images under <span class="math inline">\(\pi\)</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Original edge</th>
<th><span class="math inline">\(\pi[\text{src}]\)</span></th>
<th><span class="math inline">\(\pi[\text{dst}]\)</span></th>
<th>Permuted edge</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0\to1\)</span></td>
<td><span class="math inline">\(\pi[0]=2\)</span></td>
<td><span class="math inline">\(\pi[1]=0\)</span></td>
<td><span class="math inline">\(2\to0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(1\to0\)</span></td>
<td><span class="math inline">\(\pi[1]=0\)</span></td>
<td><span class="math inline">\(\pi[0]=2\)</span></td>
<td><span class="math inline">\(0\to2\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(1\to2\)</span></td>
<td><span class="math inline">\(\pi[1]=0\)</span></td>
<td><span class="math inline">\(\pi[2]=3\)</span></td>
<td><span class="math inline">\(0\to3\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(2\to1\)</span></td>
<td><span class="math inline">\(\pi[2]=3\)</span></td>
<td><span class="math inline">\(\pi[1]=0\)</span></td>
<td><span class="math inline">\(3\to0\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(2\to3\)</span></td>
<td><span class="math inline">\(\pi[2]=3\)</span></td>
<td><span class="math inline">\(\pi[3]=1\)</span></td>
<td><span class="math inline">\(3\to1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(3\to2\)</span></td>
<td><span class="math inline">\(\pi[3]=1\)</span></td>
<td><span class="math inline">\(\pi[2]=3\)</span></td>
<td><span class="math inline">\(1\to3\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(3\to0\)</span></td>
<td><span class="math inline">\(\pi[3]=1\)</span></td>
<td><span class="math inline">\(\pi[0]=2\)</span></td>
<td><span class="math inline">\(1\to2\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0\to3\)</span></td>
<td><span class="math inline">\(\pi[0]=2\)</span></td>
<td><span class="math inline">\(\pi[3]=1\)</span></td>
<td><span class="math inline">\(2\to1\)</span></td>
</tr>
</tbody>
</table>
<p>Now set <span class="math inline">\(A_{ij}=1\)</span> for each permuted edge <span class="math inline">\((i\to j)\)</span>:</p>
<p><span class="math display">\[A_{20}=1,\ A_{02}=1,\ A_{03}=1,\ A_{30}=1,\ A_{31}=1,\ A_{13}=1,\ A_{12}=1,\ A_{21}=1\]</span></p>
<p>Filling the <span class="math inline">\(4\times4\)</span> matrix entry by entry:</p>
<p><span class="math display">\[\mathbf{A}_\pi = \begin{bmatrix} 0&amp;0&amp;1&amp;1 \\\\ 0&amp;0&amp;1&amp;1 \\\\ 1&amp;1&amp;0&amp;0 \\\\ 1&amp;1&amp;0&amp;0 \end{bmatrix}\]</span></p>
<p>which matches <span class="math inline">\(\mathbf{PAP}^\top\)</span> exactly. ✓</p>
<p><span class="math display">\[\mathbf{PAP}^\top = \mathbf{A}_\pi \checkmark\]</span></p>
<p><br></p>
<p><strong>20. What this proves?</strong></p>
<p><span class="math inline">\(\mathbf{P}\mathbf{A}\mathbf{P}^\top = \mathbf{A}_\pi\)</span> confirms that relabeling nodes via <span class="math inline">\(\pi\)</span> is <strong>exactly</strong> the action of conjugating <span class="math inline">\(\mathbf{A}\)</span> by the permutation matrix. The graph is unchanged — only its description changes. Any model that produces the same output for both must be truly invariant to how atoms are numbered.</p>
<hr>
</section>
<section id="step-10-permutation-invariance-numerical-test" class="level2">
<h2 class="anchored" data-anchor-id="step-10-permutation-invariance-numerical-test">Step 10: Permutation Invariance Numerical Test</h2>
<p>We run the same molecule through the model twice — original ordering and permuted ordering — and checks that the scalar <span class="math inline">\(U_0\)</span> prediction is identical. This is the numerical proof that Step 8’s mean pooling achieves permutation invariance.</p>
<p><strong>21. Why the outputs should be identical?</strong></p>
<p>From Step 8, the readout is:</p>
<p><span class="math display">\[\hat{y} = \text{MLP}\left(\frac{1}{N}\sum_{i\in\mathcal{V}} \mathbf{h}_i^{(L)}\right)\]</span></p>
<p>Under permutation <span class="math inline">\(\pi\)</span>, the set <span class="math inline">\(\{\mathbf{h}_i^{(L)}\}\)</span> is reordered but unchanged as a <strong>set</strong>. Addition commutes, so:</p>
<p><span class="math display">\[\sum_{i} \mathbf{h}_{\pi(i)}^{(L)} = \sum_{i} \mathbf{h}_i^{(L)}\]</span></p>
<p>The mean — and therefore <span class="math inline">\(\hat{y}\)</span> — is identical.</p>
<p><br></p>
<p><strong>On the anchor <span class="math inline">\(C_4\)</span></strong></p>
<p>Original ordering mean pool: <span class="math display">\[\mathbf{g} = \frac{1}{4}(\mathbf{h}_0 + \mathbf{h}_1 + \mathbf{h}_2 + \mathbf{h}_3)\]</span></p>
<p>Permuted ordering (<span class="math inline">\(\pi = [2,0,3,1]\)</span>) mean pool: <span class="math display">\[\mathbf{g}_\pi = \frac{1}{4}(\mathbf{h}_2 + \mathbf{h}_0 + \mathbf{h}_3 + \mathbf{h}_1)\]</span></p>
<p>Mathematically: <span class="math inline">\(\mathbf{g} = \mathbf{g}_\pi\)</span> exactly. Numerically: within float32 rounding error.</p>
<hr>
</section>
<section id="step-11-chebnet-spectral-convolution" class="level2">
<h2 class="anchored" data-anchor-id="step-11-chebnet-spectral-convolution">Step 11: ChebNet Spectral Convolution</h2>
<p>We implement a <strong>spectral graph convolution</strong> using Chebyshev polynomials. Where Steps 7 &amp; 8 MPNN operated spatially (passing messages along edges), ChebNet operates in the <strong>spectral domain</strong> — filtering the graph signal using the Laplacian’s eigenstructure built in Steps 2-5.</p>
<p><br></p>
<p><strong>22. Why Chebyshev polynomials?</strong></p>
<p>The theoretically clean spectral filter is:</p>
<p><span class="math display">\[\mathbf{y} = \sum_{k=0}^{K-1} \theta_k \mathbf{U} \mathbf{\Lambda}^k \mathbf{U}^\top \mathbf{x}\]</span></p>
<p>But this requires explicitly computing <span class="math inline">\(\mathbf{U}\)</span> (eigendecomposition) — <span class="math inline">\(O(N^3)\)</span>, catastrophic for large graphs. Chebyshev polynomials solve this by approximating the filter using only <strong>matrix-vector products with <span class="math inline">\(\mathbf{L}\)</span></strong>, never forming <span class="math inline">\(\mathbf{U}\)</span>.</p>
<p><em>EXPLANATION:</em></p>
<p>The Laplacian <span class="math inline">\(\mathbf{L}\)</span> has an eigendecomposition:</p>
<p><span class="math display">\[\mathbf{L} = \mathbf{U}\mathbf{\Lambda}\mathbf{U}^\top\]</span></p>
<p>where <span class="math inline">\(\mathbf{U}\)</span> contains eigenvectors as columns and <span class="math inline">\(\mathbf{\Lambda} = \text{diag}(\lambda_0, \lambda_1, \ldots, \lambda_{N-1})\)</span> contains eigenvalues on the diagonal. This is the <strong>spectral domain</strong> of the graph — analogous to the Fourier transform for signals on grids.</p>
<p>Now the formula:</p>
<ul>
<li><span class="math inline">\(\mathbf{x} \in \mathbb{R}^N\)</span> — the graph signal (one scalar per node, e.g.&nbsp;<span class="math inline">\(\mathbf{h} = [2,1,1,1]^\top\)</span> on <span class="math inline">\(C_4\)</span>)</li>
<li><span class="math inline">\(\mathbf{U}^\top \mathbf{x}\)</span> — transforms the signal into the spectral domain (graph Fourier transform)</li>
<li><span class="math inline">\(\mathbf{\Lambda}^k\)</span> — scales each frequency component by <span class="math inline">\(\lambda_k^k\)</span> — this is the <strong>filter</strong></li>
<li><span class="math inline">\(\mathbf{U}\)</span> — transforms back to node domain (inverse graph Fourier transform)</li>
<li><span class="math inline">\(\theta_k\)</span> — learned scalar weight for the <span class="math inline">\(k\)</span>-th filter order</li>
<li><span class="math inline">\(\sum_{k=0}^{K-1}\)</span> — sum over <span class="math inline">\(K\)</span> filter orders, each contributing a different frequency scaling</li>
</ul>
<p>Intuitively: transform signal to frequency space → scale frequencies → transform back → weighted sum over <span class="math inline">\(K\)</span> such operations.</p>
<p><strong>23. Why it’s computationally catastrophic?</strong></p>
<p>Computing <span class="math inline">\(\mathbf{U}\)</span> requires full eigendecomposition of <span class="math inline">\(\mathbf{L}\)</span> — an <span class="math inline">\([N \times N]\)</span> matrix operation costing <span class="math inline">\(O(N^3)\)</span>. For a molecule with 100 atoms, fine. For a graph with 1 million nodes — completely intractable.</p>
<p><br></p>
<p><strong>24. What Chebyshev polynomials do instead?</strong></p>
<p>Chebyshev polynomials are a family of functions <span class="math inline">\(T_k(x)\)</span> defined by the recurrence:</p>
<p><span class="math display">\[T_0(x) = 1, \quad T_1(x) = x, \quad T_k(x) = 2x\,T_{k-1}(x) - T_{k-2}(x)\]</span></p>
<p>The key property: <strong>any polynomial of degree <span class="math inline">\(k\)</span> can be approximated as a linear combination of <span class="math inline">\(T_0, T_1, \ldots, T_k\)</span>.</strong></p>
<p>Applied to the filter — instead of <span class="math inline">\(\mathbf{U}\mathbf{\Lambda}^k\mathbf{U}^\top\)</span>, ChebNet approximates using:</p>
<p><span class="math display">\[T_k(\tilde{\mathbf{L}}) = \text{matrix polynomial in } \tilde{\mathbf{L}}\]</span></p>
<p>Each application of <span class="math inline">\(\tilde{\mathbf{L}}\)</span> is just a <strong>sparse matrix-vector multiply</strong> — <span class="math inline">\(O(|\mathcal{E}|)\)</span>, not <span class="math inline">\(O(N^3)\)</span>. The eigenvectors <span class="math inline">\(\mathbf{U}\)</span> are never computed explicitly.</p>
<p>The ChebNet filter then becomes:</p>
<p><span class="math display">\[\mathbf{y} = \sum_{k=0}^{K-1} \theta_k T_k(\tilde{\mathbf{L}})\mathbf{x}\]</span></p>
<p>Same expressiveness, tractable cost.</p>
<p><br></p>
<p><strong>Spectrum normalization — <code>L_tilde</code></strong></p>
<p>The Chebyshev recurrence requires input in <span class="math inline">\([-1, 1]\)</span>. The Laplacian spectrum lies in <span class="math inline">\([0, \lambda_{\max}]\)</span>, so we rescale:</p>
<p><span class="math display">\[\tilde{\mathbf{L}} = \frac{2}{\lambda_{\max}}\mathbf{L} - \mathbf{I}\]</span></p>
<p>On <span class="math inline">\(C_4\)</span>: <span class="math inline">\(\lambda_{\max} = 4\)</span> (from Step 4), so:</p>
<p><span class="math display">\[\tilde{\mathbf{L}} = \frac{2}{4}\mathbf{L} - \mathbf{I} = \frac{1}{2}\begin{bmatrix}2&amp;-1&amp;0&amp;-1 \\\\ -1&amp;2&amp;-1&amp;0 \\\\ 0&amp;-1&amp;2&amp;-1 \\\\ -1&amp;0&amp;-1&amp;2\end{bmatrix} - \begin{bmatrix}1&amp;0&amp;0&amp;0 \\\\ 0&amp;1&amp;0&amp;0 \\\\ 0&amp;0&amp;1&amp;0 \\\\ 0&amp;0&amp;0&amp;1\end{bmatrix} = \begin{bmatrix}0&amp;-\frac{1}{2}&amp;0&amp;-\frac{1}{2} \\\\ -\frac{1}{2}&amp;0&amp;-\frac{1}{2}&amp;0 \\\\ 0&amp;-\frac{1}{2}&amp;0&amp;-\frac{1}{2} \\\\ -\frac{1}{2}&amp;0&amp;-\frac{1}{2}&amp;0\end{bmatrix}\]</span></p>
<p>Eigenvalues of <span class="math inline">\(\tilde{\mathbf{L}}\)</span>: <span class="math inline">\(\frac{2}{\lambda_{\max}}\lambda_k - 1 = \frac{2}{4}\{0,2,2,4\} - 1 = \{-1, 0, 0, 1\}\)</span> — confirmed in <span class="math inline">\([-1,1]\)</span>. ✓</p>
<p><em>EXPLANATION</em></p>
<p><span class="math inline">\(\mathbf{L}\)</span> has eigenvalues <span class="math inline">\(\{0, 2, 2, 4\}\)</span> on <span class="math inline">\(C_4\)</span> (from Step 4). The normalized Laplacian is:</p>
<p><span class="math display">\[\tilde{\mathbf{L}} = \frac{2}{\lambda_{\max}}\mathbf{L} - \mathbf{I}\]</span></p>
<p>When a matrix is linearly transformed, its eigenvalues undergo the <strong>same transformation</strong>. So if <span class="math inline">\(\lambda_k\)</span> is an eigenvalue of <span class="math inline">\(\mathbf{L}\)</span>, then <span class="math inline">\(\frac{2}{\lambda_{\max}}\lambda_k - 1\)</span> is the corresponding eigenvalue of <span class="math inline">\(\tilde{\mathbf{L}}\)</span>.</p>
<p>Applying it elementwise to <span class="math inline">\(\{0, 2, 2, 4\}\)</span> with <span class="math inline">\(\lambda_{\max} = 4\)</span>:</p>
<p><span class="math display">\[0 \to \frac{2}{4}(0) - 1 = -1\]</span> <span class="math display">\[2 \to \frac{2}{4}(2) - 1 = 0\]</span> <span class="math display">\[2 \to \frac{2}{4}(2) - 1 = 0\]</span> <span class="math display">\[4 \to \frac{2}{4}(4) - 1 = 1\]</span></p>
<p>Result: <span class="math inline">\(\{-1, 0, 0, 1\} \subset [-1, 1]\)</span> ✓</p>
<p>The rescaling is necessary because the Chebyshev recurrence <span class="math inline">\(T_k(x) = 2x\,T_{k-1}(x) - T_{k-2}(x)\)</span> is only numerically stable when <span class="math inline">\(x \in [-1,1]\)</span>. Outside that range the polynomials grow without bound — the recurrence diverges.</p>
<p><br></p>
<p><strong><code>laplacian_matvec</code> — sparse <span class="math inline">\(\tilde{\mathbf{L}}\mathbf{v}\)</span></strong></p>
<p>Instead of forming <span class="math inline">\(\tilde{\mathbf{L}}\)</span> densely, the code computes <span class="math inline">\(\tilde{\mathbf{L}}\mathbf{v}\)</span> in three steps:</p>
<p><span class="math display">\[\tilde{\mathbf{L}}\mathbf{v} = \frac{2}{\lambda_{\max}}(\mathbf{D} - \mathbf{A})\mathbf{v} - \mathbf{v} = \frac{2}{\lambda_{\max}}(\mathbf{D}\mathbf{v} - \mathbf{A}\mathbf{v}) - \mathbf{v}\]</span></p>
<p>On <span class="math inline">\(C_4\)</span> with signal <span class="math inline">\(\mathbf{v} = [2,1,1,1]^\top\)</span> and <span class="math inline">\(\lambda_{\max}=4\)</span>:</p>
<p><strong><span class="math inline">\(\mathbf{A}\mathbf{v}\)</span></strong> via <code>scatter_add_</code> — <strong>for each edge <span class="math inline">\((i\to j)\)</span>, add <span class="math inline">\(v_i\)</span> to position <span class="math inline">\(j\)</span>:</strong></p>
<p><span class="math display">\[(\mathbf{A}\mathbf{v})_0 = v_1 + v_3 = 1+1 = 2\]</span> <span class="math display">\[(\mathbf{A}\mathbf{v})_1 = v_0 + v_2 = 2+1 = 3\]</span> <span class="math display">\[(\mathbf{A}\mathbf{v})_2 = v_1 + v_3 = 1+1 = 2\]</span> <span class="math display">\[(\mathbf{A}\mathbf{v})_3 = v_0 + v_2 = 2+1 = 3\]</span></p>
<p><strong><span class="math inline">\(\mathbf{D}\mathbf{v}\)</span></strong> — multiply each node’s feature by its degree (all degrees = 2):</p>
<p><span class="math display">\[\mathbf{D}\mathbf{v} = [4, 2, 2, 2]^\top\]</span></p>
<p><strong><span class="math inline">\(\mathbf{L}\mathbf{v} = \mathbf{D}\mathbf{v} - \mathbf{A}\mathbf{v}\)</span>:</strong></p>
<p><span class="math display">\[\mathbf{L}\mathbf{v} = [4-2,\ 2-3,\ 2-2,\ 2-3]^\top = [2,\ -1,\ 0,\ -1]^\top\]</span></p>
<p><strong><span class="math inline">\(\tilde{\mathbf{L}}\mathbf{v} = \frac{2}{4}\mathbf{L}\mathbf{v} - \mathbf{v}\)</span>:</strong></p>
<p><span class="math display">\[\tilde{\mathbf{L}}\mathbf{v} = \frac{1}{2}[2,-1,0,-1]^\top - [2,1,1,1]^\top = [1,-0.5,0,-0.5]^\top - [2,1,1,1]^\top = [-1,\ -1.5,\ -1,\ -1.5]^\top\]</span></p>
<p><br></p>
<p><strong>Chebyshev recurrence — <span class="math inline">\(K=3\)</span></strong></p>
<p><span class="math inline">\(K = 3\)</span> <em>A polynomial of order 3 allows each layer to capture information from the 2nd-order neighborhood (2-hop distance). With 3 layers, the effective receptive field is roughly 6 hops.</em></p>
<p><span class="math display">\[T_0(\tilde{\mathbf{L}})\mathbf{x} = \mathbf{x}\]</span> <span class="math display">\[T_1(\tilde{\mathbf{L}})\mathbf{x} = \tilde{\mathbf{L}}\mathbf{x}\]</span> <span class="math display">\[T_2(\tilde{\mathbf{L}})\mathbf{x} = 2\tilde{\mathbf{L}}(T_1) - T_0\]</span></p>
<p>On <span class="math inline">\(C_4\)</span> with <span class="math inline">\(\mathbf{x} = [2,1,1,1]^\top\)</span>:</p>
<p><span class="math display">\[T_0 = [2,\ 1,\ 1,\ 1]^\top\]</span> <span class="math display">\[T_1 = \tilde{\mathbf{L}}\mathbf{x} = [-1,\ -1.5,\ -1,\ -1.5]^\top\]</span></p>
<p><br></p>
<p>NOW, for <span class="math inline">\(T_2\)</span>, apply <span class="math inline">\(\tilde{\mathbf{L}}\)</span> to <span class="math inline">\(T_1 = [-1,-1.5,-1,-1.5]^\top\)</span>:</p>
<p><em>Simple pattern: directly connected nodes are selected for the chosen node.</em></p>
<p><strong><span class="math inline">\(\mathbf{A}T_1\)</span>:</strong> <span class="math display">\[(\mathbf{A}T_1)_0 = T_1[1]+T_1[3] = -1.5+(-1.5) = -3\]</span> <span class="math display">\[(\mathbf{A}T_1)_1 = T_1[0]+T_1[2] = -1+(-1) = -2\]</span> <span class="math display">\[(\mathbf{A}T_1)_2 = T_1[1]+T_1[3] = -3\]</span> <span class="math display">\[(\mathbf{A}T_1)_3 = T_1[0]+T_1[2] = -2\]</span></p>
<p><strong><span class="math inline">\(\mathbf{D}T_1\)</span></strong> (degrees all 2) (i.e., 2 <span class="math inline">\(\cdot\)</span> <span class="math inline">\(T_1\)</span>): <span class="math display">\[[{-2},\ {-3},\ {-2},\ {-3}]^\top\]</span></p>
<p><strong><span class="math inline">\(\mathbf{L}T_1 = \mathbf{D}T_1 - \mathbf{A}T_1\)</span>:</strong> <span class="math display">\[[-2-(-3),\ -3-(-2),\ -2-(-3),\ -3-(-2)]^\top = [1,\ -1,\ 1,\ -1]^\top\]</span></p>
<p><strong><span class="math inline">\(\tilde{\mathbf{L}}T_1 = \frac{1}{2}\mathbf{L}T_1 - T_1\)</span>:</strong> <span class="math display">\[[0.5,-0.5,0.5,-0.5]^\top - [-1,-1.5,-1,-1.5]^\top = [1.5,\ 1,\ 1.5,\ 1]^\top\]</span></p>
<p><strong><span class="math inline">\(T_2 = 2\tilde{\mathbf{L}}T_1 - T_0\)</span>:</strong> <span class="math display">\[2[1.5,1,1.5,1]^\top - [2,1,1,1]^\top = [3,2,3,2]^\top - [2,1,1,1]^\top = [1,\ 1,\ 2,\ 1]^\top\]</span></p>
<p><br></p>
<p><strong>Final concatenation and linear layer</strong></p>
<p><span class="math display">\[\text{out} = [T_0 \| T_1 \| T_2] = \begin{bmatrix}2&amp;-1&amp;1 \\\\ 1&amp;-1.5&amp;1 \\\\ 1&amp;-1&amp;2 \\\\ 1&amp;-1.5&amp;1\end{bmatrix} \in \mathbb{R}^{4\times 3}\]</span></p>
<p>Then <code>self.linear</code> applies <span class="math inline">\(\mathbf{W} \in \mathbb{R}^{3 \cdot \text{in\_dim} \times \text{out\_dim}}\)</span> to map each row to the output dimension.</p>
<p><br></p>
<p><strong>Key insight: locality via polynomial order</strong></p>
<p><span class="math inline">\(T_k(\tilde{\mathbf{L}})\mathbf{x}\)</span> at node <span class="math inline">\(i\)</span> depends on nodes within <span class="math inline">\(k\)</span> hops — the polynomial order <strong>directly controls the receptive field</strong>, exactly like MPNN layers. ChebNet with <span class="math inline">\(K=3\)</span> sees the same neighborhood as 3 MPNN rounds, but via spectral filtering rather than spatial aggregation.</p>
<hr>
</section>
<section id="step-12-full-chebnet-model" class="level2">
<h2 class="anchored" data-anchor-id="step-12-full-chebnet-model">Step 12: Full ChebNet Model</h2>
<p>We now assemble ChebConv layers (Step 11) into a complete model with the <strong>same interface as MPNN</strong> (Step 8) — enabling a fair comparison later. The architecture is structurally identical to MPNN with one critical difference: <strong>edge features are ignored</strong>.</p>
<p><strong>25. Why ChebNet ignores edge_attr?</strong></p>
<p>ChebNet filters operate on <span class="math inline">\(\tilde{\mathbf{L}}\)</span>, which encodes only <strong>topology</strong> — who is connected to whom. <span class="math inline">\(\tilde{\mathbf{L}}\)</span> has no slot for edge weights or bond types. The <code>edge_attr</code> argument is kept purely for interface consistency with MPNN.</p>
<p>This is a fundamental limitation relative to MPNN: two bonds of different types (single vs double) produce identical <span class="math inline">\(\tilde{\mathbf{L}}\)</span>, so ChebNet cannot distinguish them spectrally.</p>
<p><br></p>
<p><strong>Architecture comparison</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>MPNN</th>
<th>ChebNet</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input projection</td>
<td><span class="math inline">\(\mathbf{X}\mathbf{W}_{\text{in}}\)</span></td>
<td><span class="math inline">\(\mathbf{X}\mathbf{W}_{\text{in}}\)</span></td>
</tr>
<tr class="even">
<td>Core layer</td>
<td>MPNNLayer (spatial)</td>
<td>ChebConv (spectral)</td>
</tr>
<tr class="odd">
<td>Edge features</td>
<td>✓ used</td>
<td>✗ ignored</td>
</tr>
<tr class="even">
<td>Readout</td>
<td>mean pool → MLP</td>
<td>mean pool → MLP</td>
</tr>
<tr class="odd">
<td>Output</td>
<td>scalar <span class="math inline">\(\hat{U}_0\)</span></td>
<td>scalar <span class="math inline">\(\hat{U}_0\)</span></td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Data flow on <span class="math inline">\(C_4\)</span></strong></p>
<p><span class="math display">\[[4,1] \xrightarrow{\text{proj}} [4,64] \xrightarrow{\times 3\ \text{ChebConv}} [4,64] \xrightarrow{\text{mean pool}} [1,64] \xrightarrow{\text{MLP}} [1,1]\]</span></p>
<p>Each ChebConv applies the <span class="math inline">\(K=3\)</span> recurrence from Step 11, expanding receptive field by one hop per layer — after 3 layers, every node on <span class="math inline">\(C_4\)</span> has seen the full graph.</p>
<p><br></p>
<p><strong>The Expressiveness Cost</strong></p>
<p>MPNN computes messages using <span class="math inline">\([\mathbf{h}_i \| \mathbf{h}_j \| \mathbf{e}_{ij}]\)</span> — the edge feature <span class="math inline">\(\mathbf{e}_{ij}\)</span> is directly in the message. ChebConv operates entirely through <span class="math inline">\(\tilde{\mathbf{L}}\mathbf{x}\)</span> — matrix-vector products that never touch <span class="math inline">\(\mathbf{e}_{ij}\)</span>.</p>
<p>On QM9 concretely: a single bond and double bond between atoms <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> produce <strong>identical rows</strong> in <span class="math inline">\(\tilde{\mathbf{L}}\)</span>. ChebNet sees the same graph either way. MPNN doesn’t — it reads the bond type directly from <code>edge_attr</code>.</p>
<p>This is not a fixable training problem. It is a <strong>structural</strong> gap — the architecture physically cannot represent the distinction.</p>
<hr>
</section>
<section id="step-13-chebnet-permutation-invariance-why-lambda_max-must-be-precomputed" class="level2">
<h2 class="anchored" data-anchor-id="step-13-chebnet-permutation-invariance-why-lambda_max-must-be-precomputed">Step 13: ChebNet Permutation Invariance + Why <span class="math inline">\(\lambda_{\max}\)</span> must be precomputed</h2>
<p>Two things:</p>
<ol type="1">
<li>We verify ChebNet is permutation invariant like MPNN, and</li>
<li>We introduce a subtle but important point — <span class="math inline">\(\lambda_{\max}\)</span> must be computed <strong>once from the original graph</strong> and passed explicitly.</li>
</ol>
<p><strong>26. Why <span class="math inline">\(\lambda_{\max}\)</span> must be fixed across permutations?</strong></p>
<p>From Step 11, the normalization is:</p>
<p><span class="math display">\[\tilde{\mathbf{L}} = \frac{2}{\lambda_{\max}}\mathbf{L} - \mathbf{I}\]</span></p>
<p><span class="math inline">\(\lambda_{\max}\)</span> is the largest eigenvalue of <span class="math inline">\(\mathbf{L}\)</span>. Crucially, eigenvalues are <strong>invariant under permutation</strong> — they are properties of the graph, not the node labeling:</p>
<p><span class="math display">\[\mathbf{L}_\pi = \mathbf{P}\mathbf{L}\mathbf{P}^\top \implies \text{eigenvalues}(\mathbf{L}_\pi) = \text{eigenvalues}(\mathbf{L})\]</span></p>
<p>On <span class="math inline">\(C_4\)</span>: <span class="math inline">\(\lambda_{\max} = 4\)</span> regardless of how nodes are numbered. If instead <span class="math inline">\(\lambda_{\max}\)</span> were recomputed inside each forward pass from the permuted graph, floating point differences in the eigendecomposition could break invariance. Passing it explicitly eliminates this source of variance entirely.</p>
<p><br></p>
<p><strong>27. Why ChebNet’s invariance is guaranteed?</strong></p>
<p>The mean pool argument from Step 10 applies identically here. The additional ingredient is <code>laplacian_matvec</code> — <strong>does it respect permutation?</strong></p>
<p><span class="math display">\[\tilde{\mathbf{L}}_\pi \mathbf{v}_\pi = \mathbf{P}\tilde{\mathbf{L}}\mathbf{P}^\top \mathbf{P}\mathbf{v} = \mathbf{P}\tilde{\mathbf{L}}\mathbf{v}\]</span></p>
<p>The matvec output is <strong>equivariant</strong> — it permutes consistently with the input. After mean pooling, the permutation is washed out, giving an invariant scalar. ✓</p>
<p><br></p>
<p><strong>On <span class="math inline">\(C_4\)</span></strong></p>
<p>From Step 4: <span class="math inline">\(\lambda_{\max} = 4\)</span>. Passed explicitly, the normalization factor <span class="math inline">\(\frac{2}{\lambda_{\max}} = 0.5\)</span> is identical for all 100 permutations — the Chebyshev recurrence produces the same set of node vectors <span class="math inline">\(\{T_k\mathbf{x}\}\)</span>, mean pool sums them identically, and <span class="math inline">\(\hat{U}_0\)</span> is invariant.</p>
<p><br></p>
<p><strong>There are two concrete numerical steps for <span class="math inline">\(C_4\)</span>.</strong></p>
<p>FIRST – Confirm <span class="math inline">\(\lambda_{\max}\)</span> is permutation-invariant</p>
<p>From Step 4, the eigenvalues of <span class="math inline">\(\mathbf{L}\)</span> on <span class="math inline">\(C_4\)</span> are <span class="math inline">\(\{0, 2, 2, 4\}\)</span>, so <span class="math inline">\(\lambda_{\max} = 4\)</span>.</p>
<p>Now apply permutation <span class="math inline">\(\pi = [2,0,3,1]\)</span> from Step 9.</p>
<p>Then, we have:</p>
<p><span class="math display">\[\mathbf{A}_\pi = \begin{bmatrix}0&amp;0&amp;1&amp;1 \\\\ 0&amp;0&amp;1&amp;1 \\\\ 1&amp;1&amp;0&amp;0 \\\\ 1&amp;1&amp;0&amp;0\end{bmatrix}, \quad \mathbf{D}_\pi = \begin{bmatrix}2&amp;0&amp;0&amp;0 \\\\ 0&amp;2&amp;0&amp;0 \\\\ 0&amp;0&amp;2&amp;0 \\\\ 0&amp;0&amp;0&amp;2\end{bmatrix}\]</span></p>
<p><span class="math display">\[\mathbf{L}_\pi = \mathbf{D}_\pi - \mathbf{A}_\pi = \begin{bmatrix}2&amp;0&amp;-1&amp;-1 \\\\ 0&amp;2&amp;-1&amp;-1 \\\\ -1&amp;-1&amp;2&amp;0 \\\\ -1&amp;-1&amp;0&amp;2\end{bmatrix}\]</span></p>
<p>Its row sums are all zero ✓, degrees all 2 ✓ — same structure as <span class="math inline">\(\mathbf{L}\)</span>, just relabeled. Eigenvalues are still <span class="math inline">\(\{0,2,2,4\}\)</span>, so <span class="math inline">\(\lambda_{\max} = 4\)</span> unchanged. ✓</p>
<p><br></p>
<p>SECOND – Confirm <span class="math inline">\(\tilde{\mathbf{L}}_\pi\)</span> produces the same normalization</p>
<p><span class="math display">\[\tilde{\mathbf{L}}_\pi = \frac{2}{4}\mathbf{L}_\pi - \mathbf{I} = \begin{bmatrix}0&amp;0&amp;-\frac{1}{2}&amp;-\frac{1}{2} \\\\ 0&amp;0&amp;-\frac{1}{2}&amp;-\frac{1}{2} \\\\ -\frac{1}{2}&amp;-\frac{1}{2}&amp;0&amp;0 \\\\ -\frac{1}{2}&amp;-\frac{1}{2}&amp;0&amp;0\end{bmatrix}\]</span></p>
<p>Eigenvalues: <span class="math inline">\(\{-1, 0, 0, 1\}\)</span> — identical to <span class="math inline">\(\tilde{\mathbf{L}}\)</span> from Step 11. ✓</p>
<p>The normalization factor <span class="math inline">\(\frac{2}{\lambda_{\max}} = 0.5\)</span> is the same for both orderings, so the Chebyshev recurrence operates in the same spectral range regardless of permutation.</p>
<hr>
</section>
<section id="step-14-chebyshev-filter-locality-delta-signal-propagation" class="level2">
<h2 class="anchored" data-anchor-id="step-14-chebyshev-filter-locality-delta-signal-propagation">Step 14: Chebyshev Filter Locality: Delta Signal Propagation</h2>
<p>We apply the Chebyshev recurrence to a <strong>delta signal</strong> <span class="math inline">\(\delta_0\)</span> — a signal that is 1 at node 0 and 0 everywhere else — and visualizes how it spreads after each polynomial order <span class="math inline">\(k\)</span>.</p>
<p><strong>The delta signal on <span class="math inline">\(C_4\)</span></strong></p>
<p><span class="math display">\[\delta_0 = [1, 0, 0, 0]^\top\]</span></p>
<p><br></p>
<p><strong><span class="math inline">\(T_0\)</span>: identity</strong></p>
<p><span class="math display">\[T_0 = \delta_0 = [1, 0, 0, 0]^\top\]</span></p>
<p>Signal sits entirely at node 0. Zero hops taken.</p>
<p><br></p>
<p><strong><span class="math inline">\(T_1 = \tilde{\mathbf{L}}\delta_0\)</span></strong></p>
<p>From Step 11 <code>laplacian_matvec</code>, with <span class="math inline">\(\lambda_{\max}=4\)</span>:</p>
<p><strong><span class="math inline">\(\mathbf{A}\delta_0\)</span>:</strong> scatter node 0’s value to its neighbors <span class="math inline">\(\{1, 3\}\)</span>: <span class="math display">\[\mathbf{A}\delta_0 = [0, 1, 0, 1]^\top\]</span></p>
<p><strong><span class="math inline">\(\mathbf{D}\delta_0\)</span>:</strong> degree of node 0 is 2: <span class="math display">\[\mathbf{D}\delta_0 = [2, 0, 0, 0]^\top\]</span></p>
<p><strong><span class="math inline">\(\mathbf{L}\delta_0\)</span>:</strong> <span class="math inline">\(\mathbf{D}\delta_0\)</span> - <span class="math inline">\(\mathbf{A}\delta_0\)</span></p>
<p><span class="math display">\[[2-0,\ 0-1,\ 0-0,\ 0-1]^\top = [2, -1, 0, -1]^\top\]</span></p>
<p><strong><span class="math inline">\(T_1 = \tilde{\mathbf{L}}\delta_0 = \frac{1}{2}\mathbf{L}\delta_0 - \delta_0\)</span>:</strong> <span class="math display">\[[1, -0.5, 0, -0.5]^\top - [1, 0, 0, 0]^\top = [0, -0.5, 0, -0.5]^\top\]</span></p>
<p>Signal has spread exactly <strong>1 hop</strong> — nonzero only at nodes 1 and 3 (direct neighbors of node 0). ✓</p>
<p><br></p>
<p><strong><span class="math inline">\(T_2 = 2\tilde{\mathbf{L}}T_1 - T_0\)</span></strong></p>
<p>Apply <code>laplacian_matvec</code> to <span class="math inline">\(T_1 = [0, -0.5, 0, -0.5]^\top\)</span>:</p>
<p><strong><span class="math inline">\(\mathbf{A}T_1\)</span>:</strong> <span class="math display">\[(\mathbf{A}T_1)_0 = T_1[1]+T_1[3] = -0.5+(-0.5) = -1\]</span> <span class="math display">\[(\mathbf{A}T_1)_1 = T_1[0]+T_1[2] = 0+0 = 0\]</span> <span class="math display">\[(\mathbf{A}T_1)_2 = T_1[1]+T_1[3] = -1\]</span> <span class="math display">\[(\mathbf{A}T_1)_3 = T_1[0]+T_1[2] = 0\]</span></p>
<p><strong><span class="math inline">\(\mathbf{D}T_1\)</span> = (2 <span class="math inline">\(\cdot\)</span> <span class="math inline">\(T_1\)</span>):</strong> <span class="math display">\[[0, -1, 0, -1]^\top\]</span></p>
<p><strong><span class="math inline">\(\mathbf{L}T_1\)</span>:</strong> <span class="math display">\[[0-(-1),\ -1-0,\ 0-(-1),\ -1-0]^\top = [1, -1, 1, -1]^\top\]</span></p>
<p><strong><span class="math inline">\(\tilde{\mathbf{L}}T_1 = \frac{1}{2}\mathbf{L}T_1 - T_1\)</span>:</strong> <span class="math display">\[[0.5, -0.5, 0.5, -0.5]^\top - [0, -0.5, 0, -0.5]^\top = [0.5, 0, 0.5, 0]^\top\]</span></p>
<p><strong><span class="math inline">\(T_2 = 2[0.5, 0, 0.5, 0]^\top - [1, 0, 0, 0]^\top\)</span>:</strong> <span class="math display">\[[1, 0, 1, 0]^\top - [1, 0, 0, 0]^\top = [0, 0, 1, 0]^\top\]</span></p>
<p>Signal has spread exactly <strong>2 hops</strong> — nonzero only at node 2, which is the only node at graph distance 2 from node 0. ✓</p>
<p><br></p>
<p><strong><span class="math inline">\(T_3 = 2\tilde{\mathbf{L}}T_2 - T_1\)</span></strong></p>
<p>Apply <code>laplacian_matvec</code> to <span class="math inline">\(T_2 = [0, 0, 1, 0]^\top\)</span>:</p>
<p><strong><span class="math inline">\(\mathbf{A}T_2\)</span>:</strong> <span class="math display">\[(\mathbf{A}T_2)_0 = T_2[1]+T_2[3] = 0\]</span> <span class="math display">\[(\mathbf{A}T_2)_1 = T_2[0]+T_2[2] = 1\]</span> <span class="math display">\[(\mathbf{A}T_2)_2 = T_2[1]+T_2[3] = 0\]</span> <span class="math display">\[(\mathbf{A}T_2)_3 = T_2[0]+T_2[2] = 1\]</span></p>
<p><strong><span class="math inline">\(\mathbf{D}T_2\)</span>:</strong> <span class="math display">\[[0, 0, 2, 0]^\top\]</span></p>
<p><strong><span class="math inline">\(\mathbf{L}T_2\)</span>:</strong> <span class="math display">\[[0-0,\ 0-1,\ 2-0,\ 0-1]^\top = [0, -1, 2, -1]^\top\]</span></p>
<p><strong><span class="math inline">\(\tilde{\mathbf{L}}T_2 = \frac{1}{2}\mathbf{L}T_2 - T_2\)</span>:</strong> <span class="math display">\[[0, -0.5, 1, -0.5]^\top - [0, 0, 1, 0]^\top = [0, -0.5, 0, -0.5]^\top\]</span></p>
<p><strong><span class="math inline">\(T_3 = 2[0, -0.5, 0, -0.5]^\top - [0, -0.5, 0, -0.5]^\top\)</span>:</strong> <span class="math display">\[[0, -1, 0, -1]^\top - [0, -0.5, 0, -0.5]^\top = [0, -0.5, 0, -0.5]^\top\]</span></p>
<p><br></p>
<p><strong>Summary Table</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(k\)</span></th>
<th><span class="math inline">\(T_k(\tilde{\mathbf{L}})\delta_0\)</span></th>
<th>Nonzero nodes</th>
<th>Hops reached</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\([1, 0, 0, 0]^\top\)</span></td>
<td><span class="math inline">\(\{0\}\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\([0, -0.5, 0, -0.5]^\top\)</span></td>
<td><span class="math inline">\(\{1, 3\}\)</span></td>
<td>1</td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\([0, 0, 1, 0]^\top\)</span></td>
<td><span class="math inline">\(\{2\}\)</span></td>
<td>2</td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\([0, -0.5, 0, -0.5]^\top\)</span></td>
<td><span class="math inline">\(\{1, 3\}\)</span></td>
<td>oscillates</td>
</tr>
</tbody>
</table>
<p><strong>The locality guarantee holds exactly</strong>: <span class="math inline">\(T_k\)</span> is nonzero only within <span class="math inline">\(k\)</span> hops of the source. At <span class="math inline">\(k=3\)</span>, the signal bounces back — this is the <strong>oscillatory nature of Chebyshev polynomials</strong> reflecting the graph’s spectral structure.</p>
<hr>
</section>
<section id="step-15-wl-color-refinement-on-c_4" class="level2">
<h2 class="anchored" data-anchor-id="step-15-wl-color-refinement-on-c_4">Step 15: WL Color Refinement on <span class="math inline">\(C_4\)</span></h2>
<p>We now implement the <strong>1-Weisfeiler-Lehman (1-WL) color refinement</strong> algorithm — the theoretical backbone of message passing expressiveness. Each round, a node’s color is updated by hashing its current color together with its neighbors’ colors (sorted for permutation invariance).</p>
<p><span class="math display">\[\text{color}_i^{(t+1)} = \text{hash}\!\left(\text{color}_i^{(t)},\ \text{sort}\!\left\{\text{color}_j^{(t)} : j \in \mathcal{N}(i)\right\}\right)\]</span></p>
<p><br></p>
<p><strong>Initialization</strong></p>
<p>No labels provided <span class="math inline">\(\to\)</span> all nodes get color 1:</p>
<p><span class="math display">\[\text{colors}^{(0)} = \{0:1,\ 1:1,\ 2:1,\ 3:1\}\]</span></p>
<p><br></p>
<p><strong>Round 1</strong></p>
<p>For each node, form signature <span class="math inline">\((\text{color}_i,\ \text{sorted neighbor colors})\)</span>, then assign a hash integer.</p>
<p>Adjacency of <span class="math inline">\(C_4\)</span>: <span class="math inline">\(\mathcal{N}(0)=\{1,3\},\ \mathcal{N}(1)=\{0,2\},\ \mathcal{N}(2)=\{1,3\},\ \mathcal{N}(3)=\{0,2\}\)</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th><span class="math inline">\(\text{color}_i^{(0)}\)</span></th>
<th>Neighbor colors</th>
<th>Signature</th>
<th>Hash</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1</td>
<td><span class="math inline">\(\{1,1\}\)</span></td>
<td><span class="math inline">\((1,(1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td>1</td>
<td><span class="math inline">\(\{1,1\}\)</span></td>
<td><span class="math inline">\((1,(1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td>2</td>
<td>1</td>
<td><span class="math inline">\(\{1,1\}\)</span></td>
<td><span class="math inline">\((1,(1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>3</td>
<td>1</td>
<td><span class="math inline">\(\{1,1\}\)</span></td>
<td><span class="math inline">\((1,(1,1))\)</span></td>
<td>0</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{colors}^{(1)} = \{0:0,\ 1:0,\ 2:0,\ 3:0\}\]</span></p>
<p>All nodes still identical — uniform initialization on a regular graph produces uniform colors.</p>
<p><br></p>
<p><strong>Round 2</strong></p>
<p>All colors are 0, all degrees are 2, all neighbor colors are <span class="math inline">\(\{0,0\}\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th>Signature</th>
<th>Hash</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\((0,(0,0))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\((0,(0,0))\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\((0,(0,0))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\((0,(0,0))\)</span></td>
<td>0</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{colors}^{(2)} = \{0:0,\ 1:0,\ 2:0,\ 3:0\}\]</span></p>
<p>The actual computation is just:</p>
<ul>
<li>Every node has color 0 (from Round 1)</li>
<li>Every node’s neighbors also have color 0</li>
<li>So every node forms signature (0, (0,0)) — identical across all nodes</li>
</ul>
<p><br></p>
<p><strong>Round 3</strong></p>
<p>Identical to Round 2 — colors have <strong>stabilized</strong>:</p>
<p><span class="math display">\[\text{colors}^{(3)} = \{0:0,\ 1:0,\ 2:0,\ 3:0\}\]</span></p>
<p><br></p>
<p><strong>28. What this result demonstrates?</strong></p>
<p>1-WL <strong>cannot distinguish any node in <span class="math inline">\(C_4\)</span></strong> from any other when initialized uniformly. Every node sees two neighbors of the same color at every round — the signatures are always identical.</p>
<p>This directly connects to Step 7’s observation: node 0 receives identical messages from nodes 1 and 3 because <strong>those nodes are WL-indistinguishable</strong>. Message passing is exactly 1-WL, so it inherits this blindness.</p>
<p><span class="math display">\[\mathbf{M}_0 = \mathbf{m}_{10} + \mathbf{m}_{30}\]</span></p>
<p>With <span class="math inline">\(h_1 = h_3\)</span> (identical features), <span class="math inline">\(\mathbf{m}_{10} = \mathbf{m}_{30}\)</span> — exactly the same failure mode as WL producing identical signatures. <strong>MPNN and WL fail on precisely the same graphs.</strong></p>
<p>The fix — injecting distinct initial features (like QM9’s atom types) — is precisely what breaks this symmetry and allows the network to differentiate nodes.</p>
<hr>
</section>
<section id="step-16-wl-indistinguishable-graphs-k_33-vs-prism" class="level2">
<h2 class="anchored" data-anchor-id="step-16-wl-indistinguishable-graphs-k_33-vs-prism">Step 16: WL-Indistinguishable Graphs: <span class="math inline">\(K_{3,3}\)</span> vs Prism</h2>
<p>We construct a <strong>concrete counterexample</strong> to 1-WL’s discriminative power: two non-isomorphic graphs that are provably identical under all rounds of WL refinement.</p>
<p><strong>The two graphs</strong></p>
<p><strong><span class="math inline">\(K_{3,3}\)</span></strong> — complete bipartite: every node in <span class="math inline">\(\{0,1,2\}\)</span> connects to every node in <span class="math inline">\(\{3,4,5\}\)</span>.</p>
<p><strong>Prism</strong> — triangular prism: two triangles <span class="math inline">\((0\text{-}1\text{-}2)\)</span> and <span class="math inline">\((3\text{-}4\text{-}5)\)</span> joined by rungs <span class="math inline">\((0\text{-}3),(1\text{-}4),(2\text{-}5)\)</span>.</p>
<p>Both are <strong>3-regular</strong> — every node has exactly 3 neighbors.</p>
<p><br></p>
<p><strong>WL on <span class="math inline">\(K_{3,3}\)</span></strong></p>
<p><strong>Round 0</strong></p>
<p>Uniform initialization:</p>
<p><span class="math display">\[\text{colors}^{(0)} = \{0:1,\ 1:1,\ 2:1,\ 3:1,\ 4:1,\ 5:1\}\]</span></p>
<p><br></p>
<p><strong>Round 1 — <span class="math inline">\(K_{3,3}\)</span></strong></p>
<p>Every node has 3 neighbors, all color 1:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th>Signature</th>
<th>Hash</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td>4</td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>5</td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{colors}^{(1)}_{K_{3,3}} = \{0:0,\ 1:0,\ 2:0,\ 3:0,\ 4:0,\ 5:0\}\]</span></p>
<p><br></p>
<p><strong>Round 1 — Prism</strong></p>
<p>Every node also has 3 neighbors, all color 1:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th>Neighbors</th>
<th>Signature</th>
<th>Hash</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><span class="math inline">\(\{1,2,3\}\)</span></td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\(\{0,2,4\}\)</span></td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(\{0,1,5\}\)</span></td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>3</td>
<td><span class="math inline">\(\{0,4,5\}\)</span></td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td>4</td>
<td><span class="math inline">\(\{1,3,5\}\)</span></td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td>5</td>
<td><span class="math inline">\(\{2,3,4\}\)</span></td>
<td><span class="math inline">\((1,(1,1,1))\)</span></td>
<td>0</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{colors}^{(1)}_{\text{prism}} = \{0:0,\ 1:0,\ 2:0,\ 3:0,\ 4:0,\ 5:0\}\]</span></p>
<p><br></p>
<p><strong>Rounds 2 &amp; 3</strong></p>
<p>Both graphs: all colors 0, all nodes have 3 neighbors of color 0 → signature <span class="math inline">\((0,(0,0,0))\)</span> → hash 0 for everyone. Colors stabilize identically on both graphs for all subsequent rounds.</p>
<p><span class="math display">\[\text{colors}^{(t)}_{K_{3,3}} = \text{colors}^{(t)}_{\text{prism}} \quad \forall\, t \geq 1\]</span></p>
<p><br></p>
<p><em>THE PUNCHLINE</em></p>
<p>1-WL assigns <strong>identical color histograms</strong> to both graphs at every round, yet they are structurally different — <span class="math inline">\(K_{3,3}\)</span> has no triangles, the prism has two. Any GNN that is bounded by 1-WL expressiveness (i.e.&nbsp;standard MPNN and ChebNet from this project) <strong>cannot distinguish these two molecules</strong> and would predict the same <span class="math inline">\(U_0\)</span> for both, regardless of depth.</p>
<p><br></p>
<p><strong>29. Given that both graphs fool 1-WL, think of a simple structural property (computable from the graph) that would differentiate them?</strong></p>
<p><strong>Triangle count.</strong></p>
<p><span class="math inline">\(K_{3,3}\)</span> contains zero triangles — it’s bipartite, so no odd cycles exist. The prism contains exactly two triangles (the two faces <span class="math inline">\(0\text{-}1\text{-}2\)</span> and <span class="math inline">\(3\text{-}4\text{-}5\)</span>).</p>
<p>Triangle count is computable as <span class="math inline">\(\frac{1}{6}\text{tr}(\mathbf{A}^3)\)</span> — a property detectable by 3-node subgraph counting but invisible to 1-WL, which only aggregates 1-hop neighborhood color histograms and therefore cannot detect closed loops of any length.</p>
<p><br></p>
<p><strong>Triangle Detection via <span class="math inline">\(\mathbf{A}^3\)</span></strong></p>
<p>The key mathematical operation:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>A3 <span class="op">=</span> A <span class="op">@</span> A <span class="op">@</span> A</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="cf">return</span> A3.diagonal().<span class="bu">any</span>().item()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="math inline">\((\mathbf{A}^3)_{ii}\)</span> counts the number of closed walks of length 3 starting and ending at node <span class="math inline">\(i\)</span> — exactly the number of triangles involving node <span class="math inline">\(i\)</span>.</p>
<p><span class="math display">\[(\mathbf{A}^3)_{ii} = \sum_{j,k} A_{ij}A_{jk}A_{ki}\]</span></p>
<p>A nonzero diagonal entry means node <span class="math inline">\(i\)</span> participates in at least one triangle.</p>
<p><br></p>
<p><strong>On <span class="math inline">\(K_{3,3}\)</span>:</strong></p>
<p><span class="math display">\[\mathbf{A}_{K_{3,3}} = \begin{bmatrix} 0&amp;0&amp;0&amp;1&amp;1&amp;1 \\\\ 0&amp;0&amp;0&amp;1&amp;1&amp;1 \\\\ 0&amp;0&amp;0&amp;1&amp;1&amp;1 \\\\ 1&amp;1&amp;1&amp;0&amp;0&amp;0 \\\\ 1&amp;1&amp;1&amp;0&amp;0&amp;0 \\\\ 1&amp;1&amp;1&amp;0&amp;0&amp;0 \end{bmatrix}\]</span></p>
<p><span class="math inline">\((\mathbf{A}^2)_{00} = \sum_k A_{0k}A_{k0} = A_{03}^2+A_{04}^2+A_{05}^2 = 3\)</span></p>
<p><span class="math inline">\((\mathbf{A}^3)_{00} = \sum_j A_{0j}(\mathbf{A}^2)_{j0}\)</span>.</p>
<p>Node 0 only connects to <span class="math inline">\(\{3,4,5\}\)</span>, and,</p>
<p><span class="math inline">\((\mathbf{A}^2)_{30} = \sum_k A_{3k}A_{k0} = A_{30}A_{00}+A_{31}A_{10}+A_{32}A_{20} = 0\)</span> since <span class="math inline">\(A_{00}=A_{10}=A_{20}=0\)</span>.</p>
<p><span class="math display">\[(\mathbf{A}^3)_{00} = 0 \implies \text{no triangles}\]</span></p>
<p><br></p>
<p><strong>On the Prism</strong></p>
<p>Check node 0 with neighbors <span class="math inline">\(\{1,2,3\}\)</span>:</p>
<p><span class="math display">\[(\mathbf{A}^3)_{00} = \sum_{j,k}A_{0j}A_{jk}A_{k0}\]</span></p>
<p>Only paths that return to 0 contribute. One such path: <span class="math inline">\(0\to1\to2\to0\)</span>:</p>
<p><span class="math display">\[A_{01}A_{12}A_{20} = 1\cdot1\cdot1 = 1\]</span></p>
<p>Triangle <span class="math inline">\(0\text{-}1\text{-}2\)</span> confirmed — diagonal is nonzero.</p>
<p><br></p>
<p><em>TYING IT BACK TO WL</em></p>
<p>Step 15 showed WL assigns identical histograms to both graphs. Yet <span class="math inline">\(\text{tr}(\mathbf{A}^3) = 0\)</span> for <span class="math inline">\(K_{3,3}\)</span> and <span class="math inline">\(&gt; 0\)</span> for the prism — a quantity <strong>invisible to 1-WL</strong> but trivially computable from <span class="math inline">\(\mathbf{A}\)</span>. This is precisely why higher-order GNNs (which explicitly count subgraph patterns) strictly dominate 1-WL in expressive power.</p>
<p><br></p>
<p><strong>MPNN Blindness to <span class="math inline">\(K_{3,3}\)</span> vs Prism</strong></p>
<p>An MPNN with uniform input features produces identical outputs for two structurally different graphs, confirming it is bounded by 1-WL.</p>
<p><br></p>
<p><strong>30. Why uniform features are essential here?</strong></p>
<p>If atom types differed, the network could trivially distinguish graphs via input features alone — that would not test WL expressiveness. Setting <span class="math inline">\(\mathbf{X} = \mathbf{1}_{6\times11}\)</span> replicates the uniform initialization of Step 15, isolating <strong>topology</strong> as the only distinguishing factor.</p>
<p><br></p>
<p><strong>The mathematical argument</strong></p>
<p>From Step 15, WL with uniform initialization produces identical color histograms for both graphs at every round. Since MPNN exactly simulates 1-WL (each message passing round = one WL refinement step), the node states after <span class="math inline">\(L\)</span> layers are identical:</p>
<p><span class="math display">\[\mathbf{h}_i^{(L)}\big|_{K_{3,3}} = \mathbf{h}_i^{(L)}\big|_{\text{prism}} \quad \forall\, i\]</span></p>
<p>Mean pooling over identical node states gives identical graph embeddings:</p>
<p><span class="math display">\[\mathbf{g}_{K_{3,3}} = \mathbf{g}_{\text{prism}}\]</span></p>
<p>Therefore <span class="math inline">\(\hat{y}_{K_{3,3}} = \hat{y}_{\text{prism}}\)</span> exactly — difference should be <span class="math inline">\(\approx 0\)</span>.</p>
<p><br></p>
<p><strong>On <span class="math inline">\(C_4\)</span></strong></p>
<p>Recall from Step 15: uniform initialization on <span class="math inline">\(C_4\)</span> produced all-identical colors at every round. The same mechanism operates here at graph level — uniform features + symmetric topology = indistinguishable under message passing.</p>
<p><br></p>
<p><strong>31. What is the minimum change to this experiment that would cause the MPNN to produce different outputs for the two graphs?</strong></p>
<p>Assign at least one distinct initial node feature — breaking the uniform <span class="math inline">\(\mathbf{X} = \mathbf{1}\)</span> assumption so that WL round 0 already sees non-identical colors, forcing divergent signatures from the very first message passing step.</p>
<hr>
</section>
<section id="step-17-atomic-reference-energies-and-baseline-subtraction" class="level2">
<h2 class="anchored" data-anchor-id="step-17-atomic-reference-energies-and-baseline-subtraction">Step 17: Atomic Reference Energies and Baseline Subtraction</h2>
<p><span class="math inline">\(U_0\)</span> (internal energy at 0K) for a molecule is <strong>dominated by atomic contributions</strong> — the energy each atom carries independently of its bonding environment. Subtracting these reference energies leaves only the <strong>interaction energy</strong>, which is what the GNN actually needs to learn.</p>
<p><br></p>
<p><strong>The decomposition</strong></p>
<p><span class="math display">\[U_0^{\text{molecule}} = \underbrace{\sum_{i \in \mathcal{V}} \epsilon_{z_i}}_{\text{atomic baseline}} + \underbrace{\Delta U_0}_{\text{interaction energy}}\]</span></p>
<p>where <span class="math inline">\(\epsilon_{z_i}\)</span> is the reference energy for atom type <span class="math inline">\(z_i \in \{\text{H, C, N, O, F}\}\)</span>.</p>
<p><br></p>
<p>On the anchor <span class="math inline">\(C_4\)</span>, suppose all 4 nodes are carbon (<span class="math inline">\(z_i = \text{C}\)</span>, index 1):</p>
<p><span class="math display">\[\text{baseline} = 4 \times \epsilon_{\text{C}}\]</span></p>
<p>From the atomref table, <span class="math inline">\(\epsilon_{\text{C}} \approx -37.8\ \text{eV}\)</span>, so baseline <span class="math inline">\(\approx -151.2\ \text{eV}\)</span>.</p>
<p><br></p>
<p><strong><code>compute_atomref_baseline</code> — line by line</strong></p>
<p><code>one_hot = x[:, :5]</code> — extracts columns 0–4 from <span class="math inline">\(\mathbf{X}\)</span>, the atom-type one-hots: <span class="math inline">\(\in \mathbb{R}^{N\times 5}\)</span>.</p>
<p><code>atom_counts = one_hot.sum(dim=0)</code> — sums each column, giving a 5-dim vector of element counts. On the anchor (4 carbons):</p>
<p><span class="math display">\[\text{atom\_counts} = [0, 4, 0, 0, 0]\]</span></p>
<p><code>refs</code> — reference energies <span class="math inline">\([\epsilon_H, \epsilon_C, \epsilon_N, \epsilon_O, \epsilon_F]\)</span> as a tensor.</p>
<p><code>(atom_counts * refs).sum()</code> — dot product:</p>
<p><span class="math display">\[\text{baseline} = \sum_{k=0}^{4} \text{count}_k \cdot \epsilon_k = 0\cdot\epsilon_H + 4\cdot\epsilon_C + 0 + 0 + 0 = 4\epsilon_C\]</span></p>
<p><br></p>
<p><strong>32. Why this matters for training?</strong></p>
<p>Without subtraction, the model must learn that a 10-carbon molecule has <span class="math inline">\(U_0 \approx -378\ \text{eV}\)</span> just from atom counting — a trivial but large signal that drowns out the chemically interesting interaction term <span class="math inline">\(\Delta U_0\)</span>. Subtracting the baseline reduces the regression target variance dramatically, making the GNN’s job purely about <strong>learning bonding interactions</strong>.</p>
<hr>
</section>
<section id="step-18-target-normalization" class="level2">
<h2 class="anchored" data-anchor-id="step-18-target-normalization">Step 18: Target Normalization</h2>
<p>We compute normalization statistics <strong>from training data only</strong> to avoid data leakage.</p>
<p><br></p>
<p><span class="math display">\[N_{\text{total}} = 130831, \quad N_{\text{train}} = 0.8 \times N_{\text{total}},\quad N_{\text{val}} = 0.1 \times N_{\text{total}},\quad N_{\text{test}} = \text{remainder}\]</span></p>
<p>A seeded <code>randperm</code> shuffles indices before slicing — ensures class/size balance is random but reproducible.</p>
<p><br></p>
<p><strong>Target normalization — WHY TRAINING DATA ONLY?</strong></p>
<p>The residual for molecule <span class="math inline">\(g\)</span> is:</p>
<p><span class="math display">\[r_g = U_0^{(g)} - \sum_{i \in \mathcal{V}_g} \epsilon_{z_i}\]</span></p>
<p>From Step 17. Then:</p>
<p><span class="math display">\[\hat{r}_g = \frac{r_g - \mu_{\text{train}}}{\sigma_{\text{train}}}\]</span></p>
<p><span class="math inline">\(\mu_{\text{train}}\)</span> and <span class="math inline">\(\sigma_{\text{train}}\)</span> are computed <strong>exclusively from training residuals</strong>. Applying those same statistics to val/test data is correct — using val/test statistics to compute them would constitute <strong>data leakage</strong>, artificially inflating performance.</p>
<p><br></p>
<p><strong>Variance reduction on <span class="math inline">\(C_4\)</span></strong></p>
<p>Suppose <span class="math inline">\(C_4\)</span> has 4 carbons, <span class="math inline">\(\epsilon_C \approx -37.8\ \text{eV}\)</span>:</p>
<p><span class="math display">\[r_{C_4} = U_0^{C_4} - 4\times(-37.8) = U_0^{C_4} + 151.2\ \text{eV}\]</span></p>
<p>The raw <span class="math inline">\(U_0\)</span> range across QM9 spans ~<span class="math inline">\(1085\ \text{eV}\)</span> — dominated by atom counting. After subtracting atomref, <span class="math inline">\(\sigma_{\text{train}}\)</span> drops to <span class="math inline">\(\sim 10\ \text{eV}\)</span>, a <strong>~100x reduction</strong> that makes the regression target tractable.</p>
<hr>
</section>
<section id="step-19-training-loop-residual-targets-normalization-mae-loss" class="level2">
<h2 class="anchored" data-anchor-id="step-19-training-loop-residual-targets-normalization-mae-loss">Step 19: Training Loop: Residual Targets, Normalization, MAE Loss</h2>
<p>We implement the full supervised learning loop. Three mathematical operations chain together: baseline subtraction (Step 17) <span class="math inline">\(\to\)</span> z-score normalization <span class="math inline">\(\to\)</span> MAE loss in normalized space <span class="math inline">\(\to\)</span> denormalize for reporting.</p>
<p><code>get_residual_target</code> — batched baseline subtraction</p>
<p>Extends Step 17’s per-molecule computation to a full batch. For each graph <span class="math inline">\(g\)</span> in the batch:</p>
<p><span class="math display">\[r_g = U_0^{(g)} - \sum_{i \in \mathcal{V}_g} \epsilon_{z_i}\]</span></p>
<p><code>batch.batch == g_idx</code> is a boolean mask selecting rows of <code>x</code> belonging to graph <span class="math inline">\(g\)</span>. Then <code>one_hot[mask].sum(dim=0)</code> counts atom types exactly as in Step 17.</p>
<p><br></p>
<p><strong>On <span class="math inline">\(C_4\)</span> (4 carbons, <span class="math inline">\(\epsilon_C \approx -37.8\ \text{eV}\)</span>):</strong></p>
<p><span class="math display">\[r_{C_4} = U_0^{C_4} - 4\times(-37.8) = U_0^{C_4} + 151.2\ \text{eV}\]</span></p>
<p><br></p>
<p><strong><code>train_epoch</code> — normalization and loss</strong></p>
<p><strong>1. Z-score normalization</strong> of the residual target:</p>
<p><span class="math display">\[\tilde{r}_g = \frac{r_g - \mu_{\text{train}}}{\sigma_{\text{train}}}\]</span></p>
<p>The model predicts <span class="math inline">\(\hat{\tilde{r}}_g \in \mathbb{R}\)</span> in normalized space. Loss is <strong>MAE</strong> (mean absolute error):</p>
<p><span class="math display">\[\mathcal{L} = \frac{1}{B}\sum_{g=1}^{B}|\hat{\tilde{r}}_g - \tilde{r}_g|\]</span></p>
<p><strong>2. Denormalization</strong> for human-readable reporting:</p>
<p><span class="math display">\[\text{MAE}_{\text{eV}} = \mathcal{L} \times \sigma_{\text{train}}\]</span></p>
<p><br></p>
<p>On <span class="math inline">\(C_4\)</span> — suppose <span class="math inline">\(\sigma_{\text{train}} = 10\ \text{eV}\)</span>, <span class="math inline">\(\mu_{\text{train}} = 0.5\ \text{eV}\)</span>, and <span class="math inline">\(r_{C_4} = 1.5\ \text{eV}\)</span>:</p>
<p><span class="math display">\[\tilde{r}_{C_4} = \frac{1.5 - 0.5}{10} = 0.1\]</span></p>
<p>If model predicts <span class="math inline">\(\hat{\tilde{r}} = 0.15\)</span>:</p>
<p><span class="math display">\[\mathcal{L} = |0.15 - 0.1| = 0.05 \implies \text{MAE}_{\text{eV}} = 0.05 \times 10 = 0.5\ \text{eV}\]</span></p>
<p><br></p>
<p><strong>33. Why MAE over MSE?</strong></p>
<p>MSE penalizes large errors quadratically — a single outlier molecule dominates training. QM9 contains molecules spanning a wide size range; MAE treats all residual errors equally regardless of magnitude, producing more robust training.</p>
<p><br></p>
<p><strong><code>evaluate</code> — <code>.sum()</code> vs <code>.mean()</code></strong></p>
<p>Training uses <code>.mean()</code> per batch (normalized by batch size). Evaluation uses <code>.sum()</code> accumulated across all batches, then divides by <code>len(loader.dataset)</code> — this correctly handles the last batch being smaller than 512 without bias.</p>
<p>The MPNN has more parameters ($<span class="math inline">\(67k) than ChebNet (\)</span>$42k). This is because the MPNN uses an Edge Network (a small MLP) to process bond features for every message, whereas ChebNet uses a shared Chebyshev weight matrix for each polynomial order.</p>
<hr>
</section>
<section id="step-20-training-loop-adam-reducelronplateau" class="level2">
<h2 class="anchored" data-anchor-id="step-20-training-loop-adam-reducelronplateau">Step 20: Training Loop: Adam + ReduceLROnPlateau</h2>
<p>We wire together the training infrastructure. Two mathematical objects govern optimization: the <strong>Adam update rule</strong> and the <strong>learning rate schedule</strong>.</p>
<p><br></p>
<p><strong>Adam optimizer</strong></p>
<p>For each parameter <span class="math inline">\(\theta\)</span>, Adam maintains running estimates of the first and second moments of the gradient:</p>
<p><span class="math display">\[m_t = \beta_1 m_{t-1} + (1-\beta_1)g_t \quad \text{(mean)}\]</span> <span class="math display">\[v_t = \beta_2 v_{t-1} + (1-\beta_2)g_t^2 \quad \text{(variance)}\]</span></p>
<p><strong>Bias-corrected update:</strong></p>
<p><span class="math display">\[\theta_t = \theta_{t-1} - \frac{\eta}{\sqrt{\hat{v}_t} + \epsilon}\hat{m}_t\]</span></p>
<p>With <code>lr=1e-3</code>, <span class="math inline">\(\beta_1=0.9\)</span>, <span class="math inline">\(\beta_2=0.999\)</span> (PyTorch defaults). The effective step size adapts per-parameter — parameters with consistently large gradients get smaller updates automatically.</p>
<p><br></p>
<p><strong>ReduceLROnPlateau</strong></p>
<p>Monitors <code>val_mae</code>. If it fails to improve for <code>patience=10</code> consecutive epochs:</p>
<p><span class="math display">\[\eta \leftarrow \eta \times 0.5\]</span></p>
<p>until <code>min_lr=1e-5</code>. On a training run of 128 epochs, this can trigger ~2–3 times, walking <span class="math inline">\(\eta\)</span> from <span class="math inline">\(10^{-3}\)</span> down toward <span class="math inline">\(10^{-5}\)</span> as the model approaches convergence.</p>
<p><br></p>
<p><strong>34. Why these choices suit QM9?</strong></p>
<p>Adam’s adaptive per-parameter learning rates handle the heterogeneous gradient scales across node MLP weights, edge MLP weights, and readout layers. ReduceLROnPlateau avoids premature convergence without requiring a fixed schedule — it responds to actual validation behavior rather than a predetermined decay curve.</p>
<p><br></p>
<p><strong>35. Why validation MAE (rather than training MAE) is passed to <code>scheduler.step()</code>?</strong></p>
<p>Training MAE measures how well the model fits data it has already seen — it will keep decreasing even as the model overfits. Validation MAE measures performance on unseen data, so when it plateaus, it signals the model has genuinely stopped improving in a generalizable sense — which is exactly when reducing the learning rate to take finer steps makes sense.</p>
<hr>
</section>
<section id="code-output" class="level2">
<h2 class="anchored" data-anchor-id="code-output">Code Output</h2>
<p><strong>Output Interpretation:</strong></p>
<ul>
<li><strong>MPNN (1.4392 eV):</strong> Outperforms ChebNet by approximately <strong>19%</strong>. In the context of QM9, this performance gap is largely attributed to the MPNN’s <strong>spatial edge processing</strong>, which explicitly models bond types (single, double, triple, aromatic).</li>
<li><strong>ChebNet (1.7810 eV):</strong> While higher than MPNN, it captures over <strong>82%</strong> of the target variance using only graph connectivity and spectral filters.</li>
<li><strong>Normalized MAE (0.1395 vs 0.1726):</strong> Both models demonstrate strong predictive power, staying well below a normalized error of 1.0 (which would be equivalent to just guessing the mean).</li>
</ul>
<p><br></p>
<p><strong>Final Comparison Summary:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: left;">MPNN (Spatial)</th>
<th style="text-align: left;">ChebNet (Spectral)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Test MAE</strong></td>
<td style="text-align: left;">1.4392 eV (Winner)</td>
<td style="text-align: left;">1.7810 eV</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Parameters</strong></td>
<td style="text-align: left;">67,777</td>
<td style="text-align: left;">42,049 (Efficient)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Input Usage</strong></td>
<td style="text-align: left;">Nodes + Edge Features</td>
<td style="text-align: left;">Nodes + Graph Laplacian</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Inductive Bias</strong></td>
<td style="text-align: left;">Local Message Passing</td>
<td style="text-align: left;">Spectral Frequency Filtering</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Final Project Conclusion</strong></p>
<p>This project successfully implemented a side-by-side comparison of Spectral vs.&nbsp;Spatial GNNs. By applying the 1-WL test, we identified the mathematical “blind spots” of these architectures. Through Delta Learning (atomref subtraction), we reduced problem complexity by 105<span class="math inline">\(\times\)</span>, ultimately proving that while spectral methods like ChebNet are parameter-efficient, spatial methods like MPNN remain superior for molecular property prediction due to their ability to explicitly integrate bond chemistry.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shreeshb51\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Shreesh Bhattarai · GDL &amp; COT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/shreeshb51">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/shreesh-bhattarai-1ba1681bb/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>